### ISSUE TITLE
Add support for RevenDB (https://ravendb.net/)

### ISSUE THREAD

**Issue by w0rxbend** [Impetus/kundera#1010]
The Original Fully Transactional Open Source NoSQL Document Database. There is java driver for RavenDb.

**Features**

   - A fluent and predictable hand-tailored API
   - Safe by default
   - Extensible and configurable
   - DDD compatible
   - Unit of Work

JVM Requirements: Java 1.8+

**Comment by devender-yadav** [comment]
Hi @limpid-kzonix,

Adding new database support depends on the need of the community. If we get requests from multiple users, we add that database addition task to our board.

If someone from the community wants to work on it, we will provide support.

-Dev
