### ISSUE TITLE
Met NPE while executing deepCopyUsingMetadata

### ISSUE THREAD

**Issue by timlong** [Impetus/kundera#102]
Hi

I met NPE when deepCopyUsingMetadata,my DO like:
@Entity
@Table(name = "publisher_stats", schema = "belugaHbase@belugaHbase")
@XmlRootElement(name = "PublisherStats")
public class PublisherStats {

```
@Id
private String rowKey;

@Embedded
@Column(name = "ads")
private PublisherAdsStats ads;

@Embedded
@Column(name = "app")
private StatsApp app;

@Embedded
@Column(name = "val")
private StatsVal val;
```

but   Class PublisherAdsStats  do not have Constructor with params
while executing deepCopyUsingMetadata function:
 if (embeddedColumnField.getAnnotation(Embedded.class) != null)
                    {
                        // Copy embedded objects
                        Class<?> embeddedColumnClass = embeddedColumnField.getType();
                        Object targetEmbeddedObj = embeddedColumnClass.newInstance();

```
                    for (Column column : embeddedColumn.getColumns())
                    {
                        PropertyAccessorHelper.set(targetEmbeddedObj, column.getField(),
                                PropertyAccessorHelper.getObject(sourceEmbeddedObj, column.getField()));
                    }

                    PropertyAccessorHelper.set(target, embeddedColumnField, targetEmbeddedObj);
                }
```

kundera will use newInstance to call default Constructor without params  which I did not define
and I  think this is the cause of NPE

**Comment by xamry** [comment]
You are right, its mandatory to define no-argument constructor in entities
and embeddables in kundera.

**Comment by mevivs** [comment]
I guess, we might need to educate end user on upfront rather than NPE.

-Vivek

**Comment by bytor99999** [comment]
I got this error too, but I have no args constructors on my entities.

Mark

**Comment by bytor99999** [comment]
I should mention that my build is off the 2.0.7.1 branch.

**Comment by mevivs** [comment]
Fixed in trunk. Please verify.

-Vivek

**Comment by bytor99999** [comment]
I won't be able to verify. Busy and I am also using 2.0.7.1 branch and not trunk. ;) But I hope the OP can verify

Mark
