### ISSUE TITLE
Package missing in Example code

### ISSUE THREAD

**Issue by antonioaltamura** [Impetus/kundera#1023]
Hi, I've just started to playing around with Cassandra (I'm pretty new to JPA too), here in your example
https://github.com/Impetus/Kundera/wiki/Getting-Started-in-5-minutes#moment-of-truth

you use 2 constants `CassandraConstants.CQL_VERSION` and `CassandraConstants.CQL_VERSION_3_0` where they came from?

I'm not clear which package I'm missing. Maybe that example could be more clear about that.

**Comment by devender-yadav** [comment]
Hi @antonioaltamura,

These are from kundera-cassandra module. 

You can start with basic CRUD example [here](https://github.com/Impetus/Kundera#sample-projects).

**Comment by antonioaltamura** [comment]
Still don't get where can I find kundera-cassandra.
Here my pom
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>HelloJPA</groupId>
  <artifactId>HelloJPA</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <repositories>
   <repository>
     <id>sonatype-nexus</id>
     <name>Kundera Public Repository</name>
     <url>https://oss.sonatype.org/content/repositories/releases</url>
    <releases>
        <enabled>true</enabled>
    </releases>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
 </repository>
 </repositories>
  <dependencies>
		<dependency>
			<groupId>com.impetus.kundera.client</groupId>
			<artifactId>kundera-cassandra</artifactId>
			<version>3.9</version>
		</dependency>
		
	</dependencies>
</project>
```
that sample code seems to have just a data model class and a test class, no proper entry point.

**Comment by devender-yadav** [comment]
@antonioaltamura it's in maven central repo. Check this [pom](https://github.com/Impetus/Kundera/blob/trunk/examples/basic-examples/kundera-cassandra-example/pom.xml) and use latest version 3.13.

Not sure what did you mean by entry point. Do you want to build a web application?

**Comment by antonioaltamura** [comment]
Thanks, it was an Eclipse/maven problem
