### ISSUE TITLE
[Question] how to persist multiple tables from a single entity?

### ISSUE THREAD

**Issue by juneng603** [Impetus/kundera#103]
hi, I am a beginner to use a Kundera library.

From our needs, 
We want to use a single entity to persist into multiple tables.

from jpa spec, 
there are @SecondaryTable, @SecondaryTables annotations for this one. 

but, in my test, Kundera doesn't support it yet.

Is there another way to this?

thanks

-- Henry

**Comment by mevivs** [comment]
Hi,
Yes. Kundera does not support it yet. IT is not possible with a singly entity.

-Vivek

**Comment by mevivs** [comment]
Hi,
One way to achieve this is via One-To-One mapping. Somehow "sharedByPrimaryKey" is not working properly. Till the time i believe you can go ahead with One-To-One ForeignKey mapping case, and you need to explicitly set the same ID in both entities.

I will get back to you, once i get "SharedByPrimaryKey" case fixed.

-Vivek

**Comment by mevivs** [comment]
Target for 2.4 release.

**Comment by mevivs** [comment]
Releasing with 2.5

**Comment by mevivs** [comment]
Please verify.

-Vivek
