### ISSUE TITLE
Kundera warns me with unintelligible messages.

### ISSUE THREAD

**Issue by juneng603** [Impetus/kundera#104]
first, here is my entity to persist.

``` java
@Table(name = "blog2", schema = "blog2@hbase")
public class BlogSample {
    @Id
    private String id;

    @Column(name = "D1")
    private String data;

    @Column(name = "D2")
    private String data2;

     ....
```

from my entity, my understanding is like this about a Kundera : 
I want to persist it in to blog2 table, store 'data' into D1 column and store 'data2' into D2 column. 

and here is it from error message from my program.

```
exception in thread "main" com.impetus.kundera.KunderaException: javax.persistence.PersistenceException: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: Column family D1 does n
ot exist in region blog2,,1345097253609.bdd3f27ccb360fc836d8c758853b4349. in table {NAME => 'blog2', FAMILIES => [{NAME => 'A', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', COMPRESSION => 'SNAPPY', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', BLOCKSIZE => '65536'
, IN_MEMORY => 'false', BLOCKCACHE => 'true'}]}
```

I didn't mean 'D1' as a column family.
somethings I missed?

-- Henry

**Comment by mevivs** [comment]
Hi,
As per HBase data model, above mentioned entity will be interpret as :
 blog2 -> HBase table.
And each column like, 

```
@Column(name = "D1")
    private String data;
```

will be defined as:
D1:D1 (e.g. column family:column name). That's why it is complaining about D1 as a column family.

I guess, a table in HBase comprise of column families and these column families contains set of columns.

-Vivek

**Comment by juneng603** [comment]
How could I define a column family and column name with different names?
I mean that I want to 'data' in 'CF1:D1'. For this operation, which annotations or configurations I've missed?

thanks vivek.

-- Henry.

**Comment by mevivs** [comment]
We had a thought about it. But unfortunately there is no other way we were able to figure out to define different column family & column name for basic column(in JPA way). But you can use Embeddable concept, if you want more than 1 columns in a different column family.

-Vivek

**Comment by mevivs** [comment]
I would request you to add your suggestions, in case you want to add something in kundera wish list for 2.0.8:
https://github.com/impetus-opensource/Kundera/issues/89

Thanks,
Vivek

**Comment by juneng603** [comment]
Ok Vivek.

I applied my idea to the issue.

**Comment by mevivs** [comment]
Thanks Kim. As of now to define different column family name you could still use @Embeddable concept to create an embeddable entity and define it's name as desired column family. Then simply add your column into this one, like:

```
@Table(name = "blog2", schema = "blog2@hbase")
public class BlogSample {
    @Id
    private String id;

    @Embedded
    private BlogData data;

    @Column(name = "D2")
    private String data2;


@Embeddable
public class BlogData {

    @Column(name = "D1")
    private String data;

```

Here "BlogData" will become your column family name and column will be "D1".

Hope it helps.

-Vivek

**Comment by juneng603** [comment]
thanks for your helps.
