### ISSUE TITLE
problem with updating an entity without calling EntityManager's methods

### ISSUE THREAD

**Issue by juneng603** [Impetus/kundera#107]
Hi, Kundera developers. 

I got a problem to update my entity without calling EntityManager's functions.

from a jpa spec, 
we could update an entity information as a persistence level once we've persisted it. 

for example

``` java
MyEntity e = new MyEntity();

// scenario 1
// tran starts
em.persist(e); 
e.setSomeField(someValue); 
// tran ends, and the row for someField is updated in the database
```

yes, this is a easy scenario from general jpa apis.

but, in case of Kundera, I could't follow the steps I've mentioned.

does not support it yet?

**Comment by xamry** [comment]
You have to call either em.persist() or em.merge() in order to update
entity into database.

Just setting properties won't do.

Regards,
Amresh

**Comment by mevivs** [comment]
This is something like implicit "dirty read/write" check done by RDBMS jpa providers. Kundera currently does not handle this and as a way around, you need to explicitly invoke jpa methods(as per JPA).

-Vivek

**Comment by juneng603** [comment]
okay!! actually, this is not a problem for me ;) just for understanding. thanks for all.
