### ISSUE TITLE
is this proper way to use Filter for hbase?

### ISSUE THREAD

**Issue by juneng603** [Impetus/kundera#108]
hi, again.

I want to use Filter for hbase. 

this is the only way I knew. 

``` java
Filter  filter = new SingleColumnValueFilter("PERSON_NAME".getBytes(), "PERSON_NAME".getBytes(), CompareOp.EQUAL,
                "vivek".getBytes());

Client client = ((Map<String, Client>)em.getDelegate()).get(persistenceUnitName);
((HBaseClient) client).setFilter(filter);
```

is there another way in a jpa-level?

**Comment by xamry** [comment]
JPA specifies getDelegate() method in EntityManager for delegator
implementation that EntityManager relies upon for database operations.

In Kundera, delegator maps closely to Clients (HBaseClient, PelopsClient
etc).
Delegator is your gateway to operations that are implemented in clients,
but are not available in JPA way.

We found Filter a good use case of leveraging this feature.

HTH,
Amresh

**Comment by mevivs** [comment]
Yes, agree as Amresh suggested.

Just wanted to add that basic JPQL support will work and no need to create Filter for them.(Please have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-hbase/src/test/java/com/impetus/client/hbase/crud/PersonHBaseTest.java)

But in case you want something other than this, like ColumnPrefixFilter etc. You can set it as mentioned above.

**Comment by juneng603** [comment]
Okay, I will reference your guides when I am implementing application repository layer based on Kundera.
thanks for your supports.
