### ISSUE TITLE
ways to initialize field value from an Entity level.

### ISSUE THREAD

**Issue by juneng603** [Impetus/kundera#111]
hi,  I am also having a question about how to initialize a field value from an Entity level.

for example, is this possible?

```
public class Twitter {
  @Id
  private String id;

  @Column(name="NAME", defaultDefinition="default 'N/A'")
  private String name;

  ...
}
```

in my test, the above example is not working. 

maybe this one is going to be worked.

```
public class Twitter {
  @Id
  private String id;

  @Column(name="NAME")
  private String name = "N/A";

  ...
}
```

any ideas?

**Comment by mevivs** [comment]
Hi Henry,
Curently kundera ignores default value from:

```
@column(name="NAME", defaultDefinition="default 'N/A'")
```

But, there are number of ways to initialize/assign values:
1) One way is assigning default value(As you mentioned)
2) Create a constructor using fields and assign it.
3) By explicitly invoking setter method.

-Vivek

**Comment by juneng603** [comment]
big thanks ;) 
- Henry
