### ISSUE TITLE
{kundera-discuss} Re: Query returns no rows. In JPA would return empty List or Null

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#114]
Hmm..i agree with you and Amresh.. returning empty or null both means "there is no record". But for better use of Kundera API i think returning an empty list should also be fine :)

-Vivek

kundera-discuss@googlegroups.com [kundera-discuss@googlegroups.com] on behalf of Amresh [amresh1002@gmail.com]
Sent:    24 August 2012 12:20
To: 
kundera-discuss@googlegroups.com
That's a good point Mark, and although JPA doesn't clearly state required behavior, from usability point of view this makes sense and requires easy changes.

Regards,
Amresh

On Fri, Aug 24, 2012 at 12:15 PM, Bytor99999 bytor99999@gmail.com wrote:
Well a good reason to return an empty list would be that in some use cases you them loop through that list to do some business logic and the best way is the for each loop. But if you put the List into the for each you have to first check with an if to see if it is null. I am very much about the least amount of code and this would require 2 more lines of code for each use case that needs to loop. I actually think that that would be the majority where you loop through the list without checking for null. Even if it is a loop in a jsp page with jstl. If it could return null in that case you then have to even add a null check in the jsp page.

So while the api in JPA doesn't specify whether the implementation has to return an empty List or always return null. I am pretty positive that Hibernate's implementation of JPA returns an empty list.

You could say it is also like Lists in entities with @OneToMany If the One side doesn't have any children the List in the domain is not null, it has a List that is empty.

But again, I am not sure what the JPA spec says, if it says anything on the matter. If it says nothing then you can obviously do whatever you want. I would just document it in the javadocs that the resultList method might return null if no records are found. Or should it throw a NoResultsFoundException or whatever that exception class is.

Thanks for your reply.

Mark

On Thursday, August 23, 2012 4:10:00 PM UTC-7, Bytor99999 wrote:
Right now I am running a query that would return no results, and therefore the List<Persons> that I assign the results to should be an empty List. I believe that is how it works in JPA and probably in the Spec. But my results is that the List is being set to null, or just not assigned as it is begins null. So now I have to do a Null pointer check everytime I run a query?

Thanks

Mark

**Comment by myeh** [comment]
I second the approach of returning an empty list.  We currently use hibernate and I had to add null checks when trying to port our code to use kundera.

**Comment by mevivs** [comment]
Kuldeep, 
please asses it and let's target it for 2.2 release

-Vivek

**Comment by mevivs** [comment]
Fixed in current trunk and releasing with 2.5
