### ISSUE TITLE
How to work with column families in HBase

### ISSUE THREAD

**Issue by mightylucene** [Impetus/kundera#116]
Hello,

I am getting following exception while working with HBase

org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: Column family name does not exist in region categories,,1347193788006.60d5d1901eafb0eb92e3355149f843a4. in table {NAME => 'categories', FAMILIES => [{NAME => 'p', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}, {NAME => 's', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}]}

Below is my entity code

/*
- To change this template, choose Tools | Templates
- and open the template in the editor.
  */
  package entities;

import java.io._;
import javax.persistence._;
import java.util.*;

/**
 *
- @author loken
  */
  @Entity
  @Table(name = "categories", schema = "KunderaExamples@cassandra_pu")
  public class Category implements Serializable {
  
  private static final long serialVersionUID = 1L;
  @Id
  private String id;
  
  public String getId() {
      return id;
  }
  
  public void setId(String id) {
      this.id = id;
  }
  
  @Column
  private String name;
  
  public String getName() {
      return this.name;
  }
  
  public void setName(String name) {
      this.name = name;
  }
  
  @Override
  public int hashCode() {
      int hash = 0;
      hash += (id != null ? id.hashCode() : 0);
      return hash;
  }
  
  @Override
  public boolean equals(Object object) {
      // TODO: Warning - this method won't work in the case the id fields are not set
      if (!(object instanceof Category)) {
          return false;
      }
      Category other = (Category) object;
      if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
          return false;
      }
      return true;
  }
  
  @Override
  public String toString() {
      return "entities.Category[ id=" + id + " ]";
  }
  }

**Comment by mevivs** [comment]
Please have a look at :
https://github.com/impetus-opensource/Kundera/issues/104

about it's usage.

**Comment by mightylucene** [comment]
Thank you Vivek.
