### ISSUE TITLE
Problem with null values

### ISSUE THREAD

**Issue by sachur** [Impetus/kundera#117]
I discovered that when I delete records in the database, I still nulls.

Since then the records could retrieve non-null?

Thanks (sorry for my English)

**Comment by mevivs** [comment]
Hi,
Are you using Cassandra? once a record deleted from cassandra, still it's row key exists. However Kundera filters out such record and those will not be accessible.

Please explain a bit more, if your scenario differ from above mentioned.

-Vivek

**Comment by sachur** [comment]
Yes, I'm using Cassandra.

But, I have an global return list, which return all the row of my DB :

```
String query = "Select p From FileCassandra p ";
Query q = em.createQuery(query);
List<FileCassandra> list = q.getResultList();
```

After delete, this method return a list where the row I deleted appear to "null".

Any solution?

**Comment by mevivs** [comment]
Are you using 2.0.7 release? I guess it is already fixed in current trunk branch.

-Vivek

**Comment by sachur** [comment]
Yes, I'm using a 2.0.7

**Comment by mevivs** [comment]
Please verify with trunk, i think it should work.

-Vivek

**Comment by sachur** [comment]
Yes, I'm using maven, and the version is 2.0.7 SNAPSHOT Kundera.

In BD, the table has 4 entries (2 null), and the method getResultList returns those 4 entries.

**Comment by xamry** [comment]
Trunk is on 2.0.8. Just pull trunk branch and build your code through
maven. It should work for you.

**Comment by sachur** [comment]
2.0.8? The latest stable version is 2.0.7?

**Comment by mevivs** [comment]
Current trunk branch is "2.0.8-SNAPSHOT".
to checkout :

git clone git://github.com/impetus-opensource/Kundera.git
git checkout trunk

and then build:
mvn clean install (to skip test) -DskipTests

**Comment by sachur** [comment]
Somehow there another? A method that returns only non-null values​​?

I thought that with version 2.0.7 there was no problem

**Comment by sachur** [comment]
I think the problem may be in the version of CQL. Where can you watch the version?

**Comment by mevivs** [comment]
You can set CQL version in kundera itself. by default it is 2.0

**Comment by mevivs** [comment]
"Somehow there another? A method that returns only non-null values​​?

I thought that with version 2.0.7 there was no problem" 

Please provide more description around this.

**Comment by mevivs** [comment]
The way to set CQL version is:

   Map<String, Client> clients = (Map<String, Client>) em.getDelegate();
   Client client =  clients.get("cassandra_pu");
((PelopsClient) client).setCqlVersion()..

Hope it helps.

-Vivek

**Comment by xamry** [comment]
You can refer to this test case for an example on how to set CQL version
before any operation:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/persistence/NativeQueryCQLV3Test.java

Regards,
Amresh

**Comment by sachur** [comment]
I think I'll go to 2.0.8
How to do it the easy way?

Thanks for your trouble

**Comment by xamry** [comment]
In order to use 2.0.8, You have to build Kundera from source, as 2.0.8 is
not yet released.

You can pull trunk branch from Github, build using maven, and
kundera-xxx-2.0.8 jars would be copied into maven repository (usually <user
home>/.m2/repository on your machine)

For details on how to build from source - visit "Build from Source" section
in https://github.com/impetus-opensource/Kundera/wiki/Download-Kundera

HTH,
Amresh

**Comment by mevivs** [comment]
I guess, it is no more an issue. Closing it.
