### ISSUE TITLE
PelopsDataHandler.fromThriftRow never returns null for entity mapped to Cassandra column family

### ISSUE THREAD

**Issue by wingnut** [Impetus/kundera#12]
Affects 2.0.x

If any entity mapped to a Cassandra CF is queried for by PK using the EntityManager.find(Class, PK) the result is always an entity.
Even if querying against an empty Cassandra.

The problem seems related to the refactoring of Client/DataHandler some time after the 2.0 release.

Expected result:
If an entity could not be found in Cassandra, null should be returned.

Actual result:
If an entity could not be found in Cassandra, an entity populated with only the PK from the query is returned.

Suggested solution:
A quick browse of the code (have not delved into it too deep) indicates that it's a missing null/empty check in the PelopsDataHandler after the actual call to Cassandra (looking at the 2.0.4 code right now).

**Comment by mevivs** [comment]
Make sense. This will be fixed in 2.0.4 release.

**Comment by xamry** [comment]
This is being looked into by me and will be fixed in 2.0.4

**Comment by mevivs** [comment]
Please retest with 2.0.4.

**Comment by mevivs** [comment]
Closing this issue now.
