### ISSUE TITLE
Problem with "No entity found by the name" when using maven-surefire-plugin > 2.3

### ISSUE THREAD

**Issue by smecsia** [Impetus/kundera#123]
When I try to write the DAO tests using the embedded Cassandra instance, I get the following error: "No entity found by the name EntityClassName".  It turns that maven-surefire-plugin with the version older than 2.3 uses the separate classloading approach named "booter" due to the limitations of the system classpath ( http://jira.codehaus.org/browse/SUREFIRE-727 ). It creates the separate void jar file named surefire-booter***.jar with the only Manifest file inside with the specified Class-Path. 
When Kundera initializes MetamodelConfiguration, it uses the findResourcesByContextLoader method of ClasspathReader class. This method uses ClassLoader from the current thread and checks if the Url of this classloader represents the jar file (urls = classLoader.getUrls() ) and if so, it tries to find the entity class file inside this jar file. But it does not contain this class and it should not. 

Please suggest your thoughts about this problem. I can provide the reproducing project if you need.

I think I could write a patch if this is a real issue.

**Comment by mevivs** [comment]
please, share your project let me have a look

---

**Comment by mevivs** [comment]
please feel free to contribute your fix for this. 

---

**Comment by smecsia** [comment]
You can find the project reproducing this problem here: https://github.com/smecsia/kundera-maven-test

**Comment by mevivs** [comment]
Thanks.

-Vivek
