### ISSUE TITLE
Where and spaces

### ISSUE THREAD

**Issue by sachur** [Impetus/kundera#124]
Hi, I like to make the following query :

SELECT ... WHERE key=value

value where there is a space between words.

For example: SELECT ... WHERE state=Very Good;

Any help?

**Comment by mevivs** [comment]
I guess, it should work for you without any issue.

-Vivek

**Comment by sachur** [comment]
Does not work, I tried to enclose it in single and double quotes, and nothing

**Comment by mevivs** [comment]
This is what i have tried with PersonCassandraTest.

Select p from PersonCassandra where p.name = vivek mishra 

And it is working for me. Also this is what i have tried on 2.1 release.

You can modify and test it by yourself, here it is:

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandraTest.java

-Vivek

**Comment by sachur** [comment]
In that line? Can not find it

**Comment by mevivs** [comment]
have a look at:
assertFindByName // line 128. 

you need to modify prepareData method to set name as  vivek mishra and then replace:

```
    assertFindByName(em, "PersonCassandra", PersonCassandra.class, "vivek", "personName");
```

with
        assertFindByName(em, "PersonCassandra", PersonCassandra.class, "vivek mishra", "personName");

**Comment by sachur** [comment]
I tried that and it does not work :(

**Comment by mevivs** [comment]
Really strange. i will modify test class accordingly and will post on update. Not sure why is it not working for you.

-Vivek

**Comment by sachur** [comment]
Now if it works, I was not using either method. Sorry for the inconvenience.

Thanks

**Comment by mevivs** [comment]
Great. closing it now.

-Vivek
