### ISSUE TITLE
Operator or

### ISSUE THREAD

**Issue by sachur** [Impetus/kundera#126]
There the or operator in select query?

For example: SELECT ... WHERE key = value1 OR  key = value2

**Comment by mevivs** [comment]
Cassandra does not provide a way to support OR Clause using secondary indexes.

-Vivek

**Comment by sachur** [comment]
Ok, thanks

**Comment by zhouhero** [comment]
can you implement "or" Operator  in kundera in client side when using cassandra?

**Comment by mevivs** [comment]
Unfortunately Cassandra IndexClause API does not provide a way for this yet!

-Vivek
