### ISSUE TITLE
MongoDB Safe Mode

### ISSUE THREAD

**Issue by jeremyhahn** [Impetus/kundera#135]
How does one go about enabling safe mode with mongo?

**Comment by mevivs** [comment]
Kuldeep,
Please look into this.

-Vivek

**Comment by kkmishra** [comment]
Hi jeremyhahn,
you can give it via xml property 
like

```
<?xml version="1.0" encoding="UTF-8"?>
<clientProperties>
    <datastores>
        <dataStore>
        <name>mongo</name>
        <connection>
            <properties>
                <property name="read.preference" value="primary"></property>
            <property name="socket.timeout" value="100000"></property>
            <property name="safe" value="true"></property>
            </properties>
        </connection>
        </dataStore>
    </datastores>
</clientProperties>
```

Thanks and Regrads
kuldeep

**Comment by kkmishra** [comment]
you have to put following property in persistenceUnit property tag.

```
 <property name="kundera.client.property" value="xmlFileName" />
```

then it will work.

Thanks and Regards
Kuldeep

**Comment by jeremyhahn** [comment]
Great, thanks. Is it safe to assume I can enable any of the write concerns in the same manner? Is there a way to control the write concern level (database, collection, single operation) or is this a single on/off at the database level?

Thanks

**Comment by mevivs** [comment]
Yes.i thin you can enable it in same way, Team is working on enabling write concern and other properties as well for  operation level. 

-Vivek

**Comment by xamry** [comment]
This has been implemented:

You can set Write concern in either of two ways:

```
WriteConcern wc = new WriteConcern(1, 300, true);
em.setProperty("write.concern", wc);
```

OR

```
WriteConcern wc = new WriteConcern(1, 300, true);
Map<String, Client> clients = (Map<String, Client>) em.getDelegate();       
MongoDBClient client = (MongoDBClient)clients.get("mongo_pu");        
client.setWriteConcern(wc);
```

Also see: https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/java/com/impetus/client/mongodb/config/OperationLevelPropertiesTest.java
