### ISSUE TITLE
missing Kundera dependencies after build from source

### ISSUE THREAD

**Issue by emgsilva** [Impetus/kundera#137]
Hi there,

I have just built Kundera from the source (using maven)... everything went smoothly and I am able to get all the "jars" (of all of the clients, although I am only working with Cassandra). I do this, and do not 

However, when I import them (I tried to import only the generated Cassandra, and also the Core) to my project (Eclipse) I notice that many of the dependencies (e.g.: javax.persist, etc.) are missing... Those are included in the stable .jar you make available for download (I have used the stable version until now successfully)... My questions is, how can I get these missing dependencies? Do you have any other Jar with these dependencies somewhere or a list of the dependencies we need to get?

I thank you in advance for your assistance! I am starting using Cassandra for some parts of my product, and I find Kundera the most interesting client and was the fastest way to start using Cassandra... however I could not get the "compound keys" working on the "stable" version (then I stumbled upon this post https://github.com/impetus-opensource/Kundera/wiki/Using-Compound-keys-with-Kundera and noticed I need the trunk version), I really hope it works and you succeed get this working nicely, as this is a very important feature in many situations...

Keep up with the good work! Cheers,

Eduardo

**Comment by xamry** [comment]
Hi,

The dependency javax.persistence.\*  and many others are specified in
pom.xml (see
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-core/pom.xml
)

You are right about Composite Keys...It's currently available in trunk
branch and is going to be part of release 2.2 (possibly within a week time)

Best Regards,
Amresh

**Comment by mevivs** [comment]
If you build from source code. and your project build is maven based. You should be able get all dependencies by simply executing:
1) mvn clean install -DskipTests
2) mvn eclipse:clean eclipse:eclipse

For downloadable jar, it is an executable jar generated via same source and it includes required dependencies only!

Yes. Compound keys is a feature available in latest "trunk" branch(Not yet released)
It should work for you, you can have a look on test package about it's usage as well.

Cheers,
Vivek

**Comment by emgsilva** [comment]
Hi,

Thank you for the quick response! I did run the commands you say... and got the "jars" in the "target" directories of each part (core, cassandra, etc.)... no problems.

However, the generated Jars do not include the dependencies. Am I doing something wrong? I am using MacOS and JDK7... I am not an experienced maven user, so maybe I am doing something wrong.

Cheers,

Eduardo

**Comment by xamry** [comment]
Jars are downloaded to maven home folder. In linux based systems its
user.home/.m2/repository

**Comment by emgsilva** [comment]
I see that I have the dependencies in the ~/.m2, however I am struggling to include them in my building path (in eclipse)... As I said before, I have no experience with maven, any tips how to do that... I do not want to make my project a maven project, is there a way to use the dependencies I downloaded without doing that? (I added the M2_REPO in eclipse, however it does not "see" the jars...)... Sorry for this question, a bit outside the scope, but I am not finding solutions when looking around on Google... any tips is welcome. My current solution is to copy/paste the .classpath entries generated by the "mvn eclipse:clean eclipse:eclipse" command to my eclipse project .classpath... this looks ugly, although seems to work :p

Thank you!

**Comment by xamry** [comment]
mvn eclipse:clean eclipse:eclipse are meant to generate eclipse settings
file according to dependencies specified in pom.xml.

**Comment by emgsilva** [comment]
Hi Amresh and Vivek,

I got this working by importing the dependencies generated on the different Kundera client parts (after run the mvn eclipse:clean eclipse:eclipse on the Kundera root directory) to my project .classpath... a bit of hacking (need to find a more consistent way to tackle this problem...) but it is working. Now I probably have another problem, but it is already related with the handling of "composite keys". I will investigate it a little bit further, if I cannot manage I will open another issue.

Thank you very much for your help! Cheers,

Eduardo

**Comment by emgsilva** [comment]
UPDATE: I just got composite keys working! Very nice! I would recommend to improve the Wiki entry about CompositeKeys, containing information about creating a "column" with composite keys with cqlsh, create the entity (which needs to have exact same variable names as the ones in Cassandra - case sensitive), and the fundamental code to use the application communicate with Cassandra, which I noticed varies from the other simpler examples... and I still do not understand some parts of the code (just copied the code provided in your tests on the CompositeKey). I think this would help a lot people to get things working faster. Probably you plan to do that once you release it on version 2.2...

Nice work! I will keep on using Kundera as it now covers completely my application requirements... Cheers,

Eduardo

**Comment by xamry** [comment]
Thanks Eduadro,

We'll refine our wiki more and incorporate your suggestions.

Regards,
Amresh

**Comment by mevivs** [comment]
create the entity (which needs to have exact same variable names as the ones in Cassandra - case sensitive): Kundera ensure case sensitivity. 

I guess what needed is  "more information around composite keys and how exactly Cassandra/Mongo handles it.

I think it is good addition to wiki.

-Vivek

**Comment by emgsilva** [comment]
Great!

Vivek: I am sorry, indeed was not a problem of "case sensitive", I had a different name (test_name instead of testName). Indeed I think would be very constructive to put together a little bit of this information about how composite keys are handled in Cassandra (I think for Cassandra the post from datastax http://www.datastax.com/dev/blog/schema-in-cassandra-1-1 was where I learn the most)... I have started using Cassandra one week ago :p and did not have the time to read long material (I am bit in a hurry to deliver an application)... It would help a lot to have that information (in the same fashion you have the "Getting Started in 5 minutes" :) 

I know and understand you are working on this actively, but this information is spread all over the web on blogs, forums, etc. etc., and if you have some nice starting guidelines here you will be appreciated even more by your users, and I am sure you will get more users too :p 

Any ways... I will be around, maybe once I am more familiar I can also give you a hand on these things :)

Cheers,

Eduardo

**Comment by mevivs** [comment]
Sure. we will update wiki for detail information and as well for a page like "getting started in 5 minutes" as well :)

Cheers,
-Vivek
