### ISSUE TITLE
Kundera tries to validate JPA entities that are from Hibernate/MySQL

### ISSUE THREAD

**Issue by emgsilva** [Impetus/kundera#138]
Hi there,

I am integrating Kundera (Cassandra) on an application where I already use Hibernate (MySQL), and will continue to use (I know that Kundera also supports MySQL DBs, but I want to keep using hibernate for now - a lot of dependencies and no time to tackle that now). I am getting a kind of conflict, if I understand it correctly...

The problem I get is the following:
`
INFO: No class to scan for persistence unit cassandra_sys. Entities will be loaded from classpath/ context-path
Exception in thread "main" com.impetus.kundera.metadata.validator.InvalidEntityDefinitionException: com.domain.parameters must have an @Id field.
    at com.impetus.kundera.metadata.validator.EntityValidatorImpl.validate(EntityValidatorImpl.java:110)
    at com.impetus.kundera.metadata.MetadataBuilder.validate(MetadataBuilder.java:92)
...
`

How can I make Kundera to "stop looking" on all the non-Kundera JPA entities? or is there any other solution to integrate Kundera and Hibernate? Is this related with the "<property name="kundera.client.property" " (i.e., do I need to define an XML property file for the entities to be supported by Kundera?).

Cheers,

Eduardo

**Comment by mevivs** [comment]
You can mention your classes under "<class>" tag in persistence.xml to specifically load your classes. and do "<excludeUnlist>" to true.

Also have a look at:
http://smecsia.me/blog/74/Developing+the+extension+for+Smartfox+server+using+Maven%2C+Spring%2C+Hibernate+and+Kundera

for more reference.

**Comment by emgsilva** [comment]
Thank you Vivek, this solved my problem!

Here is what I added to my persist.xml:
`
<class>com.domain.data.cassandra.Entity1</class>
<class>com.domain.data.cassandra.Entity2</class>
<exclude-unlisted-classes>true</exclude-unlisted-classes>
`

I suggest you add this configuration to the "configuration" section of the wiki.

Cheers,

Eduardo

**Comment by arturnt** [comment]
This helped me as well. Thanks @emgsilva
