### ISSUE TITLE
Issue with git repo

### ISSUE THREAD

**Issue by masha256** [Impetus/kundera#139]
There is something very strange going on with the Kundera github repo. I am trying to put together a pull request with my local changes but am not able to because when I clone the repo, it shows there are unstaged local changes before I even modify code!

Steps to easily reproduce:

mkdir TOTALLY_NEW_DIR
cd TOTALLY_NEW_DIR
git clone https://github.com/impetus-opensource/Kundera.git
cd Kundera
git status

<pre>
# On branch trunk
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraBooleanTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraByteTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraDoubleTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraFloatTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraLongTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraShortTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraBoolean.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraByte.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraDouble.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraFloat.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraLong.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraShort.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseBooleanTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseByteTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseDoubleTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseFloatTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseLongTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseShortTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseBoolean.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseByte.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseDouble.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseFloat.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseLong.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseShort.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoBooleanTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoByteTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoDoubleTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoFloatTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoLongTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoShortTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoBoolean.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoByte.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoDouble.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoFloat.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoLong.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoShort.java
#
no changes added to commit (use "git add" and/or "git commit -a")
</pre>

I have no idea how its possible for cloning a repo to include UNSTAGED local changes, but somehow its happening. I have tried all the usual ways to drop local changes:

git checkout -- .
git chekout -f
git reset --hard

But it still shows local changes. This even happens when I fork the repo and work in my own repo. The only explanation I was able to come up with is if somehow state files from the .git directory had got into the repo, but when browsing the github file listing, I dont see a .git directory.

Anyway, I am going to still try and create a pull request with my changes but its going to take a little longer to manually skip all the changes files above that I didn't actually change :)

**Comment by xamry** [comment]
We are looking into it

**Comment by mevivs** [comment]
Is it an issue anymore?

-Vivek

**Comment by mevivs** [comment]
Closing. Did not receive any update on this.
