### ISSUE TITLE
Create Keyspace in Hbase

### ISSUE THREAD

**Issue by tvvraju** [Impetus/kundera#14]
Hi, 

I am new to HBase / Kundera.   Could you please help me in creating keyspace/ databse name in HBase. Like create keyspace 'test'.  Also, I have downloaded Kundera examples.  I have seen an entity HAuthor.java.  The @Table annotation contains attributes name and schema.  What does this schema referes to and how to create this using shell command.

Pardon me if this is not the right place for posting.

**Comment by mevivs** [comment]
Hi,
You need to define your persistence.xml for a persistence unit for hbase like this:

<persistence-unit name="hbase">
        <provider>com.impetus.kundera.KunderaPersistence</provider>

```
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="9165" />
        <property name="kundera.keyspace" value="KunderaKeyspace" />
        <property name="kundera.dialect" value="hbase" />
        <property name="kundera.client" value="Hbase" />
        <property name="kundera.cache.provider_class"
            value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
        <property name="net.sf.ehcache.configurationResourceName"
            value="/ehcache-test.xml" />
    </properties>
</persistence-unit>
```

Please change "kundera.nodes", "kundera.port" and "kundera.keyspace"  according to your hbase settings.

Also please create same keyspace in Hbase schema(the one used as a value for "kundera.keyspace")

Kundera will automatically create columnfamily for you.( mentioned with @Table(name=""))

Let me know, if you need anything else.

Sincerely,
Vivek

**Comment by xamry** [comment]
Unlike Cassandra, there is no concept of keyspace in HBase. All tables are stored at the top level. So schema has no meaning for HBase, Kundera will ignore this.

**Comment by xamry** [comment]
Hope your query is resolved. I am closing this issue.
