### ISSUE TITLE
Hangs endlessly in WindowsTerminal.getTerminalHeight()

### ISSUE THREAD

**Issue by fabiankessler** [Impetus/kundera#141]
I followed the demos, and am executing 
entityManager.find(MyClass.class, id)
here it hangs endlessly. It's in WindowsTerminal.getTerminalHeight().
version 2.1

**Comment by fabiankessler** [comment]
It was because I had the gui tool cassandra-cli open. Is that desired behavior?

**Comment by mevivs** [comment]
I don't think so. It must be issue with getting connection from cassandra client. Nothing to do with any gui tool.

**Comment by fabiankessler** [comment]
my setup:
i started cassandra 1.1.6 from the console on windows 7.
then i connected to it with http://code.google.com/p/cassandra-gui (i said cassandra-cli before, but i meant gui) actually i used both, but gui was the problem. that swing app.
then i run my playframework project from another console in debug mode.
then i connected to my play app from idea (remote debugging). 
then i loaded a page in the browser to connect to the play app. that needs cassandra db access. that failed, endless waiting in the forementioned method. 
stopping the cassandra-gui swing app solved it.

**Comment by mevivs** [comment]
closing on this. Looks like not an issue anymore.

-Vivek
