### ISSUE TITLE
Kundera 2.3 feature wishlist.

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#144]
Format should in line with:

DB Name: Cassandra, HBase,Mongo etc.
DB Version:

Feature Description:

Thanks,
Vivek

**Comment by mevivs** [comment]
By : @OleksandrSemenov

DB Name: Cassandra
DB Version: 1.1

It will be good if issues listed below will be implemented
1) Add ability to select several rows by set of keys. For example:
a)Add IN clause support for JPQL. 
b)Or implement Criteria Query API
Unfortunately existing workarounds can do it only via CQL native query, so selects for multiple keys will not be applicable to super column families

**Comment by Pronimo** [comment]
Is there a kind of checklist for what part of JPA spec Kundera supports or leaves out?

**Comment by mevivs** [comment]
Here it is:
https://github.com/impetus-opensource/Kundera/wiki/JPQL

Work on MappedSuperClass is going on and 2.3 release will be released with this.

-Vivek

**Comment by Pronimo** [comment]
That's awesome thanks

**Comment by mevivs** [comment]
HBase versioning support is required.

**Comment by matthewadams** [comment]
DB Name: Cassandra, HBase, Mongo, Neo4j
DB Versions: latest

Feature Description:  Support JDO 3.0 API

The current implementation, based on JPA, is a functional subset of JDO, so much of this work could be done pretty quickly.

**Comment by zhouhero** [comment]
i wish kundera 2.3  can surpport cassandera 1.2!
it's very import for me ,because we are planning to use cassandera 1.2 from now on.
otherwise we will have some troubles in our dep plan.
thank you very much!

**Comment by mevivs** [comment]
Moved to 
https://github.com/impetus-opensource/Kundera/issues/165

Anybody interested to contribute?

-Vivek
