### ISSUE TITLE
Column family definition problem if there is no @Embedded annotation present

### ISSUE THREAD

**Issue by smecsia** [Impetus/kundera#147]
I've tried to use @ElementCollection annotation to persist a collection co-located with my entity like it is advised in the [twitter example](https://github.com/impetus-opensource/Kundera-Examples/wiki/Twitter). 
I'm using kundera.ddl.auto.prepare to create schema automatically, and I've noticed that Kundera creates just a basic ColumnFamily and not SuperColumnFamily . This is because Kundera's metadata scanner checks only for @Embedded annotation and not for @ElementCollection ([here](https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-core/src/main/java/com/impetus/kundera/metadata/processor/TableProcessor.java#L284)).

As a result I'm getting the following exception:

```
InvalidRequestException(why:supercolumn parameter is invalid for standard CF Entity)
```

So the code from the twitter example would not work if there would no @Embedded annotation: 

``` java
@Entity
@Table(name = "USER", schema = "KunderaExamples@twissandra")
public class User {
    @Id    
    @Column(name="USER_ID")
    private String userId;

    // Element collection, will persist co-located
    @ElementCollection
    @CollectionTable(name = "tweeted")
    private List<Tweet> tweets;
}
```

**Comment by kkmishra** [comment]
Thanks smecsia,

Fixed in trunk 
commit no b017c8e6082b2a3dc2a26f8fb29fe07bb2fee339
and 09bfc38af4dccc08b368cd1db89bac50fd4e6a5b

Please verify.

Cheers
kuldeep

**Comment by smecsia** [comment]
Thank you, it is now working as expected.
