### ISSUE TITLE
the parameter can not be set in a update feild when using jpql!

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#149]
when i use parameter in update feild, i"named parameter::datetime not found!" error happend.

my jpql is that:
 "update Test1Entity c set c.datetime = :datetime where c.key = :key"

Can anyone help me ?

**Comment by mevivs** [comment]
Confirming this as a bug. Assigning on priority.

-Vivek

**Comment by zhouhero** [comment]
thank you very much!

**Comment by mevivs** [comment]
Veirifed and fixed in trunk. 2.3 release will have this fix.

**Comment by zhouhero** [comment]
thanks for you reply.
i will try it.

**Comment by zhouhero** [comment]
it seem that this problem has not be fixed now!
could you pls give me a test sample code?

**Comment by mevivs** [comment]
What's the issue you getting with this now?

-Vivek

**Comment by zhouhero** [comment]
when i excuted the fellow jpql. the error happend.

...
String jpql = "update Test1Entity c set c.url = :url where c.key =acca0890-9c29-11e2-95f4-90b11c71b8d4";
query.setParameter(url, "dsdsds  sdsdsd");
....

---

java.lang.NullPointerException
    at com.impetus.kundera.query.KunderaQuery.setParameterValue(KunderaQuery.java:661)
    at com.impetus.kundera.query.KunderaQuery.setParameter(KunderaQuery.java:641)

##     at com.impetus.kundera.query.QueryImpl.setParameter(QueryImpl.java:642)

[my cf]
 create column family test1 with comparator = UTF8Type and key_validation_class=TimeUUIDType and column_metadata =
  [
  {column_name:userid, validation_class:UUIDType}
  {column_name:url, validation_class:UTF8Type}
  {column_name:datetime, validation_class:DateType}
  {column_name:linkcounts, validation_class:Int32Type}
  ];

**Comment by zhouhero** [comment]
could you pls check it me?
thank you very mutch!

**Comment by mevivs** [comment]
I am looking into now. Please share Version of Kundera, you are using?

-Vivek

**Comment by zhouhero** [comment]
it is kundera2.4 + cassandra1.2.3

**Comment by mevivs** [comment]
Please share your yahoo or gtalk id to fix these issues on priority.

-Vivek

**Comment by zhouhero** [comment]
my gmail is : zhouhero@gmail.com

**Comment by mevivs** [comment]
It was partially fixed, i have added a fix for this.

-Vivek

**Comment by zhouhero** [comment]
i have test it.
it work well now.
thank you very much!
