### ISSUE TITLE
TimeUUID with kundera

### ISSUE THREAD

**Issue by sahlex** [Impetus/kundera#15]
Hi.
When I try to use TimeUUIDs as keys kundera tells me:

```
InvalidRequestException(why:UUIDs must be exactly 16 bytes)
```

This is due to the requirement, that the field annotated with _Id_ of an entity has to be of Type _String_.

How do I use TimeUUIDs as key with kundera?

Best regards, Alexander.

**Comment by mevivs** [comment]
I think Kundera does not suport UUID as of now.  

Amry,
A quick fix can be made for this please?

**Comment by kcarlson** [comment]
I have a quick fix for this in PelopsClient and PelopsDataHandler.

See: https://github.com/kcarlson/Kundera/tree/Kundera-2.0.5

**Comment by xamry** [comment]
You can send us a patch and we'll incorporate this change in our coming maintenance release.

**Comment by kcarlson** [comment]
Sure. Do you have a deadline?

**Comment by mevivs** [comment]
Not really. proper fix after review will be incorporated immediately. 

Thanks,
Vivek

**Comment by farukkazmi** [comment]
Hi Kristoffer,
    Does your patch let us use UUID for an ID column too.

Thanks,

Faruk

**Comment by kcarlson** [comment]
Yes it does.

**Comment by farukkazmi** [comment]
Thanks

**Comment by mevivs** [comment]
Support Added for UUID with commit : bdb5fb42ff86e956ddf626f4b54ae8dabd5d4a58

Test case : 
https://github.com/impetus-opensource/Kundera/commit/bdb5fb42ff86e956ddf626f4b54ae8dabd5d4a58#diff-17

-Vivek

**Comment by farukkazmi** [comment]
Vivek,
   is there a way to use cassandra's CounterColumnType in kundera?

Regards,

Faruk

**Comment by mevivs** [comment]
Faruk,
As of now with 2.0.6, i don't think so.

-Vivek

**Comment by farukkazmi** [comment]
Thanks for the prompt reply

Faruk

**Comment by mevivs** [comment]
support added for UUID

**Comment by mevivs** [comment]
Hi Faruk,
CounterColumnType and as well as other counter related stuff will be added in 2.0.7.

**Comment by farukkazmi** [comment]
Thanks Vivek

Regards,

Faruk
