### ISSUE TITLE
"In" key word can not be used in jpql by using cassandra 1.1.5 !

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#151]
When  use "in"  key word in jpql by using cassandra 1.1.5, the following error happend:

" Condition in  is not suported for query on row key! "

but  in cassandra CQL1.3 , "in" can be used.

Can anyone help me get  it working ?

**Comment by mevivs** [comment]
Try using it "nativeQuery" support with Kundera. 
1) Set cql version to 3
2) Execute cql query as em.createNativeQuery or em.getNativeQuery() support.

-Vivek

**Comment by zhouhero** [comment]
Thank you for your answer!  i will try it.
By the way, when using native query , can i set params in cql3 like jpql?
It seem that the parameter setting is not working now by using native cql in cassandra 1.1.5.

**Comment by mevivs** [comment]
AFN setParameter is limited to JPQL/Named query only

-Vivek

**Comment by zhouhero** [comment]
i see,
but i want to using both setting parameter and "in" keyword in my program.
if you can make "in" keyword working in Kundera 2.3, you will help me very mutch!
Thanks!

**Comment by mevivs** [comment]
Just to brief on this, Once we enable support for newly released cassandra jdbc driver(not sure how much stable that is), this will be in.

-Vivek

**Comment by zhouhero** [comment]
by the way, is kundera 2.2  using  pelopes driver to connect to cassandera now?
in the new version(2.3), will it use cassandra jdbc driver directly?

**Comment by mevivs** [comment]
It gives you both option:
1) Pelops client 
2) Thrift client.

3rd will be jdbc driver support.

-Vivek

**Comment by zhouhero** [comment]
i see, i think it will be very good by using jdbc driver in kundera2.3.
when over 10,000 clients are online in my system, witch driver  is best?

**Comment by mevivs** [comment]
jdbc is relatively very new in comparision of thrift protocol and we are working on it. As of now most systems in production are using thrift based clients.

-Vivek

**Comment by zhouhero** [comment]
Thanks you for your support very much!
Looking forward to kundera 2.3 with jdbc driver ....

**Comment by mevivs** [comment]
Parked for release > 2.4

**Comment by zhouhero** [comment]
"in" keyword is can used in JPQL by using kundera 2.4 + cassandra1.2?

**Comment by xamry** [comment]
Not yet,

For detailed listing of keywords supported in JPQL, please see:
https://github.com/impetus-opensource/Kundera/wiki/JPQL

Please let us know if we have missed something.

Sincerely,
Amresh
