### ISSUE TITLE
is kundera 2.2 surpport cassandra 1.2? 

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#157]
as we know, the cassandra 1.2　is released 1/2,
is kundera 2.2 /2.3 surpport cassandra 1.2 now?

**Comment by impetus-opensource-admin** [comment]
Cassandra 1.2 is target candidate for kundera 2.4 release.

-Vivek

**Comment by zhouhero** [comment]
when kundera 2.3/2.4 release in your plan?

**Comment by mevivs** [comment]
2.3 will be releasing by next week(most probably). 2.4 on cards and might be an immediate release. Dates for 2.4 not yet finalized.

-Vivek

**Comment by zhouhero** [comment]
oh, good message!
thank you very much!
looking forward to...

**Comment by mevivs** [comment]
Would request you to provide an update on what feature set you looking for on wish list.

-Vivek

**Comment by zhouhero** [comment]
sorry, what's your mean?

**Comment by mevivs** [comment]
I mean.. feature set you looking for in 2.3/2.4 releases? Please add them into wishlist:
https://github.com/impetus-opensource/Kundera/issues/144

We will try to add them in upcoming releases.

**Comment by zhouhero** [comment]
i have added it.
thank you!
