### ISSUE TITLE
JPA Query using elements that are not part of the key

### ISSUE THREAD

**Issue by emgsilva** [Impetus/kundera#159]
Hi,

I am getting a strange behavior when I try to query a table by a field that is not the "key" of the column/table. For example in the following table:

```
@Id
@Column(name = "domainID")
private String domainID;

@Column(name = "domainDescription")
private String domainDescription;

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER)
@JoinColumn(name="domainID")
private Set<ServiceTypes> serviceTypes;
```

If I query the table (Domain) by the "domainDescription":

```
Query q0 = em.createQuery("select u from Domain u where u.domainDescription = test");
List<Domains> listDomains = q0.getResultList();
```

I get an error:

```
INFO [main] (QueryImpl.java:140) - On getResultList() executing query: select u from Domain u where u.domainDescription = test
ERROR [main] (ThriftClient.java:893) - Error during executing find, Caused by :null
Exception in thread "main" javax.persistence.PersistenceException: InvalidRequestException(why:No indexed columns present in index clause with operator EQ)
    at com.impetus.client.cassandra.thrift.ThriftClient.find(ThriftClient.java:894)
    at com.impetus.client.cassandra.query.CassandraEntityReader.populateRelation(CassandraEntityReader.java:154)
    at com.impetus.client.cassandra.query.CassQuery.recursivelyPopulateEntities(CassQuery.java:191)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:152)
....
```

I am getting this problem together with the one reported in https://github.com/impetus-opensource/Kundera/issues/158

I am using: Kundera 2.2, Cassandra 1.1.6.

**Comment by mevivs** [comment]
If you want to query on non row key columns, then you need to enable secondary indexes over non row key column values. Have a look at: 
http://www.datastax.com/docs/0.7/data_model/secondary_indexes

That's the reason behind error:

```
Exception in thread "main" javax.persistence.PersistenceException: InvalidRequestException(why:No indexed columns present in index clause with operator EQ)
    at com.impetus.client.cassandra.thrift.ThriftClient.find(ThriftClient.java:894)
    at com.impetus.client.cassandra.query.CassandraEntityReader.populateRelation(CassandraEntityReader.java:154)
    at com.impetus.client.cassandra.query.CassQuery.recursivelyPopulateEntities(CassQuery.java:191)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:152)
```

**Comment by emgsilva** [comment]
Hi Vivek,

Thank you for the quick response! Indeed I did not create the "secondary indexes"... Have just created it and it works are it should!

Cheers!

**Comment by pires** [comment]
I'm using `<property name="kundera.ddl.auto.prepare" value="create" />` for generating my keyspace and column familiy on an _embedded_ instance of Cassandra. Given this, how can I create _secondary indexes_? An annotation on the fields I want to use in my WHERE predicates?

**Comment by emgsilva** [comment]
Hi, I am not sure about creating it from Kundera, but you can create them easily in "cqlsh --cql3" using the following command: CREATE INDEX indexname ON table(column) 

see the description in: http://www.datastax.com/docs/1.2/ddl/indexes

**Comment by pires** [comment]
@emgsilva thanks for your help, but what I'm really interested in is having this automagically generated, cause not only it's easier to read code and forget about DDL, but also it's a nice way of having a lot less boilerplate code for testing.

**Comment by mevivs** [comment]
Have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandra.java

for creating secondary indexes via auto schema generation.

**Comment by emgsilva** [comment]
@pires I agree it is “much cleaner” to have the application and kundera driving the creation/update of schemas... unfortunately, I had several problems with this (some months ago when started using Kundera)… and I think is all related with the use of “composite keys” in some tables, so at the time I decided to create this directly using cqlsh and cassandra-cli to create my tables and the secondary indexes.

Today I did some tests and still there are some problems… I report these experiments in a new issue, since they do not have exactly something to do with “secondary indexes” (they do work fine) - take a look in: https://github.com/impetus-opensource/Kundera/issues/239 

Cheers!

**Comment by pires** [comment]
@mevivs thanks, it works :-)
