### ISSUE TITLE
Can i use "LIMIT" keyword in  JPQL when using cassandra 

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#160]
Can i use "LIMIT" keyword in  JPQL when using cassandra ?
as you know CQL can use it now.

**Comment by xamry** [comment]
LIMIT keyword is not supported as of now, but there are two ways we can
achieve this:
1. Using query.setMaxResults(n);
2. Running your CQL (native query) directly by:

Query q = entityManager.createNativeQuery("My CQL Query String",
MyEntity.class);
List<MyEntity> entities = q.getResultList();

Regards,
Amresh

**Comment by zhouhero** [comment]
by the way,
when not do setMaxResults, by default , how many records are return?
※cassandra can return 10,000 records by default.

**Comment by xamry** [comment]
Default is 100 if you not set it. This is consistent with thrift behavior
and Cassandra-cli.

CQL command line returns 10000 results.

Amresh

**Comment by zhouhero** [comment]
thank you very much!
let me try it.

**Comment by zhouhero** [comment]
by the way,
Are setFirstResult, setMaxResults implemented?
how can i do paging by using kundera?

**Comment by zhouhero** [comment]
my db is cassandra.

**Comment by mevivs** [comment]
Pagination support is not yet supported. Cassandra does not offer a way to build cursor like support on db side. Loading everything in-memory and providing implementing custom iterator is possible and we are working on it. But it is going to have extensive memory usage. Also range queries are possible only over OrderedPartitioner(not recommented by casandra), We are planning to build this in future releases.

setFirstResult will make sense once pagination is in place. Alternative way is to fetch first record from returned list of matching results.

-Vivek

**Comment by zhouhero** [comment]
i see,
thank you very much!
by the way , when  kundera 2.3 release?
i have heard that it will be released in  this weekend by planning.

**Comment by mevivs** [comment]
Releasing on 24th.

-Vivek

**Comment by zhouhero** [comment]
it's perfect!!!
Thanks!
