### ISSUE TITLE
Strange behavior on retrieving values on a OneToMany relation

### ISSUE THREAD

**Issue by emgsilva** [Impetus/kundera#163]
Hi,

I am getting a strange behavior on my DB. The DB looks like this:

```
ServiceInstances:
==> OneToMany FollowUpServices
==> OneToMany InstanceClassificationProperties
      ==> OneToMany Values
```

```
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(name="instance_id")
private Set<FollowUpServiceInstances> followUpServices;

@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(name="instance_id")
private Set<InstanceClassificationProperties> instanceClassificationProperties;

```

These tables do not have CompositeKeys, and I created them with cassandra-cli (on Cassandra 1.1.6).

On my tests I could immediately write new entries (ServiceInstances with one FollowUpService and one InstanceClassificationPropertiess, with two Values)... However, when I try to "read" (get) the values associated with the "ServiceInstance" I could not get the values from the InstanceClassProperties and its Values (although I get for the FollowUpServices)... After reading a bit about the Kundera using Cassandra "secondary indexes" I set up the "JoinColumn" of the relations (on the "many" side of the relation) as a "secondary index" (for the InstanceClassificationProperties and Values tables) and now I can get the values normally.

I infer Kundera needs us to set the "JoinColumn" as secondary indexes, is this true? On the other hand, I did not set the "JoinColumn" of FollowUpServices as secondary index, and it simply worked... I have stored (set) the values exactly the same way in the same transaction...

Am I doing something wrong? Please let me know in order to make my development process systematic.

Cheers,

Eduardo

**Comment by mevivs** [comment]
If you do not specify @JoinColumn it will consider field name as a join column field name in datbase. So may be join column field in DB is different from the one declared in entity definition.
I suggest to add @JoinColumn annotation to avoid any such confusion.

Hope it helps,
-Vivek

**Comment by emgsilva** [comment]
I did add the @JoinColumn annotation to both relations, please see:

```
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(name="instance_id")
private Set<FollowUpServiceInstances> followUpServices;

@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(name="instance_id")
private Set<InstanceClassificationProperties> instanceClassificationProperties;
```

Is this what you mean? And yes, these are the names I have on my DB too...

Cheers!

**Comment by mevivs** [comment]
Yes, look ok to me, provided instance_id is the field in DB. You may also refer:
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-tests/src/test/java/com/impetus/kundera/tests/crossdatastore/useraddress/entities

package for association mapping.

Cheers,
-Vivek

**Comment by emgsilva** [comment]
hi Vivek,

It appears to be well defined, checking also from your examples, I also saw the post from your colleague on: http://xamry.wordpress.com/2011/12/15/cross-datastore-persistence-using-kundera/

I am afraid you did not understand my original question, which was: do I need to defined in Cassandra (on the InstanceClassificationProperties table) that "instance_id" is a secondary key in order to get the Set<InstanceClassificationProperties> from the ServiceInstances getter? Basically I only got this get working after I UPDATE the table with the following:

```
UPDATE COLUMN FAMILY instanceclassificationproperties
WITH comparator = UTF8Type
AND key_validation_class=UTF8Type
AND column_metadata = [
{column_name: prop_type, validation_class: UTF8Type}
{column_name: instance_id, validation_class: UTF8Type, index_type: KEYS}
{column_name: usage_count, validation_class: DoubleType}
];
```

Meaning that I had to make the "instance_id" a secondary index in order to get the values from that table...

The weird this was that I did not need to do the same for the other 1-m relation (FollowUpServices)... 

So... is this normal?

Cheers,

Eduardo

**Comment by mevivs** [comment]
Ooh ok. I got it now. If entity A holds 1-m with entity B. Which means row key of entity A has to be present in entity B's column family definition.Handling is pretty similar the way Rdbms does.

**Comment by emgsilva** [comment]
Indeed I understand that. What I do not yet understand is whether or not I need to set that entity as "secondary index" or not (in my case I had to add the "index_type: KEYS" to the "instance_id")... only for one of the 1-m relations, the other worked without adding that.

Is this normal?

Cheers!

**Comment by mevivs** [comment]
This is really weird. As per my understanding, it has to be with "index_type: KEYS"  for all such 1-m relations(on receiving side). It has to be consistent.

Might be it is fetched from cache, else there looks no other way.

-Vivek

**Comment by mevivs** [comment]
Hi Eduardo,
Since we are releasing 2.3 kundera today. Shall i keep it open for 2.4 or close it?

-Vivek

**Comment by emgsilva** [comment]
Hi Vivek,

I am sorry for raising this issue... actually repeating everything from scratch I really had to set all the entities at the JoinColumns of the 1-m relation as "secondary indexes"... I do not remember doing that to the FollowUpServices table yesterday (that is why I raised this issue)... but I must have made that by mistake. 

Nevertheless, I can now make sure I will always do define the "secondary index" on these "JoinColumns" entities (I was not sure of that before).

Thank you for the feedback! Cheers,

Eduardo

**Comment by emgsilva** [comment]
I think we can close it, I do not remember making the mistake but I must have done so, from what I can see of my experiments today. Cheers!
