### ISSUE TITLE
JPA Annatations at Method Level

### ISSUE THREAD

**Issue by nick2013** [Impetus/kundera#164]
My understanding is that Entity beans can have their field level annotations placed on either the instance variables or the getter methods.  Kundera is failing to find @Id tags when they are on the getter method (I have not tested the other attributes).

I am using 2.2.1 against Cassandra 1.2 on Java 1.6 1.6.0_24 on Windows 7 Pro 64bit.

**Comment by ravindranathakila** [comment]
Last time I checked Kundera didn't support property based annotations.
You'll have to port them to fields. Hth.

**Comment by nick2013** [comment]
That's what I am seeing.  so I suppose this "Issue" is an enhancement request to add support.

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/issues/24

Any body interested to pick this one as well?

-Vivek

**Comment by mevivs** [comment]
Closing. Keep tracking with #24
