### ISSUE TITLE
Kundera 2.6 feature wishlist.

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#165]
Format should in line with:

DB Name: Cassandra, HBase,Mongo etc.
DB Version:

Feature Description:

Thanks,
Vivek

**Comment by mevivs** [comment]
By : @OleksandrSemenov

DB Name: Cassandra
DB Version: 1.1

It will be good if issues listed below will be implemented
1) Add ability to select several rows by set of keys. For example:
a)Add IN clause support for JPQL.
b)Or implement Criteria Query API
Unfortunately existing workarounds can do it only via CQL native query, so selects for multiple keys will not be applicable to super column families

**Comment by mevivs** [comment]
@matthewadams

DB Name: Cassandra, HBase, Mongo, Neo4j
DB Versions: latest

Feature Description: Support JDO 3.0 API

The current implementation, based on JPA, is a functional subset of JDO, so much of this work could be done pretty quickly.

**Comment by rramdin** [comment]
DB Name: Cassandra
DB Versions: latest

Feature Description: Support DecimalType with BigDecimal

Currently, it seems that BigDecimals get truncated into integers. It would be nice if BigDecimals could be stored as Cassandra DecimalTypes (decimal in cql).

**Comment by kkmishra** [comment]
Hi rramdin,
It's already supported moving decimal type issue for discussion,
issue :-
https://github.com/impetus-opensource/Kundera/issues/169

Thanks 
Kuldeep

**Comment by joaonlima** [comment]
DB Name: Cassandra
DB Version: 1.2

Feature Description: Support for @ManyToMany

**Comment by mevivs** [comment]
ManyToMany is already supported for all databases.

-Vivek

**Comment by joaonlima** [comment]
Great.. Due to [this page](https://github.com/impetus-opensource/Kundera-Examples/wiki/Introduction) I thought it was not. Thanks.

**Comment by xamry** [comment]
This (KunderaExamples) is an outdate project and is not updated. It was
originally meant for demonstrating sample codes and examples  using
kundera.

As is written on its home page, all code examples have been moved to
Kundera (https://github.com/impetus-opensource/Kundera).

Thanks for bringing this to our attention, we'll delete this project once
we are sure we're not going to lose any useful content.

Regards,
Amresh

**Comment by pdirksen** [comment]
Please implement getSingleResult() for Queries. Pleeeease...^^

**Comment by mevivs** [comment]
Yes. I guess, getSingleResult() should work as an alternative path as:

query.setMaxResults(1) and then query.getResultList().

-Vivek

**Comment by pranav-gopi** [comment]
DB Name: MongoDB
DB Version: 

Please add support for JPA 2.1  (@Index annotations in specific). 

-Pranav
