### ISSUE TITLE
Why is deleted data visible after compaction

### ISSUE THREAD

**Issue by sahlex** [Impetus/kundera#17]
Hi.

If I delete data using kundera, it's keys are still visible even after compaction has been done and the cli command _list cf-name_ doesn't show the deleted values any more. 

How so?

Alexander.

**Comment by mevivs** [comment]
This is the issue with Cassandra itself. It mark row key as soft delete. 

Try deleting from cassandra-cli itself.

---

 From: sahlex reply@reply.github.com
To: mevivs vivek.mishra@yahoo.com 
Sent: Tuesday, January 3, 2012 8:20 PM
Subject: [Kundera] Why is deleted data visible after compaction (#17)

Hi.

If I delete data using kundera, it's keys are still visible even after compaction has been done and the cli command _list cf-name_ doesn't show the deleted values any more. 

How so?

Alexander.

---

Reply to this email directly or view it on GitHub:
https://github.com/impetus-opensource/Kundera/issues/17

**Comment by sahlex** [comment]
Yes I tried that already. I think, the lucene index has still a reference to the keys and thus show them as empty objects.
Is there a way to look to the lucene index?

**Comment by mevivs** [comment]
Hmm...u can use lukall.

But i think as cassandra mark them as soft delete and returning back only rowkey populated as an object. THat's why it is coming as empty object. Lucene indexing is not used to populate object data. it is purly for indexing purpose only!

**Comment by mevivs** [comment]
on delete..even indexes should also get removed!

**Comment by sahlex** [comment]
Agreed. but have a look at this:

From cassandra cli: list LogEvent;

<pre>

Using default limit of 100
-------------------
RowKey: cfcb3c30-35f8-11e1-a9d3-0a0027000000
=> (column=level, value=INFO, timestamp=1325587855219)
=> (column=message, value=Test entry, timestamp=1325587855219)
=> (column=timestamp, value=2012-01-03 11:50:55+0100, timestamp=1325587855219)
-------------------
RowKey: cf5289c0-35f8-11e1-a9d3-0a0027000000
=> (column=level, value=INFO, timestamp=1325587854428)
=> (column=message, value=Test entry, timestamp=1325587854428)
=> (column=timestamp, value=2012-01-03 11:50:54+0100, timestamp=1325587854428)
-------------------
RowKey: d0195c30-35f8-11e1-a9d3-0a0027000000
=> (column=level, value=INFO, timestamp=1325587855731)
=> (column=message, value=Test entry, timestamp=1325587855731)
=> (column=timestamp, value=2012-01-03 11:50:55+0100, timestamp=1325587855731)
-------------------
RowKey: cff49620-35f8-11e1-a9d3-0a0027000000
=> (column=level, value=INFO, timestamp=1325587855491)
=> (column=message, value=bla bla, timestamp=1325598232793000)
=> (column=timestamp, value=2012-01-03 11:50:55+0100, timestamp=1325587855491)
-------------------
RowKey: cfa53da0-35f8-11e1-a9d3-0a0027000000
=> (column=level, value=INFO, timestamp=1325587854970)
=> (column=message, value=Test entry, timestamp=1325587854970)
=> (column=timestamp, value=2012-01-03 11:50:54+0100, timestamp=1325587854970)
-------------------
RowKey: 68490cb0-354c-11e1-99df-0a0027000000
=> (column=level, value=INFO, timestamp=1325513814537)
=> (column=message, value=KunderaExample started, timestamp=1325513814537)
=> (column=timestamp, value=2012-01-02 15:16:48+0100, timestamp=1325513814537)
-------------------
RowKey: d038a400-35f8-11e1-a9d3-0a0027000000
=> (column=level, value=INFO, timestamp=1325587855936)
=> (column=message, value=Test entry, timestamp=1325587855936)
=> (column=timestamp, value=2012-01-03 11:50:55+0100, timestamp=1325587855936)

7 Rows Returned.
Elapsed time: 29 msec(s).
</pre>


From 

``` java
Query q = em.createQuery("select e from LogEvent e");
List<LogEvent> list = q.getResultList();
```

comes:

``` xml
<logEvents>
<logEvent id="d0195c30-35f8-11e1-a9d3-0a0027000000" level="INFO" timestamp="1325587855731">
<Message>Test entry</Message>
</logEvent>
<logEvent id="cf5289c0-35f8-11e1-a9d3-0a0027000000" level="INFO" timestamp="1325587854428">
<Message>Test entry</Message>
</logEvent>
<logEvent id="d038a400-35f8-11e1-a9d3-0a0027000000" level="INFO" timestamp="1325587855936">
<Message>Test entry</Message>
</logEvent>
<logEvent id="cfcb3c30-35f8-11e1-a9d3-0a0027000000" level="INFO" timestamp="1325587855219">
<Message>Test entry</Message>
</logEvent>
<logEvent id="cff49620-35f8-11e1-a9d3-0a0027000000" level="INFO" timestamp="1325587855490">
<Message>bla bla</Message>
</logEvent>
<logEvent id="cfa53da0-35f8-11e1-a9d3-0a0027000000" level="INFO" timestamp="1325587854970">
<Message>Test entry</Message>
</logEvent>
<logEvent id="869bfeb0-35f7-11e1-a9d3-0a0027000000" timestamp="1325673085694"/>
<logEvent id="cebc6440-35f8-11e1-a9d3-0a0027000000" timestamp="1325673085695"/>
</logEvents>
```

One message has been created from within the cli, so the EntityManager cannot show this, because the index does not know about it.
The ones that have no fields but are selected by the entity manager have been deleted using the entity manager. These have been thrown away by cassandra (not visible in the cli). But the entity manager still finds them!

**Comment by mevivs** [comment]
i need to debug  this issue then..it should not populate it. unless underlying cassandra client(Pelops) return it back!

**Comment by mevivs** [comment]
Version of cassandra used?

**Comment by sahlex** [comment]
Cassandra version: 1.0.6

**Comment by mevivs** [comment]
2.0.5 will have this fixed alongwith 1.x cassandra migration task.

**Comment by sahlex** [comment]
Nice to hear...

**Comment by mevivs** [comment]
Thanks.. Just to elaborate on this. It is a known issue with cassandra 0.8.x releases. Can be easily reproduced. So witht 2.0.5 we are advancing kundera to Cassandra 1.x release, which will resolve it automatically.

Thanks,
Vivek
