### ISSUE TITLE
i can not insert the entity  witch's row key is  same as the entity i deleted!

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#173]
i can not insert the entity e2 witch's row key is  same as the entity e1 i deleted.
can anyone help me? my code is as felow:

---

...
Entity e1 = entityManeger.find("XXXX);
entityManeger.remove(e1);
entityManeger.clear();
Entity e2 = new Entity ();
e2.setRowKey(e1.getRowKey());
entityManeger.persist(e2);

**Comment by mevivs** [comment]
One question, Using ThriftClientFactory or PelopsClientFactory? We recommend to use ThriftClientFactory, which is much updated as there is no more current development going on with pelops api.

Please have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandraTest.java

Test case: onDeleteThenInsertCassandra()

**Comment by zhouhero** [comment]
thanks for your answer.

i have tried ThriftClientFactory  in kundera2.2, it worked well.
but i can not do it in kundera2.3, because when i using 2.3 by using ThriftClientFactory ,
the connection pooling problems has happend!
by the way,my cassandra version is 1.6

**Comment by mevivs** [comment]
What is the problem you getting with Thirfit client factory connection pooling in 2.3? 

-Vivek

**Comment by zhouhero** [comment]
when using kundera 2.3 , the dead loop happend. i can not connect to cassandra 1.1.6.
but it is ok when connect to kundera 1.2. 
by the way , I find that the cassandra driver jar files are cassandra-thrift-1.2.0.jar,   cassandra-all-1.2.0.jar 
by default in kundera 2.3.  In kundra 2.2 it is 1.1.6.

---

Creating JMX MBean
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435248]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435295]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435343]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435390]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435436]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435483]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435529]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435576]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435624]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435672]
ConnectionPool initialized.
Creating JMX MBean
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435248]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435295]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435343]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435390]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435436]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435483]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435529]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435576]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435624]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435672]
ConnectionPool initialized.
Creating JMX MBean
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435248]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435295]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435343]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435390]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435436]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435483]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435529]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435576]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435624]
[Cassandra Connection Pool[76-1714730435]] Obtained a new connection to [192.168.0.227,status=true,timestamp=1359678435672]
ConnectionPool initialized.
......

**Comment by mevivs** [comment]
2.3 is migrated to Cassndra 1.2.0 thrift jars as part of migration to cassandra 1.2. I will look into if there is any backward compatibility issue with Cassandra 1.2 jars(ideally there shouldn't be any)

-Vivek

**Comment by mevivs** [comment]
Cassandra 1.2 is not backward compatible with 1.1.6 . So you need to migrate to cassandra 1.2

-Vivek

**Comment by zhouhero** [comment]
can i migrate use kundera 2.3 +  cassandraXXX 1.1.6.jar  by myself?

**Comment by mevivs** [comment]
You may try it by changing in pom.xml for cassandra versions. However i believe we migrated to 1.2 version as i guess you were looking for it :)

**Comment by mevivs** [comment]
Shall we close on this?

-Vivek

**Comment by zhouhero** [comment]
when i changed to thrift client, it working well now.
