### ISSUE TITLE
HBaseClientFactory ignores 'kundera.port' property

### ISSUE THREAD

**Issue by lucarosellini** [Impetus/kundera#175]
I don't know this the right behaviour, but it seems that HBaseClientFactory is incorrectly overwriting the value of 'kundera.port' with the constant "2181".
See: https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-hbase/src/main/java/com/impetus/client/hbase/HBaseClientFactory.java#L114

I think this should be changed to something like: <code>hadoopConf.set("hbase.zookeeper.property.clientPort", port == null ? "2181" : port);</code>

Luca

**Comment by mevivs** [comment]
Thanks! It is indeed completely incorrect. Change committed as suggested by you

Cheers,
-Vivek

**Comment by mevivs** [comment]
Hi,
My Bad, change reverted. It is not an issue. port defined in persistence.xml is "Hbase master port" and default port for zookeeper is 2181. To override default zookeeper port we need to provide it as an external configuration by providing configuration xml files.
Have a look at: 
https://github.com/impetus-opensource/Kundera/wiki/HBase-Specific-Features
on how to override such port settings.

Thanks Kuldeep.

-Vivek

**Comment by mevivs** [comment]
Shall we close on this?

-Vivek

**Comment by lucarosellini** [comment]
Hello Vivek,
Even though the zookeeper configuration should be provided in an external configuration file, I still think it's misleading to silently override 'kundera.port' while honoring the companion 'kundera.nodes' property.

Luca

**Comment by mevivs** [comment]
Hmm. Just to explain given code snippet:

```
   if (conn != null && conn.getProperties() != null)
        {
            String zookeeperHost = conn.getProperties().getProperty("hbase.zookeeper.quorum");
            String zookeeperPort = conn.getProperties().getProperty("hbase.zookeeper.property.clientPort");
            hadoopConf.set("hbase.zookeeper.quorum", zookeeperHost != null ? zookeeperHost : node);
            hadoopConf.set("hbase.zookeeper.property.clientPort", zookeeperPort != null ? zookeeperPort : DEFAULT_ZOOKEEPER_PORT);
        }
        else
        {
            // in case "hbase.zookeeper.property.clientPort" is not supplied, it is different than hbase master port!
            hadoopConf.set("hbase.zookeeper.quorum", node);
            hadoopConf.set("hbase.zookeeper.property.clientPort", DEFAULT_ZOOKEEPER_PORT);
        }

```

IF block is responsible to override zookeeper host and port, if supplied as part of external configuration(e.g. config.xml). Else part is responsible to provide default configuration, which considers zookeeper is running on same machine as with HBase master with default port as "2181".

I guess it helps. I agree this could be re factored for better.

Cheers,
-Vivek

**Comment by mevivs** [comment]
Closing on this. Not an issue anymore.
