### ISSUE TITLE
Unable to run Kundera 2.3 over play2.0 framework

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#177]
Raised by emin over kundera-discuss

On Monday, February 4, 2013 10:28:12 PM UTC+5:30, emin wrote:
Hi, I have tried to use kundera to connect cassandra with play framework for almost a week. Everytime different exceptions and bugs really. I would like to share my project so that you can help me really. Download link: http://ge.tt/5aKieRX/v/0?c 

As I undersood play can connect cassandra but It doesn't recognize @Entity class. And as I know I dont need to create column family for the @Entity class in cassandra , just creating keyspace is enough. I started my cassandra like that
...cassandra-1.1.9>bin\cassandra -f
...cassandra-1.1.9>bin\cassandra-cli -host localhost -port 9160

And it is working, I insert data fro -cli.
I am getting this error. I am really waiting for your help. 

C:\Users\eminavci\workspace\deneme6>play run
[info] Loading project definition from C:\Users\eminavci\workspace\deneme6\project
[info] Set current project to deneme6 (in build file:/C:/Users/eminavci/workspace/deneme6/)
--- (Running the application from SBT, auto-reloading is enabled) ---

**Comment by xamry** [comment]
Can you please share full stacktrace (can't see it here as it's truncated)

**Comment by xamry** [comment]
I have tested this for Cassandra and MongoDB. Please have a look at: 
http://xamry.wordpress.com/2013/07/06/play-nosql-building-nosql-applications-with-play-framework/

**Comment by xamry** [comment]
Tested and documentation added, closing
