### ISSUE TITLE
HBaseSchemaManager does not enable tables after schema update

### ISSUE THREAD

**Issue by lucarosellini** [Impetus/kundera#178]
Hello,
with 'kundera.ddl.auto.prepare' configured to 'update', the update method in HBaseSchemaManager does not enable the disabled tables after the update.

Is this the correct behavior? why?

Thanks,
Luca

**Comment by mevivs** [comment]
I guess it is not a correct behavior. Looks like a fix has been provided for the same.

-Vivek

**Comment by mevivs** [comment]
Fixed. Releasing with 2.4

**Comment by xamry** [comment]
Fixed and released
