### ISSUE TITLE
com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by weburnit** [Impetus/kundera#181]
I got this error when em.persist and Model Object to MongoDB

**Comment by mevivs** [comment]
Can you please more details, such as:
1) Kundera version
2) Entity definition
3) CRUD code snippet etc.

Please have a look at: 
https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes

for quick reference.

-Vivek

**Comment by kkmishra** [comment]
Is it still not working for you? If you could send more details like your entity classes and CRUD code, we would be able to identify cause and fix this.

**Comment by mevivs** [comment]
Closing as no response received.

-Vivek
