### ISSUE TITLE
cql3 can not be excuted in the env( kundera 2.3 + cassandra 1.1.X )

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#184]
when i excute cql3 by kundera 2.3 + cassandra 1.1.X, 
the folowing exception happend.

[Exception]
javax.persistence.PersistenceException: org.apache.thrift.TApplicationException: Invalid method name: 'execute_cql3_query'

could you please confirm and fix it in kundera 2.3.1?

**Comment by xamry** [comment]
Can you please upgrade to Cassandra 1.2.0 and check whether it persists.

The reason this happened is because in newer version of Thrift,
implementation has changed for running CQL 3 queries that throws this error
in your scenario.

Sincerely,
Amresh

**Comment by zhouhero** [comment]
As you know that cassandra 1.2.0 can not do well in the table created by cql3.
By the way, when i create the table by thrift-client(not by cql3),
i can not do using the PK by name in the cql3 in kundera as you know  the PK name is not can be defined 
when creating the column family.

**Comment by mevivs** [comment]
Kundera is upgraded to 1.2 cassandra thrift(except CQL binary protocol). As per error, looks like  Cassandra is complaining for this.
Also, can you please elaborate more on: 

"
By the way, when i create the table by thrift-client(not by cql3),
i can not do using the PK by name in the cql3 in kundera as you know the PK name is not can be defined 
when creating the column family.
"

-Vivek

**Comment by mevivs** [comment]
2.5 release will work seamlessly for CQL and Thrift interoperability.

-Vivek

**Comment by zhouhero** [comment]
can you tell me when kundera 2.4 ,2.5 release?

**Comment by mevivs** [comment]
2.4 should be releasing in a week or so.
I would recommend not to intermix things
-Vivek

**Comment by zhouhero** [comment]
thanks very much!

**Comment by mevivs** [comment]
Cassandra 1.1.x does not have methods like "execute_cql3_query", which is available in cassandra 1.2 release.
We have planned and started working on this interoperability issue.

-Vivek
