### ISSUE TITLE
JPA2 support w/mongo

### ISSUE THREAD

**Issue by envisager** [Impetus/kundera#186]
Pulled down latest kundera (2.3) via maven so as to try mongo integration. As per instructions updated repository and dependency information. Maven fails because unable to find javax.persistence v2. Review of nexus only find v1 variants. 
What is the fix?

**Comment by mevivs** [comment]
```
https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
    version="2.0">
```

This should work for you.

-Vivek
