### ISSUE TITLE
how to identify target collection with mongo

### ISSUE THREAD

**Issue by envisager** [Impetus/kundera#187]
I can find nothing in the documentation on how to specify a target collection for reading or writing

**Comment by mevivs** [comment]
Can you please provide bit miore details around this issue?

-Vivek

**Comment by mevivs** [comment]
In case, you looking for how to perform simple CRUD operation:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java

PersonMongo is mapped over PERSON collection in MongoDB.

-Vivek

**Comment by xamry** [comment]
Closing.
