### ISSUE TITLE
PersistenceDelegator lock

### ISSUE THREAD

**Issue by lucarosellini** [Impetus/kundera#188]
Hello,
This is not really an issue, it's more of an explanation request.

I have a multi-threaded enviroment, each thread, among other things, persists in an hbase column family rows with a wide column (>1MB). 
The write operation seem to be very slow and threads keep accumulating over the lock in persistence delegator (https://github.com/impetus-opensource/Kundera/blob/2.3.1/kundera-core/src/main/java/com/impetus/kundera/persistence/PersistenceDelegator.java#L163).

Is there a way to elegantly solve this use-case using kundera? 
Do you have any suggestion?

Thanks,
Luca

**Comment by mevivs** [comment]
Read & Write lock is definitely needed to ensure concurrent write/read safety.  You may try by creating seperate entity manager for each thread.

i will have a look, anything else i can find as an alternative.
-Vivek

**Comment by mevivs** [comment]
Let me know, if it works for you.

-Vivek

**Comment by lucarosellini** [comment]
Seems to work Vivek, thank you very much.

**Comment by mevivs** [comment]
Great. shall we close on this?

Cheers,
-Vivek

**Comment by mevivs** [comment]
Closing. Looks like it is fine now.

-Vivek

**Comment by lucarosellini** [comment]
Unfortunately, the suggestion made by Vivek doesn't work, I am really sorry to having told you the opposite last week, my bad.
I've done many more tests and the result is always having threads waiting on the lock. 
Instantiating a new entity manager for each thread doesn't help because the ReentrantReadWriteLock inis declared as static final in PersistenceDelegator.
Vivek, could you plase elaborate a little more in detail from what  kind of data corruption is the lock trying to prevent?  

Thanks,
Luca

**Comment by mevivs** [comment]
Hi,
This has been rectified now. Please take update, it should work for you.

-Vivek

**Comment by mevivs** [comment]
Vivek, could you plase elaborate a little more in detail from what kind of data corruption is the lock trying to prevent?

If multiple threads are joined in with same persistence context, so reentarant locking is to ensure there should not be any dirty reads

-Vivek

**Comment by lucarosellini** [comment]
With this implementation two different threads are considered to belong to the same persistence context just for the fact that they run in the same JVM, without taking into account the persistence unit. Is this correct?

**Comment by mevivs** [comment]
Yes. So basically, if you have multiple threads with in same persistence context( same entity manager instance), this locking would ensure to prevent dirty reads in case of frequent read/write. Ofcourse you will create entity manager instance for a specific persistence unit configuration only!  Lifecycle of a persistence delegator instance is bound with entity manager instance.

In case of Application manager persistence context, it is possible to create single instance of entity manager but you may spoon multiple processing threads for concurrent processing, so this locking would ensure no dirty reads(can say consistency).   

Hope it makes sense :)

Cheers,
-Vivek

**Comment by mevivs** [comment]
Are we good to close on it?

**Comment by mevivs** [comment]
Closing.

-Vivek
