### ISSUE TITLE
Paging results from query

### ISSUE THREAD

**Issue by robgratz** [Impetus/kundera#191]
I have a requirement that I page over the results of what could be a large column family of data.  Based on what I've gathered from the code, there is no way to "skip n records" to a certain point in the result set (there is a TODO in the code to set starting point) and the implementation of the list that is returned from the query is an ArrayList (CassandraClient.find()) which means all results have to fit in memory.  So, I guess my question is how do I perform paging over a large set of data?  Any help is greatly appreciated.  Thanks.

**Comment by mevivs** [comment]
Work in progress and next release ( > 2.4) will provide this support.

-Vivek

**Comment by mevivs** [comment]
This has been supported for Cassandra/HBase in 2.6 release.
