### ISSUE TITLE
com.impetus.client.cassandra.pelops.PelopsClientFactory required for kunendra-mongodb

### ISSUE THREAD

**Issue by ralmodiel** [Impetus/kundera#192]
Hi,

I'm using kundera-mongo v2.3.1 but it is looking for a class in the kundera-cassandra package.  

```
    <dependency>
        <groupId>com.impetus.client</groupId>
        <artifactId>kundera-mongo</artifactId>
        <version>2.3.1</version>
    </dependency>
```

I included kundera-cassandra in my pom.xml file, but I hope to remove it in the future to deploy cleaner package.   Thanks!.

<error message="Couldn&apos;t instantiate class" type="com.impetus.kundera.client.ClientResolverException">com.impetus.kundera.client.ClientResolverException: Couldn&apos;t instantiate class
    at com.impetus.kundera.client.ClientResolver.onError(ClientResolver.java:161)
    at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:124)
    at com.impetus.kundera.configure.ClientFactoryConfiguraton.configure(ClientFactoryConfiguraton.java:68)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:104)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:77)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)

</error>

**Comment by mevivs** [comment]
This could only happen if in your persistence.xml, you have a reference to PelopsClientFactory. Please verify your persistence.xml, or another possibility is any reference jar containing persistence.xml with a reference to PelopsclientFactory! may be a test package?

-Vivek

**Comment by mevivs** [comment]
Please share your pom.xml and persistence.xml 

-Vivek

**Comment by ralmodiel** [comment]
I realized I have it in my persistence.xml as I have just extracted it from some sample codes.  What's the correct kundera.client.lookup.class for mongodb?

<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="test">
        <provider>com.impetus.kundera.KunderaPersistence</provider>  
        <properties>  
            <property name="kundera.nodes" value="test"/>
            <property name="kundera.port" value="27017"/>
            <property name="kundera.keyspace" value=""/>
            <property name="kundera.dialect" value="mongodb"/>
            <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>  
        </properties>  
    </persistence-unit>
</persistence>

**Comment by mevivs** [comment]
Please refer:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/resources/META-INF/persistence.xml

for correct configuration.

Cheers,
-Vivek

**Comment by ralmodiel** [comment]
Thanks! really great support! Highly appreciated.

**Comment by mevivs** [comment]
Shall we close this one?

**Comment by ralmodiel** [comment]
yes :-) thanks
