### ISSUE TITLE
Auto Generated Column names garbled

### ISSUE THREAD

**Issue by rickcole3-yahoo** [Impetus/kundera#197]
When I set Kundera to automatically generate my columns, they appear as a series of hex characters. This appears to be the bytes that are in the ByteBuffer that holds the name of the columns. When this happens, none of my JPA queries work (or any query for that matter). I am running with kundera 2.4-SNAPSHOT as of today. Is this correct?

CREATE KEYSPACE platform WITH replication = {
  'class': 'SimpleStrategy',
  'replication_factor': '3'
};

USE platform;

D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519: UnexpectedTableStructure: Unexpected table structure; may not translate correctly to CQL. Compact storage CF event_log has no column aliases, but comparator is not UTF8Type.
CREATE TABLE event_log (
  key text PRIMARY KEY,
  "6c6162656c" text,
  "6c6576656c" text,
  "6c6f674e616d65" text
) WITH COMPACT STORAGE AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'SnappyCompressor'};

CREATE INDEX event_log_6c6f674e616d65_idx ON event_log ("6c6f674e616d65");

D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519: UnexpectedTableStructure: Unexpected table structure; may not translate correctly to CQL. Compact storage CF manager_property has no column aliases, but comparator is not UTF8T
ype.
CREATE TABLE manager_property (
  key blob PRIMARY KEY,
  "76616c7565" text,
  "76616c7565436c6173734e616d65" text
) WITH COMPACT STORAGE AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'SnappyCompressor'};

D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519: UnexpectedTableStructure: Unexpected table structure; may not translate correctly to CQL. Compact storage CF separator has no column aliases, but comparator is not UTF8Type.
CREATE TABLE separator (
  key blob PRIMARY KEY,
  "726561644f6e6c79" boolean,
  "76616c7565" text
) WITH COMPACT STORAGE AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'SnappyCompressor'};

D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519: UnexpectedTableStructure: Unexpected table structure; may not translate correctly to CQL. Compact storage CF server has no column aliases, but comparator is not UTF8Type.
CREATE TABLE server (
  key text PRIMARY KEY,
  "636f6e6e656374696f6e54696d656f7574" varint,
  "686f7374" text,
  "6d6963726f626174636853697a65" varint,
  "6e616d65" text,
  "70617373776f7264" text,
  "706f7274" varint,
  "736563757265" boolean,
  "757365726e616d65" text
) WITH COMPACT STORAGE AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'SnappyCompressor'};

CREATE INDEX server_6e616d65_idx ON server ("6e616d65");

**Comment by kkmishra** [comment]
Hi,
To specify comparator type for column families and other configuration, you
should provide data-store specific configuration in xml file, for structure
of xml, please see link below
https://github.com/impetus-opensource/Kundera/wiki/Cassandra-Specific-Features

and then specify xml file path in persistence-unit property tag.

sample xml is here
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-core/src/test/resources/kunderaTest.xml

sample persistence-unit is here

```
<persistence-unit name="metaDataTest">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="9160" />
        <property name="kundera.keyspace" value="KunderaMetaDataTest" />
        <property name="kundera.dialect" value="cassandra" />
        <property name="kundera.client.lookup.class"
            value="com.impetus.kundera.cache.ehcache.CoreTestClientFactory" />
        <property name="kundera.cache.provider.class"
            value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
        <property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
        *<property name="kundera.client.property" value=**"kunderaTest.xml*" />
    </properties>
</persistence-unit>
```

Thanks
Kuldeep

On Wed, Mar 6, 2013 at 4:55 AM, rickcole3 notifications@github.com wrote:

> When I set Kundera to automatically generate my columns, they appear as a
> series of hex characters. This appears to be the bytes that are in the
> ByteBuffer that holds the name of the columns. When this happens, none of
> my JPA queries work (or any query for that matter). I am running with
> kundera 2.4-SNAPSHOT as of today. Is this correct?
> 
> CREATE KEYSPACE platform WITH replication = {
> 'class': 'SimpleStrategy',
> 'replication_factor': '3'
> };
> 
> USE platform;
> 
> D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519:
> UnexpectedTableStructure: Unexpected table structure; may not translate
> correctly to CQL. Compact storage CF event_log has no column aliases, but
> comparator is not UTF8Type.
> CREATE TABLE event_log (
> key text PRIMARY KEY,
> "6c6162656c" text,
> "6c6576656c" text,
> "6c6f674e616d65" text
> ) WITH COMPACT STORAGE AND
> bloom_filter_fp_chance=0.010000 AND
> caching='KEYS_ONLY' AND
> comment='' AND
> dclocal_read_repair_chance=0.000000 AND
> gc_grace_seconds=864000 AND
> read_repair_chance=0.100000 AND
> replicate_on_write='true' AND
> compaction={'class': 'SizeTieredCompactionStrategy'} AND
> compression={'sstable_compression': 'SnappyCompressor'};
> 
> CREATE INDEX event_log_6c6f674e616d65_idx ON event_log ("6c6f674e616d65");
> 
> D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519:
> UnexpectedTableStructure: Unexpected table structure; may not translate
> correctly to CQL. Compact storage CF manager_property has no column
> aliases, but comparator is not UTF8T
> ype.
> CREATE TABLE manager_property (
> key blob PRIMARY KEY,
> "76616c7565" text,
> "76616c7565436c6173734e616d65" text
> ) WITH COMPACT STORAGE AND
> bloom_filter_fp_chance=0.010000 AND
> caching='KEYS_ONLY' AND
> comment='' AND
> dclocal_read_repair_chance=0.000000 AND
> gc_grace_seconds=864000 AND
> read_repair_chance=0.100000 AND
> replicate_on_write='true' AND
> compaction={'class': 'SizeTieredCompactionStrategy'} AND
> compression={'sstable_compression': 'SnappyCompressor'};
> 
> D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519:
> UnexpectedTableStructure: Unexpected table structure; may not translate
> correctly to CQL. Compact storage CF separator has no column aliases, but
> comparator is not UTF8Type.
> CREATE TABLE separator (
> key blob PRIMARY KEY,
> "726561644f6e6c79" boolean,
> "76616c7565" text
> ) WITH COMPACT STORAGE AND
> bloom_filter_fp_chance=0.010000 AND
> caching='KEYS_ONLY' AND
> comment='' AND
> dclocal_read_repair_chance=0.000000 AND
> gc_grace_seconds=864000 AND
> read_repair_chance=0.100000 AND
> replicate_on_write='true' AND
> compaction={'class': 'SizeTieredCompactionStrategy'} AND
> compression={'sstable_compression': 'SnappyCompressor'};
> 
> D:\devtools\apache-cassandra-1.2.1a\bin..\pylib\cqlshlib\cql3handling.py:1519:
> UnexpectedTableStructure: Unexpected table structure; may not translate
> correctly to CQL. Compact storage CF server has no column aliases, but
> comparator is not UTF8Type.
> CREATE TABLE server (
> key text PRIMARY KEY,
> "636f6e6e656374696f6e54696d656f7574" varint,
> "686f7374" text,
> "6d6963726f626174636853697a65" varint,
> "6e616d65" text,
> "70617373776f7264" text,
> "706f7274" varint,
> "736563757265" boolean,
> "757365726e616d65" text
> ) WITH COMPACT STORAGE AND
> bloom_filter_fp_chance=0.010000 AND
> caching='KEYS_ONLY' AND
> comment='' AND
> dclocal_read_repair_chance=0.000000 AND
> gc_grace_seconds=864000 AND
> read_repair_chance=0.100000 AND
> replicate_on_write='true' AND
> compaction={'class': 'SizeTieredCompactionStrategy'} AND
> compression={'sstable_compression': 'SnappyCompressor'};
> 
> CREATE INDEX server_6e616d65_idx ON server ("6e616d65");
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/197
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by mevivs** [comment]
Thanks Kuldeep. Is this still an issue? However i think we should consider column name as UTF8Type as default.

-Vivek

**Comment by xamry** [comment]
Fixed in trunk
