### ISSUE TITLE
External configuration for RDBMS persistence units

### ISSUE THREAD

**Issue by cjaeger** [Impetus/kundera#199]
Hi,

is there a way to <strong>externalize the configuration</strong> (especially <i>url, username, password</i>) when using a <strong>RDBMS</strong> database<br>like <i>MySQL</i>? I followed the tutorial for cross datastore persitence with <i>MongoDB</i> here:<br>https://github.com/impetus-opensource/Kundera-Examples/wiki/Cross-datastore-persistence-using-Kundera
and implemented an external configuration as described (yes, i know: it's for NoSQL's) here:<br> https://github.com/impetus-opensource/Kundera/wiki/Data-store-Specific-Configuration<br>Trying comparable for <i>MySQL</i> like this:

<pre>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;clientProperties&gt;
    &lt;datastores&gt;
        &lt;dataStore&gt;
            &lt;name&gt;mysqlPU&lt;/name&gt;
             &lt;connection&gt;
                &lt;properties&gt;
                    &lt;property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/KunderaDemo" /&gt;
                    &lt;property name="hibernate.connection.username" value="root" /&gt;
                    &lt;property name="hibernate.connection.password" value="" /&gt;
                &lt;/properties&gt;
            &lt;/connection&gt;
        &lt;/dataStore&gt;
    &lt;/datastores&gt;
&lt;/clientProperties&gt;
</pre>

will fail. Kundera seems to ignore that file. My <strong>persistence.xml</strong> looks like this:

<pre>
&lt;persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" version="2.0"&gt;
    &lt;persistence-unit name="mysqlPU"&gt;
        &lt;provider&gt;com.impetus.kundera.KunderaPersistence&lt;/provider&gt;
        &lt;properties&gt;
            &lt;property name="hibernate.show_sql" value="true" /&gt;
            &lt;property name="hibernate.format_sql" value="true" /&gt;
            &lt;property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect" /&gt;
            &lt;property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" /&gt;
            &lt;property name="hibernate.current_session_context_class" value="thread" /&gt;
            &lt;property name="hibernate.connection.pool_size" value="10" /&gt;
            &lt;property name="kundera.client.lookup.class" value="com.impetus.client.rdbms.RDBMSClientFactory" /&gt;
            &lt;property name="kundera.client.property" value="/kundera-mysql.xml" /&gt;
        &lt;/properties&gt;
    &lt;/persistence-unit&gt;
&lt;/persistence&gt;
</pre>

When trying to persist an object, exception will be (as the connection details should be read from <i>/kundera-mysql.xml ...</i>):

<pre>
org.hibernate.service.jdbc.connections.internal.ConnectionProviderInitiator  - HHH000181: No appropriate connection provider encountered, assuming application will be supplying connections
Exception in thread "main" com.impetus.kundera.KunderaException: java.lang.UnsupportedOperationException: The application must supply JDBC connections
...
</pre>

<strong>Is there a way to use an external configuration file  for RDBMS databases like it is for NoSQL datastores?</strong>

The target shall be a cross datastore persistence using <i>MySQL</i> and <i>MongoDB</i>. Both handled by the <strong>KunderaPersistence</strong> provider and both units have to use an external configuration file...

Thanks.

**Comment by mevivs** [comment]
This is not supported by Kundera for RDBMS as it relies upon Hibernate for that. Also i believe you may try using hibernate.properties for that explicitly.

-Vivek

**Comment by cjaeger** [comment]
Thanks for the hint!

-Carsten
