### ISSUE TITLE
support for autocreate schema

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#2]
In case of Cassandra, if column family are not defined within keyspaces in cassandra.yaml.
Should we allow  autocreate schema option upon defining and persisting an entity with new keyspace and columnFamily?

Ofcourse with a check that it should not exist earlier.

Vivek

**Comment by xamry** [comment]
this is already there for HBase and MongoDB. Targeted for Cassandra in release 2.0.5

**Comment by mevivs** [comment]
will be delievered in 2.0.6
