### ISSUE TITLE
Lucene index in cluster environment

### ISSUE THREAD

**Issue by sahlex** [Impetus/kundera#20]
Hi all.

Imagine the following use case:

In a clustered server environment (or simply more than one machine with session stickiness configured) of glassfish server (or any other jee environment) using kundera, every node has its own lucene index in its own file system space.

This would definitely lead to problems as one entity is only seen on one machine!

This would be solved easily if cassandra is used as backing store - that is - using lucandra/solandra for index storage.

How is this acomplished? Is there a way to configure the lucene IndexWriters/IndexReaders for kundera? The 2.0.4 dependencies already have solandra included. Is it possible to set it via persistence.xml properties?

Best regards, 

Alexander.

**Comment by mevivs** [comment]
This is what is reported on 1 clustered environment and it make much sense. Earlier version of Kundera were using Solandra/Lucandra only. But performance is really worse along with ample number of issues reported on it.

So with 2.0.5, if a person opts of secondry indexes support on various datastore(e.g. RDBMS, cassandra, mongo etc). Then it will not create lucene stuff at all!

For making it more configurable, there is work going on to make Lucene data store configurable. So let say if you want to point lucene store to centric location you could do that by defining into persistence.xml

Thanks Alex, for brining out this discussion.

Sincerely,
Vivk
