### ISSUE TITLE
Schema generation: issues

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#202]
Currently with "kundera.ddl.auto.prepare", in case of Cassandra Kundera defines default comparator as "BytesType", within JPA it will always be string for column name so i propose it should be "UTF8Type". Also way to define sub comparator class is missing in case of super column family.

**Comment by pires** [comment]
+1

**Comment by xamry** [comment]
Fixed

**Comment by pires** [comment]
Would be nice if you guys could write the commit log referencing this issue, so one could easily check the fix code.

https://github.com/blog/831-issues-2-0-the-next-generation
https://github.com/blog/1386-closing-issues-via-commit-messages
