### ISSUE TITLE
Decimal values

### ISSUE THREAD

**Issue by sachur** [Impetus/kundera#203]
I'm trying to store decimal values ​​in a table. For this I have defined the column of type Double, but only stores the integer part of the number.

Should I use a different type for the column?

**Comment by mevivs** [comment]
Version of Kundera using?

**Comment by mevivs** [comment]
Please refer to:

https://github.com/impetus-opensource/Kundera/issues/169

**Comment by SunilHulikal** [comment]
hello sir..
this is sunil
i am newer to maven…i am facing a problem while creating new maven project it throws an below error….i am using eclipse 4.3(kepler), apache-maven 3.2.1 and i am installed maven integration for eclipse from eclipse market place…

Errors occurred during the build.
Errors running builder ‘Maven Project Builder’ on project ‘Helloworld’.
Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5

kindly reply as soon as possible……

Regards,
Sunil HR

**Comment by mevivs** [comment]
@SunilHulikal 
Not able to understand, how is it related to #203 . But yes, by looking into error looks like 

```
org.apache.maven.plugins:maven-resources-plugin:jar:2.5 
```

either repository configure with project's maven settings are missing this dependency jar or artifactId or version id is not correct

Please refrain pasting issues which are irrelevant to project.

-Vivek

**Comment by SunilHulikal** [comment]
thanks a lot sir..and sorry...
