### ISSUE TITLE
Can i use "Order by" and "limit" keyword in JPQL when using  kundera 2.3 + cassandra

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#204]
## i am creating a queue table, my table is :

create table queue (
id int,
time_id uuid,
message varchar,
put_terminal_ip varchar,
get_terminal_ip varchar,
bak varchar,
primary key(id, time_id)
## );

can i use "Order by" and "limit" keyword in JPQL when using  kundera 2.3 + cassandra 
like fellow?

"select c from QueueEntity c where c.key.Id =1 and c.getTerminalIp ='' order by c.timeId limit 1 "

**Comment by mevivs** [comment]
Hi,
I have added this support for composite key, please refer:
https://github.com/impetus-opensource/Kundera/issues/194

Order by is not supported via JPQL. We will try to get it working 2.5

-Vivek
