### ISSUE TITLE
Questions before migrating to Kundera - Help needed for evaluating migration process

### ISSUE THREAD

**Issue by jmcollin78** [Impetus/kundera#206]
Hello,

I'm comming here with a very bad experience from EclipseLink Nosql (JPA2.0 over MongoDB), and I need to evaluate the effort for migrating my application with Kundera.

Can you please answer this few questions ?
1. Is a Map mapping avaiblable (can't find in doc) ? Something like this is possible with EclipseLink, is this possible with Kundera or planned in future release:
@ElementCollection(targetClass=Invitation.class, fetch=FetchType.LAZY)
    @Column(name="invitations")
    @MapKey(name="toEmail")
    private Map<String, Invitation> invitations= new HashMap<String, Invitation>();
2. is there any issues with JBoss AS 7.1.1 ? I've seen a Issue concerning JBoss AS 7.1.1, I wonder if there is some know issues,
3. What about mapping with enum field ? Is this supported ? Can we request on those fields ?
4. Direct Mongo access : for special need, is this possible to access to direct MongoDB driver ? With EclipseLink you can do something like : ((MongoConnection) em.unwrap(javax.resource.cci.Connection.class)).getDB() to access MongoDriver. Is this supported or equivalent with Kundera ? Native request is not documented, is this not supported or just not documented ?
5. Lazy fetching : is this fully supported on @ElementCollection ? How is this internaly done ?
6. Cache : the documentation speakes about 2 cache level. Is the L2 shared with all EntityManager ?
7. Multithreading configuration : what is the recommanded configuration (one EM per thread ? / per application ?). How we ensure that entities in 2 EM are coherent ?
8. Cluster configuration : is there any replication or invalidate mechanism to evict entities from L2 cache when they have change on a cluster node ?
9. Indexing : are the index maintained automatically by Kundera ? "kundera.ddl.auto.prepare" seems to be a part of the answer.
9. and the last ... how is done the mecanism for detecting that an Entity have been change during a transaction ? Do you enhanced at runtime the entity class for example ?

Sorry for this long questions, but before migrating I have to know where I'm going before migrating.

Thanks in advance.

**Comment by xamry** [comment]
Hi,

Please find answers of some questions in red color.

Sincerely,
Amresh

On Tue, Mar 12, 2013 at 4:03 AM, jmcollin92 notifications@github.comwrote:

> Hello,
> 
> I'm comming here with a very bad experience from EclipseLink Nosql (JPA2.0
> over MongoDB), and I need to evaluate the effort for migrating my
> application with Kundera.
> 
> Can you please answer this few questions ?
> 1. Is a Map mapping avaiblable (can't find in doc) ? Something like this
> is possible with EclipseLink, is this possible with Kundera or planned in
> future release:
> @ElementCollection(targetClass=Invitation.class, fetch=FetchType.LAZY)
> @Column https://github.com/Column(name="invitations")
> @MapKey(name="toEmail")
> private Map invitations= new HashMap();

Currently supported for Neo4J only

> 1. is there any issues with JBoss AS 7.1.1 ? I've seen a Issue concerning
>    JBoss AS 7.1.1, I wonder if there is some know issues,
> 2. What about mapping with enum field ? Is this supported ? Can we request
>    on those fields ?
> 
> enum fields are supported, see test case:  PersonCassandraTest in
> kundera-cassandra.
> I don't see any reason why this should not work for mongodb
> 1. Direct Mongo access : for special need, is this possible to access to
>    direct MongoDB driver ? With EclipseLink you can do something like :
>    ((MongoConnection) em.unwrap(javax.resource.cci.Connection.class)).getDB()
>    to access MongoDriver. Is this supported or equivalent with Kundera ?
>    Native request is not documented, is this not supported or just not
>    documented ?
> 
> Not supported currently, but can easily be provided
1. Lazy fetching : is this fully supported on @ElementCollection ? How is
   
   > this internaly done ?
   > 
   > Lazy fetching supported on relationships only (as per JPA)
2. Cache : the documentation speakes about 2 cache level. Is the L2 shared
   
   > with all EntityManager ?
   > 
   > L2 Cache supported via EhCache

> 1. Multithreading configuration : what is the recommanded configuration
>    (one EM per thread ? / per application ?). How we ensure that entities in 2
>    EM are coherent ?
> 2. Cluster configuration : is there any replication or invalidate
>    mechanism to evict entities from L2 cache when they have change on a
>    cluster node ?
> 3. Indexing : are the index maintained automatically by Kundera ?
>    "kundera.ddl.auto.prepare" seems to be a part of the answer.
> 
> If you want to index into lucene, this is maintained by Kundera, otherwise
> secondary indexes are maintained into underlying database. You have to
> annotate your entity with @Index annotation
> 1. and the last ... how is done the mecanism for detecting that an Entity
>    have been change during a transaction ? Do you enhanced at runtime the
>    entity class for example ?

A copy of your entity objects are kept into persistence cache maintained by
kundera. Any changes you make into your entity object will make it dirty
and will be checked for modification during subsequent operation. This is
done in accordance with JPA specification.

**Comment by mevivs** [comment]
Adding more...
1. Is a Map mapping avaiblable (can't find in doc) ? Something like this is possible with EclipseLink, is this possible with Kundera or planned in future release:
   @ElementCollection(targetClass=Invitation.class, fetch=FetchType.LAZY)
   @Column(name="invitations")
   @MapKey(name="toEmail")
   private Map invitations= new HashMap();

```
<Vivek> 
@MapKey annotation is not supported. Please have a look at https://github.com/impetus-opensource/Kundera/issues/49 on support of Map fields in Kundera
</Vivek>
```
1. is there any issues with JBoss AS 7.1.1 ? I've seen a Issue concerning JBoss AS 7.1.1, I wonder if there is some know issues,

```
<Vivek>
It is related to OSGI model based class loading. We are working on it
</Vivek>
```
1. Multithreading configuration : what is the recommanded configuration (one EM per thread ? / per application ?). How we ensure that entities in 2 EM are coherent ?

```
<Vivek> 
Depends on configured PersistenceContextType. Ideally for heavy write operations i would suggest to have single thread per EM. Working with multiple threads should not be a problem.
</Vivek>
```
1. Cluster configuration : is there any replication or invalidate mechanism to evict entities from L2 cache when they have change on a cluster node ?

```
<Vivek> 
Depends how you interact via entity manager, these are internally handled by delegations over em.flush(),em.clear() or em.close().
</Vivek>
```
1. Indexing : are the index maintained automatically by Kundera ? "kundera.ddl.auto.prepare" seems to be a part of the answer.

```
<Vivek>
1. If you opt for default indexing which is lucene based indexing and managed by Kundera.
2. Else it will rely on native indexing enabled on MongoDB
3. kundera.ddl.auto.prepare is something to do schema generation and yes it will take care of native index over mongodb, you just need to annotate such to be indexed fields with @IndexCollection
</Vivek>
```
1. and the last ... how is done the mecanism for detecting that an Entity have been change during a transaction ? Do you enhanced at runtime the entity class for example ?

```
<Vivek>
1. We have built an custom implementation for dirty check over entity values.
2. Also, for transaction related test cases please have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-tests/src/test/java/com/impetus/kundera/tests/persistence/jta/EjbJTAContextTest.java

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/EntityTransactionTest.java

Kundera does support in-container JTA and out of container Application managed transactions.

</Vivek>
```

Hope it helps.

**Comment by jmcollin78** [comment]
Many thanks for your quick answers. I think we will have a look on Kundera.

**Comment by mevivs** [comment]
Sure. Let us know if you have anything to discuss or need any support.

Are we good to close on this issue?

-Vivek

**Comment by jmcollin78** [comment]
Yes. You can close. Is there any better place for asking questions ?

De : Vivek Mishra [mailto:notifications@github.com] 
Envoyé : mardi 12 mars 2013 08:41
À : impetus-opensource/Kundera
Cc : jmcollin92
Objet : Re: [Kundera] Questions before migrating to Kundera - Help needed for evaluating migration process (#206)

Sure. Let us know if you have anything to discuss or need any support.

Are we good to close on this issue?

-Vivek

**Comment by mevivs** [comment]
You can subscribe to  http://groups.google.com/group/kundera-discuss/subscribe for queries and discussions. 

-Vivek

**Comment by jmcollin78** [comment]
ok
