### ISSUE TITLE
Kundera with MongoDB : empty query returns null instead of empty list

### ISSUE THREAD

**Issue by jmcollin78** [Impetus/kundera#207]
Hello,

Executing this piece of code :
TypedQuery<Account> q = em.createQuery("Select e from Account e where e.email=:email", Account.class);
q.setParameter("email", email);
List<Account> res = q.getResultList();

res is null if the query has no result. We should have an empty List<Account> instead according to specification.

Edit:
hum, it seems it is no so evident... Hibernate returns null also and spec says nothing about that: http://stackoverflow.com/questions/1115480/can-javax-persistence-query-getresultlist-return-null

It is a difference with other JPA provider, but no-one is on the truth... I will check my code.

JM.

**Comment by mevivs** [comment]
Will be fixed in 2.5 release.

https://github.com/impetus-opensource/Kundera/issues/114

**Comment by xamry** [comment]
This has been fixed. Please verify in trunk and close

**Comment by jmcollin78** [comment]
Sorry but I not able to verify because I’m not using Kundera anymore.

De : Amresh [mailto:notifications@github.com] 
Envoyé : jeudi 18 avril 2013 08:21
À : impetus-opensource/Kundera
Cc : jmcollin92
Objet : Re: [Kundera] Kundera with MongoDB : empty query returns null instead of empty list (#207)

This has been fixed. Please verify in trunk and close

**Comment by mevivs** [comment]
```
Sorry but I not able to verify because I’m not using Kundera anymore
```

Any specific reason for this?

-Vivek

**Comment by jmcollin78** [comment]
Yes, I’ve seen that Kundera is not finish. I want to use it with MongoDB, and looking at the code i’ve seen many ‘TODO’ on JPA implementation method. Some basics functions don’t work (i’ve post some issues). I thought I was the first to use the MongoDB functionnality…
But your product is promising, keep on your great work. I just need something fully usable now.

JM.

De : Vivek Mishra [mailto:notifications@github.com] 
Envoyé : mardi 23 avril 2013 07:56
À : impetus-opensource/Kundera
Cc : jmcollin92
Objet : Re: [Kundera] Kundera with MongoDB : empty query returns null instead of empty list (#207)

Sorry but I not able to verify because I’m not using Kundera anymore
Any specific reason for this?
-Vivek

**Comment by mevivs** [comment]
Thanks, this is what we are working for. 
Closing this one.
