### ISSUE TITLE
Support javax.validation.constraints (@NotNull, @Size...)

### ISSUE THREAD

**Issue by jmcollin78** [Impetus/kundera#208]
Hello,
It would be great if Kundera could support the model constraints validation like @NotNull, @Size, ...

Example on an Entity:
@NotNull
@Size(min = 1, max = 256)
@Email
@Column(name="email")
private String email;

@NotNull
@Size(min = 3, max = 50)
@Column(name="pseudo")
private String pseudo;

This simplify drastically the code. This must be called before an Entity is created (persist or merge) or updated. If validation failed, a ConstraintViolationException must be send. It contains detailled informations of the constraint and the field in error.

JM.

**Comment by oprobst88** [comment]
This would be really great!
Thanks
Oliver

**Comment by mevivs** [comment]
Moving it to 2.10 release for assessment. Though @Notnull constraints doesn't make much sense in most of NoSQL databases.

-Vivek

**Comment by mevivs** [comment]
Support for bean validation has been added in this 2.10

-Vivek
