### ISSUE TITLE
Doubt in defining column name  attribute in Entity Class 

### ISSUE THREAD

**Issue by ashishkshukla** [Impetus/kundera#210]
Hi,
  I have a doubt.
  Can we give a variable value to the Column name ?
 For example-

String s= "filler";
@Column(name=s)
    private String filler;

I tried to do the same but it is showing an error that 'The value for annotation attribute Column.name must be a constant expression".

**Comment by mevivs** [comment]
This has to be constant expression. You can't assign an object reference to name attribute of @Column annotation.

-Vivek

**Comment by ashishkshukla** [comment]
Ok. Got it. Thanks.
