### ISSUE TITLE
Regarding mongoDB javascript functionality in kundera

### ISSUE THREAD

**Issue by sbheda** [Impetus/kundera#212]
How can i call MongoDB javascript file in kundera ?

**Comment by mevivs** [comment]
2.4 release  doesn't provide a handle for raw mongodb instance. It's in our roadmap and 2.5 release will enable this feature.  Will post an update on this once it's checked-in current trunk branch.

-Vivek

**Comment by jmcollin78** [comment]
Here is how I access to the MongoDB driver from Kundera:
Map<String, Client> clients = null;
            MongoDBClient client = null;
            clients = (Map<String, Client>) em.getDelegate();
            if (clients != null) client = (MongoDBClient) clients.get(persistenceUnitName);
            if (client != null) {
                try {
                    Field db = client.getClass().getDeclaredField("mongoDb");
                    if (!db.isAccessible()) {
                        db.setAccessible(true);
                    }
                    mongoDB = (DB) db.get(client);
                } catch(Exception e) {
                    log.error("Cannot access MongoDB driver. Cause : '{}'",e.getMessage());
                    throw new ExceptionTechnique(e);
                }
            }

Hope this helps

**Comment by mevivs** [comment]
Please refer:
https://github.com/impetus-opensource/Kundera/issues/248

for proper fix on this.

-Vivek
