### ISSUE TITLE
Enable external properties for HibernateClient.

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#215]
---

From: kundera-discuss@googlegroups.com [kundera-discuss@googlegroups.com] on behalf of Nick [nick.the.architect@gmail.com]
Sent: 15 March 2013 00:55
To: kundera-discuss@googlegroups.com
Subject: {kundera-discuss} HIbernate configuration only sees persistence.xml properties and not Spring EntityManagerFactory configured properties
Hi,
We are having some success using Kundera to persist our entities to a Cassandra database, but we would like to use an in-memory database to run our unit-tests, so that we have good coverage during continuous integration builds on our Jenkins server.
Obviously, there is an option to install and run Cassandra as a service on our Jenkins server, but it makes it much simpler to configure and run the build (and much simpler for the other developers).
We are using Spring to configure the emf and em, and injecting properties using the "jpaProperties" for the Spring emf. The persistence.xml is very small, with only constant values such as kundera.keyspace and kundera.cache.provider.class for the properties there.
My plan was to use the Pelops kundera.client for regular deployed usage, persisting to Cassandra, and to use the rdbms kundera.client for the unit tests that run during the build. Then my test configuration would use hibernate configurations to connect to a HSQL (or H2) in-memory database.
This configuration works fine for Pelops and the kundera.nodes, kundera.port, kundera.ddl.auto.prepare properties are passed through to the PelopsClientFactory during configuration. When we run the unit tests, the hibernate properties (hibernate.connection.url, hibernate.connection.driver_class, etc) are not passed through to the HibernateClient and we get the following error message:
WARN (ConnectionProviderInitiator.java:143) org.hibernate.service.jdbc.connections.internal.ConnectionProviderInitiator - HHH000181: No appropriate connection provider encountered, assuming application will be supplying connections
I have traced through with the debugger and it seems that the HibernateClient constructor is not passing the supplied "puProperties" to the Configuration object that is created, it is only using the results of the call to HibernateUtils.getProperties(persistenceUnit) (which only sees the properties defined in the persistence.xml).
Why is it not possible to pass the "puProperties" into the configuration as well (or instead)?

Thanks,

Nick.

**Comment by xamry** [comment]
This has been fixed. In order to provide external properties, you need to pass a Map while creating entity manager factory. Please verify in trunk and close.

**Comment by mevivs** [comment]
Any update on this?

-Vivek

**Comment by mevivs** [comment]
A fix has been added to enable external properties file such as "hibernate.properties" or "orm.xml" file. 
You just need to map it as an external file as:

```
<property name="kundera.client.property" value="hibernate.properties" />
```

Please refer fix added for the same.

-Vivek
