### ISSUE TITLE
JPA Lifecycle callbacks not called for child entities persisting to Cassandra

### ISSUE THREAD

**Issue by NickTheArchitect** [Impetus/kundera#217]
We are persisting 2 classes of Entity, that have a OneToMany relationship with cascading persist (actually CascadeType.ALL). Both classes of entity are using a pre-persist callback to set their own ID. That looks like:
            @PrePersist
            public void prePersist() {
                        this.id = UUID.randomUUID().toString();
            }
I have also tried the same technique using an EntityListener with the same code in the callback method.
The callback works for the parent entity, but is not called for the "cascaded" persist in the children.
We are using the Pelops client to persist to a Cassandra datastore.

**Comment by mevivs** [comment]
Fixed in current trunk. Please verify.

-Vivek

**Comment by mevivs** [comment]
Fixed and releasing with 2.6. Please verify.
-Vivek
