### ISSUE TITLE
Does kundera2.5 add 'null' support to JPQL + cassandra?

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#223]
It seems  that cassandra will add 'null' support to cql3.
The kundera has the plan to do it to JPQL?
- cql3 add 'null' refer:
  https://issues.apache.org/jira/browse/CASSANDRA-3783

**Comment by mevivs** [comment]
Will post an update on this once we start on CQL interoperability.

-Vivek

**Comment by xamry** [comment]
This is available with cassandra 1.2.4, we need to asses migratin from 1.2.0 to 1.2.4 as well!......

Thanks
Kuldeep

**Comment by zhouhero** [comment]
i have test it in cassandra 1.2.4+kundera2.5, the null can be updated by cql.
but the JPQL is not ok.
