### ISSUE TITLE
Cassandra1.2's atomic batch can be used by JPQL in kundera2.5 ?

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#224]
As you know , the cassandra1.2 added the atomic bacth that can rollback in the server side. Is there plan to implement server side rollbak function in kundera2.5?
Note: i can do it by cql now, but i need to prepare the cqls by myself.

**Comment by mevivs** [comment]
Will post an update on this once we start on CQL interoperability.

-Vivek

**Comment by xamry** [comment]
This has been implemented and is available in trunk. Please verify and close
