### ISSUE TITLE
select now()  is support by kundera2.5?

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#226]
As you know, now() function can be use in cassandra1.2,
Can i use it in kundera?
if not, is there a plann to do it?

**Comment by mevivs** [comment]
Will post an update on this once we start on CQL interoperability.

-Vivek

**Comment by zhouhero** [comment]
does kundera 2.5 will implement CQL interoperability?

**Comment by mevivs** [comment]
Yes. it is planned for 2.5 and should be released with this.

-Vivek

**Comment by zhouhero** [comment]
when will kunder2.5 release?

**Comment by mevivs** [comment]
Will post an update on release date.

-Vivek

**Comment by mevivs** [comment]
This will only work via native query, JPQL alternative is not available.

-Vivek

**Comment by zhouhero** [comment]
could you pls give me a samle?
