### ISSUE TITLE
The entity only key column set can not be save to CF!

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#229]
when cassandra + kundera insert data to CF,
i find that the entity only key column set can not be save to CF.

[my table]
 create columnfamily test1 (attraction_id uuid primary key, del_flg text);

[my entity]

@Entity
 @Table(name = "test1", schema = XXXX)
 @XmlRootElement(name = "Test1Entity")
 public class Test1Entity implements Serializable {
 private static final long serialVersionUID = 1L;
@Id
@Column(name = "attraction_id")
 private UUID attractionId;
@Column(name = "del_flg")
 private String delFlg;
 ...
 }

[my insert code]

...
 EntityManager em = entityManagerFactory.createEntityManager();

Test1Entity test1Entity = new Test1Entity();
 test1Entity.setAttractionId(UUID.fromString("13816710-1dd2-11b2-0000-242d50cf1ff7"));
 em.persist(test1Entity);

test1Entity = new Test1Entity();
 test1Entity.setAttractionId(UUID.fromString("13818e20-1dd2-11b2-0000-242d50cf1ffc"));
 em.persist(test1Entity);

em.flush();
em.close();

[the resut]
 select count(*) from test1,
test1 table record num:0 // worng, 2 is right!

**Comment by mevivs** [comment]
AFAIK, Cassandra does not allow to save a column family with row key only!

-Vivek

**Comment by zhouhero** [comment]
Yes, you are right.
But, i think that kundera will throw some exceptions  at this time.
How do you think so?

**Comment by mevivs** [comment]
Is there any error you getting while trying it via Cassandra-cli or CQLsh ?

-Vivek

**Comment by zhouhero** [comment]
yes,
when CQLsh, the fellow error message is printed.

Bad Request: line 1:33 required (...)+ loop did not match anything at input ')'

**Comment by mevivs** [comment]
Marking as Not an issue. Please verify and close.

**Comment by mevivs** [comment]
Closing.
