### ISSUE TITLE
Merge is not working with 2.0.4

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#23]
Merge operation is not working for on Kundera-2.0.4

**Comment by zenbones** [comment]
This is a deal breaker for us, as all our persistence is based on merge (which is stable across ORMs, unlike save/persist). Will there be a patch for this? If not, when is 2.0.5 due out?

Thanks,
David

**Comment by mevivs** [comment]
Fixed and added new kundera-core jar on remote repo.

Vivek

**Comment by zenbones** [comment]
Excellent.

David

Sent from my HTC on the Now Network from Sprint!

----- Reply message -----
From: "mevivs" reply@reply.github.com
Date: Thu, Jan 19, 2012 12:13 am
Subject: [Kundera] Merge is not working with 2.0.4 (#23)
To: "David Berkman" david.berkman@grenadefish.net

Fixed and added new kundera-core jar on remote repo.

Vivek

---

**Comment by mevivs** [comment]
David,
There was some issue with uploaded jar. I have uploaded a new one. i suggest, if you force to pick this new jar from repo.

Let me know, if you face any issue with this.

Vivek
