### ISSUE TITLE
How can i use escape in JPQL when using CASSADRA

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#233]
How can i use escape in JPQL?
I want to in insert "where" word to db ,could you tell me how to  do it?
The JPQL of fellow is right?

update  XXXEntity c set c.word='\where'  where c.key = key escape '\';

**Comment by mevivs** [comment]
Is it related to 
https://github.com/impetus-opensource/Kundera/issues/230
?

-Vivek

**Comment by zhouhero** [comment]
yes, it is same to #230.

**Comment by zhouhero** [comment]
i can use ' to escape now for your fixing on #235,
thank you!
