### ISSUE TITLE
The single quote is updated the CF too!

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#235]
i want to update the string "test test" to db, but the single quote is also updated to CF.
- my jpql: 
  update TestEntity c set c.name='test test' where c.id=1;
- the result:
  'test test' was updated to the CF.

the two single quotes were updated to CF too!

This is the bug of the JPQL in kundera?

**Comment by zhouhero** [comment]
As you know, the cql will do it well.

refero: http://cassandra.apache.org/doc/cql3/CQL.html#constants

•A string constant is an arbitrary sequence of characters characters enclosed by single-quote('). One can include a single-quote in a string by repeating it, e.g. 'It''s raining today'. Those are not to be confused with quoted identifiers that use double-quotes.

**Comment by mevivs** [comment]
Hi,
Thanks. We will look into this alongwith CQL interoperability issue. Will post an update on this .

-Vivek

**Comment by zhouhero** [comment]
Could you fix the this bug in JPQL as soon as possible in 2.4 branch?
We are using the jpql to update the CF now, 
Because this, some bugs were reported  on our dev project.
This has a big impact on our dev plan.
Thank you very mutch!

**Comment by mevivs** [comment]
Ok. Let me discuss this on priority and will update you soon on this.

-Vivek

**Comment by zhouhero** [comment]
thank you very much!
as you know, by the issue#154, 
i can not use cql to update the CF although the cql can do well in single quote.

**Comment by mevivs** [comment]
Hi,
I have added a fix for this. It should be working fine now.

-Vivek

**Comment by zhouhero** [comment]
i have test it.
it work well now.
thank you very mutch!
