### ISSUE TITLE
@ElementCollection saved but not loaded on MongoDB

### ISSUE THREAD

**Issue by damageco** [Impetus/kundera#237]
I've got a strange problem with a collection embedded in a element with MongoDB v2.4.1 and 2.4 version of Kundera.

I've got 2 classes : 
@Entity
@Table(name = "COLLECTE", schema = "NoteoCrowd@mongoPU")
public class Collecte {

```
@Id
@Column(name = "COLLECTE_ID")
private String id;

@Column(name = "EAN", nullable = false)
private String EAN;

@Column(name = "PRODUIT_ID")
private Long idProduit;

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "dateStatut")
private Date dateStatut;

@Column(name = "statut")
private int statut;

// Element collection, will persist co-located
@ElementCollection(fetch=FetchType.LAZY)
@CollectionTable(name = "photos")
private List<Photo> photos;
```

@Embeddable
public class Photo {

```
@Column (name="NOM_PHOTO")
private String nomPhoto;

@Column (name="MD5")
private String md5;

@Column (name="NOM_FICHIER")
private String nomFichier;
```

The persistence.xml file : 
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
     <persistence-unit name="mongoPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.nodes" value="localhost" />
            <property name="kundera.port" value="27017" />
            <property name="kundera.keyspace" value="NoteoCrowd" />
            <property name="kundera.dialect" value="mongodb" />
            <property name="kundera.client.lookup.class" value="com.impetus.client.mongodb.MongoDBClientFactory" />
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
        </properties>
     </persistence-unit>

</persistence>

And the following test case : 
public class TestCollecte {

```
@Test
public void testInsert() {
    // une collecte
    Collecte c = new Collecte();
    c.setId("0001");
    c.setEAN("3251248033108");
    c.setIdProduit(123342124L);
    c.setDateStatut(new Date());
    c.setStatut(0);
    // qq photos
    List<Photo> photos = new ArrayList<Photo>();
    Photo p1 = new Photo();
    p1.setNomPhoto("Photo de Face");
    p1.setMd5("1235847EA873");
    p1.setNomFichier("photo1.jpg");
    photos.add(p1);
    Photo p2 = new Photo();
    p2.setNomPhoto("Photo composition");
    p2.setMd5("234847EA873");
    p2.setNomFichier("photo2.jpg");
    photos.add(p2);
    Photo p3 = new Photo();
    p3.setNomPhoto("Photo prix");
    p3.setMd5("5164847EA873");
    p3.setNomFichier("photo3.jpg");
    photos.add(p3);

    c.setPhotos(photos);
    // Enregistrement en base
    EntityManagerFactory emf = Persistence
            .createEntityManagerFactory("mongoPU");
    EntityManager em = emf.createEntityManager();
    em.persist(c);
    em.close();
    emf.close();
}

@Test
public void testSelect() {
    // une collecte
    // Enregistrement en base
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("mongoPU");
    EntityManager em = emf.createEntityManager();
    //Collecte c = em.find(Collecte.class, "0001");
     Query q = em.createQuery("select c from Collecte c where c.id =:id");
     q.setParameter("id", "0001");
     List<Collecte> collectes = q.getResultList();
     Collecte c = collectes.get(0);
    assertThat(c.getEAN(), is("3251248033108"));
    assertThat(c.getPhotos().size(), is(3));
    assertThat(c.getPhotos().iterator().next().getMd5() , is("1235847EA873"));
    em.close();
    emf.close();
}
```

The unit test fail on the 3rd assert. MD5 is null. Looking depper with the debugger, the list have 3 elements, but they all empty.

But if I look in the database, I've got : 

{
   "_id":"0001",
   "dateStatut":   ISODate("2013-04-10T19:42:12.558   Z"),
   "EAN":"3251248033108",
   "statut":0,
   "photos":[
      {
         "nomFichier":"photo1.jpg",
         "nomPhoto":"Photo de Face",
         "md5":"1235847EA873"
      },
      {
         "nomFichier":"photo2.jpg",
         "nomPhoto":"Photo composition",
         "md5":"234847EA873"
      },
      {
         "nomFichier":"photo3.jpg",
         "nomPhoto":"Photo prix",
         "md5":"5164847EA873"
      }
   ],
   "PRODUIT_ID":NumberLong(123342124)
}

So photo informations are well record in Mongo database.

Did I missed something, are it's un bug ? 

Thanks.

David

**Comment by xamry** [comment]
This looks an issue, can u try removing  (fetch=FetchType.LAZY) and let me
know if it works

**Comment by damageco** [comment]
I've tried. The problem still here.

**Comment by mevivs** [comment]
I am looking into this. will update you soon on this.

-Vivek

**Comment by mevivs** [comment]
I looked into this issue. Issue is @Column annotation's name attribute is not persisted, so as a workaround if you change:

```
@Column (name="NOM_PHOTO")
private String nomPhoto;

@Column (name="MD5")
private String md5;

@Column (name="NOM_FICHIER")
private String nomFichier;
```

with

```
  @Column(name = "nomPhoto")
    private String nomPhoto;

    @Column(name = "md5")
    private String md5;

    @Column(name = "nomFichier")
    private String nomFichier;

```

It should work for you. I will get this fixed.

-Vivek

**Comment by mevivs** [comment]
I have added a fix for this in latest trunk.Here is revision no
88dd6f06fc78c3f93285374fd8d7c66f36aa681a

**Comment by damageco** [comment]
I've try to compile trunck version, succeed, but difficult. So I've try with the 2.5-SNAPSHOT version but no change for me. So I've look the fix. I don't see any patch in you're commit, just the 3 tests class....

**Comment by mevivs** [comment]
My Bad. here it is:
262389e62b3310baedfbbfb14ddedde59ce97af8

Also to compile current trunk, please execute:

mvn clean install -DskipTests,(Else you need to modify test files for specific server)

To build kundera-mongo only, please execute:

mvn clean install -DskipTests -Pmongo

Hope it helps.

-Vivek

**Comment by damageco** [comment]
It seem to be fix to me. Great !
