### ISSUE TITLE
Generate secondary index DDL when @Index is present on a @Column

### ISSUE THREAD

**Issue by pires** [Impetus/kundera#238]
By having:

``` java
@Column
@Index(name = "user_first_name")
private String firstName;
```

Generate DDL:

```
{column_name: firstName, validation_class:UTF8Type, index_type: KEYS}
```

This is great if you have `<property name="kundera.ddl.auto.prepare" value="create" />`, in order to have less boilerplate code when testing with _embedded_ Cassandra.

**Comment by mevivs** [comment]
It should generate secondary indexes, have a look at: 

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandra.java

for reference.

-Vivek

**Comment by pires** [comment]
Yes it does! Thank you, Vivek.
