### ISSUE TITLE
Support for @Enumerated

### ISSUE THREAD

**Issue by damageco** [Impetus/kundera#240]
I've got a problem with an enum : 

Here is my code : 
public enum StatutCollecte {
    INIT,
    SCANNE,
    ENVOYE,
    EN_SAISIE,
    VALIDE,
    REJETE}

In the main class : 
@Enumerated(EnumType.STRING)
private StatutCollecte statut;

Persist is ok, but when select I've got this message : 

12 avr. 2013 13:11:39 com.impetus.client.mongodb.MongoDBDataHandler getEntityFromDocument
GRAVE: Error while Getting entity from Document. Details:java.lang.IllegalArgumentException: Can not set entite.StatutCollecte field entite.Collecte.statut to java.lang.String

Bug ?

**Comment by xamry** [comment]
Can you please refer to test case PersonMongoTest. It tests all opertions on an entity that contains Enumberated object, just the way you are using it.

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java

**Comment by xamry** [comment]
This has been fixed and is available for testing in trunk branch. Please verify and close issue if this works for you.

**Comment by damageco** [comment]
Not it doesn't work il you use like me an external Enum file : 
package com.impetus.client.crud;

public enum Day {

```
    MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY;
```

}

day attribut look like this : 
@Column(name = "ENUM")
@Enumerated(EnumType.STRING)
private Day day = Day.FRIDAY;

Unit test log show : 
18 avr. 2013 18:22:56 com.impetus.client.mongodb.MongoDBDataHandler getEntityFromDocument
GRAVE: Error while Getting entity from Document. Details:java.lang.IllegalArgumentException: Can not set com.impetus.client.crud.Day field com.impetus.client.crud.PersonMongo.day to java.lang.String

**Comment by mevivs** [comment]
Hi KK,
please verify this.

-Vivek

**Comment by damageco** [comment]
It's work now !

Thanks

David
