### ISSUE TITLE
Kundera fails to update Cassandra scheme when there is more than 1 node

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#242]
In our company we are experiencing problem with Cassandra and Kundera when trying to update Scheme. AFAIK Cassandra doesn't support scheme update on all nodes and use one node scheme update replication instead of. 

Is it something wrong in our configuration, or Kundera really doesn't support scheme update out-of-the-box?

**Comment by mevivs** [comment]
Hi,
Can you please provide more detail on this? You want to configure Kundera for multiple nodes for auto schema configuration?

-Vivek

**Comment by bsideup** [comment]
Hi!

Funniest thing about this is that we decided not to use Cassandra anymore =)

But yes, there was a problems with auto schema migration on multiple nodes of cassandra:)

**Comment by mevivs** [comment]
Ok. BTW we fixed some issues(related to schema generation) in recent 2.5 release. 

 Kundera does support other databases as well except Cassandra :)

-Vivek

**Comment by bsideup** [comment]
Glad to hear that! Will look at 2.5 soon:)

**Comment by mevivs** [comment]
Support for multiple nodes has been added in Kundera-cassandra. Releasing with 2.6

**Comment by mevivs** [comment]
Fixed and releasing with 2.6. Please verify.
-Vivek
