### ISSUE TITLE
Define @Id and @GeneratedValue as org.bson.types.ObjectId in MongoDB 

### ISSUE THREAD

**Issue by damageco** [Impetus/kundera#244]
In 2.4, _id column identifier when defined with @Id and @GeneratedValue annotations is store in MongoDB as String. It's seems that real object id type for MongoDb is org.bson.types.ObjectId (see http://docs.mongodb.org/manual/reference/object-id/).

So _id keys defined in Java as String shoud be wrapped in this specific type by the persistance layer.

At this moment, tools like MonjaDb and Genghis can't be use to maintain database.

**Comment by damageco** [comment]
I don't see the relation between your commit and this issue. If I want to fixed it myself this where shoud I start ?

**Comment by mevivs** [comment]
Hi,
Above mentioned revision number contains multiple check-ins. Please refere given below for specific to this one:

https://github.com/impetus-opensource/Kundera/commit/7d22126df9b8e478b64ad62de73ba317f5a390a6#diff-45
https://github.com/impetus-opensource/Kundera/commit/7d22126df9b8e478b64ad62de73ba317f5a390a6#diff-44

**Comment by mevivs** [comment]
To add more on this:
https://github.com/impetus-opensource/Kundera/blob/7d22126df9b8e478b64ad62de73ba317f5a390a6/kundera-mongo/src/test/java/com/impetus/client/generatedId/entites/MongoGeneratedIdStrategyAuto.java

contains ObjectId as an @Id attribute.

Hope it clarifies.

-Vivek

**Comment by damageco** [comment]
Yes, it clarifies things. Thanks. And it works find with the ObjectId type...

...but, I've got a problem with this fix : the goal of JPA is to separate the Java model with the persistance layer. In my opinion ObjectId is part of the MongoDB system and should not be used in POJO objects. If you decide tomorrow to switch to another NoSQL system you will have to change all your business objects. So id keys defined in Java should be defined as String even if store as a ObjectId.

**Comment by mevivs** [comment]
We had a thought on this. But upon validating that instantiating objects for ObjectId is possible via java API. We decided to use it, Concern is quite valid that it is specific to ObjectId and conversion to String makes much sense. But then it leaves "_id" in inconsistent state, where java application would be referring it as "String" object but actually it is an "ObjectId" instance(IMHO it does not look elegant). 

For transition to another NoSql from MongoDB, i guess user needs to modify entity for some trivial changes such as(@Table annotation etc). So at the same time he can change from ObjectId to required type as well!

Cheers,
-Vivek

**Comment by damageco** [comment]
Ok, let's see what futures users will said at the next release of Kundera.

I think you'll need to explain this in https://github.com/impetus-opensource/Kundera/wiki/Primary-Key-Auto-generation.

Thanks,

David

**Comment by mevivs** [comment]
+1 for this. 

KK,
Please modify wiki for the same.

-Vivek
