### ISSUE TITLE
Kundera required "join column" to be BytesType

### ISSUE THREAD

**Issue by eld0** [Impetus/kundera#245]
Hi,
I've found a very annoying issue with schema validation. When I have relations to another tables Kundera always fail on start with "column not found" error. After some investigation I've found that it's require all "foreign keys" to have BytesType validator. But I have varchar as keys or uuid. I found a place in code where JoinColumn creating without a type , thats why another block of code always compare it with BytesType.
com.impetus.kundera.configure.SchemaConfiguration

``` java
private ColumnInfo getJoinColumn(String joinColumnName/*, Class columnType*/)
    {
        ColumnInfo columnInfo = new ColumnInfo();
        columnInfo.setColumnName(joinColumnName);
        columnInfo.setIndexable(true);
// columnInfo.setType(columnType);
        return columnInfo;
    }
```

and I see that type setting has been  commented. Why? Maybe this issue resolved in trunk?
Thanks

kundera 2.4
cassandra 1.1.10

**Comment by mevivs** [comment]
Fixed. Please verify with 2.5 release.

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

**Comment by eld0** [comment]
yes, sure
