### ISSUE TITLE
 Connection pool not work well when restart the cassandra server

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#246]
when i restart the cassandra db server, connection pool can not work well.

if i fix the kundera as fellow , it work well .

ThriftClientFactory.java
     createPoolOrConnection() {
...
        prop.setTestOnBorrow(true);
        prop.setTestOnReturn(true);
...
}

could you pls add setTestOnBorrow and setTestOnReturn options of them in persistenc.xml's connection pooling ?

**Comment by mevivs** [comment]
Fixed in 2.5. Please verify.

-Vivek

**Comment by mevivs** [comment]
Fixed and releasing with 2.6. Please verify.
-Vivek
