### ISSUE TITLE
Support for Play 2.1 with mongodb

### ISSUE THREAD

**Issue by yoquankara** [Impetus/kundera#247]
Kundera doesn't work with the new Play 2.1 for Mongodb.

I don't know if supporting Play 2.1 & Mongodb is a priority of this project or not. But it's worth imho. Many Play users still prefer Java to Scala and definitely want to try out increasingly popular Mongodb. However most of them now turn to Morphia, which ironically seems not work with Play 2.1 too. Kundera should & can achieve better recognition within Play community.

**Comment by mevivs** [comment]
Similar to Issue #177 ?

**Comment by mevivs** [comment]
Fixed and releasing with 2.6
-Vivek
