### ISSUE TITLE
CassandraDataHandler NullPointerException

### ISSUE THREAD

**Issue by Primeval** [Impetus/kundera#250]
Hi,

I think I have an concurrency problem with Kundera 2.3 (Cassandra 1.2.2).  When I run a test with multiple threads and a really simple Entity (normal ColumnFamily) called Message I getting an NullpointerException. 

The NullPointerException occurs because the CassandraDataHandler is null (in my case it is the PelopsDataHandler). I think the problem is that no more connections are available and Pelops block until a new connection is available but inside the PelopsClient the process goes on. When the close()-Method is called the dataHandler will be set to null. If a new connection is available the 

 Object o = getDataHandler().populateEntity(tr, m, relations, isRelation);

called with a null instance of an dataHandler. Please have a look at the code below.

@Entity
@Table(name = "Message", schema = "mykeyspace@cassandra_pu")
public class Message {
    @Id
    @Column
    private String id;

```
@Column
private String text;

// getter & setter
// equals(), hashCode() and toString()
```

}

public class PersistenceStressTest {
    static final String CASSANDRA_PU = "cassandra_pu";
    static EntityManagerFactory emf;
    ExecutorService ex = null;
    CountDownLatch countDownLatch = null;
    final int NUMBER_OF_THREADS = 10;
    final int NUMBER_OF_WORKERS = 1000;

```
@BeforeClass
public static void setUpBeforeClass() throws Exception {
    try {
        emf = Persistence.createEntityManagerFactory(CASSANDRA_PU);
    } catch (java.lang.ExceptionInInitializerError e) {
        throw new RuntimeException(e.getMessage());
    }
}

@AfterClass
public static void tearDownAfterClass() throws Exception {
    if (emf != null && emf.isOpen()) {
        emf.close();
    }
}

@After
public void tearDown() throws Exception {
    if (ex != null && !ex.isShutdown()) {
        ex.shutdown();
    }
}

@Test
public void test() {
    ex = Executors.newFixedThreadPool(NUMBER_OF_THREADS);
    countDownLatch = new CountDownLatch(NUMBER_OF_WORKERS);
    List<Worker> workers = new ArrayList<Worker>(NUMBER_OF_WORKERS);
    for (int i = 0; i < NUMBER_OF_WORKERS; i++) {
        workers.add(new Worker(i));
    }
    try {
        for (Worker worker : workers) { // create worker
            ex.execute(worker);
        } // shutdown when finish
    } finally {

        // block the main-thread until all thread's are finish with his work
        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            System.err.println(e.getMessage());
        }
    }
}

final class Worker implements Runnable {
    final int workerId;
    public Worker(final int workerId) {
        this.workerId = workerId;
    };

    @Override
    public void run() {
        EntityManager em = null;
        try {
            em = emf.createEntityManager();
            Query query = em.createQuery("select m from Message m");
            query.setMaxResults(1);
            query.getResultList();
        } catch (Exception e) {
System.err.println("Failed to open a connection for Thread '" + Thread.currentThread().getId() + "' with Worker '" + workerId
                    + "' because a '" + e.getClass().getSimpleName() + "' occurs with cause: '" + e.getMessage() + "'.");
            e.printStackTrace();
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
            countDownLatch.countDown();
        }
    }
}
```

}

persistence.xml (I decrease the number of pool connections to see faster where the NPE occurs!)

<persistence-unit name="cassandra_pu">
<provider>com.impetus.kundera.KunderaPersistence</provider>
<properties>
<property name="kundera.nodes" value="localhost" />
<property name="kundera.port" value="9160" />
<property name="kundera.keyspace" value="mykeyspace" />
<property name="kundera.dialect" value="cassandra" />
<property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" /> 
<property name="kundera.cache.provider.class"   value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
<property name="kundera.cache.config.resource"  value="/META-INF/ehcache.xml" />
<property name="kundera.pool.size.max.active"   value="10" />
<property name="kundera.pool.size.max.idle"     value="10" />
<property name="kundera.pool.size.min.idle"     value="5" />
<property name="kundera.pool.size.max.total"    value="10" />
<property name="kundera.batch.size"             value="5000" />
</properties>
</persistence-unit>

May you any ideas what I doing wrong?

Many thanks in advance!

**Comment by Primeval** [comment]
sorry my failure

**Comment by mevivs** [comment]
I will have a look. Can you please try this with ThriftClientFactory(Kundera 2.4)? You can also try by configuring for 
"kundera.pool.size.max.active" , "kundera.pool.size.max.total" properties for connection pool configurations. 

-Vivek

**Comment by mevivs** [comment]
I have verified it with current trunk branch. Add a small fix for this was failing for something else.

Please verify.

-Vivek

**Comment by Primeval** [comment]
Hi,

the changes doesn't have any effects. I try it with both (Thrift & Pelos) and with a "kundera.pool.size.max.total" value of 1000. There is an concurrency problem. I have seen in the debug that the close() method is called and later inside computeEntityViaColumns() the getDataHandler() with a null instance of an dataHandler within the same thread. I try to find out were the problem is.

**Comment by mevivs** [comment]
Can you please try with latest trunk?

-Vivek

**Comment by Primeval** [comment]
Yes I work on the latest trunk (2.5). At first I  remove his.dataHandler = null; from the close-method then the NPE doesn't occurs anymore but I think there is in general a problem.

**Comment by mevivs** [comment]
onething which i tried and was working for me was:

changing

```
final int NUMBER_OF_THREADS = 10;
final int NUMBER_OF_WORKERS = 1000;
```

with

```
final int NUMBER_OF_THREADS = 1000;
final int NUMBER_OF_WORKERS = 1000;
```

-Vivek

**Comment by mevivs** [comment]
Hi,
I have made some changes in close method earlier. Can you please take an update and try? I am not to replicate NPE at my end.

-Vivek

**Comment by Primeval** [comment]
<code>
final int NUMBER_OF_THREADS = 1000;
final int NUMBER_OF_WORKERS = 1000;
</code>

that will work for the test but not for our application. We have an JMeter test for the GUI (using 50 threads) and the same error still occurs. Anythink what help for now will to synchronize the create EntityManager method.

synchronized(Lock.class) {
                    em = CassandraUtil .getInstance().getEnityManager();

// or just
// em = emf.createEntityManager();
                } 
<code>
public final class CassandraUtil {
    public static final String CASSANDRA_PU = "cassandra_pu";
    private final EntityManagerFactory emf;
    public static final ModelProviderUtil INSTANCE = new ModelProviderUtil();
    private ModelProviderUtil() {
        try {
            emf = Persistence.createEntityManagerFactory(CASSANDRA_PU);
        } catch (java.lang.ExceptionInInitializerError e) {
            throw new RuntimeException(e.getMessage());
        }
    }
    public static ModelProviderUtil getInstance() {
        return INSTANCE;
    }
    public EntityManagerFactory getEntityManagerFactory() {
        return emf;
    }
    public EntityManager getEnityManager() {
        return emf.createEntityManager();
    }
}
</code>

I will look tomorrow again.

Regards

**Comment by Primeval** [comment]
Hi,

in the find(List<IndexClause> ixClause, EntityMetadata m, boolean isRelation, List<String> relations,
            int maxResult)-method of PelopsClient class I found this:

// close-method was not called
Map<Bytes, List<Column>> qResults  = selector.getColumnsFromRows(m.getTableName(),
 selector.newKeyRange("", "", maxResult), slicePredicate, consistencyLevel); }

// close-method was called -> may be selector was blocked because not enough connections are available?

entities = new ArrayList<Object>(qResults.size());

// NPE occurss
 populateData(m, qResults, entities, isRelation, relations);

**Comment by mevivs** [comment]
Hmm. I will have a look.
Can you please try the same with ThriftClientFactory?

-Vivek

**Comment by Primeval** [comment]
Hi,

I have a check in both PelopsClient and ThriftClient

PelosClient

```
public List find(List<IndexClause> ixClause, EntityMetadata m, boolean isRelation, 
 List<String> relations, int maxResult, List<String> columns) {
    if (closed) {
        throw new IllegalArgumentException("PelopsClient was closed.");
    }

    Selector selector = Pelops.createSelector(PelopsUtils.generatePoolName(getPersistenceUnit(), getExternalProperties()));

    SlicePredicate slicePredicate = Selector.newColumnsPredicateAll(false, Integer.MAX_VALUE);
    if (columns != null && !columns.isEmpty()) {
        slicePredicate = Selector.newColumnsPredicate(columns.toArray(new String[] {}));
    }

    if (closed) {
       throw new 
               IllegalArgumentException("PelopsClient was closed after selector from db pool was created.");
    }


    List<Object> entities = new ArrayList<Object>();
    if (ixClause.isEmpty()) {
        if (m.isCounterColumnType()) {
            IPooledConnection connection = null;
            IThriftPool thrift = null;
            try {
                thrift = Pelops.getDbConnPool(PelopsUtils.generatePoolName(getPersistenceUnit(), getExternalProperties()));
                connection = thrift.getConnection();
                org.apache.cassandra.thrift.Cassandra.Client thriftClient = connection.getAPI();
                List<KeySlice> ks = thriftClient.get_range_slices(new ColumnParent(m.getTableName()), slicePredicate,
                        Selector.newKeyRange("", "", maxResult), getConsistencyLevel());
                entities = onCounterColumn(m, isRelation, relations, ks);
            } catch (Exception irex) {
                log.error("Error during executing find, Caused by :", irex);
                throw new PersistenceException(irex);
            } finally {
                if (connection != null && !connection.isOpen()) {
                    connection.release();
                }
            }
        } else {

            if (m.getType().isSuperColumnFamilyMetadata()) {
                Map<Bytes, List<SuperColumn>> qResults = selector.getSuperColumnsFromRows(m.getTableName(), Selector.newKeyRange("", "", maxResult),
                        slicePredicate, getConsistencyLevel());
                entities = new ArrayList<Object>(qResults.size());
                computeEntityViaSuperColumns(m, isRelation, relations, entities, qResults);
            } else {

                if (closed) {
                    throw new IllegalArgumentException("PelopsClient was closed before Selector was called to get columns from rows.");
                }

                Map<Bytes, List<Column>> qResults = selector.getColumnsFromRows(m.getTableName(), Selector.newKeyRange("", "", maxResult), slicePredicate,
                        getConsistencyLevel());
                entities = new ArrayList<Object>(qResults.size());

                if (closed) {
                    throw new IllegalArgumentException("PelopsClient was closed after Selector was called to get columns from rows.");
                }

                computeEntityViaColumns(m, isRelation, relations, entities, qResults);
            }

        }
    } else {
        entities = new ArrayList<Object>();
        for (IndexClause ix : ixClause) {
            Map<Bytes, List<Column>> qResults = selector.getIndexedColumns(m.getTableName(), ix, slicePredicate, getConsistencyLevel());
            computeEntityViaColumns(m, isRelation, relations, entities, qResults);
        }
    }
    return entities;
}
```

ThriftClient:

```
public List find(List<IndexClause> ixClause, EntityMetadata m, boolean isRelation, 
      List<String> relations, int maxResult, List<String> columns){

    if (closed) {
        throw new IllegalArgumentException("ThriftClient was closed.");
    }

    List<Object> entities = new ArrayList<Object>();
    Cassandra.Client conn = null;
    try {
        // ixClause can be 0,1 or more!
        SlicePredicate slicePredicate = new SlicePredicate();

        if (columns != null && !columns.isEmpty()) {
            List asList = new ArrayList(32);
            for (String colName : columns) {
                if (colName != null) {
                    asList.add(Bytes.fromUTF8(colName).getBytes());
                }
            }
            slicePredicate.setColumn_names(asList);
        } else {
            SliceRange sliceRange = new SliceRange();
            sliceRange.setStart(Bytes.EMPTY.getBytes());
            sliceRange.setFinish(Bytes.EMPTY.getBytes());
            slicePredicate.setSlice_range(sliceRange);
        }

        conn = PelopsUtils.getCassandraConnection(pool);

        if (ixClause.isEmpty()) {
            KeyRange keyRange = new KeyRange(maxResult);
            keyRange.setStart_key(Bytes.nullSafeGet(Bytes.fromUTF8("")));
            keyRange.setEnd_key(Bytes.nullSafeGet(Bytes.fromUTF8("")));

            if (m.isCounterColumnType()) {

                List<KeySlice> ks = 
                                               conn.get_range_slices(new ColumnParent(m.getTableName()),      slicePredicate, keyRange, getConsistencyLevel());
                entities = onCounterColumn(m, isRelation, relations, ks);

            } else {

                if (closed) {
                    throw new IllegalArgumentException("ThriftClient was closed before get range slices.");
                }


                List<KeySlice> keySlices = conn.get_range_slices(new ColumnParent(m.getTableName()), slicePredicate, keyRange, getConsistencyLevel());

                if (closed) {
                    throw new IllegalArgumentException("ThriftClient was closed after get range slices.");
                }

                if (m.getType().isSuperColumnFamilyMetadata()) {
                    Map<Bytes, List<SuperColumn>> qResults = ThriftDataResultHelper.transformThriftResult(ColumnFamilyType.SUPER_COLUMN, keySlices, null);
                    entities = new ArrayList<Object>(qResults.size());
                    computeEntityViaSuperColumns(m, isRelation, relations, entities, qResults);
                } else {

                    Map<Bytes, List<Column>> qResults = ThriftDataResultHelper.transformThriftResult(ColumnFamilyType.COLUMN, keySlices, null);
                    entities = new ArrayList<Object>(qResults.size());
                    computeEntityViaColumns(m, isRelation, relations, entities, qResults);

                }
            }
        } else {
            entities = new ArrayList<Object>();
            for (IndexClause ix : ixClause) {
                List<KeySlice> keySlices = conn.get_indexed_slices(new ColumnParent(m.getTableName()), ix, slicePredicate, getConsistencyLevel());

                Map<Bytes, List<Column>> qResults = ThriftDataResultHelper.transformThriftResult(ColumnFamilyType.COLUMN, keySlices, null);
                // iterate through complete map and
                entities = new ArrayList<Object>(qResults.size());

                computeEntityViaColumns(m, isRelation, relations, entities, qResults);
            }
        }
    } catch (Exception irex) {
        log.error("Error during executing find, Caused by: ", irex);
        throw new PersistenceException(irex);
    } finally {
        PelopsUtils.releaseConnection(pool, conn);
    }
    return entities;
}
```

For both Client's several times the IllegalArgumentException is thrown:

Pelops: "PelopsClient was closed after Selector was called to get columns from rows."
Thrift: "ThriftClient was closed after get range slices."

Regards

**Comment by mevivs** [comment]
Can you please email me your sample project at vivek.mishra@impetus.co.in? Let me have a look.

These clients are considered to be thread-safe. Please see corresponding client factory. So such issues should not occur.I will have a look and get it fixed!

-Vivek

**Comment by mevivs** [comment]
Fixed, please verify. Thanks Marius for your contribution.

-Vivek

**Comment by Primeval** [comment]
Defect is fixed and the NPE doesn't occurs anymore!

THX

Marius
