### ISSUE TITLE
Duplicate persistence-units

### ISSUE THREAD

**Issue by ceguerra** [Impetus/kundera#252]
Hello,

I'm new to Kundera.  I'm trying to use version 2.4 but I'm getting the exception below.  I'm using hadoop Apache 1.0.4 and HBase 0.92.2.  I get the exception after running the command

hadoop jar /tmp/srm-data-0.0.1-SNAPSHOT-hadoop-job.jar KunderaJob

where KunderaJob is

public class KunderaJob {
  public static void main(String[] args) throws Exception {
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("itsrm");
       EntityManager em = emf.createEntityManager();
       System.out.println("hello");
       emf.close();
       em.close();
       System.exit (0);
  }
}

It seems that this is only happening at the client.  Looking at the code the following Kundera line code

xmls = Thread.currentThread().getContextClassLoader().getResources("META-INF/persistence.xml");

is loading the same persistence.xml file twice.  One from 

"/tmp/hadoop-hduser/hadoop-unjar2144902707866336842/META-INF/persistence.xml" 

and another from

"file:/tmp/srm-data-0.0.1-SNAPSHOT-hadoop-job.jar!/META-INF/persistence.xml"

Now if I put the same logic within a map or reduce function I don't get the exception.

Is this a bug and how I can get around it ?  We would like to use Kundera as a client (within a container or standalone) and also within a map/reduce job running inside hadoop.

Any help would be appreciated

Thanks,

Carlos

 hadoop jar /tmp/srm-data-0.0.1-SNAPSHOT-hadoop-job.jar KunderaJob
13/04/30 10:51:00 INFO kundera.KunderaPersistence: Loading Core
13/04/30 10:51:00 INFO loader.CoreLoader: Loading Kundera Core Metdata ...
13/04/30 10:51:00 INFO kundera.KunderaPersistence: Loading Application MetaData and Initializing Client(s) For Persistence Unit(s) itsrm
13/04/30 10:51:00 INFO configure.PersistenceUnitConfiguration: Loading Metadata from persistence.xml ...
13/04/30 10:51:01 ERROR configure.PersistenceUnitConfiguration: Error occurred during persistence unit configuration, Caused by:Duplicate persistence-units for name: itsrm. verify your persistence.xml file
com.impetus.kundera.loader.PersistenceLoaderException: com.impetus.kundera.utils.InvalidConfigurationException: Duplicate persistence-units for name: itsrm. verify your persistence.xml file
        at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:103)
        at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
        at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:104)
        at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:77)
        at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
        at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
        at com.rsa.srm.data.carlos.KunderaJob.run(KunderaJob.java:31)
        at com.rsa.srm.data.carlos.KunderaJob.main(KunderaJob.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:156)
Caused by: com.impetus.kundera.utils.InvalidConfigurationException: Duplicate persistence-units for name: itsrm. verify your persistence.xml file
        at com.impetus.kundera.configure.PersistenceUnitConfiguration.findPersistenceMetadatas(PersistenceUnitConfiguration.java:151)
        at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:86)
        ... 12 more

**Comment by mevivs** [comment]
"/tmp/hadoop-hduser/hadoop-unjar2144902707866336842/META-INF/persistence.xml"

Is this an exploded version of hadoop-job.jar? 

Where as , "file:/tmp/srm-data-0.0.1-SNAPSHOT-hadoop-job.jar!/META-INF/persistence.xml" is bundled within jar?

Looks like, we might need to relax on this constraint.

-Vivek

**Comment by ceguerra** [comment]
hi Vivek,

Thanks for replying.  So I have a hadoop jar to execute in the form of:

srm-data-0.0.1-SNAPSHOT-hadoop-job.jar
   META-INF/persistence.xml
   lib/<all the libraries i need for my hadoop job>
   KunderaJob.class

So it seems that hadoop explodes this jar under "/tmp/hadoop-hduser/hadoop-unjar2144902707866336842/".

Somehow also when you call the API to get the resources it looks at that exploded directory plus the jar given on the command line. That way I get 2 persistence.xml files loaded. I verified that by debugging Kundera code.  So is this a bug ?  Can we just load 1 persistence.xml and no more ?  Is there another way around it ?

Thanks,

Carlos

**Comment by mevivs** [comment]
This is not an issue with Kundera. Hadoop explodes and keep same jar file available for class loading. As i stated we will discuss about relaxing this constraint(build as part of NoSql intelligence).

As a work around, could you please package your jpa entities and persistence.xml as a seperate jar (Other than map reduce jar) and try running it.

-Vivek

**Comment by ceguerra** [comment]
Hi Vivek,

I tried your suggestion.  Basically instead of exploding my jar within the main jar (srm-data-0.0.1-SNAPSHOT-hadoop-job.jar) I create another jar and put it under the 'lib' dir.  

srm-data-0.0.1-SNAPSHOT-hadoop-job.jar
*\* lib/
****\* myjar.jar
****\* kundera-hbase-2.4.jar
****\* persistence-api-2.0.jar
****\* etc

But now when I run the hadoop job it's complaining that it can't find javax.persistence.Persistence class even though the library persistence-api-2.0.jar is part of the lib directory.

If you could relax that constraint that'd be awesome ;-)

Thanks,

Carlos

**Comment by mevivs** [comment]
Looks like, it's some packaging issue. Ok, i will analyze and will post an update on this.

-Vivek

**Comment by mevivs** [comment]
Fixed in current trunk. Please verify.

-Vivek

**Comment by mevivs** [comment]
Fixed and releasing with 2.6. Please verify.
-Vivek
