### ISSUE TITLE
If you don't put a schema attribute on your @Table, there's no warning

### ISSUE THREAD

**Issue by rsshilli** [Impetus/kundera#254]
I forgot the schema name in my @Table annotation on one of my entities, and the Entity was silently ignored by Kundera.  I see that you're trying to catch this case, but there's a bug in the code in com.impetus.kundera.metadata.processor.TableProcessor#populateMetadata in the most recent Kundera 2.5.  schemaStr gets set to "" instead of null.

```
        // set schema name and persistence unit name (if provided)
        String schemaStr = table.schema();

-        if (schemaStr == null)
+       if (schemaStr == null || "".equals(schemaStr))
        {
            LOG.error("It is mandatory to specify Schema alongwith Table name:" + table.name()
                    + ". This entity won't be persisted");
            throw new InvalidEntityDefinitionException("It is mandatory to specify Schema alongwith Table name:"
                    + table.name() + ". This entity won't be persisted");
        }
        MetadataUtils.setSchemaAndPersistenceUnit(metadata, schemaStr, puProperties);
```

**Comment by mevivs** [comment]
I will verify and get it fixed if it is an issue.

-Vivek

**Comment by mevivs** [comment]
Fixed in current trunk.

-Vivek

**Comment by mevivs** [comment]
A warning will be raised on not defining schema attribute! . Fixed in latest trunk.

Please verify.

-Vivek
