### ISSUE TITLE
No results produces a List with a null entry

### ISSUE THREAD

**Issue by rsshilli** [Impetus/kundera#255]
I don't have time to diagnose this any further, but the following line of code:

```
            List<Contact> contacts = entityManager.createQuery("select c from Contact c where c.linkedInId = '" + person.getId() + "'", Contact.class).getResultList();
```

produces:
    assert(contacts.size() ==1);
    assert(contacts.get(0) == null);

which is really strange.  Is anybody else seeing this?  This is on the new Kundera 2.5.

**Comment by mevivs** [comment]
I will verify it and will update you soon this.

-Vivek

**Comment by mevivs** [comment]
Can you please provide more detail on this?

Is there any record stored in Cassandra for "Contact" entity?

-Vivek

**Comment by rsshilli** [comment]
Yes, there's nothing in the db for the Contact entity.  As soon as I enter something, this seems to go away.

**Comment by mevivs** [comment]
Hi,
Please have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandraTest.java

Method onInsertCassandra()=>

``
Object p1 = prepareData("1", 10);
        Object p2 = prepareData("2", 20);
        Object p3 = prepareData("3", 15);

```
    Query findQuery = em.createQuery("Select p from PersonCassandra p");   ==> Here it is returning empty list!
    List<PersonCassandra> allPersons = findQuery.getResultList();
    Assert.assertNotNull(allPersons);
    Assert.assertTrue(allPersons.isEmpty());
```

``

persistence happens after these test cases.

-Vivek

**Comment by kkmishra** [comment]
Any update on this, is it still an issue for you ?

Thanks
Kuldeep

**Comment by rsshilli** [comment]
Yeah, that test looks good.  I can't explain why I'm seeing why I'm seeing.  I'd have to spend some time debugging it but I don't have that time right now.  I guess close it and I'll re-open it when I have a patch.
