### ISSUE TITLE
Named Query Where clause with a column name containing 'set' does not work

### ISSUE THREAD

**Issue by binuv** [Impetus/kundera#261]
The following query  throws a PersistenceException("bad jpa query: " + clause);

@NamedQuery(name="findSample",query="SELECT s " +
              "FROM Sample s " +
              "WHERE s.settlementDate = ?1")

The issue is with com.impetus.kundera.query.KunderaQuery.java   

The tokenization has pattern 'set'
List<String> tokens = tokenize(clause, INTRA_CLAUSE_PATTERN);

INTRA_CLAUSE_PATTERN value:    =|\blike\b|\bin\b|>=|>|<=|<|set

The tokenization with set will break the WHERE clause as the following tokens
 [s., SET, tlementDate, =, ?1]

I do not this side effect was not intended in the code. You might want to modify the "set" in  INTRA_CLAUSE_PATTERN  to "\bset\b" ( with preceding and following spaces just as you are using  like ).

**Comment by mevivs** [comment]
I will have a look.

-Vivek

**Comment by impetus-opensource-admin** [comment]
Fixed and will be released with 2.8
