### ISSUE TITLE
MongoDB and replication set

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#262]
Hi!

We have MongoDB configured as Replication Set, but AFAIK Kundera doesn't allow to set multiple values to "kundera.nodes" property. 

How can we pass multiple nodes (primary and secondaries) to kundera to reach this configuration:

![Scheme](http://1.bp.blogspot.com/-z2iA7Bk9ys8/T3yCN7xTiHI/AAAAAAAAAnE/NdpwALp1glQ/s1600/Picture1.png)

Thanks!

**Comment by mevivs** [comment]
Yes, Kundera does not support multiple nodes configuration AFN. But i guess you should be able to configure replication factor on mongo server itself and rest can be taken care by mongodb master/slave configuration? Isn't it?

-Vivek

**Comment by bsideup** [comment]
No.

MongoDB connector is designed to write only to primary, but read from any DB node (primary or secondary). Also, if primary node is down, mongo connector determine new primary node. More here: http://horicky.blogspot.com/2012/04/mongodb-architecture.html

Without this functionality kundera is useless because it will kill primary node really fast:)

**Comment by bsideup** [comment]
Also, i founded this very strange piece of code in MongoDBClientFactory.java:

``` java
private DB getConnection()
    {
...
List<ServerAddress> addrs = new ArrayList<ServerAddress>();

        Mongo mongo = null;
        try
        {
            mongo = onSetMongoServerProperties(contactNode, defaultPort, poolSize, addrs);

            logger.info("Connected to mongodb at " + contactNode + " on port " + defaultPort);
        }
```

And then:

``` java
private Mongo onSetMongoServerProperties(String contactNode, String defaultPort, String poolSize,
            List<ServerAddress> addrs) throws UnknownHostException
    {
        Mongo mongo = null;
        MongoOptions mo = null;
        MongoDBSchemaMetadata metadata = MongoDBPropertyReader.msmd;
        ClientProperties cp = metadata != null ? metadata.getClientProperties() : null;
        if (cp != null)
        {
            DataStore dataStore = metadata != null ? metadata.getDataStore() : null;
            List<Server> servers = dataStore != null && dataStore.getConnection() != null ? dataStore.getConnection()
                    .getServers() : null;
            if (servers != null && !servers.isEmpty())
            {
                for (Server server : servers)
                {
                    addrs.add(new ServerAddress(server.getHost(), Integer.parseInt(server.getPort())));
                }
                mongo = new Mongo(addrs);
            }
            else
            {
                logger.info("Connecting to mongodb at " + contactNode + " on port " + defaultPort);
                mongo = new Mongo(contactNode, Integer.parseInt(defaultPort));
            }
```

So it looks like support is almost done, isn't it?:)

**Comment by mevivs** [comment]
Yes. If you opt to define an external configuration file as : 
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/resources/kunderaMongoTest.xml

where a connection element can gave multiple server element as:

```
<connection>
                <properties>
                    <property name="read.preference" value="primary"></property>
                    <property name="socket.timeout" value="100000"></property>
                </properties>
                                 <servers>
                    <server>
                        <host>192.168.145.168</host>
                        <port>27017</port>
                    </server>
                    <server>
                        <host>192.168.145.167</host>
                        <port>27018</port>
                    </server>
                </servers>
            </connection>

```

And map it as a configuration file in persistence.xml as : 

```
<property name="kundera.client.property" value="kunderaMongoTest.xml" />
```

It should work for you. But generic configuration as "kundera.host" in persistence.xml will not work. 

Hope it helps.

-Vivek

**Comment by bsideup** [comment]
Awesome, thanks!

**Comment by mevivs** [comment]
Cool. Also you may try configuring HAProxy to handle such failover mechanism, until it is implemented in Kundera.

-Vivek

**Comment by bsideup** [comment]
I don't think this is possible 'cause mongo doesn't allow writes to slaves

**Comment by mevivs** [comment]
Ok. I will have a look for this. Let me know, if above configuration works for you.

Cheers,
-Vivek

**Comment by bsideup** [comment]
Ok. Checking now

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by bsideup** [comment]
Seems like it works for me. Thanks. We're good.

**Comment by mevivs** [comment]
Thanks. Closing.

**Comment by bsideup** [comment]
Seems like it doesn't works after version 2.2 (including) :(

**Comment by mevivs** [comment]
What's the error you getting?

Using Kundera version?

-Vivek

**Comment by chhavigangwal** [comment]
Tested with Kundera 2.6.1 by specifying multiple server connection in 

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/resources/kunderaMongoTest.xml

``` xml
<connection>
                <properties>
                    <property name="read.preference" value="primary"></property>
                    <property name="socket.timeout" value="100000"></property>
                </properties>
                                 <servers>
                    <server>
                        <host>192.168.145.168</host>
                        <port>27017</port>
                    </server>
                    <server>
                        <host>192.168.145.167</host>
                        <port>27018</port>
                    </server>
                </servers>
            </connection>
```

And mapped it as a configuration file in persistence.xml as :

``` xml
<property name="kundera.client.property" value="kunderaMongoTest.xml" />
```

Verified using crud test case of Mongodb PersonMongoTest

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java

Not reproducible

**Comment by mevivs** [comment]
@bsideup 

Could you please share more on this? What's exactly not working for you?

-Vivek

**Comment by bsideup** [comment]
Hello! Sorry for a long reply. 

I have working project with kundera-mongo 2.1 and everything is fine, kundera ignores kundera.nodes property and uses servers from mongo.xml, but when i switch to 2.5, it's fails trying to connect to node from kundera.nodes property and ignores servers from mongo.xml :(

**Comment by mevivs** [comment]
Hi,
Latest Kundera released version is 2.6.1. Could you please give it try, as verified by @chhavigangwal ?

Will try to test on 2.5 release as well.

BTW, using Kundera for?

If you could spare few minutes to fill for survery, here is the link:

http://www.surveymonkey.com/s/BMB9PWG

-Vivek

**Comment by bsideup** [comment]
Done with survey.

Same story with 2.6.1. Kundera ignores servers from mongo.xml :( 

Have you tried to specify non existing server in kundera.nodes property with kundera.client.property file? Seems like you use "localhost" everywhere, and you have mongo on localhost:)

**Comment by mevivs** [comment]
non existing server ? Do you mean incorrect IP in persistence.xml, but correct one in mongo.xml?

Please share persistence.xml and sample mongo.xml, if possible.

**Comment by bsideup** [comment]
**persistence.xml**

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
    <persistence-unit name="NNSPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>*NDA*</class>
        <properties>
            <property name="kundera.nodes" value="localhost" />
            <property name="kundera.client.property" value="META-INF/mongo.xml" />
            <property name="kundera.port" value="27017" />
            <property name="kundera.keyspace" value="NNS" />
            <property name="kundera.dialect" value="mongodb" />
            <property name="kundera.client.lookup.class" value="com.impetus.client.mongodb.MongoDBClientFactory" />
            <property name="kundera.annotations.scan.package" value="*NDA*" />
            <property name="kundera.ddl.auto.prepare" value="update" />
        </properties>
    </persistence-unit>

    <persistence-unit name="CommonPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>*NDA*</class>
        <properties>
            <property name="kundera.nodes" value="localhost" />
            <property name="kundera.client.property" value="META-INF/mongo.xml" />
            <property name="kundera.port" value="27017" />
            <property name="kundera.keyspace" value="Common" />
            <property name="kundera.dialect" value="mongodb" />
            <property name="kundera.client.lookup.class" value="com.impetus.client.mongodb.MongoDBClientFactory" />
            <property name="kundera.annotations.scan.package" value="*NDA*" />
            <property name="kundera.ddl.auto.prepare" value="update" />
        </properties>
    </persistence-unit>
</persistence>
```

**mongo.xml**

``` xml
<clientProperties>
    <datastores>
        <dataStore>
            <name>mongo</name>
            <connection>
                <servers>
                    <server>
                        <host>*some.existing.host.with.mongodb*</host>
                        <port>27017</port>
                    </server>
                </servers>
            </connection>
        </dataStore>
    </datastores>
</clientProperties>
```

**Comment by kkmishra** [comment]
Hi,
Would you please try with following changes in your persistence-unit

1) remove property  <property name="kundera.ddl.auto.prepare" value="update" />
2) and provide simple name of client property ie use mongo.xml insted of META-INF/mongo.xml.

Let me know if it is working for you.

Thanks
Kuldeep

**Comment by mevivs** [comment]
KK, correct me if i am wrong,

1) remove 

```
 <property name="kundera.ddl.auto.prepare" value="update" />
```

property.

2) Change 

```
          <property name="kundera.client.property" value="META-INF/mongo.xml" />
```

TO

```
          <property name="kundera.client.property" value="mongo.xml" />
```

-Vivek

**Comment by bsideup** [comment]
Nope, it's still trying connect to localhost (i should notice that i moved mongo.xml to src/main/resources instead of src/main/resources/META-INF/ )

**Comment by mevivs** [comment]
Just to verify

```
 <property name="kundera.ddl.auto.prepare" value="update" />
```

is commented out in persistence.xml

Could you please share more on logs?

-Vivek

**Comment by bsideup** [comment]
Whoa! It works after a clean redeploy (without kundera.ddl.auto.prepare)

So, the problem is in the kundera.ddl.auto.prepare, yes?
