### ISSUE TITLE
Entitymatadata should not be null on @SecondaryTable (v2.5)

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#263]
com.impetus.kundera.KunderaException: Entitymatadata should not be null
        at com.impetus.kundera.persistence.PersistenceDelegator.getClient(PersistenceDelegator.java:542)
        at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:262)
        at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:210)
        at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:257)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366)
        at sun.proxy.$Proxy177.find(Unknown Source)

**Comment by mevivs** [comment]
Can you please provide more detail on this? Latest Kundera release does not support @SecondryTable annotation.

-Vivek

**Comment by bsideup** [comment]
@mevivs 
https://github.com/impetus-opensource/Kundera/issues/103
you sure?

**Comment by mevivs** [comment]
YES. Issue referred was a fix for "SharedByPrimaryKey" case only.

-Vivek

**Comment by bsideup** [comment]
Oh, sorry. I understood it wrong.

And..... any estimates on @SecondaryTable support?

**Comment by mevivs** [comment]
Planned with @MappedSuperclass support. Will post an update once we start on it.

-Vivek

**Comment by bsideup** [comment]
It's not what i'm looking for, but ok.

And... is there any way to support multiple databases on one entity? We're planing to lazy migrate database from cassandra to mongodb, and we need to connect two databases at the same time with one Entity. Is it possible?

**Comment by mevivs** [comment]
Without changing Entity for @Table annotation? If yes, there is some tweaks which you need to do pro grammatically to get this working.

```
With any persistence technology, schema name is fixed at the time of creating entity class.

For using different schema names wrt single entity class in different test environments, you can use tweaks:

1. Create separate persistence units in persistence.xml for each environment.

2. Modify persitence unit into entity metadata programmatically in test case corresponding to that particular environment. 
Map<String, Metamodel> metaModels = KunderaMetadata.INSTANCE.getApplicationMetadata().getMetamodelMap();

    EntityMetadata entityMetadata = KunderaMetadataManager.getEntityMetadata(Account.class);
                for (Metamodel m : metaModels.values())
                {
                    entityMetadata = ((MetamodelImpl) m).getEntityMetadataMap().get(Account.class);
                    if (entityMetadata != null)
                    {
                        break;
                    }
                }
   entityMetadata.setPersistenceUnit("kundera_testu_pu");

3. Modify schema name in test case corresponding to that environment

PersistenceUnitMetadata puMetadata = KunderaMetadata.INSTANCE.getApplicationMetadata()
                        .getPersistenceUnitMetadata("kundera_testu_pu");
String schema = puMetadata.getProperty(PersistenceProperties.KUNDERA_KEYSPACE);
entityMetadata.setSchema(schema);

```

So in above mention example, you can use Account entity for different persistence unit at runtime.
Hope it helps.

**Comment by bsideup** [comment]
But will it works with 2 databases (and schemes) at the same time?

Because our workflow looks something like:
1) read from mongo
2) if result is null, read from cassandra
3) if result is not null, persist result to mongo and return result

**Comment by mevivs** [comment]
I guess given below steps should work for you:

Precondition: Your entity by default annotated for mongoDB

1) Read from mongodb
2) if result is null, switch for pu to Cassandra(refer above code snippet)
3) read from Cassandra
4) If result is not null, switch for pu to mongodb
5) Persist to mongoDB
6) return result.

HTH,

-Vivek

**Comment by bsideup** [comment]
Okay, thanks, i will try it.

BTW, it is not possible to not specify Schema in @Table, right? This is only one point where my flow doesn't work;(

**Comment by mevivs** [comment]
Nope. That's how entity is mapped to a "keyspace" for given persistence unit

-Vivek

**Comment by bsideup** [comment]
but keyspace if already set for PU in persistence.xml

**Comment by mevivs** [comment]
To map an entity for a persistence unit you need to mention it under <class> tag but that's optional, so if user does not mention it under class tag, it's difficult to recognize entity is meant for which database, unless you specify something like schema to map properly with a persistence unit.

-Vivek

**Comment by mevivs** [comment]
Support for SecondryTable and AbstractEntityClass is releasing with 2.9.  

Is this still an issue?

-Vivek
