### ISSUE TITLE
support for TTL per column value while inserting data.

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#265]
Currently Kundera does not provide support to provide TTL while inserting data in column family as:

```
set test[row1][col2] = 'val2' with ttl=60
```

or 

```
INSERT INTO users (KEY, password) VALUES ('jsmith', 'ch@ngem3a') USING TTL 86400;
```

**Comment by pires** [comment]
+1

**Comment by xamry** [comment]
In addition to Per-column TTL which is already there, Per-CF TTL is slated for Cassandra 2.0 release:
https://issues.apache.org/jira/browse/CASSANDRA-3974

**Comment by pires** [comment]
Why was this closed? Is it supported already?

**Comment by mevivs** [comment]
Yes. TTL has been supported in recent 2.6 release.

**Comment by pires** [comment]
How can I use it, then?

**Comment by mevivs** [comment]
Hi Paulo,
Please refer:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandraTTLTest.java

-Vivek

**Comment by pires** [comment]
Is it possible for one to set TTL with JPA annotations? Something like:

```
@Entity(ttl = 60)
public class MyEntity {
  @Id
  private UUID id;

  ...

}
```
