### ISSUE TITLE
No Entity metadata found for the class

### ISSUE THREAD

**Issue by dondragon2** [Impetus/kundera#266]
I am using version 2.5 of kundera. Everything is setup properly in my estimation but I keep getting the following warning when persisting a collection in an entity and the collection is never persisted. What could be wrong?

13:25:02,730  WARN KunderaMetadataManager:152 - No Entity metadata found for the class class java.util.HashSet. Any CRUD operation on this entity will fail.If your entity is for RDBMS, make sure you put fully qualified entity class name under <class></class> tag in persistence.xml for RDBMS persistence unit. Returning null value.

@Entity
@Table(name = "MyEntry",schema = "MAGII@magii_pu")
@TableGenerator(name = "table_gen")
public class MyEntry implements  Serializable {

```
@Id
@TableGenerator(name = "table_gen_1")
@GeneratedValue(generator = "table_gen", strategy = GenerationType.TABLE)
Long id = -1L;

@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER, mappedBy = "entry")
Set<CurrentStep> currentSteps;
```

...
## }

@Entity
@Table(name = "CurrentStep",schema = "MAGII@magii_pu")
@TableGenerator(name = "table_gen")
public class CurrentStep {

```
@Id
@TableGenerator(name = "table_gen_2")
@GeneratedValue(generator = "table_gen", strategy = GenerationType.TABLE)
Long id = -1L;
```

 @ManyToOne(fetch = FetchType.LAZY)
    MyEntry entry;
...
## }

<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" version="2.0">

```
<persistence-unit name="magii_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.uluru.safire.cassandra.domain.CurrentStep</class>
    <class>com.uluru.safire.cassandra.domain.MyEntry</class>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="9160" />
        <property name="kundera.keyspace" value="MAGII" />
        <property name="kundera.dialect" value="cassandra" />
        <property name="kundera.client" value="pelops" />
        <property name="kundera.ddl.auto.prepare" value="create" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
    </properties>
</persistence-unit>
```

</persistence>

---

```
    MyEntry entry = new MyEntry();
    entry.setState(0);
    entry.setVersion(0);
    entry.setName("test"+System.currentTimeMillis());

    CurrentStep step = new CurrentStep();
    step.setName("donald");

    entry.addCurrentSteps(step);

    em.persist(entry);
```

**Comment by mevivs** [comment]
Hi,
This looks ok to me. Can you please given below code snippet? If it works for you?

```
@Entity
@Table(name = "MyEntry",schema = "MAGII@magii_pu")
@TableGenerator(name = "table_gen")
public class MyEntry implements Serializable {

@Id
@TableGenerator(name = "table_gen_1")
@GeneratedValue(generator = "table_gen", strategy = GenerationType.TABLE)
@Column(name="myentry_id")
private Long id = -1L;

@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER, mappedBy = "entry")
Set<CurrentStep> currentSteps;
}

```

```
@Entity
@Table(name = "CurrentStep",schema = "MAGII@magii_pu")
@TableGenerator(name = "table_gen")
public class CurrentStep {

@Id
@TableGenerator(name = "table_gen_2")
@GeneratedValue(generator = "table_gen", strategy = GenerationType.TABLE)
private Long id = -1L;
@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "myentry_id")
private MyEntry entry;
}
```

Added @JoinColumn and @Column annotation in CurrentStep and MyEntry entities respectively.

Also, you may also refer to:
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-tests/src/test/java/com/impetus/kundera/tests/crossdatastore/useraddress/entities

for different association entity definitions.

Hope it helps.

-Vivek

**Comment by dondragon2** [comment]
Thanks for the insight but there is a failure when setting the entry variable on the current step and the warning is still there. Below is the output that I see.

14:57:36,219  WARN KunderaMetadataManager:152 - No Entity metadata found for the class class java.util.HashSet. Any CRUD operation on this entity will fail.If your entity is for RDBMS, make sure you put fully qualified entity class name under <class></class> tag in persistence.xml for RDBMS persistence unit. Returning null value.
14:57:36,240 DEBUG CacheBase:170 - Node: com.uluru.safire.cassandra.domain.MyEntry$0:: ADDED TO  Persistence Context
14:57:36,243 DEBUG CacheBase:170 - Node: com.uluru.safire.cassandra.domain.CurrentStep$-1:: ADDED TO  Persistence Context
14:57:36,245 DEBUG PersistenceDelegator:422 - Flushing following flush stack to database(s) (showing stack objects from top to bottom):
[[com.uluru.safire.cassandra.domain.MyEntry$0]com.uluru.safire.cassandra.domain.MyEntry$0, [com.uluru.safire.cassandra.domain.CurrentStep$-1]com.uluru.safire.cassandra.domain.CurrentStep$-1]
14:57:36,245 DEBUG PooledConnection:212 - [Cassandra Connection Pool[1-809222561]] Obtained a new connection to [localhost,status=true,timestamp=1368644256245]
14:57:36,264 DEBUG PersistenceDelegator:196 - Data persisted successfully for entity : class com.uluru.safire.cassandra.domain.MyEntry
14:57:36,271  INFO QueryImpl:150 - On getResultList() executing query: Select p from MyEntry p
14:58:15,389  WARN CassandraDataHandlerBase:1203 - Error while setting field value, Caused by: com.impetus.kundera.property.PropertyAccessException: java.io.StreamCorruptedException: invalid stream header: 00000000
14:58:15,389 DEBUG CacheBase:170 - Node: com.uluru.safire.cassandra.domain.CurrentStep$-1:: ADDED TO  Persistence Context
[MyEntry{id=0, currentSteps=[CurrentStep{id=-1, dueDate=null, finishDate=null, startDate=null, caller=donald, owner=null, status=null, actionId=1, stepId=0}], historySteps=null, name=test1368644256200, state=0, version=0}]

**Comment by xamry** [comment]
This warning is not going to affect correct working of your entity
persistence in all likelyhood (let us know if it does).
But definitely this warning shouldn't be there. Your code would need to be
run in order to reproduce the bug. Would it be possible for you to send
your sample project code?

**Comment by dondragon2** [comment]
sorry you can download the sample project from.

http://www.gisonline.mobi/samples/sample.zip

Let me know if you are able to download the project

**Comment by xamry** [comment]
I tried setting up your project, but there are compilation errors. namely
classes in com.uluru.safire.api package are missing. (probably coming from
parent project)

Could you send that code as well.

Amresh

**Comment by dondragon2** [comment]
Thanks for pointing that out. I made the changes. Please try again. http://www.gisonline.mobi/samples/sample.zip

**Comment by mevivs** [comment]
Can you please verify this with latest 2.6 release?
