### ISSUE TITLE
Fork Junits

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#272]
With current Kundera build, all junits are executed on a single thread. We should fork junits for better performance and faster run. We simply need to configure pom files for examples as:

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.9</version>
                <configuration>
                    <forkCount>10</forkCount>
                    <reuseForks>true</reuseForks>
                </configuration>
            </plugin>
```

**Comment by pires** [comment]
If multiple tests run concurrently, we may end having corrupt data for embedded daemons like Cassandra.
