### ISSUE TITLE
Spring persistence config support

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#275]
Hi!

Is it possible to set persistence properties from Spring? Something like that:

<bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean" depends-on="config">
        <property name="persistenceUnitName" value="SomePU"/>
        <property name="jpaProperties">
            <props>
                <prop key="kundera.nodes">mongo1</prop>
            </props>
        </property>
    </bean>

**Comment by mevivs** [comment]
Hi
Nothing is visible on above description. Please provide correct details.

-Vviek

**Comment by bsideup** [comment]
Damn, i doesn't know that GitHub isn't allow XML.

But after upgrade to 2.5 issue is gone. Sorry:)
