### ISSUE TITLE
[Cassandra] Secondary indexes are not generated in entity identified by composite-key

### ISSUE THREAD

**Issue by pires** [Impetus/kundera#277]
Please, see discussion at https://groups.google.com/forum/?fromgroups=#!topic/kundera-discuss/R9H6YIUXQQI.

The problem happens at schema generation, when an entity has a composite-key, namely method _CassandraSchemaManager.onCompoundKey()_, where it's missing code for dealing with indexable columns.

**Comment by pires** [comment]
Hey @mevivs you have fixed this, or at least provided a working patch. Can this be closed then?

**Comment by mevivs** [comment]
Hi Paulo,
This has been fixed with : 
0e7f36d48555e9ea0b5b57e2aadd8fae8fbfaeb2

-Vivek

**Comment by mevivs** [comment]
Fixed and releasing with 2.6. Please verify.
-Vivek

**Comment by pires** [comment]
Works for me. Thanks.
