### ISSUE TITLE
JPQL or CQL 3.0?

### ISSUE THREAD

**Issue by sachur** [Impetus/kundera#279]
After installing cassandra 1.2 and have CQL 3.0, which I recommend to use JPQL or CQL3.0? Which is more efficient?

Thanks

**Comment by mevivs** [comment]
If you set CQL3.0 as a version with Kundera, then by default all JPQL will automatically be converted in to CQL queries via Kundera!

With 2.5 release onwards, Kundera automatically does all CRUD in CQL3 way, if you opt for CQL3 version while dealing with Kundera.

HTH,

-Vivek

**Comment by sachur** [comment]
When working with CQL 3.0, JPQL queries do not work, only the native queries.

Should I stop using JPQL and use only native queries?

**Comment by mevivs** [comment]
That's not entirely correct. Have a look at : 
https://github.com/impetus-opensource/Kundera/wiki/JPQL

for supported feature set. However support for IN clause etc will not work as of now, work is planned for future Kundera releases.

You may also find a number JPQL junits running over CQL3 undera kundera-cassandra/test package.

-Vivek

**Comment by sachur** [comment]
Thank you very much. For now I will continue using JPQL

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by sachur** [comment]
Yes. Regards
