### ISSUE TITLE
Cassandra Primary Key Auto generation Exception

### ISSUE THREAD

**Issue by jinagko** [Impetus/kundera#286]
Hi~
with Cassandra-1.2.4.
Kundera-cassandra-2.5.
I used "TABLE generation strategy" like that:
1.User.java;

@Entity
@Table(name = "USER", schema = "keyspace-Name@pu-name")
public class User
{
    @Id
    @TableGenerator(name = "id_gen", allocationSize = 30, initialValue = 100)
    @GeneratedValue(generator = "id_gen", strategy = GenerationType.TABLE)
    private String id;
    @Column
    private String name;
    // getter and setter
}

2.Struts2Action.java;

public String execute(){
        EntityManager em = entityManagerFactory.createEntityManager();
        User user = new User();
            user.setFirstName("John");
            user.setLastName("Smith");
            user.setCity("London");
            em.persist(user);
            em.close();  
            entityManagerFactory.close();  
        return "success";
}

occur an exception:

(root cause)

java.lang.ClassCastException: org.apache.cassandra.thrift.Cassandra$Client cannot be cast to org.scale7.cassandra.pelops.pool.IThriftPool$IPooledConnection
    com.impetus.client.cassandra.pelops.PelopsClient.releaseConnection(PelopsClient.java:815)
    com.impetus.client.cassandra.CassandraClientBase.getGeneratedValue(CassandraClientBase.java:1636)
    com.impetus.client.cassandra.pelops.PelopsClient.generate(PelopsClient.java:821)
    com.impetus.client.cassandra.pelops.PelopsClient.generate(PelopsClient.java:94)
    com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:144)
    com.impetus.kundera.persistence.IdGenerator.setGeneratedIdIfApplicable(IdGenerator.java:57)
    com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:147)
    com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    java.lang.reflect.Method.invoke(Method.java:597)
    org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    $Proxy21.persist(Unknown Source)
    com.test.action.Struts2Action.execute(Struts2Action.java:15)

this Exception Pointing to  "em.persist(user);"

It's so kind of your to read this, and could anyone teach me how to use cassandera with "Primary Key Auto generation" ,please?

**Comment by kkmishra** [comment]
I suggest you to try with kundera-2.5.1, and let me know if problem persists.

Thanks
Kuldeep

**Comment by jinagko** [comment]
Dear,Kuldeep
Thanks for your reply, I had try with kundera latest version,It occur another Exception like that:

HTTP Status 500 - com.impetus.kundera.KunderaException: Error while using keyspace

(root cause )

InvalidRequestException(why:unconfigured columnfamily kundera_sequences)
    org.apache.cassandra.thrift.Cassandra$get_result.read(Cassandra.java:6592)
    org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    org.apache.cassandra.thrift.Cassandra$Client.recv_get(Cassandra.java:556)
    org.apache.cassandra.thrift.Cassandra$Client.get(Cassandra.java:541)
    com.impetus.client.cassandra.CassandraClientBase.getGeneratedValue(CassandraClientBase.java:1614)
    com.impetus.client.cassandra.pelops.PelopsClient.generate(PelopsClient.java:809)
    com.impetus.client.cassandra.pelops.PelopsClient.generate(PelopsClient.java:1)
    com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:148)
    com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:60)
    com.impetus.kundera.graph.ObjectGraphBuilder.getNode(ObjectGraphBuilder.java:106)
    com.impetus.kundera.graph.ObjectGraphBuilder.getObjectGraph(ObjectGraphBuilder.java:73)
    com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:142)
    com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    java.lang.reflect.Method.invoke(Method.java:597)
    org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    $Proxy21.persist(Unknown Source)

is it means I have to create a columnfamily name " kundera_sequences" as default ?

but when I create a columnfamily ,It change to another exception ,

InvalidRequestException(why:invalid operation for non commutative columnfamily kundera_sequences)
    org.apache.cassandra.thrift.Cassandra$add_result.read(Cassandra.java:17674)
    org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    org.apache.cassandra.thrift.Cassandra$Client.recv_add(Cassandra.java:871)
    org.apache.cassandra.thrift.Cassandra$Client.add(Cassandra.java:855)
    com.impetus.client.cassandra.CassandraClientBase.getGeneratedValue(CassandraClientBase.java:1626)
    com.impetus.client.cassandra.pelops.PelopsClient.generate(PelopsClient.java:809)
    com.impetus.client.cassandra.pelops.PelopsClient.generate(PelopsClient.java:1)
    com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:148)
    com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:60)
    com.impetus.kundera.graph.ObjectGraphBuilder.getNode(ObjectGraphBuilder.java:106)
    com.impetus.kundera.graph.ObjectGraphBuilder.getObjectGraph(ObjectGraphBuilder.java:73)
    com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:142)
    com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    java.lang.reflect.Method.invoke(Method.java:597)
    org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    $Proxy21.persist(Unknown Source)

where is the problem ?
Thanks.

**Comment by mevivs** [comment]
Hi,
Did you opt for auto schema generation option via Kundera? As per the error, it looks like column family is not in place.

In case you didn't and want Kundera to manage your schema, then you need to configure as:

```
<property name="kundera.ddl.auto.prepare" value="create" />
```

in persistence.xml

Else you can also create it manually. Please refer https://github.com/impetus-opensource/Kundera/wiki/Common-Configuration for more information.

-Vivek

**Comment by jinagko** [comment]
oh~yep,thank you very much!
