### ISSUE TITLE
NPE with generated value

### ISSUE THREAD

**Issue by bejayoharen** [Impetus/kundera#292]
I am porting some code and am getting this exception:

Caused by: java.lang.NullPointerException
    at com.impetus.kundera.configure.MetamodelConfiguration.processGeneratedValueAnnotation(MetamodelConfiguration.java:452)
    at com.impetus.kundera.configure.MetamodelConfiguration.scanClassAndPutMetadata(MetamodelConfiguration.java:370)
    at com.impetus.kundera.configure.MetamodelConfiguration.loadEntityMetadata(MetamodelConfiguration.java:227)
    at com.impetus.kundera.configure.MetamodelConfiguration.configure(MetamodelConfiguration.java:107)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:109)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:81)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at com.xonami.rest.db.EMFactory.<clinit>(EMFactory.java:19)
    ... 61 more

I assuming this has something to do with the @GeneratedValue annotations,  but I can't figure out what. I am using mongodb. My annotations look like this:

```
@Id
@Column
@GeneratedValue(strategy = GenerationType.AUTO)
private String key;
```

Some of them are annotated with @Column, some are not.

**Comment by mevivs** [comment]
Hi,
Do you need  primary key to  be auto generated using @GeneratedValue?

-Vivek

**Comment by mevivs** [comment]
Please refer:
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-mongo/src/test/java/com/impetus/client/generatedId

for more on usage of @GeneratedValue over MongoDB.

**Comment by bejayoharen** [comment]
The original code uses it (@GeneratedValues). I'd like to map the original code as closely as possible before changing things, so yes, I need autogenerated primary keys.

**Comment by bejayoharen** [comment]
That link uses ObjectIds, which are familiar from mongo. It also uses @TableGenerator. The docs here:

https://github.com/impetus-opensource/Kundera/wiki/Primary-Key-Auto-generation

use Strings and no mention of @TableGenerator. I Followed the docs. What do I need to change?

If my usage is not correct:
- the docs should be updated, and
- A correct error message should be displayed rather than a NPE.

**Comment by mevivs** [comment]
Did you try referrring to:
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-mongo/src/test/java/com/impetus/client/generatedId

for more on usage of @GeneratedValue over MongoDB.

If yes, and still getting error, please share your code snippet link

-Vivek

**Comment by mevivs** [comment]
KK,
Please look into this.

-Vivek

**Comment by bejayoharen** [comment]
"Did you try referrring to:" Yes. As I said, it is different from the docs:
- The Docs use the String type for generated ids, whereas the code you linked to uses ObjectIds.
- The Docs make no mention of @TableGenerator, whereas the code you linked to uses it.

Do I need to change both things, or just the type? I have 19 generated values in my code, so it's a fair bit of code to go over and I'd like to just change the type if that's all I need to change. Moreover:
- Your docs are wrong.
- This should not cause a NPE. it should display a useful error message.

**Comment by mevivs** [comment]
As per 
https://github.com/impetus-opensource/Kundera/wiki/Primary-Key-Auto-generation:

Table generation strategy is only applicable to "Cassandra" and "HBase". 

```
The Docs use the String type for generated ids, whereas the code you linked to uses ObjectIds.
```

In case, you want _id field in mongodb to be of type ObjectId, then only you need to declare it as "ObjectId" in your entities. If you define them as "String" type, by default _id field in mongodb will persisted as  auto generated "ObjectId.toString()", method

```
Your docs are wrong.
```

I will get them updated for above mentioned information, Thanks for pointing it out.

```
This should not cause a NPE. it should display a useful error message.
```

It should not be thrown and a proper message should have been displayed. I will verify it.

Thanks,
-Vivek

**Comment by mevivs** [comment]
Version of Kundera referring to? Is it 2.5 or 2.5.1?

-Vivek

**Comment by bejayoharen** [comment]
- I am using 2.5. I'll try 2.5.1 and will report if it's different.
- I have changed all instances of String to ObjectId and error remains. I cannot share the code, but if I can't get past this I'll try to reproduce on a smaller example, if I can.

**Comment by mevivs** [comment]
For:

```
This should not cause a NPE. it should display a useful error message.
```

Did you specify Entity with @Table annotation, as for example:

```
@Table(name = "PERSON", schema = "keyspace@mongo_pu")
```

To map it correctly with MongoDB, you need to add this over Entity definition.

-Vivek

**Comment by bejayoharen** [comment]
Yes, I did that. IIRC, I also got a different mysterious error until I added that.

It _is_ possible I'm using some other unsupported annotations.

**Comment by mevivs** [comment]
Ok. Let me know, if you can carve out a sample example to verify and look into the issue.

-Vivek

**Comment by bejayoharen** [comment]
Is @MappedSuperclass supported?

**Comment by mevivs** [comment]
Not yet. 
https://github.com/impetus-opensource/Kundera/issues/56

**Comment by bejayoharen** [comment]
Thanks. That may be my issue. I can't tell with current error messages.
