### ISSUE TITLE
@ManyToOne does not fetch parent

### ISSUE THREAD

**Issue by bejayoharen** [Impetus/kundera#296]
In my system, a user may have one or more email addresses. I have removed fields that are not required for explanation:

```
@Entity(name = "XonamiUser")
@Table(name = "XonamiUser", schema = "xonami@mongo")
public class XonamiUser implements {

@Id
@Column
private String userId;

@Column
@OneToMany(cascade=CascadeType.ALL, mappedBy="xonamiUser", fetch=FetchType.EAGER, targetEntity = EmailAddress.class )
private Set<EmailAddress> emails;
....

@Entity( name = "EmailAddress" )
@Table( name = "EmailAddress", schema = "xonami@mongo" )
public class EmailAddress {
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
private ObjectId key;

@Column
private String userId; //FIXME

@Column
@ManyToOne( fetch = FetchType.EAGER, optional = false )
private XonamiUser xonamiUser;

@Column
private String email;
....
```

Creating a user with a single email address produces this:

<pre>
db.XonamiUser.find().pretty();
{
    "_id" : "42000ddb-716b-4132-b3b7-465abbfa1894",
    ....
}
db.EmailAddress.find().pretty();
{
    "_id" : ObjectId("51b7d7285b06e68029cbed1c"),
    "email" : "bjorn@....",
....
    "userId" : "42000ddb-716b-4132-b3b7-465abbfa1894"
}
</pre>

Great! (Note I get the same result even if I userId field in my email object).

Unfortunately, when I fetch the Email address using this query:

```
SELECT ea FROM EmailAddress ea WHERE ea.emaillc = :email: 
```

I get an object that does not have a XonamiUser attached (ie, the xonamiUser Field in EmailAddress is null). I can fetch the XonamiUser by calling find(XonamiUser.class, ea.userId) on the entity manager, but this is obviously a step I should not need to take.
- I should not need to manually fetch the XonamiUser object.
- I have tried several things with @JoinColumn (although this is not necessary in Hibernate or Datanucleus, IIRC.)
- I should not need to store a userId field in my email object.
- note that if I try to persist the email address before the XonamiUser, I get an Error about a null key, even if I later persist the XonamiUser object in the same transaction. I don't think this is a problem in hibernate or datanucleus.

**Comment by mevivs** [comment]
Can you please modify

```
@Column
@ManyToOne( fetch = FetchType.EAGER, optional = false )
private XonamiUser xonamiUser;
```

as

```
@Column
@ManyToOne( fetch = FetchType.EAGER, optional = false )
@JoinColumn(name="userId")
private XonamiUser xonamiUser;

```

and then try?

-Vivek

**Comment by bejayoharen** [comment]
This only works if I have a userId variable in EmailAddress, which is not how Hibernate or Datanucleus behave, and I don't think it's to spec.

**Comment by mevivs** [comment]
if XonamiUser has one to many relation with EmailAddress, which means XonamiUser's id will be a reference key and will be stored down in EmailAddress. IIRC that should be same behaviour in traditional RDBMS as well.

Issue on which i am working upon is, it is currently limited to have XonamiUser's @Id attribute present as @JoinColumn with EmailAddress entity. 

-Vivek

**Comment by pires** [comment]
@mevivs is right.

You need to identify the **JoinColum**(s) to join with. Otherwise, it isn't possible. Oh, and you can call it whatever you want.
