### ISSUE TITLE
persist fails to store modified data

### ISSUE THREAD

**Issue by bejayoharen** [Impetus/kundera#298]
I am fetching data using EntityManager.find(). Then, modifying by setting a previously null Sting to not null, and persisting it to mongo. The following code works as expected:

```
//begin transaction
XonamiUser xu = em.find( .... );
xu.modifyIt();
em.merge(xu);
//end transaction
```

but this code does not:

```
//begin transaction
XonamiUser xu = em.find( .... );
xu.modifyIt();
em.persist(xu);
//end transaction
```

Both should work.

http://stackoverflow.com/questions/1069992/jpa-entitymanager-why-use-persist-over-merge

Persist is preferred in this case.

http://stackoverflow.com/questions/8469871/jpa-merge-vs-persist

**Comment by pires** [comment]
You can use _merge()_ but be sure to make changes to your entity prior to merging/updating changes to the database. _persist()_ may expect the entity to be changed in the database like changing the returning ID and you'll have problems with that, especially if you use auto-generated IDs.

Example:

``` java
MyEntity e = new MyEntity();
em.persist(e);

...

e = em.find("e_id");
e.setAttributeX("x");
e.setAttributeY(null);
em.merge(e);
```

Another interesting article can be found at http://spitballer.blogspot.pt/2010/04/jpa-persisting-vs-merging-entites.html
