### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by bejayoharen** [Impetus/kundera#299]
When making the following (incorrect) query:

```
"SELECT u FROM XonamiUser u WHERE userId = :userId"
```

I get this error message:

<pre>
INFO com.impetus.kundera.query.KunderaQuery - No column found by this name : erId checking for embeddedfield
Jun 12, 2013 2:36:16 PM org.restlet.resource.ServerResource doCatch
WARNING: Exception or error caught in server resource
Internal Server Error (500) - attribute of the given name and type is not present in the managed type, for name:erId
</pre>

Obviously, my query should have been:

```
"SELECT u FROM XonamiUser u WHERE u.userId = :userId"
```

but the error message for my original query was incorrect and confusing.

Incidentally, the incorrect query worked on hibernate. I don't mind that Kundera is more picky about this, but just FYI.

**Comment by mevivs** [comment]
Fixed in current trunk.

-Vivek
