### ISSUE TITLE
Nativequery returns all results

### ISSUE THREAD

**Issue by bejayoharen** [Impetus/kundera#301]
Using a native query in mongodb seems to always return all results. For example, in this code, I get a full, unfiltered list of users no matter what I put in my query:

```
List<XonamiUser> users = em.createNativeQuery(query,XonamiUser.class).getResultList();
```

on the mongodb shell, I am easily able to filter users:

```
db.XonamiUser.find( { "accountStatus" : "ACTIVE" , "searchList" : "jazz" } );
```

Of course, I don't get any errors, even if my query is wrong, so I suspect no parsing of my query is being done at all.

**Comment by mevivs** [comment]
Native query will never be parsed within Kundera, as they are meant for database. Also, please share native query which you are working upon?

-Vivek

**Comment by bejayoharen** [comment]
I tried a variety of queries. Here's one:

```
        String query = "db.XonamiUser.find( { \"accountStatus\" : \"ACTIVE\", \"searchList\" : \"jazz\" } )" ; 
        @SuppressWarnings("unchecked")
        List<XonamiUser> users = em.createNativeQuery(query,XonamiUser.class).getResultList();
```

and another:

```
        String query = "\"accountStatus\" : \"ACTIVE\", \"searchList\" : \"jazz\"" ; 
```

and so on. I always got a list of all users. There's no docs or tests (that I'm aware of) for how to do this in mongo, so I'm not sure what form the native query takes.

**Comment by mevivs** [comment]
First, this is a db script, not a native query. To execute a DB script with MongoDB in Kundera, please refer:
https://github.com/impetus-opensource/Kundera/issues/248

This would simply return you object returned by mongodb itself. There is no such native query support for MongoDB.

-Vivek

**Comment by bejayoharen** [comment]
Are you saying native queries are not supported with Kundera/mongo? There are release notes (eg here: https://groups.google.com/forum/?fromgroups#!topic/mongodb-user/KGZiwC1aYwA) which specify support for native queries. Mongo is not excluded.

What would a native mongo query look like, if not that?

**Comment by mevivs** [comment]
AFAIK, example which you referring to are just db scripts, not the native queries within MongoDB. You can execute them as i mentioned above.

**Comment by mevivs** [comment]
Please refer, https://github.com/impetus-opensource/Kundera#08-nov-2012---kundera-22-released 
for release notes.

-Vivek

**Comment by bejayoharen** [comment]
Those release notes say the same thing.

**Comment by bejayoharen** [comment]
I tried this query (where client is as per your code):

```
        String jScript = "db.XonamiUser.find( { \"accountStatus\" : \"ACTIVE\" } ) ;" ;
        Object result = client.executeScript(jScript);

        System.out.println( result.getClass() );
        System.out.println( result );
```

which output:

```
class com.mongodb.BasicDBObject
{ "value" : "DBQuery: xonami.XonamiUser -> undefined"}
```

I don't see how this is usable.

But on the shell the same query got different results, which are quite usable:

```
db.XonamiUser.find( { "accountStatus" : "ACTIVE" } ) ;
{ "_id" : "6f168024-6650-404b-b829-0afa055bbecf", "searchList" : [ "xowave", "bjorn@xowave.com", "bjornroche", "bjorn", "roche" ], "paymentPlan" : NumberLong(0), "restrictionFlags" : NumberLong(0), "accountStatus" : "ACTIVE", "password" : .... }
{ "_id" : "4a508c1a-5c9e-435d-b0a3-8b685c693dfb", "searchList" : [  "audio",    "xo audio",     "another@user.com",     "another user",     "another",  "user",     "rock",     "jazz",     "indie",    "dittmer",  "multi",    "word",     "multi-word tag" ], "paymentPlan" : NumberLong(0), "restrictionFlags" : NumberLong(0), "accountStatus" : "ACTIVE", .... }
```

Also, I note your test doesn't check the values, it just checks to see if it's null or not. I should note that even if my query returns no results, the response in non-null, so this code:

```
        String jScript = "db.XonamiUser.find( { \"accountStatus\" : \"NEW\" } ) ;" ;
        Object result = client.executeScript(jScript);

        System.out.println( result.getClass() );
        System.out.println( result );
```

also output:

```
class com.mongodb.BasicDBObject
{ "value" : "DBQuery: xonami.XonamiUser -> undefined"}
```

I think you need better tests.

**Comment by mevivs** [comment]
Thanks. Could you please enhance and contribute such pull requests?

I will discuss within team about incorporating such db scripts => Entity transformation.

-Vivek

**Comment by bejayoharen** [comment]
As you can probably tell, I have my hands full porting my app to MongoDB among other tasks. :( I wish I could help more than by submitting bug reports, but if I have some time I will try to familiarize myself with the codebase.

**Comment by mevivs** [comment]
Sure. looking forward for more discussion around Kundera usage and your app portability issue(s).

-Vivek

**Comment by mevivs** [comment]
Fixed on current trunk

-Vivek
