### ISSUE TITLE
Data Migration from MYSQL to Cassandra

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#309]
Hi We are planning to migrate from mysql to no sql (cassandra).The columnfamilies in the cassandra DB dont have the same structure as the old mysql db.
Need ideas on the ways to export data from old system to Cassandra.
Are there any tools available in the market which can help.
I have billions of data which needs migration.

**Comment by mevivs** [comment]
Hi,
Have a look at:
http://www.datastax.com/docs/datastax_enterprise2.0/sqoop/sqoop_about

See if it helps.

-Vivek

**Comment by pires** [comment]
Moving from a relational to a non-relational data-model difficulty level is proportional to your level of relational data-model design skills. It takes lots of study - there are plenty presentations out there - and practice! Do not take this lightly, or you'll face hell very soon ;-)
