### ISSUE TITLE
Fix for the #313 issue ,please check on

### ISSUE THREAD

**Issue by jinagko** [Impetus/kundera#314]
Hi,
I fix the problem yesterday~,Although nobody understand what I said,It works well on my project now.
<a href="https://github.com/impetus-opensource/Kundera/issues/313">#313</a>
kundera-core-2.5.1,
com.impetus.kundera.graph.ObjectGraphBuilder
Fixed in method  "private Node getNode(.......)"
before:

<pre><code>
        // Generate and set Id if @GeneratedValue present.

        if (initialNodeState != null && initialNodeState.getClass().equals(TransientState.class))
        {
               
                idGenerator.generateAndSetId(entity, entityMetadata, pd);
         }
</code></pre>

after:

<pre><code>
        // Generate and set Id if @GeneratedValue present.

        if (initialNodeState != null && initialNodeState.getClass().equals(TransientState.class))
        {
            Object id = PropertyAccessorHelper.getId(entity, entityMetadata);
            if(id==null){
                idGenerator.generateAndSetId(entity, entityMetadata, pd);
            }
        }</code></pre>

**Comment by mevivs** [comment]
Hi,
Thanks for the fix. I did get the issue #313 . Got one of team member to fix it.

Assigning KK, to review and fix this.

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek
