### ISSUE TITLE
Invalid INSERT created when mapping entity with double, float field

### ISSUE THREAD

**Issue by phillipchengyi** [Impetus/kundera#317]
public class Product{
        @EmbeddedId
    private ProductId id;

```
    @Column(name = "oPrice")
private double originalPrice;
```

}
double originalPrice = 100d;

then i persist product, i got following error 

Caused by: InvalidRequestException(why:Invalid STRING constant (100.0) for oPrice of type double)
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)

same things happen when i changed the type to float, the error i got is:
InvalidRequestException(why:Invalid STRING constant (100.0) for oPrice of type float)
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)

i saw similar issue for boolean type and was fixed, is this still there. i am using version 2.5.

**Comment by phillipchengyi** [comment]
i am struck here, could you give me a light on this?

**Comment by phillipchengyi** [comment]
for float and double, in the CQLTranslator.appendValue, single quotation mark should not be added, after cassandra v 1.2.0, this is not supported.

**Comment by mevivs** [comment]
Can you please verify this with 2.5.1 release?

-Vivek

**Comment by phillipchengyi** [comment]
closed in 2.5.1
