### ISSUE TITLE
problem using property name="kundera.ddl.auto.prepare" value="update" 

### ISSUE THREAD

**Issue by phillipchengyi** [Impetus/kundera#319]
kundera 2.5, cassandra 1.2.0
while i use property name="kundera.ddl.auto.prepare" value="update",
it will try to add an existing column family, i do not understand why?
if the column family exists, it should leave it as is, why try to add another one?

Caused by: InvalidRequestException(why:Cannot add already existing column family "Category" to keyspace "reminder")
    at org.apache.cassandra.thrift.Cassandra$system_add_column_family_result.read(Cassandra.java:31561)

**Comment by mevivs** [comment]
If you have given "update" and column family already exists it will try to update existing one with new columns.

Also,i suggest you to upgrade on 2.5.1, which is the latest release version.

-Vivek

**Comment by phillipchengyi** [comment]
closed in 2.5.1
