### ISSUE TITLE
Query over row key column with ">","<",">=","<="  over Random partitioner

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#320]
Current CQL3 support in Kundera for queries over "row key" column works only for byteorderedpartitioner. Queries such as:

"Select p from Person p where p.id > value";
"Select p from Person p where p.id < value"
"Select p from Person p where p.id >= value ";
"Select p from Person p where p.id <= value ";

doesn't currently work for Random partitioning. Code base needs to work accordingly by using "token" function.
Affected modules:
1. JPQL queries.
2. Pagination over Cassandra

**Comment by impetus-opensource-admin** [comment]
Already fixed with 2.7.1
