### ISSUE TITLE
setting consistecny level Quorum

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#331]
Hi,
I see that the WITH CONSISTENCY clause has been removed from CQL 3 commands.
I am using kunedra-cassandra for my project.
In terminal i am able to  set the consistency level to Quorum using the command:-CONSISTENCY QUORUM.
But as soon as i log out of that Cql it is again set to ONE.
Is there any way i can set the consistency level to QUORUM using kundera-Cassandra?

**Comment by mevivs** [comment]
```
    For example, if persistence unit name is "cassandra_pu", then you can set it using Kundera as (on operation level for each session): 
```

```
      Map<String, Client> clientMap = (Map<String, Client>) em.getDelegate();
        ThriftClient tc = (ThriftClient) clientMap.get("cassandra_pu");
        tc.setCqlVersion(CassandraConstants.CQL_VERSION_3_0);
        tc.setConsistencyLevel(ConsistencyLevel.QUORUM);
```

Also, it is possible to set it via external xml configuration file as well.

-Vivek

**Comment by Gargee** [comment]
Thanks a lot.

**Comment by Gargee** [comment]
Can i get any example for the  external xml configuration file

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/wiki/Cassandra-Specific-Features.

Also, please look https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/resources/META-INF/persistence.xml, for:

```
<property name="kundera.client.property" value="kunderaTest.xml" />
```

for reference.

-Vivek

**Comment by Gargee** [comment]
thanks

**Comment by Gargee** [comment]
Whats the string name for setting the consistency level?I could set the CQL version using the external config file but the consistency level doesn't seem to be working.

--"<?"xml version="1.0" encoding="UTF-8"?>
--<clientProperties>
--  "<"datastores">"
--      "<"dataStore">
            "<"name>cassandra"<"/name>
            "<"connection">"
                "<"properties">"
                    "<"property name="cql.version" value="3.0.0">"</"property>
                "<"/properties>
                "<"properties>
                "<"property name="ConsistencyLevel" value="QUORUM"></property>
                "</"properties>
            "</"connection>
        "</"dataStore>
    "</"datastores>
"</"clientProperties>

**Comment by mevivs** [comment]
My Bad. consistencyLevel is only possible at operation level. So you can set it only via previously mentioned way for each read/write consistency level.

-Vivek

**Comment by Gargee** [comment]
The WITH CONSISTENCY clause has been removed from CQL 3 commands in the release version of CQL 3. 
 I am setting my configurations using :
    Map<String, String> propertyMap = new HashMap<String, String>();
    propertyMap.put(CassandraConstants.CQL_VERSION,
    CassandraConstants.CQL_VERSION_3_0);
how can we set consistency level in this ?

**Comment by mevivs** [comment]
propertyMap.put("consistency.level",ConsistencyLevel.QUORUM);

**Comment by Gargee** [comment]
The method put(String, String) in the type Map<String,String> is not applicable for the arguments (String, 
 ConsistencyLevel) :(

**Comment by mevivs** [comment]
Change map generics parameter as:

```
 Map<String, Object> props = new HashMap<String, Object>();
props.put("consistency.level",ConsistencyLevel.QUORUM);
props.put(CassandraConstants.CQL_VERSION,CassandraConstants.CQL_VERSION_3_0);
```

```
import org.apache.cassandra.db.ConsistencyLevel;
```

Hope this helps.

-Vivek

**Comment by Gargee** [comment]
Thanks Vivek.Got some generics class also ;) this works perfectly fine.
Was wondering if this becomes configurable in external file things will be easy to change in a production env and really VERY NICE feature which kundera can provide. 

I have this kind of code :  
@PersistenceContext(unitName = "cassandra_pu", type = PersistenceContextType.EXTENDED)
    private EntityManager em;
with the external configs for setting the cql version .

was wondering how to get this work with the solution u gave.

**Comment by dtuzikov** [comment]
As for JPA, you can set additional properties within @PersistenceContext annotation:

``` java
@PersistenceContext(type = PersistenceContextType.EXTENDED, properties = {
        @PersistenceProperty(name = "consistency.level", value="QUORUM")
})
private EntityManager em;
```

but i have found, that CassandraClientProperties class for now accepts only enum value for consistency.level option.

``` java
public void populateClientProperties(Client client, Map<String, Object> properties) {
        CassandraClientBase cassandraClientBase = (CassandraClientBase) client;
        if (properties != null) {
            for (String key : properties.keySet()) {
                Object value = properties.get(key);
                if (key.equals(CONSISTENCY_LEVEL) && value instanceof ConsistencyLevel) {
                    cassandraClientBase.setConsistencyLevel((ConsistencyLevel) value);
                }
                else if (key.equals(CQL_VERSION) && value instanceof String) {
                    cassandraClientBase.setCqlVersion((String) value);
                }
...
```

May be this should be created as an issue?

**Comment by mevivs** [comment]
:+1: for relaxing enum constraint. Will discuss alternate solutions and as well as @PersistenceProperty option.

-Vivek

**Comment by mevivs** [comment]
@dtuzikov  
Out of context, 1 question. Using Kundera for?

-Vivek

**Comment by Gargee** [comment]
@dtuzikov Thanks a lot for the solution.
@mevivs thanks for your support

**Comment by dtuzikov** [comment]
@mevivs 
I'm using Kundera for working with historical database on Cassandra 1.2. (Financial app)

**Comment by mevivs** [comment]
@dtuzikov 
Thanks. Could you please spare couple of minutes to provide your feedback? Here it is:
http://www.surveymonkey.com/s/BMB9PWG

-Vivek

**Comment by jfgosselin** [comment]
Hi, 

```
@PersistenceContext(type = PersistenceContextType.EXTENDED, properties = {
       @PersistenceProperty(name = "consistency.level", value="QUORUM")
  })
```

I was also going to use something like this to set the consistency.level, is it working ?

**Comment by Gargee** [comment]
Yes this is working for me.

**Comment by jfgosselin** [comment]
Hmmm 

Looking at the Kundera code, the following method is called with the properties passed via  @PersistenceProperty but consistency.level is ignored : 

com.impetus.client.cassandra.CassandraClientProperties

```
public void populateClientProperties(Client client, Map<String, Object> properties)
{
    CassandraClientBase cassandraClientBase = (CassandraClientBase) client;

    if (properties != null)
    {
        for (String key : properties.keySet())
        {
            Object value = properties.get(key);
            if (key.equals(CONSISTENCY_LEVEL) && value instanceof ConsistencyLevel)
            {
                cassandraClientBase.setConsistencyLevel((ConsistencyLevel) value);
            }
            else if (key.equals(CQL_VERSION) && value instanceof String)
            {
                cassandraClientBase.setCqlVersion((String) value);
            }
            else if (key.equals(TTL_PER_SESSION) && value instanceof Boolean)
            {
                if(((Boolean) value).booleanValue())
                {
                    cassandraClientBase.setTtlPerRequest(false);
                }                    
                cassandraClientBase.setTtlPerSession((Boolean) value);

            }
            else if (key.equals(TTL_PER_REQUEST) && value instanceof Boolean)
            {
                if(((Boolean) value).booleanValue())
                {
                    cassandraClientBase.setTtlPerSession(false);
                }  
                cassandraClientBase.setTtlPerRequest((Boolean) value);
            }
            else if (key.equals(TTL_VALUES) && value instanceof Map)
            {
                cassandraClientBase.setTtlValues((Map) value);
            }

            // Add more properties as needed
        }
    }
}
```

**Comment by mevivs** [comment]
It's not an issue. Working fine. Please see #401  for more on this.

-Vivek
