### ISSUE TITLE
Remove cassandra-all dependency from kundera-cassandra, which crashes container on class unloading.

### ISSUE THREAD

**Issue by pires** [Impetus/kundera#332]
I've spoke to @mevivs about this critical issue before and even opened a bug on Cassandra JIRA. See https://issues.apache.org/jira/browse/CASSANDRA-5739.

**Comment by pires** [comment]
Any advances on this?

**Comment by mevivs** [comment]
Well as discussed, i did add my comments on JIRA. this does not look to be a Kundera issue
