### ISSUE TITLE
JPQL query with IN :list not working

### ISSUE THREAD

**Issue by macluck** [Impetus/kundera#333]
Hi,

I am making a jpql query to mysql database where I use operator IN for the list of strings:

```
"select a.id, a.name from Entity a where a.name IN :list"
```

But the query is translated with a wrong syntax for mysql. The part with list looks like this:

```
AND name IN '[name1, name2, name3]'
```

thus returning with exception. It would be very useful to have the support of list in jpql query.

Thank you

Kind Regards,
Anton Maklakov

**Comment by macluck** [comment]
Hi,

I have tested this again with Kundera 2.6.1, but problem still exists. I am wondering was it ever addressed?

Kind Regards,
Anton Maklakov

**Comment by mevivs** [comment]
Work is not yet started on this. It will be part of 2.7 release(Releasing on 3rd september).

-Vivek

**Comment by macluck** [comment]
Okay, good to know,. Thank you!

**Comment by kkmishra** [comment]
Hi,
It is fixed in current trunk branch, please verify.

Thanks
Kuldeep

**Comment by mevivs** [comment]
Any update on this? Releasing with 2.7. 
-Vivek

**Comment by macluck** [comment]
Hi, I can't verify it today. Will do it tomorrow with the 2.7 release.

Thank you

**Comment by macluck** [comment]
I verify, it's working now with 2.7 release
