### ISSUE TITLE
Random fail when retrieving "1-m" relations in Kundera/Cassandra setup

### ISSUE THREAD

**Issue by emgsilva** [Impetus/kundera#334]
Hi,

I have been having some problems with a Cassandra node (cassandra 1.2.6)  with Kundera 2.6. The problem is very strange.

I have a 1-m JPA relation: “services types have many properties”. This relation works "most of the times”, i.e., I get the service types and through them I get the associated properties ("getProperties()"). This is specified in the service type persistency entity class:

```
...
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(name = "service_id”)
private Set<Properties> serviceProperties; 
...
```

However, from time to time (it really looks random) I fail to retrieve the “properties”, although I get the “service” (I print some of its values) and furthermore (from Cassandra log files in DEBUG mode) I seem to also get the associated properties - the log for calls that are successful and the problematic call are exactly the same, no difference at all.

This is the persistence.xml of the keyspace where the problem takes place:

```
<persistence-unit name="cassandra_ServiceTypes">
          <provider>com.impetus.kundera.KunderaPersistence</provider>
          <class>cassandra.servtypes.ServiceTypes</class>
          <class>cassandra.servtypes.Properties</class>
          <exclude-unlisted-classes>true</exclude-unlisted-classes>
          <properties>
               <property name="kundera.nodes" value="localhost" />
               <property name="kundera.port" value="9160" />
               <property name="kundera.keyspace" value="servicetypes" />
               <property name="kundera.dialect" value="cassandra" />
               <!-- <property name="kundera.ddl.auto.prepare" value="create"/> -->
               <property name="kundera.client" value="pelops" />
               <property name="kundera.client.lookup.class"
                    value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
               <property name="kundera.cache.provider.class"
                    value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
               <property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
          </properties>
</persistence-unit>
```

The problem I get is simply a “java.lang.NullPointException” when I try to read the service properties…

Do you have any idea why this happens?

Thank you in advance for your help! By the way, I always use "github issues", do you advise/prefer me to use Google Groups instead for this kind of problem?

**Comment by mevivs** [comment]
Assigning to KK.  " github issues" are also fine as long as it's working for you.

BTW, using Kundera for?

-Vivek

**Comment by emgsilva** [comment]
I am using Kundera for Cassandra (as referred at the beginning of my issue: Kundera 2.6 and Cassandra single node version 1.2.6).

Thank you for the quick reply :+1:

**Comment by emgsilva** [comment]
Hi,

Not sure if you had a look in this issue... I have created a temporary hack that solves my problem, but I do think there is something wrong (either in my configurations - not sure, since it works most of the times - or in Kundera/Cassandra - as mentioned in my original post, Cassandra reports/logs exactly the same things, so leads me to think that it is something in Kundera or my usage of Kundera).

The "hack" I created was a "recursive" call to the method I use to get these 1-m values (I know they always have a values in the "m" part, since "services" always have "properties"), so if I get a "null" exception when I try to read the "properties" ("service.getProperties()") I create recursive call new call to the method... I limit this recursion to three calls separated by 200 ms... 

This makes the code work all times. I do enter this recursion cycle in a random manner, which I cannot explain... 

For now it will be possible to do this hack... but we are about to make a production release of our server, and would not like to leave this issue hanging in the code. 

Thank you for your assistance! Looking forwards to hearing from you.

/Eduardo

**Comment by mevivs** [comment]
Hi,
Please share more on error logs. Let me know, if you want me to connect over Gtalk/yahoo IM to quickly resolve it.

-Vivek

**Comment by emgsilva** [comment]
Hi Vivek,

Thank you very much for your reply… I have some positive developments on the issue :) but think found another...

I was trying to gather more detailed logging (log4j with ALL messages level), and got more “information” on the fact that the “service properties” were not obtained when the error was taking place. Please see these two excerpts of the logs of “calls” on our REST API (which internally makes two calls to Cassandra): call without problem (https://www.dropbox.com/s/6ukm9fy16tl0wxi/log-call-withoutProblems.txt) and call with problem, not retrieving the “properties of the service” (https://www.dropbox.com/s/zz719xcb702lnka/log-call-withProblems.txt).

I decided to make some small changes on the code, and detected I was not closing one Kundera “EntityManager” in on call to Cassandra… I corrected this, and also decided to “close” all Kundera “EntityManagers” and “EntityManagerFactories” in each method they are used (I used to have global “entity manager factory” in some classes, which were closed in a “finalize()” method… this was probably the source of the problem I reported originally… since once I did that I am not getting the behavior reported. I cannot explain why this was happening, namely why some moments after I would be able again to get the correct values from Cassandra with Kundera.

So, just to make sure I was getting rid of all the problems related with this, I decided to make a "stress test" where I send a query to this API resource (which internally uses Kundera to query Cassandra) every 0.01 seconds. It keeps up with the load for a while (several minutes), but then at a given point I get another problem - see the log here (https://www.dropbox.com/s/p74w2kjdrxsobzz/newProblems-cannotConnectToCassandra.txt - very large file 46 MB). I am thinking this can have something to do with the amount of “open resources” that are open and not closed in my web service. I do not open any other DB connection (MySQL, etc.)… in fact in this test I only use Kundera to retrieve the “service” and “service properties” from Cassandra… The log I appended is since I start my Tomcat and start receiving calls to when it starts failing, I then force the client to stop sending calls to the web service.

Any ideas on why this takes place? It seems that connections are open and not closed, I do not seem to see the “close” connections messages in the logs (I do have EntityManager and EntityManagerFactory close() in my code), is this it: "com.impetus.kundera.persistence.PersistenceDelegator  - Flushing following flush stack to database(s)”? 

I saw discussions about “maximum number of open files” that the OS supports, I actually increased that in my computer… Also tried to play with Tomcat “timeouts” and “max threads”, but the same behavior takes place. Cassandra log does not report any problem. I see the “number of open files” increasing all the time, does not seem I am releasing resources ever… (I use "lsof -n | wc -l” to see it). 

Have you ever seen this before in your tests, applications, etc., with Kundera (with Tomcat6 and Cassandra)?

Cheers,

Eduardo

**Comment by mevivs** [comment]
Hi Eduardo,
I am downloading these log files. Let me know, we can connect on gtalk to quickly discuss and resolve it.

-Vivek

**Comment by mevivs** [comment]
Hi Eduardo,
First, i am assuming your entityManager and entityManagerFactory are "Application managed" Or you are using something like Spring managed "LocalContainerEntityManagerFactoryBean". 

If you are progrmatically creating entity manager factory instance, i suggest to create a single entity manager factory and multiple entity manager instance(unless they are meant to different persistence unit or same persistence unit with different configuration). 

i had a look on logs:

```
2013-08-01 18:24:11,743 [DEBUG] [http-8080-1] com.impetus.kundera.loader.GenericClientFactory  - Returning fresh client instance for persistence unit : cassandra_ServiceTypes
Aug 1, 2013 6:24:11 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
com.impetus.kundera.KunderaException: All hosts are down. please check servers manully.
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.getPoolUsingPolicy(ThriftClientFactory.java:187)
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.instantiateClient(ThriftClientFactory.java:173)
    at com.impetus.kundera.loader.GenericClientFactory.getClientInstance(GenericClientFactory.java:209)
    at com.impetus.kundera.persistence.EntityManagerImpl.discoverClient(EntityManagerImpl.java:991)
```

Kundera relies on Connection pool for this, and simply return connections back to pool after successfully processing request.  Using Kundera-cassandra for multiple node or on a single node? 

Few things, you may try:
1. Single entity manager factory instance for one persistence unit.
2. Properly close all entity manager instances after complete processing.
3. Define a max, max active pool property value as 50(persistence.xml)

Let me know, if these works for you.

-Vivek

**Comment by mevivs** [comment]
There have been some fixes added in current trunk around such issues. You may also want to give it try as well.

-Vivek

**Comment by emgsilva** [comment]
Hi Vivek,

Thank you very much for the insights… I only saw the updates now. 

I will be processing them in the upcoming hours. Let me however give some more context and also ask some clarifications:
- 1) I do manage the EntityManager and EntityMangerFactory in the Application (I do not use any solution like Spring - maybe I should consider… what would be some “quick and easy” solutions for that? I do not have knowledge on this topic).
- 2) Concerning the “single entity factory and multiple entity manager instances”… I was doing something like that, but seemed to see more problems from that (maybe was my implementation of that). At the moment I am indeed opening one EntityManagerFactory per method that have calls to cassandra (so a factory per entityManager… I know it is not ideal, but was an experiment and it solved some issues) => I will try to change this to my previous setup, but I will any ways create a factory per “API call”… I will “close” them (and all entityManagers) after the call… Are they being released if I do “entityManagerFactory.close()”, or do I need to do anything else to release them? To me this seems to be the problem...
- 3) I am at the moment using a “single node” cassandra…. I did not completely understand your statement "Kundera relies on Connection pool for this, and simply return connections back to pool after successfully processing request”… Cassandra defines a “maximum connection pool size”, which when reached blocks all further connections from clients. Is my problem here, I mean somehow the kundera connections to cassandra do not “get closed” and at a given point Cassandra connection pool does not accept further connections? If so, how can I make sure they get closed? (I do seem to close them… but something does get wrong in the way…).

I will be testing the variables you referred… if the problem persists I will let you know and then maybe we can indeed chat through this (if possible), but it would be nice to have some clarifications on the questions I made above so that I can try to tackle the problem.

Thank you very much for your very active support!

Cheers,

Eduardo

**Comment by mevivs** [comment]
```
1) I do manage the EntityManager and EntityMangerFactory in the Application (I do not use any solution like Spring - maybe I should consider… what would be some “quick and easy” solutions for that? I do not have knowledge on this topic).
```

I will share a project reference for this later.

```
2) Concerning the “single entity factory and multiple entity manager instances”… I was doing something like that, but seemed to see more problems from that (maybe was my implementation of that). At the moment I am indeed opening one EntityManagerFactory per method that have calls to cassandra (so a factory per entityManager… I know it is not ideal, but was an experiment and it solved some issues) => I will try to change this to my previous setup, but I will any ways create a factory per “API call”… I will “close” them (and all entityManagers) after the call… Are they being released if I do “entityManagerFactory.close()”, or do I need to do anything else to release them? To me this seems to be the problem...
```

I think with current trunk it should be fine.

```
3) I am at the moment using a “single node” cassandra…. I did not completely understand your statement "Kundera relies on Connection pool for this, and simply return connections back to pool after successfully processing request”… Cassandra defines a “maximum connection pool size”, which when reached blocks all further connections from clients. Is my problem here, I mean somehow the kundera connections to cassandra do not “get closed” and at a given point Cassandra connection pool does not accept further connections? If so, how can I make sure they get closed? (I do seem to close them… but something does get wrong in the way…).
```

This is what got fixed in current trunk.  

Let me know, if we need a quick discussion to get your application into production :) 

-Vivek

**Comment by emgsilva** [comment]
Thank you Vivek!

I have just included the "trunk" version in my local maven rep and pom.xml, and have the "stress test" running already for 30 minutes (I did not touch my code, so it opens EntityManagerFactory/EntityManager and then closes them in the Application)... and it is performing like a charm :D no problems at all! I did a quick check on the "open files" of the OS (lsof -n | wc -l) and they are stable (go a bit up, but then go down again), so I imagine your update solves this issue or "releasing resources/connections" :)

I will take your recommendations in consideration for improving the way I handle Kundera (minimize the number of EntityManagerFactory and close all EntityManager)... possibly look into using Spring (I did not use it, trying to avoid adding yet another framework, but maybe it is worth...) - by the way, any other recommendation of some other framework to do what you suggest Spring does?

I now understand your question: "for what we are using Kundera" :) We are a startup (www.sigmabees.com) that develops products around the concept of "user-centric service composition", at the moment we are developing our first product, which is an "online shopping" tool (organizer and recommendation system). We use Kundera/Cassandra to manage different types of data, but mostly "statistical" data on usage and also as a "persistent cache" (since we do have a lot of data that needs to be read often and changes sometimes, and Cassandra does offer much better read times than MySQL and other RDBMs solutions...). I am planning to write some of our experiences with Kundera/Cassandra some day, when time allows. I will let you know about that! 

Again, thank you for your excellent support! I will close the issue, since this seems to have been completely solved by the code update you made.

Eduardo

**Comment by mevivs** [comment]
Great! 
Most of production J2EE app works in "container managed entity manager factory instances". Kundera is easily deployable over web and as well as EJB containers:
1. Tomcat
2. Glassfish,Jboss AS7 etc. (EJB container)

Container managed ones are maintained by servers and entity manager and factory instances are implicitly handled by Container itself(which i believe is less error prone).

Also, We are compiling a wiki page for Kundera powered Apps which are running into production systems. Could you please spare few minutes to provide these details? Format is:

 Application Name                                :             __________________________________
 Application Description                         :            __________________________________
Application / Organization Link (optional)      :       __________________________________

Looking forward for your reply on my mail id, that is vivek.mishra@impetus.co.in

You may also provide your feedback at  http://www.surveymonkey.com/s/BMB9PWG
Cheers,
-Vivek

**Comment by emgsilva** [comment]
I will do that for sure in a while, once we are some time through our private beta (to be launched soon). 

Thank you again for all the support! cheers,

Eduardo
