### ISSUE TITLE
How to use @com.impetus.kundera.index.Index annotation?

### ISSUE THREAD

**Issue by pranav-gopi** [Impetus/kundera#335]
How to use @com.impetus.kundera.index.Index annotation. Can you provide sample? 

I need to generate index for column using annotations. But JPA 2.0 doesn't support this. I found @Index annotation in Kundera package. How can I use this?

-Pranav

**Comment by mevivs** [comment]
Please refer:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongo.java

-Vivek

**Comment by pranav-gopi** [comment]
I tried using @IndexCollection and @Index annotation as given in sample code. But it is not creating index in MongoDB. 
"
@Table( name = "city" , schema = "world@mongodb" )
@IndexCollection( columns = { @Index(name="district") } )
"
-Pranav

**Comment by mevivs** [comment]
Did you enable 
"kundera.ddl.auto.prepare" option in persistence.xml?

-Vivek

**Comment by pranav-gopi** [comment]
Now it works. I forgot to add "kundera.ddl.auto.prepare".
"
property name="kundera.ddl.auto.prepare" value="create" 
"

Thanks a lot for quick reply.

-Pranav

**Comment by mevivs** [comment]
Good. closing on this.

-Vivek

**Comment by pranav-gopi** [comment]
What to do for multiple column index?

-Pranav

**Comment by mevivs** [comment]
You mean compound index in mongodb?

I think, you need to execute these as db script using "Kundera".

-Vivek

**Comment by pranav-gopi** [comment]
Please reply for the below doubts
1) How to define 'unique' index using annotations. 
2) What are the values expected in 'type' attribute of @Index annotation
3) I need to implement compound index. So can we define compound index using kundera @Index annotations.

-Pranav

**Comment by mevivs** [comment]
```
1) How to define 'unique' index using annotations. 
```

specific to mongo. need to execute as a dbscript(javascript) using Kundera.

```
2) What are the values expected in 'type' attribute of @Index annotation
```

type can be "DSC" or "ASC"

```
3) I need to implement compound index. So can we define compound index using kundera @Index annotations.
```

Need to execute as DB script as:

```
        Map<String, Client<Query>> clients = (Map<String, Client<Query>>) em.getDelegate();
        Client client = clients.get(_PU);


         // compound index
        String jScript = ""db.products.ensureIndex( { \"item\": 1, \"location\": 1, \"stock\": 1 } )";

        Object result = ((MongoDBClient) client).executeScript(jScript);
```

-Vivek
