### ISSUE TITLE
Is there any way to place persistence.xml outside the war file..

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#338]
Hi,
Is there any way we can place persistence.xml outside the warfile .right now as we know we need to place it in .....src/main/resources/META-INF/persistence.xml..
As i need to change the DB with each env in various phases of (dev/test/pro)...changing from war file is messy..

**Comment by mevivs** [comment]
If this is because of changing connection and other Cassandra configuration. I would recommend to use "External properties configuration"(using kundera.client.property) in persistence.xml  for this. 

But only new entity manager factory instance will take these changes into effect.

-Vivek

**Comment by Gargee** [comment]
Cool thanks.

**Comment by Gargee** [comment]
Hi vivek,
What should be the  name of the property?
<?xml version="1.0" encoding="UTF-8"?>
<clientProperties>
    <'datastores>
        <'dataStore>
            <'name>cassandra</name>
            <'connection>
                <'properties>
                      <'property name="cql.version" value="3.0.0"></property>
                <'/properties>
                <'properties>
                      <'property name="kundera.nodes" value="BELG53NML1"></property>
                <'/properties>
            <'/connection>
        <'/dataStore>
    <'/datastores>
<'/clientProperties>

I have 9 nodes across 2 datacentres all listening on port 9160.How do i specify it here in the external file?

**Comment by mevivs** [comment]
Here i am sharing a sample xml(say KunderaTest.xml) file:

```
<?xml version="1.0" encoding="UTF-8"?>

<clientProperties>
    <datastores>
             <dataStore>
                <name>cassandra</name>
          <schemas>
        <schema>
        <name>KunderaCassandraXmlTest</name>     <!-- keyspace name -->                                
        <properties>
           <property name="strategy.class" value="NetworkTopologyStrategy" />
           <property name="durable.writes" value="true" />
        </properties>
        <dataCenters>
          <dataCenter>
            <name>DC1</name>        <!-- datacenter name -->
            <value>3</value>        <!-- replication factor -->
         </dataCenter>
         <dataCenter>
            <name>DC2</name>         <!-- datacenter name -->
            <value>2</value>         <!-- replication factor -->
        </dataCenter>
           </dataCenters>
               </schema>
             </schemas>
                <connection>
                   <properties>
                         <property name="cql.version" value="3.0.0"/>
                   </properties>
           <servers>
            <server>
               <host>node1</host>
               <port>9160</port>
            </server>
            <server>
               <host>node2</host>
               <port>9160</port>
            </server>
           </servers>

                </connection>
            </dataStore>
   </datastores>
</clientProperties>
```

`<host>` tag is representing Node's ip address and `<port>` for specifying port.  Also, in case you opted for "kundera.ddl.auto.prepare" in persistence.xml then properties and tags mentioned under `<schmea >` tags are required for automatically creating schema.

In your case, you need to repeat 

```
            <server>
               <host>node1</host>
               <port>9160</port>
            </server>
```

for all 9 cassandra nodes in your cluster. And finally map it to persistence.xml with

```
            <property name="kundera.client.property" value="kunderaTest.xml" />
```

Please refer 
https://github.com/impetus-opensource/Kundera/wiki/Using-multiple-node-support-and-load-balancing-policy-in-Kundera

AND 
https://github.com/impetus-opensource/Kundera/wiki/Cassandra-Specific-Features
for more of data store specific configuration and multiple node support.

Hope this helps. 

-Vivek

**Comment by Gargee** [comment]
Thanks
