### ISSUE TITLE
Getting the Count of some record in Cassandra using Kundera

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#345]
Hi,
I have a column family which looks like this:-
CREATE TABLE "ChangeRequest" ( "ChangeRequestID" uuid, "SubmissionID" uuid, "SubmissionDateTime" timestamp, "CreateUser" varchar, "UpdateUser" varchar,  "ModType"  varchar,"ModSequence" int,"ModID" set <uuid>, PRIMARY KEY("ChangeRequestID", "ModSequence") );

I need to get the count of submissions made (count of the SubmissionID ).Is it feasible in Cassandra?If yes how..

**Comment by mevivs** [comment]
Execute as a native CQL3 native query

-Vivek

**Comment by Gargee** [comment]
so when i do a  select count(*) from "ChangeRequest"; i get the total count of records ..but what i want is the Number of records with unique ChangeRequestID.
When i do :-  select count ("ChangeRequestID") from "ChangeRequest"; i get the error:-
Bad Request: line 1:14 no viable alternative at input 'ChangeRequestID'

is there a way to get the unique count for a given column.

**Comment by mevivs** [comment]
Only unique thing in Cassandra is row key. I don't think such functions exist in CQL(Cassandra). 

One alternative could to create an entity which contains row key and ChangeRequestID as a column. 
Execute a query such as:

"Select ChangeRequestID, key from ChaneRequest".  and convert list of ChangeRequestID into a unique set. As You are fetching only 1 column, so it should not be an issue. 

Else, make ChangeRequestID a row key, which will make it unique.

-Vivek

**Comment by Gargee** [comment]
thanks
