### ISSUE TITLE
Higest value of a column in a columnfamly

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#346]
Hi All,
I am at the end of my wits to figure out how to get the  the highest value of  PhotoLogSeqNum for a given photoID in cql /kundera :(
So suppose we have a table like this(below) and we need to find the highest value of PhotoLogSeqNum for a given photoID.

Photo
--photoID         | --     PhotoLogSeqNum             |-- ChangeStatusID        |--Description

1---------------------      1   ------------------------------                         1    -------------------         just loaded
1---------------------      2   ------------------------------                 1    -------------------        updated some data
1---------------------      3   ------------------------------              1   -------------------        again updated
2---------------------      1   ------------------------------              1   -------------------        new pic
2---------------------      2   ------------------------------              1   -------------------        updated cat
2---------------------      3   ------------------------------              2     -------------------       submitted and approved

**Comment by mevivs** [comment]
This looks to me a case of counter column family. Highest value of PhotoLogSeqNum for each photoId value? Or for complete table?

Another possible solution might be to keep a flag value(secondary index enabled), and Highest value of PhotoLogSeqNum will hold a unique flag value. Which allows you to query using that "flag" field.

-Vivek

**Comment by Gargee** [comment]
This looks to me a case of counter column family. Highest value of PhotoLogSeqNum for each photoId value? Or for complete table?Answer:-GB I need it per photoID.
Another possible solution might be to keep a flag value(secondary index enabled), and Highest value of PhotoLogSeqNum will hold a unique flag value. Which allows you to query using that "flag" field.Answer:-GBI dont have the option to try this.

**Comment by mevivs** [comment]
Have PhotoID,PhotoLogSeqNum as a composite key and run a CQL query like:

select PhotoLogSeqNum from Photo order by PhotoLogSeqNum DESC LIMIT 1;

-Vivek

**Comment by Gargee** [comment]
cool thanks.
