### ISSUE TITLE
Issue while persisting set<uuid> using kundera cassandra

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#348]
HI ,
I am trying to persist set<'uuid'> using kundera cassandra.But i am getting the below  error.Is any any issue persisting set<'uuid'>???

8 Aug 2013 04:14:21,165 ERROR http-bio-8443-exec-9 com.impetus.client.cassandra.pelops.PelopsClient (PelopsClient.java:453) - Error during persist, Caused by:
nvalidRequestException(why:Invalid list literal for ModID of type set<uuid>)
       at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
       at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
       at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
       at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
       at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:448)
       at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:84)
       at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:182)
       at com.impetus.kundera.graph.Node.flush(Node.java:525)
       at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:452)
       at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:181)
       at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)

**Comment by mevivs** [comment]
Using latest trunk?
ThrifClientFactory?

**Comment by Gargee** [comment]
06-July-2013 - Kundera 2.6 released.

@PersistenceContext(unitName = "cassandra_pu", type = PersistenceContextType.EXTENDED,

properties = {@PersistenceProperty(name = "consistency.level", value="QUORUM")} )

Persistence.xml :-

<provider>com.impetus.kundera.KunderaPersistence</provider>

<properties>

<property name="kundera.nodes"

value="a,y,x" />

<property name="kundera.port" value="9160" />

<property name="kundera.keyspace" value="EPCContent" />

<property name="kundera.dialect" value="cassandra" />

<property name="kundera.client.lookup.class"

value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />

<property name="kundera.cache.provider.class"

value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />

<property name="kundera.cache.config.resource" value="/ehcache-test.xml" />

<property name="kundera.client.property" value="../../webapp/WEB-INF/kunderaClientConfig.xml" />

</properties>

I am using the following configurations in the external file:-

<dataStore>

<name>cassandra</name>

<connection>

<properties>

<propertyname="cql.version"value="3.0.0"></property>



<propertyname="loadbalancing.policy"value="roundrobin"></property>

<propertyname="retry"value="true"></property>

<propertyname="retry.delay"value="1"></property>

<propertyname="max.wait"value="3000"></property>

</properties>

**Comment by mevivs** [comment]
Map/Collection support over basic type is supported in current trunk only.

-Vivek

**Comment by Gargee** [comment]
Hi Vivek,Thanks for the reply,but as per my company policies we can only refer to stable releases for including it in our code base.Any idea when we can get a stable release in kundera with this feature?

**Comment by mevivs** [comment]
I will post an update. But tentatively it's around 22nd august.

-Vivek

**Comment by Gargee** [comment]
OK ..our release too is around that time.I hope it syncs up.

**Comment by Gargee** [comment]
Hi When I am trying to compile the Trunk code I get this error:-

BELC02JV1E8DKQ4:Kundera-trunk a-gbanerjee$ mvn eclipse:eclipse
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.core:kundera-core:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-source-plugin @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.jacoco:jacoco-maven-plugin @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 314, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-cassandra:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-hbase:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-mongo:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-rdbms:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-neo4j:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 67, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.kundera.rest:kundera-rest:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING] 'repositories.repository.layout' for maven-repository.dev.java.net uses the unsupported value 'legacy', artifact resolution might fail. @ line 26, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-redis:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus.client:kundera-oracle-nosql:jar:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus:kundera-tests:jar:2.7-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.xerial:snappy:jar -> duplicate declaration of version 1.0.1-rc4 @ line 263, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-clean-plugin is missing. @ line 532, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 471, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 496, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ line 509, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ com.impetus:kundera:2.7-SNAPSHOT, /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/pom.xml, line 271, column 15
[WARNING] 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ line 71, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-changes-plugin is missing. @ line 96, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 104, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-jxr-plugin is missing. @ line 107, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-report-plugin is missing. @ line 110, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.codehaus.mojo:jdepend-maven-plugin is missing. @ line 116, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.codehaus.mojo:javancss-maven-plugin is missing. @ line 120, column 12
[WARNING] 'reporting.plugins.plugin.version' for org.codehaus.mojo:dashboard-maven-plugin is missing. @ line 124, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.impetus:kundera:pom:2.7-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-source-plugin @ line 271, column 15
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.jacoco:jacoco-maven-plugin @ line 314, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 225, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ line 248, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 271, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] kundera-trunk
[INFO] kundera-core
[INFO] kundera-cassandra
[INFO] kundera-hbase
[INFO] kundera-mongo
[INFO] kundera-rdbms
[INFO] kundera-neo4j
[INFO] kundera-rest
[INFO] kundera-redis
[INFO] kundera-oracle-nosql
[INFO] kundera-tests
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building kundera-trunk 2.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ kundera ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.5.3.201107060350:prepare-agent (pre-test) @ kundera ---
[INFO] Skipping JaCoCo for project with packaging type 'pom'
[INFO]
[INFO] <<< maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera <<<
[INFO]
[INFO] --- maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera ---
[INFO] Not running eclipse plugin goal for pom project
[INFO] Using Eclipse Workspace: null
[INFO] Adding default classpath container: org.eclipse.jdt.launching.JRE_CONTAINER
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building kundera-core 2.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera-core >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ kundera-core ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.5.3.201107060350:prepare-agent (pre-test) @ kundera-core ---
[INFO] argLine set to -javaagent:/Users/a-gbanerjee/.m2/repository/org/jacoco/org.jacoco.agent/0.5.3.201107060350/org.jacoco.agent-0.5.3.201107060350-runtime.jar=destfile=/Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/kundera-core/target/jacoco.exec,includes=com.*
[INFO]
[INFO] <<< maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera-core <<<
[INFO]
[INFO] --- maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera-core ---
[INFO] Using Eclipse Workspace: null
[INFO] Adding default classpath container: org.eclipse.jdt.launching.JRE_CONTAINER
[INFO] File /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/kundera-core/.project already exists.
       Additional settings will be preserved, run mvn eclipse:clean if you want old settings to be removed.
[INFO] Wrote Eclipse project for "kundera-core" to /Users/a-gbanerjee/Downloads/KunderaCassandra/Kundera-trunk/kundera-core.
[INFO]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building kundera-cassandra 2.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-eclipse-plugin:2.9:eclipse (default-cli) @ kundera-cassandra >>>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] kundera-trunk ..................................... SUCCESS [0.833s]
[INFO] kundera-core ...................................... SUCCESS [0.346s]
[INFO] kundera-cassandra ................................. FAILURE [0.330s]
[INFO] kundera-hbase ..................................... SKIPPED
[INFO] kundera-mongo ..................................... SKIPPED
[INFO] kundera-rdbms ..................................... SKIPPED
[INFO] kundera-neo4j ..................................... SKIPPED
[INFO] kundera-rest ...................................... SKIPPED
[INFO] kundera-redis ..................................... SKIPPED
[INFO] kundera-oracle-nosql .............................. SKIPPED
[INFO] kundera-tests ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.566s
[INFO] Finished at: Fri Aug 09 12:28:02 PDT 2013
[INFO] Final Memory: 17M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kundera-cassandra: Could not resolve dependencies for project com.impetus.client:kundera-cassandra:jar:2.7-SNAPSHOT: The following artifacts could not be resolved: com.impetus.core:kundera-core:jar:2.7-SNAPSHOT, com.impetus.core:kundera-core:jar:tests:2.7-SNAPSHOT: Failure to find com.impetus.core:kundera-core:jar:2.7-SNAPSHOT in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of cassandra-dependency has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kundera-cassandra

**Comment by mevivs** [comment]
Try with mvn clean install -DskipTests

**Comment by Gargee** [comment]
thanks..i should have tried this ...please let me know when the next stable release is made as My code cant go to production till then.

**Comment by kkmishra** [comment]
Verified and this will be releasing with 2.7.

Thanks
Kuldeep

On Sat, Aug 10, 2013 at 11:31 AM, Gargee Banerjee
notifications@github.comwrote:

> thanks..i should have tried this ...please let me know when the next
> stable release is made as My code cant go to production till then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/348#issuecomment-22434784
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by Gargee** [comment]
Hi ,
Is Kundera 2.7 getting released tomorrow? i.e 22nd Aug.

**Comment by mevivs** [comment]
We  are releasing 2.6.1 today and 2.7 will be released on 3rd sept.

-Vivek

**Comment by Gargee** [comment]
So can we expect the collections support in 2.6.1 ?

**Comment by Gargee** [comment]
because with the snap shot we are getting into jenkins build issues for guava libraries dependencies.We need collections support very badly asap

**Comment by mevivs** [comment]
Yes. Map collection support will be part of 2.6.1 release.

**Comment by mevivs** [comment]
Releasing today with 2.6.1.

**Comment by Gargee** [comment]
when can  we have the jars in http://mvnrepository.com/artifact/com.impetus.core/kundera-core
I understand set collection will also be a part of this release.

**Comment by mevivs** [comment]
Yes. We release kundera jars  over Nexus repo.

 https://oss.sonatype.org/content/repositories/releases/com/impetus

Add 

```
<repository>
            <id>sonatype-nexus</id>
            <name>Kundera Public Repository</name>
            <url>https://oss.sonatype.org/content/repositories/releases</url>
            <releases>
            <enabled>true</enabled>
            </releases>
            <snapshots>
            <enabled>false</enabled>
            </snapshots>
          </repository>
```

in pom.xml

-Vivek

**Comment by Gargee** [comment]
I understand we need to add to our Company's  Nexus repo only the Kundera Core and Kundera Cassandra jars.Can you please confirm

**Comment by mevivs** [comment]
Above mentioned repository link is where we release. Hence for a maven based project, it's recommended to add this a repository configuration.

-Vivek
