### ISSUE TITLE
The "name" property on @Entity is not honored

### ISSUE THREAD

**Issue by TheGeekPharaoh** [Impetus/kundera#349]
In JPA, I can annotate my entity as follows:

@Entity(name="Foo")
@Table(...)
public class FooBean ... {

   ...

}

From there, I can write JPQL queries referencing the "name" from the @Entity annotation, as follows:

"SELECT f FROM Foo f..."

Kundera, however, does not honor the "name" property on @Entity.  Rather, you can only query using the class name:

"SELECT f FROM FooBean f"

This should be corrected, as it is commonplace to use an alternative Entity name in queries.

**Comment by mevivs** [comment]
Releasing with 2.8.1
