### ISSUE TITLE
NullPointerException when persisting Entity with a null-valued @Embedded property

### ISSUE THREAD

**Issue by TheGeekPharaoh** [Impetus/kundera#350]
I have a pretty standard entity to be persisted in MongoDB using Kundera 2.6.  In this entity is a property annotated as @Embedded.  The class for this embedded value is annotated properly, as well.  However, when I persist an instance of this Entity where the embedded property is set to null I see the following exception:

Caused by: java.lang.NullPointerException
    at com.impetus.client.mongodb.DocumentObjectMapper.setFieldValue(DocumentObjectMapper.java:153) [kundera-mongo-2.6.jar:]
    at com.impetus.client.mongodb.DocumentObjectMapper.getObjectFromDocument(DocumentObjectMapper.java:126) [kundera-mongo-2.6.jar:]
    at com.impetus.client.mongodb.MongoDBDataHandler.onViaEmbeddable(MongoDBDataHandler.java:465) [kundera-mongo-2.6.jar:]
    at com.impetus.client.mongodb.MongoDBDataHandler.getEntityFromDocument(MongoDBDataHandler.java:131) [kundera-mongo-2.6.jar:]
    at com.impetus.client.mongodb.MongoDBClient.loadData(MongoDBClient.java:352) [kundera-mongo-2.6.jar:]
    at com.impetus.client.mongodb.query.MongoDBQuery.populateEntities(MongoDBQuery.java:129) [kundera-mongo-2.6.jar:]

If I set a value for this property, the exception goes away.  I have also tested this with different @Embedded and @Embeddable properties and classes.  It is reproducible at will.

**Comment by mevivs** [comment]
Please share entity definition along with CRUD code snippet.

-Vivek

**Comment by TheGeekPharaoh** [comment]
For example...

@Entity
@Table(name = "TrackedEvent", schema = "holocron@Holocron")
@IndexCollection(columns = { @Index(name = "endDate"),
        @Index(name = "startDate"), @Index(name = "name"),
        @Index(name = "ownerUUID") })
@NamedQueries(value = {
        @NamedQuery(name = "TrackedEvent.findAll", query = "SELECT DISTINCT e FROM TrackedEventBean e"),
        @NamedQuery(name = "TrackedEvent.count", query = "SELECT COUNT(e) FROM TrackedEventBean e"),
        @NamedQuery(name = "TrackedEvent.findByOwnerUUID", query = "SELECT e FROM TrackedEventBean e WHERE e.ownerUUID = :ownerUUID") })
public class TrackedEventBean extends AbstractNonTransactionalDomainEntity {

```
private static final long serialVersionUID = 809593834341260441L;

@Column(length = 500)
@Length(max = 500)
private String description = null;

@Column
@Temporal(TemporalType.TIMESTAMP)
private Date endDate = null;

@Embedded
private EventCategoryBean eventCategory = null;
```

...

}

@Embeddable
public class EventCategoryBean implements Serializable {

```
private static final long serialVersionUID = -3669638152854495740L;

@Column(length = 100, name = "categoryName")
@Length(max = 100)
private String name = null;
```

...

}

The CRUD is just a simple...

TrackedEventBean e = new TrackedEventBean();
e.setEventCategory(new EventCategory());  
...set other properties...

entityManager.persist(e);

If I leave out the e.setEventCategory() line the Exception is thrown.  I have also tested this with other @Embeddable classes and witnessed the same result.

**Comment by kkmishra** [comment]
Hi,
AbstractNonTransactionalDomainEntity, is it a mapped super class entity or
what ?
Please provide some more detail about it.

Thanks
Kuldeep

On Sun, Aug 11, 2013 at 6:45 AM, sdnakhla notifications@github.com wrote:

> For example...
> 
> @Entity https://github.com/Entity
> @Table https://github.com/Table(name = "TrackedEvent", schema =
> "holocron@Holocron")
> @IndexCollection(columns = { @Index https://github.com/Index(name =
> "endDate"),
> @Index https://github.com/Index(name = "startDate"), @Indexhttps://github.com/Index(name
> = "name"),
> @Index https://github.com/Index(name = "ownerUUID") })
> @NamedQueries(value = {
> @NamedQuery(name = "TrackedEvent.findAll", query = "SELECT DISTINCT e FROM
> TrackedEventBean e"),
> @NamedQuery(name = "TrackedEvent.count", query = "SELECT COUNT(e) FROM
> TrackedEventBean e"),
> @NamedQuery(name = "TrackedEvent.findByOwnerUUID", query = "SELECT e FROM
> TrackedEventBean e WHERE e.ownerUUID = :ownerUUID") })
> public class TrackedEventBean extends AbstractNonTransactionalDomainEntity
> {
> 
> private static final long serialVersionUID = 809593834341260441L;
> 
> @Column(length = 500)
> @Length(max = 500)
> private String description = null;
> 
> @Column
> @Temporal(TemporalType.TIMESTAMP)
> private Date endDate = null;
> 
> @Embedded
> private EventCategoryBean eventCategory = null;
> 
> ...
> 
> }
> 
> @Embeddable
> public class EventCategoryBean implements Serializable {
> 
> private static final long serialVersionUID = -3669638152854495740L;
> 
> @Column(length = 100, name = "categoryName")
> @Length(max = 100)
> private String name = null;
> 
> ...
> 
> }
> 
> The CRUD is just a simple...
> 
> TrackedEventBean e = new TrackedEventBean();
> e.setEventCategory(new EventCategory());
> 
> ...set other properties...
> 
> entityManager.persist(e);
> 
> If I leave out the e.setEventCategory() line the Exception is thrown. I
> have also tested this with other @Embeddable classes and witnessed the same
> result.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/350#issuecomment-22450498
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by TheGeekPharaoh** [comment]
It is a mapped superclass, but has no properties or methods.  It's just there due to design convention.  I've also tried removing it and not having any superclasses, but the results are the same.

**Comment by mevivs** [comment]
Tried with Simple entity as:

```
@Entity
@Table(name = "TrackedEvent", schema = "holocron@Holocron")
@IndexCollection(columns = { @Index(name = "endDate"),
@Index(name = "startDate"), @Index(name = "name"),
@Index(name = "ownerUUID") })
@NamedQueries(value = {
@NamedQuery(name = "TrackedEvent.findAll", query = "SELECT DISTINCT e FROM TrackedEventBean e"),
@NamedQuery(name = "TrackedEvent.count", query = "SELECT COUNT(e) FROM TrackedEventBean e"),
@NamedQuery(name = "TrackedEvent.findByOwnerUUID", query = "SELECT e FROM TrackedEventBean e WHERE e.ownerUUID = :ownerUUID") })
public class TrackedEventBean {

private static final long serialVersionUID = 809593834341260441L;

@Column(length = 500)
@Length(max = 500)
@Id
private String description = null;

@Column
@Temporal(TemporalType.TIMESTAMP)
private Date endDate = null;

@Embedded
private EventCategoryBean eventCategory = null;

```

Working fine.

-Vivek

**Comment by TheGeekPharaoh** [comment]
The persist works with no problem.  I receive an exception when I query for results, though.

**Comment by mevivs** [comment]
Assigning KK

**Comment by TheGeekPharaoh** [comment]
Any update on this?

**Comment by kkmishra** [comment]
Hi,
Changes pushed in current trunk branch, please verify and let me know if
problem persists.

Thanks
Kuldeep

On Mon, Aug 19, 2013 at 5:49 AM, sdnakhla notifications@github.com wrote:

> Any update on this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/350#issuecomment-22844843
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by TheGeekPharaoh** [comment]
Looks good.  Thanks.
