### ISSUE TITLE
Using elementcollections in entities causes weird schemas in MongoDB

### ISSUE THREAD

**Issue by pdirksen** [Impetus/kundera#351]
Using elementcollections in entities causes weird schemas in MongoDB.
Adding a elementcollection seems to affect all other entities too.

Using: Kundera 2.6

``` java
@Entity
@Table(name = "feature", schema = "test@nosqlpu")
public class Feature implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private String id;

  @Basic(optional = false)
  @Column(nullable = false, unique = true)
  private String name;

  @ElementCollection(targetClass = String.class)
  private List<String> alternativeNames = new LinkedList<>();

}
```

And now the diff between (json formatted).

``` json
{
   "_id": {
     "value": {
       "0": "5",
       "1": "2",
       "2": "0",
       "3": "6",
       "4": "1",
       "5": "7",
       "6": "f",
       "7": "a",
       "8": "0",
       "9": "d",
       "10": "9",
       "11": "8",
       "12": "1",
       "13": "3",
       "14": "8",
       "15": "9",
       "16": "2",
       "17": "c",
       "18": "f",
       "19": "8",
       "20": "8",
       "21": "f",
       "22": "c",
       "23": "9" 
    },
     "hash": NumberInt(0) 
  },
   "name": {
     "value": {
       "0": "t",
       "1": "e",
       "2": "s",
       "3": "t",
    },
     "hash": NumberInt(0) 
  }
}
```

'alternativeNames' is not set. Excluding the ElementCollection results as expected:

``` json
{
   "_id": "52061ffe0d98d44c7e5a9c8a",
   "name": "test",
}
```

**Comment by mevivs** [comment]
Can you please share CRUD code snippet, which are trying with?

-Vivek

**Comment by pdirksen** [comment]
It is just a simple persist.

``` java
EntityTransaction transaction = em.getTransaction();
transaction.begin();

Feature f = new Feature();
f.setName("test");

em.persist(f);
transaction.commit();
em.clear();
```

There are some other entities around, but I'm afraid I am not allowd to share them. If you need all entities I can try to export them refactored.

**Comment by kkmishra** [comment]
Hi,
I confirm it is an issue with @ElementCollection, it will be fixed in 2.7.
As of now you can use it without using @ElementCollection annotation.

Thanks
Kuldeep

On Sat, Aug 10, 2013 at 4:53 PM, pdirksen notifications@github.com wrote:

> It is just a simple persist.
> 
> EntityTransaction transaction = em.getTransaction();transaction.begin();
> Feature f = new Feature();f.setName("test");
> em.persist(f);transaction.commit();em.clear();
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/351#issuecomment-22438216
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by pdirksen** [comment]
Thanks.

I use kundera as a kind of drop-in-replacement for an existing project. This is not the only error i got but first I have to lock it down to some specific lines before I post them.

**Comment by mevivs** [comment]
2.7 release is planned for 3rd Sept. Let me know, if you have any other issues to share.

-Vivek
