### ISSUE TITLE
Superclass properties not honored on @Embedded/@Embeddable

### ISSUE THREAD

**Issue by TheGeekPharaoh** [Impetus/kundera#353]
I have an @Entity that has a property that is @Embedded.  This value has an abstract base class that also declares columns to be persisted.  However, these properties do not seem to be persisted when persisting the object.  For example:

My entity:
@Entity(name = "ImageObject")
@Table(name = "Images", schema = "...")
public class ImageObjectBean extends AbstractMediaObjectBean {

```
private static final long serialVersionUID = 7564967795036282103L;

@Id
private String id = null;

@Embedded
private ImageObjectMetadataBean metadata = null;
```

...

}

The superclass:

@MappedSuperclass
public abstract class AbstractMediaObjectMetadataBean implements Serializable {

```
private static final long serialVersionUID = 7889362115559588643L;

@Column(length = 64)
@Length(max = 64)
@NotEmpty
private String contentType = null;

@Column
@NotNull
private int contentLength = -1;
```

...
}

The subclass:

@Embeddable
public class ImageObjectMetadataBean extends AbstractMediaObjectMetadataBean {

```
private static final long serialVersionUID = 677559354623566490L;

@Column
private String test=null;
```

...
}

When I persist my object, I see the "test" property from ImageObjectMetadataBean being written to the database (MongoDB, in this case) but do not see "contentType" or "contentLength".  I have also tried putting @Embeddable and no annotation on the superclass, but still see the same behavior.  If I do not make use of a superclass it works, but I need it due to design constraints.

**Comment by mevivs** [comment]
Support for MappedSuperClass is on the plan:
https://github.com/impetus-opensource/Kundera/issues/56

But not supported on current trunk.

-Vivek

**Comment by TheGeekPharaoh** [comment]
Is there an estimated time for when this will be implemented?

**Comment by mevivs** [comment]
Planned for releases after 2.7.

BTW  using Kundera for?

-Vivek

**Comment by TheGeekPharaoh** [comment]
Persisting geolocated data.  It's highly structured due to the way its being used, hence my question.

**Comment by mevivs** [comment]
Ok. Will discuss and try to prioritize it for 2.8

It will be great, if you can spare few minutes to fill in survey:

http://www.surveymonkey.com/s/BMB9PWG

-Vivek

**Comment by TheGeekPharaoh** [comment]
Survey completed
