### ISSUE TITLE
How to associate two column families with  compound primary keys

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#356]
Hi I have two columnfamilies which have compund primary keys.I need to make a join query on them .Can you suggest what can i do to achieve that.My tables look like this:-
# CREATE TABLE "MediaCategoryGroup" ("MCategoryID" int, "MCategoryName" varchar,"LangID" int, PRIMARY KEY("LangID","MCategoryID"));
# CREATE TABLE "MediaCategory" ("MCategoryID" int, "SubMCategoryName" varchar, "PhotoRankID" int, "VirtualTourID" int, "LangID" int, PRIMARY KEY("LangID", "PhotoRankID"));

Now for a given MCategoryID and LangID in   MediaCategoryGroup i need to fetch all the MediaCategory.
Can you please help me find how to do this. 

If its a single column association i can do thi si know:-
@Entity
@Table(name = "MediaCategory", schema = "EPCContent@cassandra_pu")
public class MediaCategory {

@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
        @JoinColumn(name = "MCategoryID")
private MediaCategoryGroup m_mcg;

but i m not sure how to achieve this with a compund key association.

**Comment by mevivs** [comment]
So MediaCategoryGroup contains 1-M with MediaCategory. Such join queries will not work. Personally, i think you should denormalize and avoid such join queries. Not a valid use case for Cassandra.

-Vivek

**Comment by Gargee** [comment]
Atually when I had a single primary key on MediaCategoryGroup  I could make it work but now when I have "LangID" also as a part of the primary key ..I can't think of a way.Ya I guess the table structure needs to be reworked.

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by Gargee** [comment]
yes..
