### ISSUE TITLE
String values being persisted as char arrays sometimes

### ISSUE THREAD

**Issue by TheGeekPharaoh** [Impetus/kundera#357]
I am attempting to persist an object that looks something like this into a MongoDB datastore...

@Entity
@Table(name = "TrackedEvent", schema = "holocron@Holocron")
@IndexCollection(columns = { @Index(name = "endDate"),
        @Index(name = "startDate"), @Index(name = "name"),
        @Index(name = "ownerUUID") })
public class TrackedEventBean extends AbstractNonTransactionalDomainEntity {

```
private static final long serialVersionUID = 809593834341260441L;

@Column(length = 500)
@Length(max = 500)
private String description = null;

@Column
@Temporal(TemporalType.TIMESTAMP)
private Date endDate = null;

@Embedded
private EventCategoryBean eventCategory = null;

@Embedded
private EventMetadataBean eventMetadata = null;

@Id
private String id = null;
```

...

}

The id value is set to a UUID string value.  However, what I see persisted in the database looks like a character array, rather than a String.  What is odd is that String properties in eventCategory or eventMetadata look find.  The String-valued properties in the Entity itself, though, are all persisted as char[].  For example:

{ "_id" : { "value" : [     "5",    "2",    "1",    "0",    "2",    "d",    "a",    "8",    "0",    "3",    "6",    "4",    "0",    "8",    "1",    "b",    "5", "1",   "d",    "c",    "9",    "9",    "f",    "5" ], "hash" : 0 }, "description" : { "hash" : 0, "value" : [  "D",    "e",    "s",    "c",    "r",    "i",    "p", "t",   "i",    "o",    "n",    " ",    "6",    "4",    "2",    "6",    "6",    "2",    "7",    "4",    "7",    "2",    "2",    "7",    "2",    "6",    "9",    "8", "8",   "0" ] }, "startDate" : ISODate("2013-08-18T02:12:56.943Z"), "endDate" : ISODate("2013-08-18T02:12:56.943Z"), "location" : { "coordinates" : [  78.79583827220412,  123.57475783381857 ], "locationName" : "Location -7087347123951574629", "locationDescription" : "Location description -7063430557213659560" }, "eventMetadata" : { "publicEvent" : true, "lastUpdate" : ISODate("2013-08-18T02:12:56.930Z"), "createdDate" : ISODate("2013-08-18T02:12:56.930Z") }, "name" : { "hash" : 0, "value" : ["E",   "v",    "e",    "n",    "t",    " ",    "-",    "2",    "8",    "9",    "5",    "3",    "8",    "8",    "5",    "3",    "5",    "6",    "2",    "7",    "4", "7",   "0",    "3",    "5",    "2" ] }, "eventCategory" : { "categoryName" : "Category c16c7ba1-ee74-4786-8a18-d54cc7a3c199" }, "ownerUUID" : { "hash" : 0, "value" : [    "a",    "9",    "3",    "d",    "5",    "1",    "0",    "b",    "-",    "3",    "1",    "6",    "3",    "-",    "4",    "3",    "4",    "7",    "-",    "b", "2",   "4",    "f",    "-",    "4",    "3",    "d",    "b",    "e",    "c",    "7",    "0",    "e",    "f",    "5",    "e" ] } }

Why is it that embedded Strings are persisted just fine, but Strings within the Entity are not?

**Comment by TheGeekPharaoh** [comment]
I've done a bit more investigation and uncovered an additional detail that seems to trigger this error condition.  I have the following property defined in this entity:

@ElementCollection
private List<String> users = null;

With this property defined, I see the strange behavior I reported earlier.  If I remove this property from my Entity class, the behavior goes back to normal.  Additionally, the negative effects are not local to just this one Entity.  If I have a class with this property, ALL of my entities are affected with the strange behavior.  Hope that helps.

**Comment by pdirksen** [comment]
This is a duplicate of #351. Should be solved in Kundera-Trunk.

**Comment by TheGeekPharaoh** [comment]
Solved.  Thanks.
