### ISSUE TITLE
Not able to use the 2.7 snapshot using maven

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#359]
Hi ,
I am trying to use the trunk code ,i have created the jars from the trunk using
mvn clean install -DskipTests..
but our build fails when i put the depedency 
<'dependency>
   <'groupId>com.impetus.client<'/groupId>
   <'artifactId>kundera-cassandra<'/artifactId>
   <'version>2.7-SNAPSHOT<'/version'>
  <'/dependency'>
1. add kundera-core 2.7-SNAPSHOT
   <'dependency'>
   <'groupId>com.impetus.core</groupId'>
   <'artifactId>kundera-core</artifactId'>
   <'version>2.7-SNAPSHOT</version'>
   <'/dependency'>

3 add snapshots in  <'repositorys>
<'repositorys>
<'repository'>
   <'url>http://nexus.sb.karmalab.net/nexus/content/repositories/snapshots</url'>
   <'id>snapshots</id'>
  <'/repository'>
 and i get this error:-
[ERROR] Failed to execute goal on project LUXContent: Could not resolve dependencies for project com.expedia.lux:LUXContent:war:pLUXMain.main-SNAPSHOT: Failed to collect dependencies for [org.javassist:javassist:jar:3.18.0-GA (compile), velocity:velocity:jar:1.5 (compile), com.expedia.lux:LUXCommonObjects:jar:pLUXMain.main-SNAPSHOT (compile), com.expedia.lux:LUXDataModels:jar:pLUXMain.main-SNAPSHOT (compile), com.expedia.lux:LUXReloadableFileCache:jar:pLUXMain.main-SNAPSHOT (compile), com.expedia.lux:LUXExternalMessages:jar:pLUXMain.main-SNAPSHOT (compile), com.expedia.lux:LUXContentLCMSMessages:jar:pLUXMain.main-SNAPSHOT (compile), com.fasterxml.jackson.core:jackson-databind:jar:2.1.3 (compile), com.fasterxml.jackson.core:jackson-core:jar:2.1.3 (compile), javax.servlet.jsp:javax.servlet.j
sp-api:jar:2.2.1 (provided), org.apache.commons:commons-exec:jar:1.1 (compile), net.sf.json-lib:json-lib:jar:0.9 (compile), net.sf.ezmorph:ezmorph:jar:0.9 (compile), commons-fileupload:commons-fileupload:pom:1.2.2 (compile), net.sourceforge.jexcelapi:jxl:jar:2.6 (compile), org.springframework:spring-orm:jar:3.2.1.RELEASE (compile), com.impetus.client:kundera-cassandra:jar:2.7-SNAPSHOT (compile), com.impetus.core:kundera-core:jar:2.7-SNAPSHOT (compile), org.apache.cassandra:cassandra-all:jar:1.2.5 (compile), org.scale7:scale7-core:jar:1.3 (compile), javax.persistence:persistence-api:jar:2.0 (compile), commons-lang:commons-lang:jar:2.5 (compile), com.eaio.uuid:uuid:jar:3.4 (compile), org.aspectj:aspectjrt:jar:1.6.11 (compile), org.aspectj:aspectjweaver:jar:1.6.11 (compile), org.codehaus.jett
ison:jettison:jar:1.3.2 (compile), log4j:log4j:jar:1.2.17 (compile), log4j:apache-log4j-extras:jar:1.1 (compile), javax.inject:javax.inject:jar:1 (compile), javax.servlet:jstl:jar:1.1.2 (compile), taglibs:standard:jar:1.1.2 (compile), org.primefaces:primefaces:jar:3.4 (compile), org.primefaces.themes:redmond:jar:1.0.6 (compile), commons-fileupload:commons-fileupload:jar:1.2.2 (compile), net.jawr:jawr:jar:3.3.3 (compile), com.lowagie:itext:jar:2.1.7 (compile), org.apache.poi:poi:jar:3.8 (compile), org.apache.poi:poi-ooxml:jar:3.8 (compile), org.apache.commons:commons-lang3:jar:3.1 (compile), commons-io:commons-io:jar:2.4 (compile), com.sun.faces:jsf-api:jar:2.1.12 (compile), com.sun.faces:jsf-impl:jar:2.1.12 (compile), org.apache.commons:commons-email:jar:1.2 (compile), com.sun.xml.fastinfo
set:FastInfoset:jar:1.2.12 (compile), org.apache.httpcomponents:httpclient:jar:4.2.1 (compile), org.apache.httpcomponents:fluent-hc:jar:4.2.1 (compile), org.apache.httpcomponents:httpasyncclient:jar:4.0-beta3 (compile), com.sun.xml.bind:jaxb-impl:jar:2.2.5-2 (compile), javax.xml.bind:jaxb-api:jar:2.2.5 (compile), javax.servlet:javax.servlet-api:jar:3.0.1 (provided), javax.el:javax.el-api:jar:2.2.4 (provided), junit:junit:jar:4.10 (test), org.powermock:powermock-module-junit4:jar:1.5.1 (test), org.powermock:powermock-api-mockito:jar:1.5.1 (test), org.powermock:powermock-api-easymock:jar:1.5.1 (test), org.powermock:powermock-module-junit4-rule:jar:1.5.1 (test), org.powermock:powermock-classloading-xstream:jar:1.5.1 (test), org.easymock:easymock:jar:3.1 (test), commons-beanutils:commons-beanu
tils:jar:1.8.3 (compile), commons-collections:commons-collections:jar:3.0 (compile), commons-dbcp:commons-dbcp:jar:1.4 (compile), com.microsoft:sqljdbc:jar:4.0 (compile), org.springframework:spring-context:jar:3.2.1.RELEASE (compile), org.springframework:spring-web:jar:3.2.1.RELEASE (compile), org.springframework:spring-webmvc:jar:3.2.1.RELEASE (compile), org.springframework:spring-test:jar:3.2.1.RELEASE (test), org.springframework:spring-aop:jar:3.2.1.RELEASE (compile), org.springframework:spring-context-support:jar:3.2.1.RELEASE (compile), org.springframework:spring-jdbc:jar:3.2.1.RELEASE (compile)]: Failed to read artifact descriptor for com.impetus.core:kundera-core:jar:2.7-SNAPSHOT: Could not find artifact com.impetus:kundera:pom:2.7-SNAPSHOT in expedia-jlux-snapshot (http://nexus.sb.
karmalab.net/nexus/content/repositories/build-test-snapshot) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

**Comment by mevivs** [comment]
You need to manually build  2.7-SNAPSHOT on local machine. It's not available on central maven repository.

-Vivek
