### ISSUE TITLE
Issue updating collections to null once they have been set any value

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#362]
Hi,
I am having issues updating collections once they have been set any value.
The table looks like this:-
CREATE TABLE "Photos" ("PhotoID" uuid, "PhotoLogSeqNum" int, "ChangeStatusID" int, "ChangeRequestID" uuid,"ModUser" varchar,"RejectionID" int,"LockTime" timestamp, "UploadFormat" varchar, "PhotoWidth" int, "PhotoHeight" int, "UploadChannel" varchar, "DM" boolean, "SupplierSegmentation" varchar, "Filename" varchar, "MediaUseRank" int,  "ParagraphID" int, "CatalogItemID" int, "CreateDate" timestamp, "CreateUser" varchar, "SKUGroupID" int, "LCMSMediaID" int, "IsLockedBool" boolean,"RoomTypeID" Set <'varchar'> ,"PhotoSize" int , PRIMARY KEY ( "ChangeRequestID","PhotoID","PhotoLogSeqNum") );

1.When i set the data ,"RoomTypeID" Set <'varchar'> it is getting set.
2.When i set this column to null its not getting set to null.
my code looks like this:-
    public void setPhoto(Photos p) {
        EntityManager em = cKDao.getEntityManager();
        em.merge(p);
        em.close();

```
}
```

I tried persist  also ..
em.persist(p);
but all other fields are getting updated except the  RoomTypeID" Set <'varchar'>.
Looks like an issue with Kundera.

**Comment by mevivs** [comment]
2.When i set this column to null its not getting set to null.

Means, you do not want to store a value while persisting. But want to update it later? This is what not working for you?

-Vivek

**Comment by Gargee** [comment]
HI Vivek,
I first set some value for that column "RoomTypeID" Set <'varchar'> and later on i need to update that column to null.

but  when i do em.persist(p)/em.merge(p); if i set the value of "RoomTypeID" to some value its getting updated to the set value.but if i set it to null its not getting updated to null and Kundera is not even throwing any exception .

**Comment by mevivs** [comment]
Hi Gargee,
Did you try to set it as an empty hashset?

Anything which is set to null is simply ignored by Kundera. In nosql world there is no definition of NULL. See if it works.

-Vivek

**Comment by Gargee** [comment]
Hi Vivek,
Ill definitely try this tomorrow morning and let you know .
Thanks
Gargee

**Comment by mevivs** [comment]
Hi Gargee,
Ok. I request you to spare few minutes to fill in for Kundera survey, here is the link:

http://www.surveymonkey.com/s/BMB9PWG

-Vivek

**Comment by Gargee** [comment]
Hi Vivek,
I tried with empty hashset but the column "RoomTypeID" Set <'varchar'>  is not getting updated.
Its restoring the old value.

**Comment by mevivs** [comment]
I will have a look, and get it fixed for 2.7

-Vivek

**Comment by Gargee** [comment]
ok Thanks Vivek.So I hope i can push the fix in production after 3rd sep.

**Comment by mevivs** [comment]
Yes. I understand that map support was required to get your application in production. 

Your application is now running in production? Or this is a blocker for you before going into production?

-Vivek

**Comment by Gargee** [comment]
Its a blocker right now.
Thanks
Gargee

**Comment by kkmishra** [comment]
Hi Gargee,
It is fixed for both null and empty collection/map, and pushed into current
working branch ie. trunk, please verify.

Thanks
Kuldeep

On Mon, Aug 26, 2013 at 6:27 AM, Gargee Banerjee
notifications@github.comwrote:

> Its a blocker right now.
> Thanks
> Gargee
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/362#issuecomment-23239250
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by Gargee** [comment]
Hi Kuldeep.,
I have verified with the trunk code and update to null is working fine now.
Thanks for the prompt support.
-Gargee

**Comment by mevivs** [comment]
Closing. Releasing with 2.7 release.

-Vivek
