### ISSUE TITLE
Entities from another jar

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#364]
Hello!

Does Kundera allows to get entities from another jar? For example, i have 2 modules:
- model.jar
- application.war

and i want to store entities and DAOs in model.jar, but my persistence.xml and other things are in application.war

is it possible? Had no luck with :(

**Comment by mevivs** [comment]
it should work. add model.jar within 

```
<jar-file> </jar-file>

```

if model.jar is available in classpath. It should work.

-Vivek

**Comment by bsideup** [comment]
Ok, thanks!

**Comment by impetus-opensource-admin** [comment]
Any update? Are we good to close on it?

-Vivek

**Comment by bsideup** [comment]
Yeah, works fine, but with <class>some.class.from.Jar</class> instead of <jar-file> :) 

Thanks!

**Comment by mevivs** [comment]
Hmm. Should have worked in both the cases(may be relative jar path is not correct). Closing.

-Vivek
