### ISSUE TITLE
when excute one time native cql there will be memory leak in namedNativeQueries cache!

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#366]
when excute one time native cql there will be memory leak in namedNativeQueries cache. pls see it:

ApplicationMetadata.java's addQueryToCollection():
....
          namedNativeQueries.put(queryName, new QueryWrapper(queryName, query, isNativeQuery, clazz));
...

when and where release the QueryWrapper from the namedNativeQueries map after excuting the one time native cql?

**Comment by zhouhero** [comment]
the one time native cql , jpql should not to be cached i think.

**Comment by mevivs** [comment]
Fix will require change across multiple databases. Planned for release after 2.7.

-Vivek
