### ISSUE TITLE
UserName and Passsword Authentication

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#367]
Hi ,
I need to know if i can set the authentication for Cassandra for username and password  through Kundera externally ?
i can see we can do it in Persistence.xml using 
kundera.username (Optional)**:** User name to authenticate to for Cassandra and MongoDB.

kundera.password (Optional)**:** Password for login authentication for Cassandra and MongoDB.

but can we put this data in the external config file ?

**Comment by mevivs** [comment]
In external config file you can add that under server tag as:

```
                    <server>
                        <host>localhost</host>
                        <port>9160</port>
                                                <properties>
                                         <property name="kundera.username" value="kunderauser" />
                                         <property name="kundera.password" value="kunderapassword" />
                                                </properties>
                    </server>
```

It should work for you.

-Vivek

**Comment by Gargee** [comment]
thanks
