### ISSUE TITLE
Pagination in RDBMS

### ISSUE THREAD

**Issue by sbheda** [Impetus/kundera#370]
Hi,
How to implement pagination in MySQL using kundera.

**Comment by subes** [comment]
If kundera properly works with spring-data-jpa and its jparepository, it
should be possible to reuse the paging implementation done in spring.
Normally one has to write his own paging implementation on top of the jpa
api, but here spring comes in handy.

An orm like kundera only needs to provide support for limits in the query
(start row and end row numbers) and sorting capabilities. As i read this
should be the case for kundera.

Though i have not yet tested if kundera is ready in that regard to be used
with spring-data.

Worst case you could look for tutorials that explain this for plain jpa.
Am 03.09.2013 13:10 schrieb "shraddha" notifications@github.com:

**Comment by mevivs** [comment]
```
If kundera properly works with spring-data-jpa and its jparepository, it
should be possible to reuse the paging implementation done in spring.
Normally one has to write his own paging implementation on top of the jpa
api, but here spring comes in handy.
```

Kundera works and can be easily integrated with spring JPA repository.

Kundera does provide support for pagination over Cassandra,HBase and with 2.7 it will be supported for MongoDB as well.  For RDBMS, it's unsupported, but you can set limit on number of records.

-Vivek

**Comment by sbheda** [comment]
Thank you very much for your reply.
