### ISSUE TITLE
Handling EntityManager instances

### ISSUE THREAD

**Issue by pranav-gopi** [Impetus/kundera#371]
Hi,
In the spring-kundera example,
https://github.com/impetus-opensource/Kundera/wiki/Using-Kundera-with-Spring
entityManager instance is closed for save and remove, but not closed for find query functions. Won't this approach create new entityManager instances every time we call find function which are not closed at all?
## 

Pranav

**Comment by mevivs** [comment]
It's just to demonstrate how you can hook up things with spring. However, in real world scenario, with application managed entity manager you may not be creating so many emf and em instance for each method invocation.

-Vivek

**Comment by pranav-gopi** [comment]
Hi,
I have a bean class with one to many lazy fetch join to another bean. So in find method if I close entitymanager and try to access child class, it will throw Lazy Initialization Exception. 

<code>
@OneToMany(cascade={CascadeType.ALL},fetch=FetchType.LAZY)
@JoinColumn(name="showid")
private List<ShowmapBean> referencedShowmapList;
</code>

So either I had to keep entityManager open or I have to use Eager fetch in bean class. Is their any other way to avoid the exception and to close entityManager instance within find function?

While using spring transaction management also I was facing this issue.

## 

Thanks,
Pranav

**Comment by mevivs** [comment]
Hi,
First, I suggest you to inject single EntityManager/EntityManagerFactory instance for each service instance. That way you would not get into any such issues.

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by pranav-gopi** [comment]
Ya, thanks for your reply
Pranav
