### ISSUE TITLE
Wrong value being inserted into DB Kundera + Mongo

### ISSUE THREAD

**Issue by vsreekar** [Impetus/kundera#372]
Following are two prime beans for this issue.

@Entity
@Table(name = "product", schema = "griff-notification@griff-notification")
public class Product implements Serializable, GriffNotificationDto {

```
/**
 * 
 */
private static final long serialVersionUID = 4242890624607140773L;

/**
 * Any extra information of the product to be stored in this field
 */
@Embedded
@AttributeOverride(column = @Column(name = "info"), name = "info")
private Info info;

/**
 * Id of the product
 */
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
@Column(name = "product_id")
private String productId;

/**
 * Name of the product
 */
@Column(name = "product_name")
private String productName;
```

}

@Entity
@Table(name = "product_ecosystem_map", schema = "griff-notification@griff-notification")
public class ProductEcosystemMap implements Serializable, GriffNotificationDto {

```
/**
 * 
 */
private static final long serialVersionUID = 8153462679027161808L;

/**
 * Primary key for the table
 */
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
@Column
private String _id;

@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "ecosystem_type", referencedColumnName = "ecosystem_type")
private DeviceEcosystem ecosystem;

@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "product_id", referencedColumnName = "product_id")
private Product product;

@Column(name = "product_ref_id")
private String productRefId;
```

}

Check the below log, passed Id of the product to be inserted  is different and the one that actually is being inserted are not the same.

2013-09-05 12:26:52,606 - [main] TRACE [com.onmobile.apps.griff.notification.data.dao.GriffNotificationDao:save:115] - Saving dto ProductEcosystemMap [_id=null, ecosystem=DeviceEcosystem [ecosystemType=ANDROID, config=Info [info={"DESC":"Description for ANDROID","URL":"http://test.android.om"}]], product=Product [productId=52282b343250fa43d196cbb3, productName=Product 9, info=Info [info={"DESC":"Description of the product 9"}]], productRefId=ca755f53-db40-4938-b288-fc2072adb0aa]
2013-09-05 12:26:52,607 - [main] DEBUG [com.impetus.kundera.persistence.context.CacheBase:logCacheEvent:152] - Node: com.onmobile.apps.griff.notification.data.domain.ProductEcosystemMap$52282b343250fa43d196cbd8:: ADDED TO  Persistence Context
2013-09-05 12:26:52,607 - [main] DEBUG [com.impetus.kundera.persistence.PersistenceDelegator:flush:442] - Flushing following flush stack to database(s) (showing stack objects from top to bottom):
[[com.onmobile.apps.griff.notification.data.domain.DeviceEcosystem$ANDROID]com.onmobile.apps.griff.notification.data.domain.DeviceEcosystem$ANDROID, [com.onmobile.apps.griff.notification.data.domain.Product$52282b343250fa43d196cbd9]com.onmobile.apps.griff.notification.data.domain.Product$52282b343250fa43d196cbd9, [com.onmobile.apps.griff.notification.data.domain.ProductEcosystemMap$52282b343250fa43d196cbd8]com.onmobile.apps.griff.notification.data.domain.ProductEcosystemMap$52282b343250fa43d196cbd8]

Pls do let me know if I'm doing anything wrong here

**Comment by mevivs** [comment]
Hi,
Can you please share a bit more on how actually you are performing CRUD? Also If ProductEcosystemMap is holding a relationship with Product, any persistence via ProductEcosystemMap  needs to cascaded(CascadeType.ALL). 

Looking for CRUD code snippet and output on mongo shell.

-Vivek

**Comment by vsreekar** [comment]
Hello,

I'm using spring transaction manager. Below is more code snippets for your details

@Repository
public abstract class GriffNotificationDao<T extends GriffNotificationDto> {
    @PersistenceContext
    private EntityManager entityManager;

```
protected void save(T dtoBean) {
    if (null == dtoBean) {
        if (LOGGER.isDebugEnabled()) {
            LOGGER.debug("Cannot save null dto");
            return;
        }
    }

    if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Saving dto " + dtoBean);
    }

    getEntityManager().persist(dtoBean);
    getEntityManager().flush();
}
public EntityManager getEntityManager() {
    return entityManager;
}
```

}

@Repository
@Transactional
public class ProductEcosystemMapDaoImpl extends
        GriffNotificationDao<ProductEcosystemMap> implements
        ProductEcosystemMapDao {
    @Override
    public void addProductEcosystemMap(ProductEcosystemMap productEcosystemMap) {
        save(productEcosystemMap);
    }
}

@Component
@Configurable
public class ProductEcosystemMapDataOnDemand {

```
@Autowired
private ProductEcosystemMapDao productEcosystemMapDao;

private void init() throws JSONException {
            //other application specific code

            //This list will give me all the available products in the product table
    List<Product> products = productDod.getProductList();
            //This list will give me all the available ecosystems in DB
    List<DeviceEcosystem> ecosystems = deviceEcosystemDod
            .getDeviceEcosystemsList();

    for (Product product : products) {
        for (DeviceEcosystem ecosystem : ecosystems) {
            ProductEcosystemMap productEcosystemMap = new ProductEcosystemMap();

            productEcosystemMap.setEcosystem(ecosystem);
            productEcosystemMap.setProduct(product);

            productEcosystemMap.setProductRefId(UUID.randomUUID()
                    .toString());

            productEcosystemMapDao
                    .addProductEcosystemMap(productEcosystemMap);

        }
    }
    }
```

}

Following is the data output from console

> db.product.find()
> { "_id" : "52283128325051137ffd398b", "info" : { "info" : "{\"DESC\":\"Description of the product 0\"}" }, "product_name" : "Product 0" }
> { "_id" : "52283128325051137ffd398c", "info" : { "info" : "{\"DESC\":\"Description of the product 1\"}" }, "product_name" : "Product 1" }
> { "_id" : "52283128325051137ffd398d", "info" : { "info" : "{\"DESC\":\"Description of the product 2\"}" }, "product_name" : "Product 2" }
> { "_id" : "52283128325051137ffd398e", "info" : { "info" : "{\"DESC\":\"Description of the product 3\"}" }, "product_name" : "Product 3" }
> { "_id" : "52283128325051137ffd398f", "info" : { "info" : "{\"DESC\":\"Description of the product 4\"}" }, "product_name" : "Product 4" }
> { "_id" : "52283128325051137ffd3990", "info" : { "info" : "{\"DESC\":\"Description of the product 5\"}" }, "product_name" : "Product 5" }
> { "_id" : "52283128325051137ffd3991", "info" : { "info" : "{\"DESC\":\"Description of the product 6\"}" }, "product_name" : "Product 6" }
> { "_id" : "52283128325051137ffd3992", "info" : { "info" : "{\"DESC\":\"Description of the product 7\"}" }, "product_name" : "Product 7" }
> { "_id" : "52283128325051137ffd3993", "info" : { "info" : "{\"DESC\":\"Description of the product 8\"}" }, "product_name" : "Product 8" }
> { "_id" : "52283128325051137ffd3994", "info" : { "info" : "{\"DESC\":\"Description of the product 9\"}" }, "product_name" : "Product 9" }
> db.product_ecosystem_map.find()
> { "_id" : "522834173250770ffb6259a7", "product_ref_id" : "920b7df3-e4b6-414b-8b4e-ce1a7f294fad", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259a8" }
> { "_id" : "522834173250770ffb6259a9", "product_ref_id" : "3bd7cf91-610f-4ecd-8700-fea2e0def34d", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259aa" }
> { "_id" : "522834173250770ffb6259ab", "product_ref_id" : "4f4b6770-8ea2-43ea-b925-7b54b13b9ab2", "product_id" : "522834173250770ffb6259ac", "ecosystem_type" : "ANDROID" }
> { "_id" : "522834173250770ffb6259ad", "product_ref_id" : "5012d073-9839-4a2c-a943-88d7658feb68", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259ae" }
> { "_id" : "522834173250770ffb6259af", "product_ref_id" : "2482c5d3-8451-49be-8ee4-8643d57aa269", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259b0" }
> { "_id" : "522834173250770ffb6259b1", "product_ref_id" : "9302e7e3-1640-45c5-9c58-e7eb13e51b96", "product_id" : "522834173250770ffb6259b2", "ecosystem_type" : "UNKNOWN" }
> { "_id" : "522834173250770ffb6259b3", "product_ref_id" : "074c25f6-95e7-4b4b-a84c-846c1e835284", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259b4" }
> { "_id" : "522834173250770ffb6259b5", "product_ref_id" : "50a2c027-738c-43f2-afc9-2e80f2261a7b", "product_id" : "522834173250770ffb6259b6", "ecosystem_type" : "UNKNOWN" }
> { "_id" : "522834173250770ffb6259b7", "product_ref_id" : "caf7f4be-65a0-4c2f-8b35-59a69f430e89", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259b8" }
> { "_id" : "522834173250770ffb6259b9", "product_ref_id" : "8b73e2e3-479c-4263-be67-c7b1a2978c64", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259ba" }
> { "_id" : "522834173250770ffb6259bb", "product_ref_id" : "c0623a0a-a0f9-4718-b3e3-e8fbc69a1fb1", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259bc" }
> { "_id" : "522834173250770ffb6259bd", "product_ref_id" : "1ceb2287-200d-41a3-87cc-e7b04d209449", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259be" }
> { "_id" : "522834173250770ffb6259bf", "product_ref_id" : "dec3cc97-7ed1-406a-9a03-51e352423a07", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259c0" }
> { "_id" : "522834173250770ffb6259c1", "product_ref_id" : "4c5e07de-a3eb-4d8d-98ef-3f343ff22429", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259c2" }
> { "_id" : "522834173250770ffb6259c3", "product_ref_id" : "ee2b6f93-f953-4e9c-98d4-ab7859a40246", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259c4" }
> { "_id" : "522834173250770ffb6259c5", "product_ref_id" : "2075f772-c473-4864-a9f6-5433d3c21b53", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259c6" }
> { "_id" : "522834173250770ffb6259c7", "product_ref_id" : "40e8d455-8150-4111-b4c8-14fc0e81be0c", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259c8" }
> { "_id" : "522834173250770ffb6259c9", "product_ref_id" : "291e513e-5e48-4a77-b7f1-66783f3d83f7", "product_id" : "522834173250770ffb6259ca", "ecosystem_type" : "UNKNOWN" }
> { "_id" : "522834173250770ffb6259cb", "product_ref_id" : "f0631669-db6f-403f-af20-04d2609ce4d0", "ecosystem_type" : "ANDROID", "product_id" : "522834173250770ffb6259cc" }
> { "_id" : "522834173250770ffb6259cd", "product_ref_id" : "0e73c62a-ab9f-4f8b-b4ec-c59b8f6f0a7a", "ecosystem_type" : "UNKNOWN", "product_id" : "522834173250770ffb6259ce" }

Pls do let me know if you need more details

**Comment by mevivs** [comment]
So, you are persisting Products and DeviceEcoSystem associatios alongwith ProuctEcosystemMap?

IF yes.

Modify 

```
@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "ecosystem_type", referencedColumnName = "ecosystem_type")
private DeviceEcosystem ecosystem;

@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "product_id", referencedColumnName = "product_id")
private Product product;
```

With

```
@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.ALL)
@JoinColumn(name = "ecosystem_type", referencedColumnName = "ecosystem_type")
private DeviceEcosystem ecosystem;

@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
@JoinColumn(name = "product_id", referencedColumnName = "product_id")
private Product product;
```

See, if it works for you.

-Vivek

**Comment by mevivs** [comment]
Also, There have been few fixes around this in latest 2.7 release. I would suggest to verify it with 2.7, in case working with older releases.

-Vivek

**Comment by vsreekar** [comment]
Hello Vivek,

Data in Product and DeviceEcosystem is already persisted. I'm fetching the data from the other 2 tables and using them to add data in to this ProductEcosystemMap.

Before call to entityManager.persist() id of the product is different and after call to persist id of the product is different.

Also, after I added cascade = CascadeType.All it is inserting new values with the new id's generated. This is not at all intended for.

Pls help me with this. Do let me know if you need any other information

Thanks!
- Sreekar

**Comment by vsreekar** [comment]
I shall verify with 2.7 and will let you know.

Thanks!
- Sreekar

**Comment by vsreekar** [comment]
Vivek,

Tried with 2.7 too. Same response.

Thanks!
- Sreekar

**Comment by mevivs** [comment]
I think it's related to https://github.com/impetus-opensource/Kundera/issues/363

Let me verify and post an update on this.

-Vivek

**Comment by vsreekar** [comment]
Vivek,

Following is summary my findings with the list of issues I have faced.
1. If a Filed of an entity is a custom object and has enum - Mongo DB throws cannot serialize that object exception
2. If an entity has nested objects defined as fields (similar to above point) - Mongo DB throws cannot serialize nested object exception. I faced this issue when i tried using an embedded composite key for ProductEcosystemMap. I had made a embedded bean with Product & DeviceEcosystem and I was not able to insert data into table. (Sorry I cannot provide trace for this)
3. The first issue that I reported about Id of the object specified in the entity being changed by default by Kundera

I'm not sure if I have done something wrong here. Pls do help me if I've done something wrong

Also just to mention, I have solved all the above mentioned issues in the following way (listed in the same order mentioned in the above section)
1. Changed enum field to string
2. Removed composite key and created a manual unique index on the fields required.
3. Removed @JoinColumn for all the fields and made them plain strings. I'm converting the obtained strings to respective objects by interacting with DB again.

**Comment by mevivs** [comment]
```
If a Filed of an entity is a custom object and has enum - Mongo DB throws cannot serialize that object exception
```

You mean enum within an embeddable entity? I will verify this, however enums are supported(without ordinal)

```
If an entity has nested objects defined as fields (similar to above point) - Mongo DB throws cannot serialize nested object exception. I faced this issue when i tried using an embedded composite key for ProductEcosystemMap. I had made a embedded bean with Product & DeviceEcosystem and I was not able to insert data into table. (Sorry I cannot provide trace for this)
```

Need to verify, but composite keys are supported for MongoDB. Here is the link for junits.
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/compositeType

```
The first issue that I reported about Id of the object specified in the entity being changed by default by Kundera
```

It's an issue with auto generation(issue #363) in mongodb. We are working on it.

-Vivek

**Comment by mevivs** [comment]
Just to add on point 3. IT should work fine if you relax with @GeneratedValue.Soon will post an update on this with fix.

-Vivek

**Comment by mevivs** [comment]
Could you please share @Info embeddable entity definition?

-Vivek

**Comment by vsreekar** [comment]
Thank you for the other updates.
Below is the code snippet for Info

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import org.apache.log4j.Logger;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.json.JSONException;
import org.json.JSONObject;

@Embeddable
@JsonIgnoreProperties(value = { "json" })
public class Info {

```
private static final Logger LOGGER = Logger.getLogger(Info.class);

/**
 * Actual column which stores the JSON string as configuration
 */
@Column(name = "info")
private String info;

/**
 * Column value converted to a JSON object
 */
@Transient
private JSONObject json;
```

}

**Comment by mevivs** [comment]
Thanks. But i can't find an enum object within Info entity!

-Vivek

**Comment by vsreekar** [comment]
Hello Vivek,

Enum was a field in DeviceEcosystem entity. As informed I have changed same to string now. 

Pls do let me know if you need any other details.

Thanks!
- Sreekar

**Comment by mevivs** [comment]
Hi,
Can you please provide composite key definitions ProductEcosystemMap for:

```
If an entity has nested objects defined as fields (similar to above point) - Mongo DB throws cannot serialize nested object exception. I faced this issue when i tried using an embedded composite key for ProductEcosystemMap. I had made a embedded bean with Product & DeviceEcosystem and I was not able to insert data into table. (Sorry I cannot provide trace for this)
```

How different it is from https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/compositeType ?

-Vivek

**Comment by vsreekar** [comment]
Vivek,

Difference with my compound key is it doesn't have basic java types (like String and entity) as members but it has one more entity, with @JoinColumn, as member.

In this case, it is trying to insert the member entity also into table and it fails. I found this jira similar to my issue https://jira.mongodb.org/browse/HADOOP-42

Hope this explains. If not I shall provide you sample implementation for the same.

Thanks!
- Sreekar

**Comment by mevivs** [comment]
```
Incorrect value of product_id and device ecosystem mapping
```

This has been resolved in current trunk. Please validate.

For error such as

```
   "Mongo DB throws cannot serialize that object exception". 
```

This happens if MongoDB is not able to serialize/deserialize any custom object( or unsupported data types).  Kundera does provide object mapping for all data types, but for objects such JSONObject it would simply rely on underlying database(in this case MongoDB). 

Composite key/Compound key are supported for basic data types in Kundera, rest it will rely on database for object's serialization/deserilization.

I am attaching a project for your reference(created using entities shared by you), here is the link:

https://www.dropbox.com/s/7l54jp1bdtch8tw/Examples.zip

Hope it helps.

-Vivek

**Comment by mevivs** [comment]
Any update? Got chance to verify it with latest trunk?

-Vivek

**Comment by vsreekar** [comment]
Hello Vivek,

I shall verify today and will update you on the same. I have never worked with git till now, so I assume I will take sometime. Thanks for understanding.

Thanks!
- Sreekar

**Comment by vsreekar** [comment]
Hello Vivek,

"Incorrect value of product_id and device ecosystem mapping"
This is functioning fine now.

Thanks!
- Sreekar

**Comment by mevivs** [comment]
I think we are good to close on this?

Support for enum,composite key and possible mongodb data type is already supported in Kundera. Serialization/DeSerialization errors on server side are because of unsupported mongodb data types.

-Vivek

**Comment by vsreekar** [comment]
Yes we are good to close this.

Yes, I understand the other constraints and as informed earlier I found a way around for the same.

Thanks!
- Sreekar
