### ISSUE TITLE
Kundera 2.8 feature wishlist

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#373]
Format should in line with:

DB Name: Cassandra, HBase,Mongo etc.

DB Version:

Feature Description:

Specific reason(if any):

**Comment by ttuti** [comment]
Support for kundera JavaConfig in SpringMVC for the persistence unit

**Comment by jfgosselin** [comment]
Decoupled persistence unit name from entity (e.g @Table(name = "Games", schema = "CS@cassandra_pu")) to support multiple persistence units.

Issue discussed here :
https://groups.google.com/forum/#!searchin/kundera-discuss/Entity$20persistence$20unit/kundera-discuss/FCrYXqVcEL0/rOshNBK5luUJ

Thanks

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/issues/315

Work in progress.
