### ISSUE TITLE
connection pooling using cp30 in kundera

### ISSUE THREAD

**Issue by sbheda** [Impetus/kundera#374]
Hi,

How can I implement connection pooling using cp30 in kundera.

**Comment by mevivs** [comment]
Kundera relies on Hibernate for RDBMS. if you configure c3P0 as hibernate properties either in persistence.xml or as external property configurations, it should work for you.

-Vivek

**Comment by sbheda** [comment]
Thank you  for quick replay,
Can you provide  persistence.xml source code for c3P0 configuration ?

**Comment by mevivs** [comment]
If you properties as:

```
  <property name="hibernate.c3p0.min_size">5</property>
  <property name="hibernate.c3p0.max_size">20</property>
  <property name="hibernate.c3p0.timeout">300</property>
  <property name="hibernate.c3p0.max_statements">50</property>
  <property name="hibernate.c3p0.idle_test_period">3000</property>
```

in persistence.xml under configured persistence unit, it should work.

-Vivek

**Comment by sbheda** [comment]
Hi Vivek,

Thank you very much.
I tried this configuration but its not working. Every time new connection object is created. 
Persistance.xml is below :

<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" version="2.0">
<persistence-unit name="mysqlUnit" transaction-type="RESOURCE_LOCAL">
<provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.Person</class>  
    <class>com.Address</class>  
    <properties>
     <property name="kundera.client.lookup.class" value="com.impetus.client.rdbms.RDBMSClientFactory"/>
     <property name="hibernate.format_sql" value="true"/>
     <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect"/>

```
 <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/hibernateDB"/> 
 <property name="hibernate.connection.username" value="root"/>
 <property name="hibernate.connection.password" value="root"/> 

 <property name="hibernate.c3p0.min_size" value="5"/>
 <property name="hibernate.c3p0.max_size" value="100"/>
 <property name="hibernate.c3p0.timeout" value="300"/>
 <property name="hibernate.c3p0.max_statements" value="50"/>
 <property name="hibernate.c3p0.idle_test_period" value="3000"/> -->
 <property name="hibernate.hbm2ddl.auto" value="update"/>
 <property name="current_session_context_class" value="thread"/>

</properties>   
```

</persistence-unit>
</persistence>

**Comment by kkmishra** [comment]
Hi,
This is what I have tried.

Verified initial number of open threads in mysql:

```
mysql> show status like 'Threads_connected';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| Threads_connected | 1     |
+-------------------+-------+
1 row in set (0.00 sec)
```

2) After configuring persistence.xml with:

```
                        <property name="hibernate.c3p0.min_size" value="10" />
            <property name="hibernate.c3p0.max_size" value="100" />
            <property name="hibernate.c3p0.timeout" value="300" />
            <property name="hibernate.c3p0.max_statements" value="50" />
            <property name="hibernate.c3p0.idle_test_period" value="3000" />
            <property name="hibernate.hbm2ddl.auto" value="update" />
            <property name="current_session_context_class" value="thread" />
```

3) Upon establishing a connection with database with above mentioned configurations as 

```
Persistence.createEntityManagerFactory("pu");

```

4) Verified number of open connection as:

```
mysql> show status like 'Threads_connected';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| Threads_connected | 11    |
+-------------------+-------+
1 row in set (0.00 sec)
```

It seems to me working fine. A new pool initialization will only happen in case of new entity manager factory only . If you enable logs for "INFO", you should be able to trace logs on c3p0 connection pool creation.

Please let me know, if anything else needs you verified or want us to verify.

Thanks
Kuldeep

**Comment by mevivs** [comment]
Are we good to close on this?
