### ISSUE TITLE
Apache Cassandra 1.2.8, Kundera 2.6 NoSuchMethodError:org.apache.cassandra.thrift.TBinaryProtocol

### ISSUE THREAD

**Issue by ttuti** [Impetus/kundera#375]
I keep getting the error:

   Getting the error NoSuchMethodError:org.apache.cassandra.thrift.TBinaryProtocol

I have detailed my project and the error in this page:

http://stackoverflow.com/questions/18638491/getting-the-error-nosuchmethoderror-org-apache-cassandra-thrift-tbinaryprotocol

What would be the problem?

**Comment by mevivs** [comment]
Kundera cassandra libraries are running on 1.2.4 version. Ideally 1.2.8 or higher versions should always be backward compatible, but in this case unfortunately they are not!

Cassandra version upgrade is planned and i will post an update on this.

-Vivek
