### ISSUE TITLE
CQL

### ISSUE THREAD

**Issue by kcarlson** [Impetus/kundera#38]
I have created a new branch with the intent of implementing native queries in kundera. 

My goal is to enable CQL queries against cassandra as I am not sure if "native" queries are possible against the other data stores.

Right now they "work" but have not been extensively tested.

Has anyone else thought of implementing this? Suggestions?

https://github.com/kcarlson/Kundera/tree/CQL

**Comment by xamry** [comment]
EntityManagerImpl.createNativeQuery() is something we thought would be best suited for supporting native queries...(CQL for cassandra, MongoDBQuery for Mongo and maybe Hive for HBase)...

**Comment by kcarlson** [comment]
That's exactly what I did for Cassandra. EntityManagerImpl.createNativeQuery() creates a CassNativeQuery object.

**Comment by mevivs** [comment]
Nice start!
Just had a quick look. 2 thoughts:
1) No other client and query interface(class) should be required.
2) Even if creating CassNativeQuery, then it should extend CassQuery object.

Considering Kundera is meant for dealing with multiple Database along-with cross data store persistence. This will not work. 

I will have a deeper look into this.  

Have a look at cross data persistence example in Kundera-Examples to get a better understanding of this.  Thanks again for this initiative 

Cheers,
Vivek

**Comment by mevivs** [comment]
Support for native, named query along with so many other JPA features will be part of 2.0.6 release. 

-Vivek

**Comment by kcarlson** [comment]
Ok. Thanks for the feedback!

So will CQL be implemented in 2.0.6?

**Comment by mevivs** [comment]
Yes. Please go ahead with your changes for CQL implementation. As it will surly help us to ease in implementation and integration within framework.

Thanks,
Vivek

**Comment by mevivs** [comment]
Hi,
I have uploaded checkstyle file which we are using to make it in sync. location:

https://github.com/downloads/impetus-opensource/Kundera/cassandra_code_style.xml

-Vivek

**Comment by kcarlson** [comment]
Will do!

**Comment by farukkazmi** [comment]
Hi Vivek,
   Any idea when 2.0.6 will be released. Will it include Kristoffer's uuid fix too.

**Comment by mevivs** [comment]
We are working on date. Currently Kristoffer's changes are under review and once he is done with changes, i will immediatly incorporate them. But yes, uuid fix will be there.

**Comment by farukkazmi** [comment]
Thanks

**Comment by mevivs** [comment]
I have added CQL support with commit: c2858de2392f9983bab59614dbaa1642fdaebf3c

**Comment by kcarlson** [comment]
nice

**Comment by mevivs** [comment]
Please test your scenarios. Though i have added a test case at:

https://github.com/impetus-opensource/Kundera/commit/c2858de2392f9983bab59614dbaa1642fdaebf3c#diff-5

**Comment by farukkazmi** [comment]
Looks good Vivek

**Comment by mevivs** [comment]
suuport added.
