### ISSUE TITLE
Cache implementation in RDBMS

### ISSUE THREAD

**Issue by sbheda** [Impetus/kundera#389]
Hi ,
  How to implement cache in RDBMS using kundera.

**Comment by mevivs** [comment]
You mean configuring ehcache?

-Vivek

**Comment by sbheda** [comment]
Thanks for quick replay.
Yes, I want to configure ehcache of hibernate or jpa.

**Comment by mevivs** [comment]
This is supported with 2.10 and now it is also possible to plugin other cache frameworks with Kundera as well.

-Vivek
