### ISSUE TITLE
Kundera + JBoss AS7

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#390]
Hi!

Seems like Kundera doesn't work well with JBoss:

https://gist.github.com/bsideup/40f7e22ec6ae0ecc6d7c

**Comment by mevivs** [comment]
Hi,
There have been multiple discussions around this, you may refer:
https://github.com/impetus-opensource/Kundera/issues/180

It should work with JBoss 5,6 and 7.1.1

-Vivek

**Comment by bsideup** [comment]
in #180 there was problem with locating persistence.xml, but my problem is in the "WEB-INF/classes" folder. 

And yes, setting "jboss.as.jpa.managed" to "true" doesn't fix it :(

Thanks!

**Comment by mevivs** [comment]
version of jboss?
packaging structure of war?

-Vivek

**Comment by mevivs** [comment]
jboss.as.jpa.managed as false   not "true"!

**Comment by bsideup** [comment]
Oops. Yes, it is "false". 

JBoss AS 7.1.1.Final "Brontes"

i will try to package simple project with this issue to reproduce today

**Comment by mevivs** [comment]
Have a look at:
https://github.com/impetus-opensource/Kundera/tree/kundera-structure/container/jboss/data-keeper

It's a sample app deployable over JBoss 7.1.1 final

-Vivek

**Comment by bsideup** [comment]
``` bash
git clone https://github.com/bsideup/KunderaJBossIssue.git
cd KunderaJBossIssue/modules/app/
mvn clean package jboss-as:run
```

https://gist.github.com/bsideup/b2dde7bf3cfc6d72c5c1

what am i doing wrong?

**Comment by mevivs** [comment]
Nothing i can conclude from this log. Not sure if you can do a manual deploy, if it works.

-Vivek

**Comment by bsideup** [comment]
Manual deploy to JBoss instance returns the same log.

How did you run your application?

**Comment by mevivs** [comment]
KK,
Can you please provide more inputs on this?

-Vivek

**Comment by mevivs** [comment]
It seems netty.jar is giving some issues.

https://community.jboss.org/thread/197426?start=0&tstart=0

**Comment by bsideup** [comment]
Yes, but i changed nothing in this project, only transferred it to my own repo, so it should work well, isn't it?

**Comment by kkmishra** [comment]
Just modified pom.xml to exclude netty.jar, try now, it should work fine for you.

Thanks
KK

**Comment by mevivs** [comment]
Just to give you a brief about this project.

It's a polyglot application built to deal with multiple datastores(e.g. Cassandra and MongoDB). However you may modify it for single database by modifying:
1) appContext.xml
2) Entity definitions.

HTH.

-Vivek

**Comment by bsideup** [comment]
Ok, netty exclusion works. Moving forward to make it looks like our project and break it:)

**Comment by bsideup** [comment]
Woohoo! 

``` xml
<exclude-unlisted-classes>true</exclude-unlisted-classes>
```

this parameter fixed issue in our project.

**Comment by mevivs** [comment]
Cool. Are we good to close on this?

-Vivek

**Comment by bsideup** [comment]
Partially :)

Am i right that there is no chance not to specify each entity class in persistence.xml?

**Comment by pires** [comment]
+1 for not having to specify every class in _persistence.xml_.
