### ISSUE TITLE
Decouple and remove hibernate dependency from kundera-core

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#392]
With current implementation, kundera-core relies on hibernate for proxy instance validation over RDBMS entities. This needs to be decoupled and move from kundera-core to kundera-rdbms.

-Vivek

**Comment by bsideup** [comment]
Yeah, it makes sense and will decrease size of final binary. Good enhancement!

**Comment by pires** [comment]
+1

**Comment by mevivs** [comment]
It's already decoupled with 2.7.1. kundera-core no more requires on hibernate.

-Vivek
