### ISSUE TITLE
Retry service doesn't retry on a cassandra node after restart

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#394]
While running in cluster, things works fine with Kundera. However, if a node eligible for retry goes down, but upon restart it didn't join retry host pool. Only workaround is either hot deploy of application or creating new factory instance.

CassandraRetryService should consider such nodes for scheduling later.

**Comment by mevivs** [comment]
@zhouhero
Thanks for contributing on this defect.

-Vivek

**Comment by pires** [comment]
+1

**Comment by mevivs** [comment]
Fixed and released with 2.7.1

-Vivek
