### ISSUE TITLE
com.impetus.client.cassandra.CassandraClientBase.populateClientProperties  not called ?

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#397]
I'm using Kundera with org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean .

I'm able to set the cql.version as a JPA properties but I can't pass the consistency.level.

Looking at com.impetus.client.cassandra.CassandraClientBase it seems that 
the method is never called.

**Comment by mevivs** [comment]
ConsistencyLevel is something needs to be set per read/write request:

You can set it with client as:

```
        Map<String, Client> clientMap = (Map<String, Client>) em.getDelegate();
        ThriftClient tc = (ThriftClient) clientMap.get("cassandra");  // "cassandra" is persistence unit name.
        tc.setConsistencyLevel(ConsistencyLevel.QUORUM); 
```
