### ISSUE TITLE
setting Time to Live using Kundera

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#399]
Hi,
in cassandra we can using cql 
 UPDATE commands support setting a column expiration time (TTL). In the update  we set the column to expire at x seconds...
Can we set time to live for any column in any update using kundera?

**Comment by impetus-opensource-admin** [comment]
Please refer:
https://github.com/impetus-opensource/Kundera/issues/265

**Comment by Gargee** [comment]
thanks
