### ISSUE TITLE
 org.jboss.security.acl.ACLImpl must have a default no-argument constructor

### ISSUE THREAD

**Issue by chonton** [Impetus/kundera#40]
I am getting the following when running KunderaExample:

10:11:57.166 [main] INFO  c.impetus.kundera.KunderaPersistence - Loading Core
10:11:57.217 [main] INFO  c.impetus.kundera.loader.CoreLoader - Loading factories ... 
10:11:57.752 [main] INFO  o.hibernate.cfg.annotations.Version - Hibernate Annotations 3.4.0.GA
10:11:58.035 [main] INFO  org.hibernate.cfg.Environment - Hibernate 3.3.0.SP1
10:11:58.051 [main] INFO  org.hibernate.cfg.Environment - hibernate.properties not found
10:11:58.088 [main] INFO  org.hibernate.cfg.Environment - Bytecode provider name : javassist
10:11:58.126 [main] INFO  org.hibernate.cfg.Environment - using JDK 1.4 java.sql.Timestamp handling
10:11:58.815 [main] INFO  o.h.annotations.common.Version - Hibernate Commons Annotations 3.1.0.GA
10:11:58.866 [main] INFO  org.hibernate.ejb.Version - Hibernate EntityManager 3.4.0.GA
10:11:59.045 [main] DEBUG org.hibernate.ejb.Ejb3Configuration - Look up for persistence unit: cassandra_pu
10:12:00.557 [main] DEBUG org.hibernate.util.DTDEntityResolver - trying to resolve system-id [http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd]
10:12:00.943 [main] INFO  c.impetus.kundera.KunderaPersistence - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s) cassandra_pu
10:12:00.945 [main] DEBUG c.i.kundera.loader.ApplicationLoader - Loading User Application...
10:12:00.990 [main] DEBUG c.i.k.loader.PersistenceUnitLoader - Loading Metadata from persistence.xml...
10:12:01.056 [main] INFO  c.i.k.loader.PersistenceUnitLoader - Looking up for persistence unit: cassandra_pu
10:12:01.180 [main] DEBUG c.i.k.loader.PersistenceXMLLoader - Persistent Unit name from persistence.xml: cassandra_pu
10:12:01.181 [main] DEBUG c.i.kundera.loader.MetamodelLoader - Loading Entity Metadata...
10:12:01.182 [main] INFO  c.i.kundera.loader.MetamodelLoader - No class to scan for persistence unit cassandra_pu. Entities will be loaded from classpath/ context-path
10:12:01.499 [main] DEBUG c.i.kundera.loader.MetamodelLoader - Metadata not found in cache for User
10:12:01.566 [main] DEBUG c.i.k.m.v.EntityValidatorImpl - Validating User
10:12:01.597 [main] DEBUG c.i.kundera.metadata.MetadataBuilder - Processing @Entity >> class User
10:12:01.597 [main] DEBUG c.i.k.m.processor.TableProcessor - Processing @Entity(User) for Persistence Object.
10:12:01.602 [main] DEBUG c.i.k.m.processor.TableProcessor - userId => Id
10:12:01.713 [main] DEBUG c.i.k.m.processor.IndexProcessor - Processing @Entity User for Indexes.
10:12:03.395 [main] DEBUG c.i.kundera.loader.MetamodelLoader - Metadata not found in cache for org.jboss.security.acl.ACLImpl
Exception in thread "main" 10:12:03.395 [main] DEBUG c.i.k.m.v.EntityValidatorImpl - Validating org.jboss.security.acl.ACLImpl
javax.persistence.PersistenceException: org.jboss.security.acl.ACLImpl must have a default no-argument constructor.
    at com.impetus.kundera.metadata.validator.EntityValidatorImpl.validate(EntityValidatorImpl.java:77)
    at com.impetus.kundera.metadata.MetadataBuilder.validate(MetadataBuilder.java:84)
    at com.impetus.kundera.metadata.MetadataBuilder.buildEntityMetadata(MetadataBuilder.java:102)
    at com.impetus.kundera.loader.MetamodelLoader.scanClassAndPutMetadata(MetamodelLoader.java:213)
    at com.impetus.kundera.loader.MetamodelLoader.loadEntityMetadata(MetamodelLoader.java:154)
    at com.impetus.kundera.loader.MetamodelLoader.load(MetamodelLoader.java:69)
    at com.impetus.kundera.loader.ApplicationLoader.load(ApplicationLoader.java:43)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:95)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:72)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:83)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:60)
    at KunderaExample.main(KunderaExample.java:15)

**Comment by mevivs** [comment]
Looks like 

org.jboss.security.acl.ACLImpl is annotated with @Entity. But default constructor is missing from it.

-Vivek

**Comment by chonton** [comment]
It has a package scope constructor.

**Comment by mevivs** [comment]
Please try with public default constructor.

**Comment by chonton** [comment]
This class is not under my control. It comes from a jboss jar. Consider logging a warning message and continuing. 

Is there a better way to limit the extent of classes considered?  I believe the jpa spec suggests or requires that only classes from the same jar that the persistence.xml came from should be considered. 

This requirement is somewhat tricky to implement. You'll need to getResources("/META-INF/persistence.xml"). Then for each URL find the jar or folder that contains the class file.  Now, the super tricky part, determine if the class should be collected without loading the class. (You don't want to fire off any static initialization that the class might do.)

Chas

**Comment by chonton** [comment]
I have some classes that does this sort of process for an IOC testing framework. Interested?

**Comment by mevivs** [comment]
Please share. I will have look. Custom class loading issue raised earlier is somewhat related to this?
-Vivek

**Comment by mevivs** [comment]
Currently kundera scan classpath to load such entities. Having relative path in persistence.xml as per jpa spec is definitlly require. You are right! Once kundera start supporting mapping files(orm.xml) other ways will also be possible

**Comment by mevivs** [comment]
Hi,
Wondering, if you are going to share something on this? This will be released with 2.0.6

-Vivek

**Comment by chonton** [comment]
Vivek,

I'll be working on this next weekend.

regards,
chas

**Comment by mevivs** [comment]
Hi,
I have worked on this issue. Could you please try if this is occuring now on latest branch? (2.0.6)

-Vivek

**Comment by mevivs** [comment]
Verified and Test case added in kundera-core, hence closing it.

-Vivek
