### ISSUE TITLE
persistence.xml is hardcoded in kundera loader, not allowing for different config files

### ISSUE THREAD

**Issue by dentinger** [Impetus/kundera#400]
The "persistence.xml" is hardcoded in the config loading process of kundera and does not allow for a user provided persistence file name (i.e.  like org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean).  This is presenting several limitations.  1) I am not able to have different persistence.xmls for different parts of my build.  (i.e.  One that specifies a localhost cassandra persistence unit for unit testing "unit-persistence.xml",  one that specifies a development environment for integration/functional tests "integration-persistence.xml")  and 2)  this limits kundera from being packaged in an app in such a way that it can nicely live/play with and be separate from other persistence unit configurations.

**Comment by mevivs** [comment]
Could you please share a sample app to test and implement this ?

-Vivek

**Comment by mevivs** [comment]
With 2.10 release , it is possible to provide external persistence.xml file path as well.
