### ISSUE TITLE
Using @PersistenceContext

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#401]
Analyze, if we need to enable @PersistenceContext to provide client level properties such as Consistency Level or any other properties etc.

Issues to refer:
https://github.com/impetus-opensource/Kundera/issues/331

**Comment by pires** [comment]
+1

**Comment by chhavigangwal** [comment]
I tried with 

```
 @PersistenceContext(unitName = "cassandra-pu,mongo-pu",type = 
PersistenceContextType.EXTENDED, properties = {
             @PersistenceProperty(name = "consistency.level", 
value="QUORUM"),
             @PersistenceProperty(name = CassandraConstants.CQL_VERSION, 
value=CassandraConstants.CQL_VERSION_3_0)
```

it is working fine for me.

**Comment by dtuzikov** [comment]
You can write any value for "consistency.level" property

``` java
@PersistenceProperty(name = "consistency.level", value="AnyValueHere !!!"
```

doesn't matter, because it will be ignored in CassandraClientProperties.populateClientProperties method due to value type check.

``` java
if (key.equals(CONSISTENCY_LEVEL) && value instanceof ConsistencyLevel) {
      cassandraClientBase.setConsistencyLevel((ConsistencyLevel) value);
}
```

The same issue is true for some other properties like "ttl.per.session" and "ttl.per.request".
