### ISSUE TITLE
Missing space between statements in CassandraClientBase.executeBatch()

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#410]
Line 1408 :                    batchQueryBuilder.append(query);

Should be : batchQueryBuilder.append(" " + query);

**Comment by mevivs** [comment]
Is this happening in case of  "USING TTL " ?

-Vivek

**Comment by mevivs** [comment]
:+1:  for change. A junit needs to be added for the same as well.

-Vivek

**Comment by chhavigangwal** [comment]
Can you please share the exact scenario ?

Could not reproduce the issue.

A junit added for the same :
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/client/crud/batch/CQL3BatchProcessorTest.java

**Comment by jfgosselin** [comment]
If I remember it was a query with blob at the end.
