### ISSUE TITLE
How can we set the Limit in a select statment

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#412]
Is there any way we can set the limit on the number of records that are fetched on a select statement?
in the logs i see that the limit is defaulted to 100.  How can I change this limit?

LOGS:-
2013-09-30 09:52:41,512 [INFO ] [main] com.impetus.client.cassandra.CassandraClientBase  - Executing query SELECT \* FROM "Moderator" LIMIT 100.

**Comment by mevivs** [comment]
query.setMaxResults(); should work for you.

-Vivek

**Comment by Gargee** [comment]
Thanks this works!
