### ISSUE TITLE
Kundera doesn't return all list of entity

### ISSUE THREAD

**Issue by NotItemName** [Impetus/kundera#413]
In method <b>populateRelation</b> of the class <b>CassandraEntityReader</b> was hardcode maxResult 100, when CQL query doesn't have where clause.

**Comment by mevivs** [comment]
I guess, You can always override that by query.setMaxResults() { with or without where clause}.

I see your point here. It is happening in case of associated entities. Will get it fixed.

-Vivek

**Comment by bsideup** [comment]
AFAIK Cassandra also had it own limit by 10.000 records per request.
