### ISSUE TITLE
Cassandra map<text, blob> ClassCastException: java.nio.HeapByteBuffer cannot be cast to [B

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#420]
When I read the data from a Cassandra CQL map<text, blob> , I get a ClassCastException.
I can persist the entity and read the entity but if I access the map e.g. :

```
 System.out.println(new String(f.getDataMap().get("my key")));
```

I get a ClassCastException: java.nio.HeapByteBuffer cannot be cast to [B/

It seems that the map is copied as a Map<String, HeapByteBuffer> instead of Map<String, byte[]>

Entity:

```
 @Entity
 @Table(name = "foo_table", schema = "kunderatest@cassandra_storage_pu")
 public class {

   @Id
   private String id;

   @Column(name = "dm")
   private Map<String, byte[]> dataMap;

  }
```

Schema :

```
 CREATE TABLE foo_table (
   id text,
   dm map<text, blob>,
   PRIMARY KEY (id)
 )  
```

**Comment by mevivs** [comment]
Fixed on current trunk. Releasing with 2.8

-Vivek
