### ISSUE TITLE
MongoDB Kundera Query not returning appropriate Data 

### ISSUE THREAD

**Issue by ashishkshukla** [Impetus/kundera#424]
Hi,
I was trying to interact with mongodb using Kundera.
My Entity class is like below:-
@Table(name = "accounts", schema = "idbench@mongodb_pu")
public class IdbenchAccounts {
@Id 
@Column(name="_id")
private ObjectId _id;
@Column(name ="a")
private int a;
@Column(name ="b")
private int  b;
//Getters and Setters
}

and I am trying to execute the following Query:-
Query qu = em.createQuery("select p from IdbenchAccounts p");

If I am running the code I am getting  the following Exception :-

com.impetus.kundera.query.QueryHandlerException: javax.persistence.PersistenceException: com.impetus.kundera.property.PropertyAccessException: java.lang.NumberFormatException: For input string: "89.0"
    at com.impetus.client.mongodb.query.MongoDBQuery.populateEntities(MongoDBQuery.java:139)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:150)
    at code.KunderaExample.main(KunderaExample.java:26)
Caused by: javax.persistence.PersistenceException: com.impetus.kundera.property.PropertyAccessException: java.lang.NumberFormatException: For input string: "89.0"
   at com.impetus.client.mongodb.DocumentObjectMapper.setFieldValue(DocumentObjectMapper.java:222)

As you can see in the entity definition class , I have declared columns type of a and b as int. because if I execute  "db.accounts.find()" command through mongoshell ,  i can see the output as below : 

{ "_id" : ObjectId("52552c2a7e2632bf44fa6d5f"), "a" : 5, "b" : 89 }
{ "_id" : ObjectId("52552c347e2632bf44fa6d60"), "a" : 5, "b" : 65 }
{ "_id" : ObjectId("52552c357e2632bf44fa6d61"), "a" : 5, "b" : 65 }
{ "_id" : ObjectId("52552c437e2632bf44fa6d62"), "a" : 8, "b" : 5 }

we can see a and b are integer type .
I am not getting why the code is throwing the above exception  .

But when I am replacing the "int" to "float" in the entity definition class , the code is working means not throwing any exception.But it is returning values of a and b as 5.0 and 89.0 respectively. 
I am not getting why it is replacing integer value to float. when i use find command through mongo shell i can see integer value like "5" not "5.0" n using kundera query it is returning "5.0" not "5".
Kindly Look into this .

Thanks,
Ashish

**Comment by chhavigangwal** [comment]
By default mongo shell treats all numbers as floating point values. Please refer  http://docs.mongodb.org/manual/core/shell-types/#numberlong.

In order to access number data inserted via mongo shell using Kundera :
- It is recommended to use Double/Float data type.
- In case you still want to keep the data type of field as int then while inserting the values via mongo shell you should type cast it using "numberint" (http://docs.mongodb.org/manual/core/shell-types/#numberint)  to override its default behavior.
