### ISSUE TITLE
MongoDB-Specific-Features page

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#425]
https://github.com/impetus-opensource/Kundera/wiki/MongoDB-Specific-Features

this page totally should have link to https://github.com/impetus-opensource/Kundera/blob/9f7cd186965704d50c01f9c84fc166ff295d9fd5/src/kundera-mongo/src/main/java/com/impetus/client/mongodb/MongoDBConstants.java

it covers many of important aspects of MongoDB configuration with Kundera, for example, "connection.perhost" option.

Thanks!

**Comment by chhavigangwal** [comment]
Added.
