### ISSUE TITLE
I write a likely tool which is named SZLorm by myself

### ISSUE THREAD

**Issue by szlwin** [Impetus/kundera#427]
I'm from China and I write a likely tool which is named SZLorm by myself.

I want to talk it with you,and I hope you interesting in it.(My english is not god)

It's now support the database:
-MySQL
-Oracle
-HBase (base on phoenix)
-Redis (only suport map now)

It's can do:
1.You can commit one data to multity data source as use a service (support the transaction,if the data base is support)

2.You can once get many data from multity data source as use a service

3.You need't know the driver detail with the data source.

4.It's can be moved to another project easy.

5.You need't write any code,only need to config some file.

6.It has the strong chech function,you can do it as only write an express string like:
userId != 0 and userT.id != 0 and ( productCount > 0 or totalPrice >= 0 ) or ( productCount*(totalPrice+10) > 200 )

It's not limit to NoSQL,it's target to all data source:
1.SQL
2.NoSQL
3.HTTP
4.SOAP
5.systems
6.other

I define the data source is: It's can be read and update the data.

It's struct can be expanded to support  the multity data source(in future),and I also want it can be an platform,not only a tool.

I copy the some config xml file,you can see it,it may be long:
1.orm-con-config.xml
<?xml version="1.0" encoding="utf-8"?>
<orm-connection-info>
           <orm-dataSource-config>
        <orm-dataSource name="MySQL" type="sql" >
            <dataSource>com.orm.sql.connection.datasource.DBDataSource</dataSource>
        </orm-dataSource>
        <orm-dataSource name="Oracle" type="sql" >
            <dataSource>com.orm.sql.connection.datasource.DBDataSource</dataSource>
        </orm-dataSource>

```
    <orm-dataSource name="HBase" type="sql" >
        <dataSource>com.orm.sql.connection.datasource.DBDataSource</dataSource>
    </orm-dataSource>

    <orm-dataSource name="Redis" type="noSql" >
        <dataSource>com.orm.sql.connection.datasource.JredisDataSource</dataSource>
    </orm-dataSource>       
</orm-dataSource-config>


<orm-connection-config>
    <orm-connection name="MySQL" type="sql">
        <connection>com.orm.sql.connection.DataBaseConnection</connection>
        <convert>com.orm.sql.mysql.convert.container.MySQLConvertContainer</convert>
        <executer>com.orm.sql.mysql.execute.container.MySQLExecuteContainer</executer>
        <data-convert>com.orm.sql.datatype.convert.mysql.MySQLDataTypeConvert</data-convert>
    </orm-connection>

    <orm-connection name="Oracle" type="sql">
        <connection>com.orm.sql.connection.DataBaseConnection</connection>
        <convert>com.orm.sql.oracle.convert.container.OracleConvertContainer</convert>
        <executer>com.orm.sql.oracle.execute.container.OracleExecuteContainer</executer>
        <data-convert>com.orm.sql.datatype.convert.oracle.OracleDataTypeConvert</data-convert>
    </orm-connection>

    <orm-connection name="HBase" type="sql">
        <connection>com.orm.sql.connection.DataBaseConnection</connection>
        <convert>com.orm.sql.hbase.convert.container.HBaseConvertContainer</convert>
        <executer>com.orm.sql.hbase.execute.container.HBaseExecuteContainer</executer>
        <data-convert>com.orm.sql.datatype.convert.hbase.HbaseDataTypeConvert</data-convert>
    </orm-connection>

    <orm-connection name="Redis" type="noSql">
        <connection>com.orm.sql.connection.redis.RedisConnection</connection>
        <convert>com.orm.sql.redis.convert.container.RedisConvertContainer</convert>
        <executer>com.orm.sql.redis.execute.container.RedisExecuteContainer</executer>
        <data-convert>com.orm.sql.datatype.convert.redis.RedisDataTypeConvert</data-convert>
    </orm-connection>           
</orm-connection-config>
```

</orm-connection-info>

2.orm-con-config.xml
<?xml version="1.0" encoding="utf-8"?>
<orm-config>
    <orm-datasource-info default="data1">
        <orm-datasource name="data1" data-source-class="com.mchange.v2.c3p0.ComboPooledDataSource" interface="" type="sql">
            <name>MySQL</name>
            <properties>
                <property name="driverClass" value="com.mysql.jdbc.Driver"/>
                <property name="jdbcUrl" value="jdbc:mysql://localhost/orm-test?useUnicode=true&amp;characterEncoding=utf8"/>
                <property name="user" value="root"/>
                <property name="password" value="1234"/>
                
            </properties>
        </orm-datasource>
        <orm-datasource name="data3" type="sql">
            <name>MySQL</name>
            <driver-class>com.mysql.jdbc.Driver</driver-class>
            <url>jdbc:mysql://localhost/orm-test-bk?useUnicode=true&amp;characterEncoding=utf8</url>
            <username>root</username>
            <password>1234</password>
        </orm-datasource>
        <orm-datasource name="data2" data-source-class="com.mchange.v2.c3p0.ComboPooledDataSource" interface="" type="sql">
            <name>MySQL</name>
            <properties>
                <property name="driverClass" value="com.mysql.jdbc.Driver"/>
                <property name="jdbcUrl" value="jdbc:mysql://localhost/orm-test-bk?useUnicode=true&amp;characterEncoding=utf8"/>
                <property name="user" value="root"/>
                <property name="password" value="1234"/>
                
            </properties>
        </orm-datasource>
        <orm-datasource name="data4" data-source-class="com.mchange.v2.c3p0.ComboPooledDataSource" interface="" type="sql">
            <name>Oracle</name>
            <properties>
                <property name="driverClass" value="oracle.jdbc.driver.OracleDriver"/>
                <property name="jdbcUrl" value="jdbc:oracle:thin:@localhost:cbims"/>
                <property name="user" value="cbims"/>
                <property name="password" value="cbims"/>
                <property name="maxActive" value="30"/>
                <property name="maxWait" value="10"/>
                <property name="maxIdle" value="10"/>
                <property name="validationQuery" value="10"/>
            </properties>
        </orm-datasource>
        <orm-datasource name="data5" data-source-class="com.mchange.v2.c3p0.ComboPooledDataSource" type="sql">
            <name>HBase</name>
            <properties>
                <property name="driverClass" value="com.salesforce.phoenix.jdbc.PhoenixDriver"/>
                <property name="jdbcUrl" value="jdbc:phoenix:localhost:2181:/hbase"/>
                
            </properties>
        </orm-datasource>
        <orm-datasource name="data6" type="noSql">
            <name>Redis</name>
            <properties>
                <property name="host" value="localhost"/>
                <property name="port" value="6379"/>
            </properties>
        </orm-datasource>       

```
</orm-datasource-info>

<orm-data-file-info>
    <orm-file path="dom/"/>
</orm-data-file-info>

<orm-view-file-info>
    <orm-file path="service-view"/>
</orm-view-file-info>

<orm-rule-file-info>
    <orm-file path="rule"/>
</orm-rule-file-info>

<orm-connection-info default="con1">
    <orm-connection name="con1">
        <data-source-info>
            <data-source ref="data1"/>
        </data-source-info>
    </orm-connection>
    <orm-connection name="con2">
        <data-source-info>
            <data-source ref="data2"/>
        </data-source-info>
    </orm-connection>
    <orm-connection name="con3">
        <data-source-info>
            <data-source ref="data4"/>
        </data-source-info>
    </orm-connection>
    <orm-connection name="con4">
        <data-source-info>
            <data-source ref="data5"/>
        </data-source-info>
    </orm-connection>
    <orm-connection name="con5">
        <property-info>
            <property name="type" value="map"/>
            <!-- <property name="timeout" value="5"/>
            <property name="datatype" value="5"/>
            <property name="codetype" value="5"/> -->
        </property-info>
        <data-source-info>
            <data-source ref="data6"/>
        </data-source-info>
    </orm-connection>
</orm-connection-info>

<orm-service-info>
    <orm-file path="service"/>
</orm-service-info>
<!-- <orm-define>
    <data-vailables>
        <data-vailable key="dataOne" value="data1"/>
    </data-vailables>
</orm-define>-->
```

</orm-config>

3.Dom config file
<?xml version="1.0" encoding="utf-8"?>

<orm--data-mapping>
    <data name="user" class="">
        <property-info>
            <property name="id" type="int"/>
            <property name="uidd" type="string"/>
            <property name="uid" type="string"/>
            <property name="name" type="string"/>
            <property name="activeTime" type="date"/>
            <property name="status" type="int"/>
            <property name="password" type="string"/>
        </property-info>
        <table-info>
            <table name="userInfo" data-source="data1" key="u_id" key-type="increment">
                <column name="u_id" ref-property="id" type=""/>
                <column name="u_name" ref-property="name"/>
                <column name="u_password" ref-property="password"/>
            </table>
            <table name="userInfo" data-source="data2" key="u_id" key-type="increment">
                <column name="u_id" ref-property="id"/>
                <column name="u_name" ref-property="name"/>
                <column name="u_password" ref-property="password"/>
            </table>
            <table name="userInfo" data-source="data4" key="u_id" key-type="sequence" seq="TEST_USER_SEQ">
                <column name="u_id" ref-property="id"/>
                <column name="u_name" ref-property="name"/>
                <column name="u_password" ref-property="password"/>
            </table>
            <table name="USER_INFO" data-source="data5" key="u_id" key-type="set">
                <column name="u_id" ref-property="uid"/>
                <column name="u_name" ref-property="name"/>
                <column name="u_atime" ref-property="activeTime" type="long"/>
                <column name="u_status" ref-property="status"/>
            </table>  
        </table-info>
    </data>
</orm--data-mapping>

<orm--data-mapping>
    <data name="order" class="">
        <property-info>
            <property name="id" type="int"/>
            <property name="userId" type="int"/>
            <property name="count" type="int"/>
            <property name="totalPrice" type="double"/>
            <property name="date" type="date"/>
            <property name="dateTime" type="date"/>
        </property-info>
        <table-info>
            <table name="orderInfo" data-source="data1" key="o_id" key-type="increment">
                <column name="o_id" ref-property="id"/>
                <column name="o_userId" ref-property="userId"/>
                <column name="o_count" ref-property="count"/>
                <column name="o_totalPrice" ref-property="totalPrice"/>
                <column name="o_date" ref-property="dateTime" type="timestamp"/>
            </table>
            <table name="orderInfo" data-source="data2" key="o_id" key-type="increment">
                <column name="o_id" ref-property="id"/>
                <column name="o_userId" ref-property="userId"/>
                <column name="o_count" ref-property="count"/>
                <column name="o_totalPrice" ref-property="totalPrice"/>
                <column name="o_date" ref-property="dateTime" type="timestamp"/>
            </table>
            <table name="orderInfo" data-source="data4" key="o_id" key-type="sequence" seq="TEST_ORDER_SEQ">
                <column name="o_id" ref-property="id"/>
                <column name="o_userId" ref-property="userId"/>
                <column name="o_count" ref-property="count"/>
                <column name="o_totalPrice" ref-property="totalPrice"/>
                <column name="o_date" ref-property="dateTime" type="timestamp"/>
            </table>  
        </table-info>
    </data>
</orm--data-mapping>
1. View confile file
   <orm-view-mapping>
   
   <view name="OrderInfo" class="" target-main="order">
       <property-info>
           <property name="id" ref-property="id"/>
           <property name="userId" ref-property="userId"/>
           <property name="productCount" ref-property="count"/>
           <property name="totalPrice" ref-property="totalPrice"/>
           <property name="dateTime" ref-property="dateTime"/>
           <property name="userT" relation="one-to-one" data="user" key="id" rel-key="userId">
               <property name="id" ref-property="id"/>
               <property name="userName" ref-property="name"/>
               <property name="uname" ref-property="name"/>
               <property name="upassword" ref-property="password"/>
           </property>
           <property name="productList" relation="one-to-many" data="product" key="orderId" rel-key="id">
               <property name="id" ref-property="id"/>
               <property name="orderId" ref-property="orderId"/>
               <property name="productName" ref-property="name"/>
               <property name="productCount" ref-property="count"/>
               <property name="productPrice" ref-property="price"/>
           </property>
       </property-info>
   
   </view>
   </orm-view-mapping>

5.Rule confile file
<orm-rule-mapping>
    
    
    <rule-view-info name="save-Order" view-ref="OrderInfo">

```
    <rule name="checkProduct" type="check" property="productList" pattern="GREATER:0"/>


    <rule name="check0" type="check" property="userT.userName" pattern="NOTEQUAL:'test0'"/>

    <rule name="checkName" type="checkPattern" pattern="userT.userName = userT.uname"/>

    <rule name="insertUser" type="insert" property="userT" />

    <rule name="checkUser" type="checkDataPattern" property="userT" sql="select a.id as u_id from userT a where a.id = #userT.id" pattern="u_id = userId"/>

    <rule name="checkUser1" type="checkData" property="userT" pattern="NOTNULL"/>

    <rule name="check1" type="checkPattern" pattern="userId != 0 and userT.id != 0 and ( productCount > 0 or totalPrice >= 0 ) or ( productCount*(totalPrice+10) > 200 )"/>

    <rule name="checkUerId" type="check" property="userId" pattern="NOTNULL;NOTEQUAL:2"/>

    <rule name="insertOrder" type="insert" property="OrderInfo" />

    <rule name="insertProduct" type="insert" property="productList" />


    <rule name="deleteProduct" type="delete" sql="delete p.* from productList p where p.productPrice = 20" />

</rule-view-info>

<rule-view-info name="get-user" view-ref="OrderInfo">
    <rule name="selectUser" type="get" property="userT" sql="select a.userName from userT a where a.id = #userT.id"/>
    <rule name="selectOrder" type="get" property="OrderInfo"/>
    <rule name="getProduct" type="query" property="productList" sql="select p.id,p.productPrice from productList p where p.orderId = #id"/>


</rule-view-info>

<rule-view-info name="back-Order" view-ref="OrderInfo">
    <rule name="insertProduct1" type="insert" property="productList" />
</rule-view-info>
```

</orm-rule-mapping>

5.Service config file
<?xml version="1.0" encoding="utf-8"?>
<service-info>
   <service name="SAVE_ORDER" version="1.0" model="OrderInfo">
        <task-info name="order" type="commit">
            <task execute="save-Order" con="con1"/>
        </task-info>
        <task-info name="synOrder" type="syn" depend="order">
            <task execute="save-Order" con="con2"/>
            <task execute="save-Order" con="con3"/>
        </task-info>
    </service>
</service-info>

**Comment by mevivs** [comment]
Hi,
Interesting. Few queries:
1. How is it related to Kundera?
2. It is built using Kundera or want to integrate it with Kundera?

Looking forward for your response.

-Vivek

**Comment by impetus-opensource-admin** [comment]
Not An Issue. Closing
