### ISSUE TITLE
Kundera 2.8, empty @Table annotation

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#436]
if Entity has @Table annotation without body (tableName of schema definitions) Kundera will fail to verify MongoDB Schema. Default tableName in @Table annotation is "", maybe it's treated as valid table name and not checked for empty value?

**Comment by chhavigangwal** [comment]
Fixed.
in case of entity where tableName in @Table annotation is "", the default entity name is treated as default table name.
