### ISSUE TITLE
HBase-0.90.4 migration

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#44]
Migration of current 2.0.6 branch over HBase-0.90.4

**Comment by mevivs** [comment]
Changes commited  revision number: 865529dcb41e85eecef3cfc68218a376868764c5

**Comment by kkmishra** [comment]
I tested kundera-hbase for Hbase-0.90.4,
And kundera-habse working fine on hbase-0.90.4. with crud (persist,delete and find) in case of single entity and association(in case of association both entities are going to same database ie hbase ).
