### ISSUE TITLE
Decouple ehcache dependency from kundera-core

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#450]
Currently ehcache is in tight coupling with kundera-core. Decouple and make second level cache framework extensible to bind other cache frameworks at runtime.

-Vivek

**Comment by pires** [comment]
+1

**Comment by mrniko** [comment]
+1

**Comment by mevivs** [comment]
Looks like current ehcache support is broken. Targeting to fix it with 2.10 as well.

-Vivek

**Comment by mrniko** [comment]
+1

**Comment by mevivs** [comment]
@mrniko 
Using Kundera for? 

-Vivek

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
