### ISSUE TITLE
Verify polyglot persistence for Hibernate with higher versions of MySQL

### ISSUE THREAD

**Issue by chhavigangwal** [Impetus/kundera#452]

**Comment by chhavigangwal** [comment]
When trying polyglot with MySQL-5.1+ , it throws foreign key constraint .

**Comment by DaVincii** [comment]
The newer version of MySQL has InnoDB as its default engine which imposes default foreign key constraints on schema so in order to use polyglot persistence with Kundera with MySQL as one of the datastore please make sure that you do not use InnoDb as storage engine for your database.
