### ISSUE TITLE
Kundera with Multiple PUM 

### ISSUE THREAD

**Issue by publicocean0** [Impetus/kundera#453]
If i set a not default path for persistence.xml ... there is a exception 
    <bean id="pum"
        class="org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager">
        <property name="persistenceXmlLocations">
            <list>
                <value>META-INF/dao/persons/persistence.xml</value>
            </list>
        </property>
    </bean>

**Comment by publicocean0** [comment]
there is problems also if i want use Spring MutablePesistenceInfo: if i configure PUM inside spring config(without use pesistence.xml) i can set it passing probperties from a general file properties ... for example. It is possible with Hibernate but not with Kundera

**Comment by mevivs** [comment]
Hi,
Can you please provide more details around it? Few code snippets or a demo project will surly help.

-Vivek

**Comment by mevivs** [comment]
Fixed and releasing 2.10. 

support for createContainerEntityManagerFactory() has been added.

-Vivek

**Comment by msfbrasil** [comment]
Does anyone have an example or code snippet using "createContainerEntityManagerFactory()" in order to allow to place "persistence.xml" file in another place?
Put it on "/opt/my-application/conf/persistence.xml", for example?

Thanks and best regards,
Mauro.
