### ISSUE TITLE
Maven build fails for kundera-elastic-search if tests are disabled

### ISSUE THREAD

**Issue by acwest-cc** [Impetus/kundera#454]
Trying to build the trunk with tests disabled fails, the maven.test.skip flag appears to be broken. If I try the 2.8.1 tag, it builds properly
mvn clean install -Dmaven.test.skip=true
....
[ERROR] Failed to execute goal on project kundera-elastic-search: Could not resolve dependencies for project com.impetus.client:kundera-elastic-search:jar:2.9-SNAPSHOT: Failure to find com.impetus.core:kundera-core:jar:tests:2.9-SNAPSHOT in http://mirrors.ibiblio.org/pub/mirrors/maven was cached in the local repository, resolution will not be reattempted until the update interval of clover has elapsed or updates are forced -> [Help 1]

**Comment by mevivs** [comment]
Can you please try with

mvn clean install -DskipTests ?

-Vivek

**Comment by acwest-cc** [comment]
That did the trick, everything built successfully... Thank you. It looks like maven.test.skip disables building of the tests as well. Perhaps the documentation on building Kundera needs to be updated? I am thinking particularly of https://github.com/impetus-opensource/Kundera/wiki/Stable-Release

**Comment by mevivs** [comment]
Are we good to close it?

**Comment by acwest-cc** [comment]
It isn't a major issue, but the dependencies for the build should probably
be fixed so that if you aren't compiling the tests, it shouldn't depend on
other tests being compiled

**Comment by mevivs** [comment]
Keeping it open for 2.10

**Comment by mevivs** [comment]
kundera-core contains  generic entities and other configurations required by other modules. With `-Dmaven.test.skip=true` it would simply skip test compilation, hence ideal way is to go with `-DskipTests` to skip test execution.

I have modified 
 https://github.com/impetus-opensource/Kundera/wiki/Stable-Release   for the same.
