### ISSUE TITLE
Bug in ResultIterator

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#463]
In the class com.impetus.client.cassandra.query.ResultIterator for the method 

```
 private String appendWhereClauseWithScroll(String parsedQuery)
{
    String queryWithoutLimit = parsedQuery.replaceAll(
            parsedQuery.substring(parsedQuery.lastIndexOf(CQLTranslator.LIMIT), parsedQuery.length()), "");
```

it fails with  StringIndexOutOfBoundsException for a query that doesn't have LIMIT in it.

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
