### ISSUE TITLE
ResultIterator and @EmbeddedId

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#464]
It seems that the ResultIterator doesn't work with @EmbeddedId

(https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/kundera/query/ResultIteratorTest.java)

For a table like :

```
TABLE foo (
    a     uuid,             
    b      text,                
    c      blob,                
    data    text,           
  PRIMARY KEY ((a), b, c))
```

With a query like this :  
   SELECT \* FROM foo WHERE a=bed3212d-e20a-4659-a563-0415ce9adcd0 AND b='abc';

**Comment by chhavigangwal** [comment]
Fixed. Please verify.
Junit to refer : 
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/kundera/query/ResultIteratorEmbeddableTest.java

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
