### ISSUE TITLE
Invalid Lucene query in case of a Double field in entity is passed for query with a negative value

### ISSUE THREAD

**Issue by tarang-dawer** [Impetus/kundera#468]
Example : - Select p from Entity p where p.volume= -1.0 

generated Query ; - Entity.volume:-1.0

The generated query is invalid as when it's passed to a lucene based indexing server, a parse exception is thrown.

**Comment by chhavigangwal** [comment]
Fixed. Please verify.

Junit to refer :
https://github.com/impetus-opensource/Kundera/blob/trunk/src/jpa-engine/fallback-impl/src/test/java/com/impetus/kundera/query/LuceneQueryTest.java

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>

**Comment by tarang-dawer** [comment]
Verified & working.
