### ISSUE TITLE
Cassandra's super column family error.

### ISSUE THREAD

**Issue by yo2dh** [Impetus/kundera#47]
Hi,

I have a problem about  cassandra's super column family.

Cassandra SCF:

<pre>
create column family sctest with comparator=UTF8Type and default_validation_class=UTF8Type and key_validation_class=UTF8Type and subcomparator=UTF8Type and column_type=Super;
</pre>

<pre>
@Entity
@Table(name = "sctest" , schema = "Test@cassandraPU")
public class SCTEST
{
    @Id
    @Column(name = "id")
    private String  id;

    @Embedded
    private SC      sc;

    public SCTEST( )
    {
    }

    public SCTEST( String ID , String data )
    {
        this.id = ID; 
        this.sc = new SC ( data );
    }

// get set functions ...
}
</pre>

sc class :

<pre>
@Embeddable
public class SC 
{
    @Column(name = "data")
    public String data;
    
    public SC ()
    {
    }

    public SC (String data)
    {
        this.setData( data );
    }

    public String getData()
    {
        return data;
    }

    public void setData( String data )
    {
        this.data = data;
    }
}
</pre>

main class :

<pre>
...
        SCTEST newSC = new SCTEST ( "id" , "data" );
        em.persist( newSC );

        Query q = em.createQuery("select u from SCTEST u");
        @SuppressWarnings("unchecked")
        List<SCTEST> sclist = q.getResultList();
        if (sclist != null && false == sclist.isEmpty() )
        {
            for ( SCTEST sct : sclist )
            {
                System.out.println ( sct.getId() );
            }
        }        
...
</pre>

persist() function works well.
results :

<pre>
[default@Test] list sctest;
Using default limit of 100
-------------------
RowKey: id
=> (super_column=sc,
     (column=data, value=data, timestamp=1331814344692))

1 Row Returned.
</pre>

However, I got error when getResultList() ran :

<pre>
java.lang.NullPointerException
    at com.impetus.client.cassandra.pelops.PelopsDataHandler.fromColumnThriftRow(PelopsDataHandler.java:295)
    at com.impetus.client.cassandra.pelops.PelopsClient.populateData(PelopsClient.java:619)
    at com.impetus.client.cassandra.pelops.PelopsClient.find(PelopsClient.java:518)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:102)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:159)
    at com.testkun.kunderatest.App.main(App.java:124)
</pre>

I found out the reason of error.
This is because there is no column in cassandra's super column family.

I want to call PelopsDataHandler.fromSuperColumnThriftRow() instead of PelopsDataHandler.fromColumnThriftRow().

What will I do?

Please let me know.

**Comment by mevivs** [comment]
In case of super column families, you need to set "index_home_dir" for lucene indexing. As secondary indexes does not work over super col family in cassandra. So any query.getResultList() will only be working over super col family if lucene indexing is enabled.

you need to set a property in your persistence.xml under cassandra's persistence unit.

**Comment by yo2dh** [comment]
persistence.xml
        properties>
            property name="kundera.nodes" value="X.X.X.X" />
            property name="kundera.port" value="9160" />
            property name="kundera.keyspace" value="Test" />
            property name="kundera.dialect" value="cassandra" />
            property name="kundera.client" value="Pelops" />
            property name="kundera.cache.provider.class"
                value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
            property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
            property name="index_home_dir" value="F:/" />
        /properties>

error :

<pre>
Exception in thread "main" com.impetus.kundera.index.IndexingException: no segments* file found in org.apache.lucene.store.RAMDirectory@27ba1599 lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@29e0042f: files: []
    at com.impetus.kundera.index.LuceneIndexer.getIndexReader(LuceneIndexer.java:183)
    at com.impetus.kundera.index.LuceneIndexer.search(LuceneIndexer.java:246)
    at com.impetus.kundera.index.IndexManager.search(IndexManager.java:193)
    at com.impetus.kundera.query.QueryImpl.populateUsingLucene(QueryImpl.java:640)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:112)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:159)
    at com.testkun.kunderatest.App.main(App.java:124)
</pre>

**Comment by mevivs** [comment]
please make sure to do emf.close().

**Comment by yo2dh** [comment]
My main source code :

<pre>
        EntityManagerFactory emf = Persistence.createEntityManagerFactory ( "cassandraPU" );
        EntityManager em = emf.createEntityManager();   

        Query q = em.createQuery("select u from SCTEST u");
        @SuppressWarnings("unchecked")
        List<SCTEST> sclist = q.getResultList();  // ------  !!  Exception  !!
        if ( sclist != null )
        {
            for ( SCTEST sct : sclist )
            {
                System.out.println ( sct.getId() );
            }
        }        


        em.close();    
        emf.close();   
</pre>


Do I wrong?

**Comment by mevivs** [comment]
first thing is you need to persist your indexes by enabling 
property name="index_home_dir" value="F:/" />

And then only above written code will work.

As there are no indexes created in "F:/" that's why it is giving you error like  "no segments found" !

Also i recommend if you set this property like:

property name="index_home_dir" value="F:/lucene" /> this will store all your indexes inside "lucene" folder. Ofcourse you can rename "lucene" to any name which you want.

-Vivek

**Comment by mevivs** [comment]
Is it working for you?

**Comment by mevivs** [comment]
closing it as stale issue now, working fine.
