### ISSUE TITLE
Invalid Lucene Query in case of a Double Field, when > or >= operators are used in the Query.

### ISSUE THREAD

**Issue by tarang-dawer** [Impetus/kundera#470]
Example : - Select p from Entity p where p.volume > 9.0 

query : - Entity.volume:{9.0 TO null}

This query gives parseException in a lucene based query server.

**Comment by chhavigangwal** [comment]
Fixed. Please verify.
Junit to refer :

https://github.com/impetus-opensource/Kundera/blob/trunk/src/jpa-engine/fallback-impl/src/test/java/com/impetus/kundera/query/LuceneQueryTest.java

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>

**Comment by tarang-dawer** [comment]
Verified & working.
