### ISSUE TITLE
Support Cassandra CLUSTERING ORDER BY with JPA annotations

### ISSUE THREAD

**Issue by pires** [Impetus/kundera#485]
How can one map the following Cassandra statement to Kundera entity mapping?

``` sql
CREATE TABLE latest_temperatures (
   weatherstation_id text,
   event_time timestamp,
   temperature text,
   PRIMARY KEY (weatherstation_id,event_time),
) WITH CLUSTERING ORDER BY (event_time DESC);
```

This must be available during schema generation, otherwise one won't be able to `ALTER TABLE latest_temperature WITH CLUSTERING BY (event_time DESC);` given the ordering has been already defined and would imply destroying every available data.

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
