### ISSUE TITLE
One To Many Relationship fails for an Object with Composite Key(EmbeddedID)

### ISSUE THREAD

**Issue by yeshvanthni** [Impetus/kundera#486]
One To Many Relationship fails for an Object with Composite Key(EmbeddedID)

Example: Tweet has many tags. Tweet has a composite key with timestamp and tweetid.( Ignore the business necessity of this example)

Class Tweet{
@EmbeddedId
TweetIdStamp   id;   //Compound key=Tweet_id+timestamp

@OneToMany
@JoinColumn(name=tagFgnKey)
List<Tag> tags;

}

The above entity fails because it couldn't persist the embeddedId as a foreign key in Tags column family. This is a design issue. However we choose to persist internally, This use case has to be handled

**Comment by mevivs** [comment]
Only one-To-one and many-to-one are supported over composite keys with other entities. 

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by yeshvanthni** [comment]
Yes
