### ISSUE TITLE
MongoDBQuery getSingleResult should return null/exception in case no data is found

### ISSUE THREAD

**Issue by sumeetchhetriwellogic** [Impetus/kundera#488]
Hello,

Love the work you guys have been doing, had an issue to report though,

this line inside MongoDBQuery.java getSingleResult() function should be changed from 

return results.isEmpty() ? results : results.get(0);

TO

return results.isEmpty() ? null : results.get(0);

OR

if(results.isEmpty()) throw new EntityNotFoundException;
else results.get(0);

Thanks,
Sumeet Chhetri

**Comment by mevivs** [comment]
:+1:  for returning null. scheduling it to release with 2.10

-Vivek

**Comment by chhavigangwal** [comment]
Fixed.Please verify
Junit to refer :
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
