### ISSUE TITLE
slf4j binding should not be exposed through transitive dependency

### ISSUE THREAD

**Issue by yeshvanthni** [Impetus/kundera#489]
Kundera-Cassandra/pom.xml has slf4j-log4j in default scope. If a project uses logback as the chosen logger there will be multiple bindings in the classpath which is failing the expected logback configuration.
As per slf4j documentation (http://slf4j.org/faq.html#maven2) this should be switched to test scope or made <optional>true</optional.

**Comment by mevivs** [comment]
Fixed on current trunk.

-Vivek

**Comment by yeshvanthni** [comment]
Thank you

**Comment by mevivs** [comment]
@yeshvanthni 
Using kundera for? Request you to please spare few minutes to fill in kundera survey
http://www.surveymonkey.com/s/BMB9PWG

-Vivek

**Comment by yeshvanthni** [comment]
Done. Thanks.

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
