### ISSUE TITLE
Pagination - MongoDBQuery can support setFirstResult using the skip clause

### ISSUE THREAD

**Issue by sumeetchhetriwellogic** [Impetus/kundera#490]
The QueryImpl class has the following implementation for setFirstResult()

@Override
    public Query setFirstResult(int startPosition)
    {
        throw new UnsupportedOperationException("setFirstResult is unsupported by Kundera");
    }

MongoDB can support setFirstResult using the skip function, i think this can be implemented in Kundera mongodb client (MongoDBQuery/MongoDBClient) code.

I assume you guys already know this but may be planning it for a future release, is so can this be expected in the next release?

**Comment by mevivs** [comment]
Pagination is supported over Kundera mongoDB via limit function. So if fetchSize is set to 1 or maxResults is set to 1, it will return single record (e.g getSingleResult).

However, Implementing setFirstResult() using skip() is very much on roadmap. Thanks for raising it!

I will post an update soon on this, if we can plan it within 2.10 release.

-Vivek

**Comment by mevivs** [comment]
Targeting for 2.11 release

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1
