### ISSUE TITLE
MongoDB - Pre Perisist/Update callback hooks not getting honored with @MappedSuperclass

### ISSUE THREAD

**Issue by sumeetchhetriwellogic** [Impetus/kundera#492]
With an abstract base class with @MappedSuperclass and a child entity class, the @PrePersist and the @PreUpdate callback hooks are not getting called.

Retested with a normal Event class(without a base class) and still both the hooks are not working.

**Comment by chhavigangwal** [comment]
Fixed. Please verify.
Junit to refer  :
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/java/com/impetus/kundera/client/crud/inheritence/AbstractEntityEventListenerTest.java

**Comment by mevivs** [comment]
Fixed. Releasing with 2.9.1

-Vivek

<b>
Note: Group artifactId has been changed. Please refer https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note for the same.
</b>
