### ISSUE TITLE
kundera.ddl.auto.prepare problem

### ISSUE THREAD

**Issue by baumhacklf** [Impetus/kundera#496]
Could be deleted. I've found the problem.

**Comment by mevivs** [comment]
Ok. with "create-drop" it should get deleted, while with "create", it will exist till you re-instantiate emf for same keyspace.

**Comment by baumhacklf** [comment]
You are very fast :)
First it was a problem in the configuration (my fault). Now all tables are deleted. Only the keyspace still exists.
