### ISSUE TITLE
support for Querying over cassandra Supercolumn values 

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#5]
support for Querying over cassandra Supercolumn values . As of now it is not provided by Cassandra. As secondry index support is not provided by Cassandra. So solution is to build query support over supercolumn values.

**Comment by anismiles** [comment]
I think, Cassandra 0.7 has secondary indexes features, and for earlier version, Kundera has Lucandra to store indexes into cassandra backed lucene.

**Comment by mevivs** [comment]
Secondry index over supercolumn are not yet supported in cassandra.  In case when we generate dynamic super columns and want to query back specific super column as of now there is no such way to retrieve this. We are planning to build such functionality in system.

**Comment by anismiles** [comment]
oh i see. that's wonderful.

**Comment by mevivs** [comment]
Code changes commited.
