### ISSUE TITLE
ManyToMany JoinTable

### ISSUE THREAD

**Issue by baumhacklf** [Impetus/kundera#507]
Hey there.
In my old application there are many-to-many relationships. I tried these implementations with the Kundera framework and got an other join table. 

Classes:
@Entity
@Table(name = "bundle_barcode", schema = "test@cassandra_pu")
public class BundleBarcode {

```
@Id
@Column(name = "barcode_id", nullable = false)
private long id;

@ManyToMany
@JoinTable(name = "bundle_barcode_join", joinColumns = @JoinColumn(name = "barcode_id"), inverseJoinColumns = @JoinColumn(name = "bundle_id"))
private Set<Bundle> bundles;

    // ...
```

}

@Entity
@Table(name = "bundle", schema = "test@cassandra_pu")
@IndexCollection(columns = { @Index(name = "item") })
public class Bundle {

```
@Id
@Column(name = "bundle_id", nullable = false)
// @GeneratedValue(strategy = GenerationType.AUTO)
private long bundleId;

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "item_id")
private Item item;

@ManyToMany(mappedBy = "bundles")
private Set<BundleBarcode> barcodes;

    // ...
```

}

It's nearly the same implementation in the Oracle Hibernate implementation. 
In Oracle/Hibernate/JPA framework only two columns are created.
![oracle_jpa](https://f.cloud.github.com/assets/4173776/1961268/b0497ecc-826c-11e3-814f-79b0cd0978fb.PNG)

With Kundera it looks like following.
![kundera_jpa](https://f.cloud.github.com/assets/4173776/1961273/bad64b0e-826c-11e3-99c1-f04d797f9dc9.PNG)

Is it a bug or could you give me a hint how should I use it?
PS: Kundera names of the colums are the table name + bundle_id.

**Comment by mevivs** [comment]
Since a column family in Cassandra must have a row key. Where as it is not mandatory with Oracle. Hence a join table in Cassandra is implemented in this way. as Cassandra allows a billion columns for a row key, that's the reason for column name as table name + bundle_id

In short, Kundera replaces more rows of RDBMS with more columns in Cassandra.

Hope it helps.
-Vivek

**Comment by baumhacklf** [comment]
So I have to write own queries to get for example all barcodes (in this example) for one bundle? Because the entity manager won't return any entries.

**Comment by mevivs** [comment]
Can you please elaborate more on this?  As far as retrieving such many to many association are concerned, Kundera implicitly handles it for you.  Please refer 
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-tests/src/test/java/com/impetus/kundera/tests/crossdatastore/useraddress/MTMBiAssociationTest.java

for a sample junit and running JPQLs

-Vivek

**Comment by baumhacklf** [comment]
Bundle result = em.find(Bundle.class, smallBundle.getBundleId());
Will return a bundle with 0 barcodes (many-to-many relationship). 

BundleBarcode loadedBarcode = em.find(BundleBarcode.class, barcodeOne.getId());
will throw an exception:

10:03:31,797 ERROR [ThriftClient]() Error while fetching key slices of column family bundle_barcode_join for column name bundle_id , Caused by: .
InvalidRequestException(why:[62756e646c655f69645f31]=[31] failed value validation (Expected 8 or 0 byte long (1)))

The many-to-many relationship looks the same as in the unit test from kundera :S 
Maybe it's a problem with cassandra? Can't find the error :S

**Comment by mevivs** [comment]
```
 InvalidRequestException(why:[62756e646c655f69645f31]=[31] failed value validation (Expected 8 or 0 byte long (1)))
```

please set CQL version to CQL3 with client.

```
Bundle result = em.find(Bundle.class, smallBundle.getBundleId());
Will return a bundle with 0 barcodes (many-to-many relationship). 
```

if Bundle is holding associatied values with Barcode, then it should return.
-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek
