### ISSUE TITLE
Parameters do not work on NativeQuery

### ISSUE THREAD

**Issue by bramp** [Impetus/kundera#508]
When I run this code:

```
String cql = "SELECT ids FROM something WHERE value = ?1";
Query q = entityManager.createNativeQuery(cql, MyClass.class);
q.setParameter(1, value);
```

it throws an exception:

```
com.impetus.kundera.query.QueryHandlerException: No named parameter present for query
    at com.impetus.kundera.query.KunderaQuery.setParameterValue(KunderaQuery.java:755)
    at com.impetus.kundera.query.KunderaQuery.setParameter(KunderaQuery.java:718)
    at com.impetus.kundera.query.QueryImpl.setParameter(QueryImpl.java:473)
```

looking a the Kundera code (QueryResolver.java), it doesn't support parameters for NativeQueries. The list of valid parameters it built up initFilter(), which is called from postParsingInit(). However, postParsingInit is not called if the query is native:

``` QueryResolver
if (!isNative)
{
...
        parser.parse();
        kunderaQuery.postParsingInit();
...
}
```

**Comment by mevivs** [comment]
setParameter support is only available with JPQL and named queries. 

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by canopenerda** [comment]
@mevivs 

Since setParameter is not supported on native queries (includes named native queries), what is the suggested way to execute parameterized native queries except constructing the query with parameter and value in entirety?

Thank you!

Regards,
Malcolm

**Comment by chhavigangwal** [comment]
@mqian 

There is no way to run parameterized native queries using Kundera as of now.

Chhavi

**Comment by canopenerda** [comment]
@chhavigangwal 

According to my previous experience with other JPA implementation, setParameter also takes care of named native query. So I think this could be an enhancement in the future release of kundera.

Thank you!

Regards,
Malcolm

**Comment by robertBrem** [comment]
+1

**Comment by AntonYudin** [comment]
+1
