### ISSUE TITLE
Using Collections.EMPTY_SET or Collections.EMPTY_MAP causes a NullPointerException

### ISSUE THREAD

**Issue by pdirksen** [Impetus/kundera#511]
An additional warning appears:

Warnung: Returning null as error during clone, Caused by:Class com.impetus.kundera.utils.ObjectUtils can not access a member of class java.util.Collections$EmptySet with modifiers "private".

Instantiating a new HashMap oder a new HashSet solves it, but EmptySet and EmptyMap should work too.

**Comment by mevivs** [comment]
Duplicate of https://github.com/impetus-opensource/Kundera/issues/381 ?

**Comment by pdirksen** [comment]
The cause is a duplicate yes.

**Comment by impetus-opensource-admin** [comment]
Closing ... the duplicate issues. Please track through #381.
