### ISSUE TITLE
Kundera Cassandra Provider does not work for JPQL delete

### ISSUE THREAD

**Issue by yeshvanthni** [Impetus/kundera#513]
JPQL for  delete has the following behaviour which is not expected,

1.does a fetch before delete which causes a select that impacts performance
2.there is no delete query fired after that and the actual delete doesn't happen

**Comment by mevivs** [comment]
Cassandra allows to delete record by row key. If you enable CQL3 version with Kundera  and fire such Delete JPQL it should work. Have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/client/crud/UpdateDeleteJPQLLiteralTest.java

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek
