### ISSUE TITLE
EntityManager does not get created.

### ISSUE THREAD

**Issue by Deepak-Vohra** [Impetus/kundera#516]
If  @PersistenceContext is used to inject EntityManager  or @PersistenceUnit  used to inject EntityManagerFactory the following exception is generated.

Exception in thread "main" java.lang.NullPointerException
    at kundera.KunderaClient.create(KunderaClient.java:50)
    at kundera.KunderaClient.main(KunderaClient.java:37)

If EntityManager is created from factory as follows:
emf = Persistence.createEntityManagerFactory("kundera");
         em = emf.createEntityManager();

the following exception gets generated:

INFO: EntityManagerFactory created for persistence unit : kundera
Exception in thread "main" java.lang.NoSuchMethodError: javax.persistence.Entity
ManagerFactory.getProperties()Ljava/util/Map;

**Comment by mevivs** [comment]
Have a look at https://github.com/impetus-opensource/Kundera/tree/trunk/examples/container/tomcat-glassfish for Container managed EM/EMF binding.

-Vivek

**Comment by Deepak-Vohra** [comment]
Thanks Vivek. Not using a application/web server. The following error is fixed by updating  the javax.persistence jar  to version 2.0.

INFO: EntityManagerFactory created for persistence unit : kundera
Exception in thread "main" java.lang.NoSuchMethodError: javax.persistence.Entity
ManagerFactory.getProperties()Ljava/util/Map;

But, still getting NullPointer if injecting EM with @PersistenceContext or factory with @PersistenceUnit.

**Comment by Deepak-Vohra** [comment]
The @PersistenceContext or  @PersistenceUnit may be used  only if using a web/application server.

**Comment by mevivs** [comment]
@dvohra 

As i said earlier, @PersistenceUnit and @PersistenceContext are for container manager entity manager or entity manager factory, For application managed em/emfs you need to use

```
Persistence.createEntityManagerFactory(pu).
```

Not sure what your case is, please share persistence.xml, entity definition and CRUD code snippet to look into this

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by Deepak-Vohra** [comment]
Yes. Thanks Vivek for the DELETE with WHERE example.
