### ISSUE TITLE
In-memory mock db for testing

### ISSUE THREAD

**Issue by mxk1235** [Impetus/kundera#521]
May application is switching from using MySql to using Cassandra.  In the past, I was able to run unit tests in my app by creating a fresh instance of derby in memory, which would be gone after all my tests finished.   Here is a sample persistence config for doing this with JPA/Derby. 

"javax.persistence.jdbc.driver": "org.apache.derby.jdbc.EmbeddedDriver",
"javax.persistence.jdbc.url": "jdbc:derby:memory:testdb;create=true",

Is a feature like this on the horizon for Kundera?  Because Kundera doesn't really take any url configs, but rather a list of hosts, ideally, I'd like to be able to say, kundera.client.lookup.class=com.impetus.client.cassandra.InMemoryClientFactory,
and my tests will be run against a temporary instance.

thanks in advance.

**Comment by mxk1235** [comment]
Fwiw, the current workaround that I found was to start an EmbeddedCassandraService and configure kundera.nodes="localhost".  I don't like this solution very much because it still uses a system-wide resource (port), but I am willing to live with it for now.

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek

**Comment by mxk1235** [comment]
is this a feature you'd rather not support?

**Comment by mevivs** [comment]
In case of Cassandra, you need to enable EmbeddedCassandraService for in-memory Cassandra daemon thread. Same goes with HBase, mongoDB as well. 

Feature has been supported as the way provided by Cassandra api itself!

HTH,
-Vivek

**Comment by mxk1235** [comment]
I agree that this is not an issue, but rather a feature parity request, since other JPA implementations allow you to do this without starting up your own cassandra thread, and thus not making me use a separate code path just for testing.

but i understand that it might messes with kundera code too much.  no problem if you'd like to close it.
