### ISSUE TITLE
FindByExample with Kundera 2.9

### ISSUE THREAD

**Issue by msfbrasil** [Impetus/kundera#522]
Hello there!

I'm creating a generic DAO implementation to access Cassandra using Kundera 2.9.
Everything is fine until now.

Kundera is great, by the way :-D.

All basic operations are "up and running", and now I was trying to add a generic "findByExample" when I've got the message below:

org.apache.commons.lang.NotImplementedException: Criteria Query currently not supported by Kundera

Questions:

1- CriteriaQueries are on the roadmap?

2- Best alternative to that, considering features provided by version 2.9 of Kundera,  is to manually build a string to perform the query? Probably using MetaModel (this.em.getMetamodel(), and on)?

Thanks and best regards,
Mauro.

**Comment by impetus-opensource-admin** [comment]
```
1- CriteriaQueries are on the roadmap?
```

Yes. https://github.com/impetus-opensource/Kundera/issues/118

```
2- Best alternative to that, considering features provided by version 2.9 of Kundera, is to manually build a string to perform the query? Probably using MetaModel (this.em.getMetamodel(), and on)?
```

You may use em.createNativeQuery(),em.createQuery() or em.createNamedQuery(). You may refer these for examples:
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/kundera/query/ResultIteratorTest.java

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandraTest.java

https://github.com/impetus-opensource/Kundera/wiki/JPQL

HTH,
-Vivek

**Comment by msfbrasil** [comment]
Thanks a lot for the information Vivek.

The examples are nice, but I want to build a generic "findByExample" (valid for any entity, or at least to handle the "flat" and very simple entities we have now).

Thanks anyway. 
The examples to create the queries will be quite useful.

**Comment by mevivs** [comment]
Closing it as support for Criteria queries can be tracked with #118 

-Vivek

**Comment by msfbrasil** [comment]
Hello there!

I don't know if this could be of any help to anyone.

And I don't know if this is the place to post such kind of code, but I've created a helper class to help me to create the "so called" generic "findByExample". :-p

Its limited to what I've needed here (flat entities with EmbeddedId - for composite keys - support at most).
It's not something hard to do, and I don't know if it's at least the best of doing such a thing, but could save someone's work.

Could I place it here?

Just trying to help.

Best regards,
Mauro.

**Comment by mevivs** [comment]
Please submit a pull request and let me have a look on it, will see if we can reuse the same with JPA criteria query implementation.#118

-Vivek

**Comment by msfbrasil** [comment]
Vivek, the helper I've mentioned is really a simple peace of code that is completely unrelated with Kundera code.

It would be considerably easier to me place it here if I can't attach it by some other mean.
And the code will be broken because I'll need to remove some dependencies, not relevant for the understanding and usage, and codes related with our product.

Is it possible just to place the code here, or you advice to proceed with "pull request"?
In that case, where do you suggest to place the code?

Best regards,
Mauro.

**Comment by msfbrasil** [comment]
Hello there, Vivek!

I've got stuck with the option to get the code and make a "pull request", so I've decided by the hybrid approach below.

First I've posted the helper class that, given an example (entity with some values) and the entity's class, it builds a map with the name only of the fields that have valid values (by valid, I mean "not null").

This helper is at: "http://codetidy.com/8206/".

Some details:
1- Method "getEntityFields" uses MetaModel to build a list of the entity's fields that are "persistable" (I've considered that "MetaModel" is the right guy for the job, maybe not?);
2- "EmbeddedId" fields are the only exception regarding some hierarchy on my entities, which are mostly simple and flat;
3- Method "buildEntityFieldsValuesMap" uses reflection to get the fields of the provided example that have "valid" values.

The final step to build the "findByExample" query is done on my "JpaDAO" (which is my basic DAO implementation), and the code block is below:

# 

```
private static final String BASIC_SELECT_SQL_FORMAT = "SELECT entityName FROM %s entityName ";

private Query buildFindByExampleQuery(Map<String, Object> fieldsValuesMap) {

    String findByExampleSQL = String.format(BASIC_SELECT_SQL_FORMAT, this.persistentClass.getSimpleName());
    Query findByExampleQuery = null;

    if (fieldsValuesMap.size() > 0) {

        findByExampleSQL += " WHERE ";
        int fieldsIndex = 1;

        // First we add the "WHERE" clauses with parameters.
        //
        for (String field : fieldsValuesMap.keySet()) {

            if (fieldsIndex > 1) {

                findByExampleSQL += " AND ";
            }

            findByExampleSQL += " entityName." + field + " = :" + field;

            fieldsIndex++;
        }
    }

    findByExampleQuery = this.em.createQuery(findByExampleSQL);

    if (fieldsValuesMap.size() > 0) {

        // And now, we set those parameters.
        //
        for (String field : fieldsValuesMap.keySet()) {

            findByExampleQuery.setParameter(field, fieldsValuesMap.get(field));
        }
    }

    return findByExampleQuery;
}
```

# 

As I've said, it's quite a simple block of code, and I don't even know if this is the best way to get the job done, but I truly expect it could be of some help.

Some private info is missing and the code won't work "as is", but I think it's easy to understand the idea.

I hope this helps.

Thanks and best regards,
Mauro.

**Comment by mevivs** [comment]
@msfbrasil 
Thanks. I am planning to have a look on this in a day or two and will share my thoughts on this

Sincerely,
-Vivek
