### ISSUE TITLE
Lower case Enum constants do not work

### ISSUE THREAD

**Issue by dzalbo** [Impetus/kundera#529]
I accidentally used lower case in defining Enum constants, which is allowed in Java, but fails to work in Kundera

Because EnumAccessor does toUpperCase(), it can never find proper enum constant and fails.

this might cause some headache

**Comment by mevivs** [comment]
I will have a look and fix it.

Thanks,
-Vivek

**Comment by mevivs** [comment]
Fixed on current trunk.

-Vivek

**Comment by mevivs** [comment]
Fixed and released with 2.11
