### ISSUE TITLE
Problems with "IN" clause on Kundera 2.10 ...

### ISSUE THREAD

**Issue by msfbrasil** [Impetus/kundera#530]
Hello there!

I've tried to validate the use of "IN" clause on new 2.10 version of "Kundera", but got the following problems:
# 

19 Fev 2014 10:21:18 [main] INFO  com.impetus.client.cassandra.CassandraClientBase.executeQuery - Executing query SELECT \* FROM "tags" WHERE token("id") IN ('[teste1', 'teste2', 'qq coisa]') LIMIT 1000000.
19 Fev 2014 10:21:18 [main] ERROR com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery - Error during executing query SELECT \* FROM "tags" WHERE token("id") IN ('[teste1', 'teste2', 'qq coisa]') LIMIT 1000000, Caused by: InvalidRequestException(why:line 1:52 mismatched input ',' expecting ')') .
19 Fev 2014 10:21:18 [main] ERROR com.impetus.client.cassandra.CassandraClientBase.executeQuery - Error while executing native CQL query Caused by: .
javax.persistence.PersistenceException: InvalidRequestException(why:line 1:52 mismatched input ',' expecting ')')
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1927)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2103)
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:834)
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:916)
# 

Aside the exception got, the list items are appended with "[" and "]".

Debugging with Eclipse and removing those character from searching elements didn't make any difference for the exception.

Any ideas?

Thanks and best regards,
Mauro.

**Comment by mevivs** [comment]
Running as a native CQL3 query or as a JPQL?

-Vivek

**Comment by msfbrasil** [comment]
I've used the following configuration to initialize the "EntityManagerFactory":

propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);

So, CQL3, right?

Thanks!

**Comment by mevivs** [comment]
Correct.
executing via em.createNativeQuery or em.createQuery?

em.createNativeQuery is to execute CQL3 queries in native way. whereas em.createQuery is for JPQL queries with in clause

Please share code snippet and let me have a look.

-Vivek

**Comment by msfbrasil** [comment]
Code follows below:

# 

public List<ConfigurationTag> findByIds(List<String> configurationTagIdsList) {

```
List<ConfigurationTag> configurationTagList = null;

try {

    configurationTagList = this.em
            .createQuery(
                    "SELECT entityName FROM " + this.persistentClass.getSimpleName()
                            + " entityName WHERE entityName.id IN :configurationTagIdsList ")
            .setParameter("configurationTagIdsList", configurationTagIdsList)
            .setMaxResults(getEntityMaxResults()).getResultList();

} catch (Exception exception) {

    throw new PersistenceException(ConfigurationTagDAO.class.getSimpleName()
            + " - Failed to list configurationTags with ids [" + configurationTagIdsList + "]: ", exception);
}

return configurationTagList;
```

}

# 

Thanks and best regards,
Mauro.

**Comment by mevivs** [comment]
As per JPA, setParameter should match data type of entityName.id ( i assume it is not of type list).
Support such as setParameterList needs to be added explicitly added in Kundera to enhance query support.

Marking it as an enhancement.

-Vivek

**Comment by msfbrasil** [comment]
I forgot to mention that the "id" field is a String.
Is it a problem?

Will a fix be provided to consider use of "IN" clause with String fields, or you will left this to "setParameterList" enhancement?

Thanks and best regards,
Mauro.

**Comment by mevivs** [comment]
Queries such as 
        inClause = "Select u from CassandraPrimeUser u where u.key.userId IN (\"mevivs\",\"cgangwal's\",\"kmishra\") ORDER BY tweetId ASC";

should work.

I will get it fixed for setParameter in current trunk, but support for setParameterList() needs to planned.

HTH,
-Vivek

**Comment by msfbrasil** [comment]
Just trying to understand it here :-D
You've suggested to provide an formated string on "setParameter", instead of the list itself, right?

*\* Format includes: "," as per string item separator and "\\"" as string delimiter.

I just tried that and the query logged was:

SELECT \* FROM "tags" WHERE token("id")INtoken('\"teste1\",\"teste2\",\"qq coisa\"') LIMIT 1000000

Which cause the exception below:

# 

19 Fev 2014 14:51:04 [main] ERROR com.impetus.client.cassandra.CassandraClientBase.executeQuery - Error while executing native CQL query Caused by: .
javax.persistence.PersistenceException: InvalidRequestException(why:line 1:38 no viable alternative at input 'INtoken')
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1921)

# 

Maybe I misunderstood you?
Am I missing something?

Thanks and best regards,
Mauro.
