### ISSUE TITLE
Neo4j kundera.datastore.file.path - what is it?

### ISSUE THREAD

**Issue by janinko** [Impetus/kundera#532]
What is `kundera.datastore.file.path` property in persistence.xml for?

It says "For Neo4J, it's mandatory to specify kundera.datastore.file.path property in persistence.xml" (BTW exception with this message is caught in KunderaPersistence and thrown away, so I needed to debug Kundera do get to it), but I don't know what should I set there.

**Comment by mevivs** [comment]
Kundera currently supports embedded Neo4J server.  `kundera.datastore.file.path` is local/remote  path to file system directory. It is mandatory if using Kundera with Neo4J only.

-Vivek

**Comment by janinko** [comment]
So it doesn't support standalone Neo4J server?

**Comment by chhavigangwal** [comment]
Opening https://github.com/impetus-opensource/Kundera/issues/604 to enable support
