### ISSUE TITLE
Changed GroupID without notice

### ISSUE THREAD

**Issue by janinko** [Impetus/kundera#533]
It seems to me that groupid changed between versions 2.9 an 2.9.1 and there is no information about this. On https://github.com/impetus-opensource/Kundera/wiki/Stable-Release page there is:

```
 <dependency>
   <groupId>com.impetus.core</groupId>
   <artifactId>kundera-core</artifactId>
   <version>2.10</version>
 </dependency>
```

but it looks like it is now:

```
 <dependency>
   <groupId>com.impetus.kundera.core</groupId>
   <artifactId>kundera-core</artifactId>
   <version>2.10</version>
 </dependency>
```

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/blob/trunk/src/README.md#note

We did publish it as part of release email as well.

-Vivek

**Comment by mevivs** [comment]
Same is available on https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes as well

HTH,
-Vivek

**Comment by janinko** [comment]
Ok, sorry about the part with no information, but I think the wiki https://github.com/impetus-opensource/Kundera/wiki/Stable-Release should be changed.

**Comment by mevivs** [comment]
I will have a look, will add over there as well

-Vivek

**Comment by mevivs** [comment]
Wiki page changed. Are we good to close on this?

-Vivek
