### ISSUE TITLE
order by

### ISSUE THREAD

**Issue by crcube** [Impetus/kundera#54]
I am really new with kundera, i have a cassandra cluster with 2 nodes, i don´t have any problem with the inserts but when i try to do a select i need the last of the elements that i have insert.
i tried to do something like 
select d from Sensor d where d.codParam=212, It works but i want the last element that has been insert, 
How can i get it?
Thanks a million.

**Comment by mevivs** [comment]
Hi,
Currently cassandra does provide support for order by only in case of  SliceRange query(using reversed as option). Unfortunately this support is not available over secondary indexes, as far as i know. I will have a look on this, if came to know anything around this.

Thanks,
Vivek

**Comment by crcube** [comment]
and if i use >=5 and <=5 it works?
and when i do a select and it returns more than one value kundura order it by timestamp??
I'm really new with kundera and i have some problems to find all the documentantion
thanks

**Comment by mevivs** [comment]
Hi,
As long as fields are indexed or it is range query, it should work for you.
You can refer:
http://mevivs.wordpress.com/2012/02/13/how-to-crud-and-jpa-association-handling-using-kundera/

Hope this helps!

-Vivek
