### ISSUE TITLE
ORDER BY not working with compound key.

### ISSUE THREAD

**Issue by pritish5699** [Impetus/kundera#542]
Hi,

Here is my entity class:

@Entity
@Table(name = "box_tier", schema = "KunderaExamples@cassandra_pu")
@IndexCollection(columns = { @Index(name = "cid"), @Index(name = "admin") })
@XmlRootElement(name = "BoxTier")
@XmlSeeAlso({Date.class})
//@XmlSeeAlso({String.class,Long.class,Date.class,Integer.class,Boolean.class})
@NamedQueries({
    @NamedQuery(name="BoxTier.getByCidType",query="select bt from BoxTier bt where bt.cid=:cid and td.admin=:admin"),
    @NamedQuery(name="BoxTier.getByCidTier",query="select bt from BoxTier bt where bt.cid=:cid and td.admin=:admin and td.tier=:tier")
    })
public class BoxTier {

```
//@TableGenerator(name = "id_gen", allocationSize = 1, initialValue = 1)
//@GeneratedValue(generator = "id_gen", strategy = GenerationType.TABLE)
@EmbeddedId
private CompoundKey key;

@Column(name="seq")
private long seq;

@Column(name="cid")
private String cid;

@Column(name="admin")
private boolean admin;

@Column(name ="tier")
private int tier;

@Column(name="vault_space")
private long vaultSpace;  // in byte, please use -1 to indicate the unlimited tier

@Column(name="max_file_size")
private long maxFileSize;

@Column(name="allowed_file_types")
private String allowedFileTypes;

@Column(name="alert_percentage") //90%
private int alertPercentage;

@Column(name="security_level")
private int securityLevel;  //1 ->standard, 2--> password, 3-->file lock

@Column(name="create_dt")
private Timestamp timestamp;
```

Here is my compound key class:

@Embeddable
public class CompoundKey {

```
@Column(name="userid")
private String userid;

@Column(name="tweetid")
private UUID tweetid;
```

Below query does not work:

String queryString="select bt from BoxTier bt where bt.key.userid='1767660' ORDER BY bt.key.tweetid DESC";

I am getting following exception:

![exception](https://f.cloud.github.com/assets/4121465/2376019/da3581c4-a871-11e3-8805-a701b8bc7d80.PNG)

Temporary workaround given by Vivek is to use createNativeQuery, and that is working fine.

**Comment by mevivs** [comment]
Targetting for 2.11 release.

-Vivek

**Comment by pritish5699** [comment]
Thanks Vivek.
