### ISSUE TITLE
Could not find any META-INF/persistence.xml

### ISSUE THREAD

**Issue by jeevitesh** [Impetus/kundera#543]
hi all,
New guy to kundera need your help in running my first application in kundera
This is my folder architecture of project
SRC
 |- com.junitTestKundera
 |  -testKundera.java
 |
 |-com.testkundera
 | -App.java
 | -user1.java
 |JRE SYSTEM LIBRARY
 |Web APP LIBRARY
 |WebContent
 | -META-INF
        -persistence.xml
 | -Web-INF
        -lib
            all library goes here
Just following the example given in https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes
getting error as soon as hits line
EntityManagerFactory emf = Persistence.createEntityManagerFactory("hbase_pu");

tried with web project and standlone project adding test to run the above code all the time it fails. Also added map
 Map<String, String> properties = new HashMap<String, String>();

```
    // Ensure RESOURCE_LOCAL transactions is used.
    properties.put("kundera.nodes","192.168.1.42");
    properties.put("kundera.port","60010");
    properties.put("kundera.keyspace","KunderaExamples");
```

.........
EntityManagerFactory emf = Persistence.createEntityManagerFactory("hbase_pu", properties);

Still it is throwing error. Please help me how to configure...

**Comment by mevivs** [comment]
Hi,
Please move persistence.xml within SRC folder and try.
SRC
|- 
| -META-INF
-persistence.xml

persistence.xml should be with root folder where entity definition is placed.

-Vivek

**Comment by mevivs** [comment]
A sample web project can be found at:
https://github.com/impetus-opensource/Kundera/tree/trunk/examples/container/tomcat-glassfish/data-keeper/src/main

-Vivek

**Comment by jeevitesh** [comment]
thanks vivek..
Now my error got unable to find persistence got resolved but unfortunately
getting different error in the same domain
ERROR configure.PersistenceUnitConfiguration: Unconfigured persistence
unit: hbase_pu please validate with persistence.xml
ERROR kundera.KunderaPersistence: EnrityManagerFactory not created,
returning null.

**Comment by jeevitesh** [comment]
thanks vivek..

it is mid night so went completely wrong in my sentence formation.

my previous error got resolved but unfortunately getting different error in
the same domain

ERROR configure.PersistenceUnitConfiguration: Unconfigured persistence
unit: hbase_pu please validate with persistence.xml
ERROR kundera.KunderaPersistence: EnrityManagerFactory not created,
returning null.

here is my persistance.xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="hbaseTest">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.nodes" value="192.168.1.42"/>
            <property name="kundera.port" value="60010"/>
            <property name="kundera.keyspace" value="KunderaExamples"/>
            <property name="kundera.dialect" value="hbase"/>
            <property name="kundera.client.lookup.class"
value="com.impetus.client.hbase.HBaseClientFactory" />
            <property name="kundera.cache.provider.class"
value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource"
value="/ehcache-test.xml"/>
        </properties>
    </persistence-unit>
</persistence>

**Comment by mevivs** [comment]
as per provided persistence.xml persistence unit name is "hbaseTest" . Though looks like "hbase_pu" is configured with either of the entities?

-Vivek

**Comment by jeevitesh** [comment]
hi vivek,

thanks a lot...now getting another issue.. it will be of great help if can
provide some insight

When I run my program I get following warning.
14/03/12 11:39:46 INFO zookeeper.RecoverableZooKeeper: The identifier of
this process is 5116@DELL-75
14/03/12 11:39:46 WARN client.ZooKeeperSaslClient: SecurityException:
java.lang.SecurityException: Unable to locate a login configuration
occurred when trying to find JAAS configuration.
14/03/12 11:39:46 INFO client.ZooKeeperSaslClient: Client will not
SASL-authenticate because the default JAAS configuration section 'Client'
could not be found. If you are not using SASL, you may ignore this. On the
other hand, if you expected SASL to work, please fix your JAAS
configuration.
14/03/12 11:39:46 INFO zookeeper.ClientCnxn: Socket connection established
to 192.168.1.42/192.168.1.42:2181, initiating session
14/03/12 11:39:46 INFO zookeeper.ClientCnxn: Session establishment complete
on server 192.168.1.42/192.168.1.42:2181, sessionid = 0x144b4dddfc8000a,
negotiated timeout = 40000

Created a table in hbase
'users', {NAME => 'city'}, {NAME => 'first_name'}, {NAME => 'last_name'}
and when I issue command scan users results in zero rows.
but in persistence.xml I removed couple of line.

 <property name="kundera.cache.provider.class"
value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource"
value="/ehcache-test.xml"/>

```
    </properties>
```

Now it looks like

<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="hbase_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.nodes" value="192.168.1.42"/>
            <property name="kundera.port" value="60010"/>
            <property name="kundera.keyspace" value="KunderaExamples"/>
            <property name="kundera.dialect" value="hbase"/>
            <property name="kundera.client.lookup.class"
value="com.impetus.client.hbase.HBaseClientFactory" />
            <property name="hbase.zookeeper.quorum"
value="192.168.1.42"></property>
<property name="hbase.zookeeper.property.clientPort"
value="2181"></property>
        </properties>
    </persistence-unit>
</persistence>

**Comment by mevivs** [comment]
Hi, 
Properties specific to HBase 

```
   <property name="hbase.zookeeper.quorum" value="192.168.1.42"></property>
<property name="hbase.zookeeper.property.clientPort" value="2181"></property>
```

must be defined with external configuration. Please have a look at:
https://github.com/impetus-opensource/Kundera/wiki/Data-store-Specific-Configuration

AND

https://github.com/impetus-opensource/Kundera/wiki/HBase-Specific-Features

for mapping such properties.

Hope it helps.

-Vivek

**Comment by jeevitesh** [comment]
bit more information which is missed earlier
Hbase server version
HBase Version 0.96.1.1-hadoop2
but in my client hbase point to 0.94.3 is something i need to worry about.
zookeeper I have not installed explicitly. In server zookeeper is hosted
which comes by default with hbase.

**Comment by mevivs** [comment]
For sample persistence.xml, please  refer:
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-hbase/src/test/resources/META-INF/persistence.xml#L20

-Vivek

**Comment by mevivs** [comment]
Kundera HBase apis are compatible with 0.94.3. I assume that 0.96 must be backward compatible!

-Vivek

**Comment by jeevitesh** [comment]
thanks a lot, I'll follow on those lines...

**Comment by jeevitesh** [comment]
Hi vivek,
Still error persists not able to understand for where error is _propagating.
Please i would request your reslve my issue it looks like etc/host file
issue._
ERROR
When I run my Program app.java (
https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes
)
14/03/12 15:38:49 INFO zookeeper.ClientCnxn: Opening socket connection to
server /192.168.1.42:2181
14/03/12 15:38:49 INFO zookeeper.RecoverableZooKeeper: The identifier of
this process is 8084@DELL-75
14/03/12 15:38:49 _WARN client.ZooKeeperSaslClient: SecurityException:
java.lang.SecurityException: Unable to locate a login configuration
occurred when trying to find JAAS configuration._
_14/03/12 15:38:49 INFO client.ZooKeeperSaslClient: Client will not
SASL-authenticate because the default JAAS configuration section 'Client'
could not be found. If you are not using SASL, you may ignore this. On the
other hand, if you expected SASL to work, please fix your JAAS
configuration._
14/03/12 15:38:49 INFO zookeeper.ClientCnxn: Socket connection established
to 192.168.1.42/192.168.1.42:2181, initiating session
14/03/12 15:38:49 INFO zookeeper.ClientCnxn: Session establishment complete
on server 192.168.1.42/192.168.1.42:2181, sessionid = 0x144b5c45aa60005,
negotiated timeout = 40000

Kundera test.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientProperties>
<datastores>
<dataStore>
<name>hbase</name>
<connection>
<properties>
<property name="hbase.zookeeper.quorum" value="192.168.1.42"></property>
<property name="hbase.zookeeper.property.clientPort"
value="2181"></property>
</properties>
</connection>
<schemas>
<schema>
<name>KunderaExamples</name>
<tables>

<table>
<name>users</name>
<properties>
<property name="city" value="UTF8Type" />
<property name="first_name" value="UTF8Type" />
<property name="last_name" value="UTF8Type" />
</properties>
</table>

</tables>
</schema>
</schemas>
</dataStore>
</datastores>
</clientProperties>

persistence.xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
http://java.sun.com/xml/ns/persistence
http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" version="2.0">
    <persistence-unit name="hbase_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.nodes" value="192.168.1.42"/>
            <property name="kundera.port" value="60010"/>
            <property name="kundera.keyspace" value="KunderaExamples"/>
            <property name="kundera.dialect" value="hbase"/>
<property name="kundera.ddl.auto.prepare" value="create" />
            <property name="kundera.client.lookup.class"
value="com.impetus.client.hbase.HBaseClientFactory" />
            <property name="kundera.client.lookup.class"
value="com.impetus.client.hbase.HBaseClientFactory" />
<property name="kundera.client.property" value="kunderaTest.xml" />
        </properties>
    </persistence-unit>
</persistence>

I was bit curious so when I started hbase I looked at log for "error" key
word
zookeeper.ClientCnxn: Opening socket connection to server localhost/
127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
in google when i searched for the above error they all were refering to
etc/hosts file....
mine looks fine to me
192.168.1.42    database     database.companyname.com
127.0.0.1       localhost    localhost.localdomain.com

**Comment by mevivs** [comment]
Seems like your JVM is defaulting to IPv6 traffic. Try adding -Djava.net.preferIPv4Stack=true to your HBASE_OPTS envvar (just a few lines below JAVA_HOME in hbase-env.sh), and restarting HBase.

http://hortonworks.com/community/forums/topic/connecting-with-haredb-hbase-client/

see if it helps

-Vivek

**Comment by jeevitesh** [comment]
hi vivek,
Looks like this the issue with me
https://issues.apache.org/jira/browse/HBASE-2418
http://hbase.apache.org/book/zk.sasl.auth.html
What is your view?

**Comment by jeevitesh** [comment]
Hi vivek,
As per my understanding i feel for Authentication purposes i need to
provide some kind file.. Because any client who gets ip will able to write
. So from verion 91 hbase  to validate client we need to do above steps

Sent from my Windows Phone

**Comment by mevivs** [comment]
```
 Client will not
SASL-authenticate because the default JAAS configuration section 'Client'
could not be found. If you are not using SASL, you may ignore this. On the
other hand, if you expected SASL to work, please fix your JAAS
```

Zookeeper version mismatch issue?

HBase 0.94.3 comes with     <zookeeper.version>3.4.3</zookeeper.version> . Can you please verify if it is same on server as well?  

I believer HBase shell to remotely connect with Server is working fine?

-Vivek

**Comment by jeevitesh** [comment]
Hi vivek,
The version of zookeeper were different in server it was 3.4.5 now copied
the 3.4.3 jar to the following location
Now
/home/hadoop/hadoop-2.2.0/share/hadoop/common/lib/zookeeper-3.4.5.jar
/home/hadoop/hadoop-2.2.0/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/zookeeper-3.4.5.jar
/home/hadoop/hbase-0.96.1.1-hadoop2/lib/zookeeper-3.4.5.jar

Also have set to pick IPV4 disabled IP6 alltogether. using setx
_JAVA_OPTIONS -Djava.net.preferIPv4Stack=true

Some things i noticed while running test

_java.lang.IllegalArgumentException: Not a host:port pair: PBUF_
__
_database�������(_

I guess some were it needs host:port

here are my server logs and client logs I guess need to increase ZK tick
time out

_Server log_
2014-03-13 11:53:35,458 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181]
server.NIOServerCnxnFactory: Accepted socket connection from /
192.168.1.119:14016
2014-03-13 11:53:35,459 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181]
server.ZooKeeperServer: Client attempting to establish new session at /
192.168.1.119:14016
2014-03-13 11:53:35,462 INFO  [SyncThread:0] server.ZooKeeperServer:
Established session 0x144ba1ae3090005 with negotiated timeout 40000 for
client /192.168.1.119:14016
2014-03-13 11:53:35,826 WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181]
server.NIOServerCnxn: Exception causing close of session 0x144ba1ae3090005
due to java.io.IOException: Connection reset by peer
2014-03-13 11:53:35,827 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181]
server.NIOServerCnxn: Closed socket connection for client /
192.168.1.119:14016 which had sessionid 0x144ba1ae3090005

_Client Log_
14/03/13 11:53:02 INFO persistence.EntityManagerFactoryImpl: Loading Core
14/03/13 11:53:02 INFO loader.CoreLoader: Loading Kundera Core Metdata ...
14/03/13 11:53:02 INFO persistence.EntityManagerFactoryImpl: Loading
Persistence Unit MetaData For Persistence Unit(s) hbase_pu.
14/03/13 11:53:02 INFO configure.PersistenceUnitConfiguration: Loading
Metadata from persistence.xml ...
14/03/13 11:53:02 INFO configure.PersistenceUnitConfiguration: Finishing
persistence unit metadata configuration ...
14/03/13 11:53:02 INFO configure.MetamodelConfiguration: No class to scan
for persistence unit hbase_pu. Entities will be loaded from classpath/
context-path
14/03/13 11:53:02 INFO configure.ClientMetadataBuilder: Loading client
factory for persistence unit hbase_pu
14/03/13 11:53:02 INFO client.ClientResolver: Initializing client factory
for: hbase_pu
14/03/13 11:53:02 INFO client.ClientResolver: Finishing factory
initialization
14/03/13 11:53:02 INFO configure.SchemaConfiguration: Configuring schema
export for : hbase_pu
14/03/13 11:53:02 WARN configure.AbstractPropertyReader: File
kunderaTest.xml not found, Caused by
14/03/13 11:53:02 WARN hbase.HBaseConfiguration: instantiating
HBaseConfiguration() is deprecated. Please use HBaseConfiguration#create()
to construct a plain Configuration
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:zookeeper.version=3.4.3-1240972, built on 02/06/2012 10:48 GMT
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client environment:host.name
=DELL-75.unilog
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.version=1.6.0_16
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.vendor=Sun Microsystems Inc.
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.home=C:\Program Files\Java\jdk1.6.0_16\jre
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.class.path=E:\jeevi\XRFWorkSpace200\TestNucleus10\build\classes;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\activation-1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\asm-3.3.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\avro-1.5.3.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\avro-ipc-1.5.3.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\cglib-2.2.2.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-cli-1.2.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-codec-1.4.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-collections-3.2.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-configuration-1.9.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-el-1.0.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-httpclient-3.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-io-2.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-lang-2.4.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-logging-1.1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-math-2.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\commons-net-1.4.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\core-3.1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\guava-13.0.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\hadoop-core-1.1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\hbase-0.94.3.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\high-scale-lib-1.1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\hsqldb-1.8.0.10.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\httpclient-4.1.2.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\httpcore-4.1.3.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jackson-core-asl-1.8.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jackson-jaxrs-1.8.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jackson-mapper-asl-1.8.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jackson-xc-1.8.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jamon-runtime-2.3.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jasper-compiler-5.5.23.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jasper-runtime-5.5.23.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\javassist-3.12.1.GA.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jaxb-api-2.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jaxb-impl-2.2.3-1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jersey-core-1.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jersey-json-1.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jersey-server-1.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jets3t-0.6.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jettison-1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jetty-6.1.26.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jetty-util-6.1.26.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jruby-complete-1.6.5.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jsp-2.1-6.1.14.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jsp-api-2.1-6.1.14.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jta-1.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\jts-1.11.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\junit-4.8.2.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\kundera-core-2.10.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\kundera-hbase-2.10.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\libthrift-0.8.0.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\log4j-1.2.16.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\metrics-core-2.1.2.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\netty-3.2.4.Final.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\oro-2.0.8.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\persistence-api-2.0.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\protobuf-java-2.4.0a.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\servlet-api-2.5-6.1.14.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\slf4j-api-1.7.5.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\slf4j-log4j12-1.6.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\snappy-java-1.0.3.2.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\stax-api-1.0.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\velocity-1.7.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\xmlenc-0.52.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\xmlpull-1.1.3.1.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\xpp3_min-1.1.4c.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\xstream-1.4.3.jar;E:\jeevi\XRFWorkSpace200\TestNucleus10\WebContent\WEB-INF\lib\zookeeper-3.4.3.jar;/E:/eclipse/configuration/org.eclipse.osgi/bundles/399/1/.cp/;/E:/eclipse/configuration/org.eclipse.osgi/bundles/397/1/.cp/;/E:/eclipse/configuration/org.eclipse.osgi/bundles/398/1/.cp/
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.library.path=C:\Program
Files\Java\jdk1.6.0_16\bin;.;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Common Files\Acronis\SnapAPI\;C:\Program
Files\Java\jdk1.6.0_16\bin;C:\apache-maven-3.1.1\bin;C:\Program
Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft ASP.NET\
ASP.NET Web Pages\v1.0\;C:\Program Files\Windows Kits\8.0\Windows
Performance Toolkit\;C:\Program Files\Microsoft SQL
Server\110\Tools\Binn\;E:\jeevi\software\apache-ant-1.9.3\bin;
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.io.tmpdir=C:\Users\jems\AppData\Local\Temp\
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:java.compiler=<NA>
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client environment:os.name=Windows
7
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client environment:os.arch=x86
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:os.version=6.1
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client environment:user.name
=jems
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:user.home=C:\Users\jems
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Client
environment:user.dir=E:\jeevi\XRFWorkSpace200\TestNucleus10
14/03/13 11:53:03 INFO zookeeper.ZooKeeper: Initiating client connection,
connectString=192.168.1.42:2181 sessionTimeout=180000 watcher=hconnection
14/03/13 11:53:03 INFO zookeeper.ClientCnxn: Opening socket connection to
server /192.168.1.42:2181
14/03/13 11:53:03 INFO zookeeper.RecoverableZooKeeper: The identifier of
this process is 5588@DELL-75
14/03/13 11:53:07 WARN client.ZooKeeperSaslClient: SecurityException:
java.lang.SecurityException: Unable to locate a login configuration
occurred when trying to find JAAS configuration.
14/03/13 11:53:07 INFO client.ZooKeeperSaslClient: Client will not
SASL-authenticate because the default JAAS configuration section 'Client'
could not be found. If you are not using SASL, you may ignore this. On the
other hand, if you expected SASL to work, please fix your JAAS
configuration.
14/03/13 11:53:07 INFO zookeeper.ClientCnxn: Socket connection established
to 192.168.1.42/192.168.1.42:2181, initiating session
14/03/13 11:53:07 INFO zookeeper.ClientCnxn: Session establishment complete
on server 192.168.1.42/192.168.1.42:2181, sessionid = 0x144ba1ae3090005,
negotiated timeout = 40000
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

Still the error persists

**Comment by mevivs** [comment]
@jeevitesh 
Can you give it a try with HBase 0.94.3 . it would help to understand if issue is with some configuration or something else

-Vivek

**Comment by mevivs** [comment]
```
14/03/13 11:53:02 WARN configure.AbstractPropertyReader: File
kunderaTest.xml not found, Caused by
14/03/13 11:53:02 WARN hbase.HBaseConfiguration: instantiating
HBaseConfiguration() is deprecated. Please use HBaseConfiguration#create()
to construct a plain Configuration
```

looks like kunderaTest.xml is not in classpath. That could be the issue

-Vivek

**Comment by jeevitesh** [comment]
I moved kunderaTest.xml outside meta-inf folder no longer i'm getting that issue..
But still i'm unable add rows to user table... moving into hbase 0.94.3 lets hope things get settled there

**Comment by mevivs** [comment]
Okay. Let me know, if still it doesn't work for you.

-Vivek

**Comment by jeevitesh** [comment]
Finally it worked for me... really a big thanks to you.. you showed so much of patience in addressing issues.. I'm really happy I don't have words to explain...looking forward to work with you thanks..

I don't know exactly which one resolved the issue..
I switched to hbase 0.94.3 
and after that there was some etc host issue...
in my windows system C:\Windows\System32\drivers\etc

# localhost name resolution is handled within DNS itself.

```
127.0.0.1       localhost
```

# ::1             localhost

192.168.1.42    database

**Comment by mevivs** [comment]
Cool! Great. Looks like we are good to close on this.

-Vivek
