### ISSUE TITLE
Question about entity inheritance

### ISSUE THREAD

**Issue by builtofire** [Impetus/kundera#545]
Hi ALL, sorry to be lame

so can i have this ?

class ACasssandraObject {
   @Column
   private Date dob;

   @Column
   private Date dom;
}

@Entity 
class Customer extends ACassandraObject {
   @Id
   private int id;
   @Column
   private String name;
}

and i should have in the customer table 4 columns ?
because i see that in code you use clazz.getDeclaredFields() and this is not looking and superclasses 
so the question is what am i missing here ? is there another way to define entity inheritance ?

**Comment by mevivs** [comment]
Given below definitions should help you out.

<b>Entities</b>

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/java/com/impetus/kundera/client/crud/inheritence/TwitterProfile.java
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/java/com/impetus/kundera/client/crud/inheritence/FacebookProfile.java

<B>Abstract entity </B>

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/java/com/impetus/kundera/client/crud/inheritence/SocialProfile.java

<B>Mapped super class</B>
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/java/com/impetus/kundera/client/crud/inheritence/GuidDomainObject.java

**Comment by builtofire** [comment]
ok, something makes sense :)

now the second question :

why do i need an id in the abstract class ?
@MappedSuperclass
public abstract class ACasssandraObject {
@Id
private int id;
@Column
private Date dob;
@Column
private Date dom;
}

if i leave out the @id then i get the @id missing error in customer entity

**Comment by mevivs** [comment]
@Id
private int id;

You can keep it with sub class entity as well. Mapped super class is not an entity but attributes can be inherited with sub classes

-Vivek

**Comment by builtofire** [comment]
thanks for the example, it really helped me, but i still feel confused :)

**Comment by mevivs** [comment]
http://docs.oracle.com/javaee/5/api/javax/persistence/MappedSuperclass.html

This should help you out

-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?
