### ISSUE TITLE
Cannot find the latest 2.11 release jar in maven repository

### ISSUE THREAD

**Issue by sumeetchhetriwellogic** [Impetus/kundera#551]
Hi, 

I'm unable to find the latest Kundera 2.11 release jar in the repository mentioned (https://oss.sonatype.org/content/repositories/releases/com/impetus/core/kundera-core/).
Can someone please point me to the correct updated repository or upload the latest jars if not already done.

Thanks,
Sumeet Chhetri

**Comment by mevivs** [comment]
Hi,
ArtifactId has been changed since 2.9.1 onwards. {https://github.com/impetus-opensource/Kundera/tree/trunk/src#note}

https://oss.sonatype.org/content/repositories/releases/com/impetus/kundera/core/kundera-core/2.11/

HTH,
-Vivek

**Comment by mevivs** [comment]
Are we good to close on this?

-Vivek
