### ISSUE TITLE
blob, map and DSClient

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#553]
With Kundera 2.11 and DSClient . 

When a blob is used for a composite key there's a ClassCastException from HeapByteBuffer to byte[]. Same kind of issue when a map< ascii , blob > is used .
Here's an example of schema that doesn't work :
          CREATE TABLE test (
            a uuid,
            b blob,
            c text,
            d blob,
            e text,
            f map < ascii , blob >,
            PRIMARY KEY ((a, b), c, d)
          )

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/commit/3469ddf5259b5fbc7c9f5afbaccc8ac3de10d228

A fix has been added for the same. Also, default character encoding is supported for UTF-8 only. for Ascii support i will open another issue for the same. Rest for blob and other type it should be good to go.

-Vivek

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1
