### ISSUE TITLE
Fail recovery in Cassandra Cluster

### ISSUE THREAD

**Issue by vanessaschissato** [Impetus/kundera#554]
Hi,

We are currently using Kundera 2.11 with a Cassandra Cluster (5 nodes). 
I figure out that when a node fails, Kundera try the next available (my configuration is below).
BUT, when the node is restarted, Kundera doesn't reconnect to this node never more while the application is running.
So, if i stop one node per time, restarting them immediatally (a delivery scenario), so that there isn't more than one node stopped at the same time, Kundera crashs the entire application because doesn't reconnect to a node that has failed before (error stack below).

persistence.xml:

&lt;persistence xmlns=&quot;http://java.sun.com/xml/ns/persistence&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
    xsi:schemaLocation=&quot;http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd&quot;
    version=&quot;2.0&quot;&gt;
    &lt;persistence-unit name=&quot;myPU&quot; transaction-type=&quot;RESOURCE_LOCAL&quot;&gt;
        &lt;provider&gt;com.impetus.kundera.KunderaPersistence&lt;/provider&gt;
        &lt;properties&gt;
            &lt;property name=&quot;kundera.nodes&quot; value=&quot;cassandra1, cassandra2, cassandra3, cassandra4, cassandra5&quot;/&gt;
            &lt;property name=&quot;kundera.port&quot; value=&quot;9160&quot;/&gt;
            &lt;property name=&quot;kundera.keyspace&quot; value=&quot;mykeyspace&quot;/&gt;
            &lt;property name=&quot;kundera.dialect&quot; value=&quot;cassandra&quot;/&gt;
            &lt;property name=&quot;kundera.client.lookup.class&quot; value=&quot;com.impetus.client.cassandra.thrift.ThriftClientFactory&quot; /&gt;
            &lt;property name=&quot;kundera.client.property&quot; value=&quot;KunderaLoadConfig.xml&quot; /&gt; 
        &lt;/properties&gt;
    &lt;/persistence-unit&gt;
&lt;/persistence&gt;

---

KunderaLoadConfig.xml:

&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;clientProperties&gt;
    &lt;datastores&gt;
        &lt;dataStore&gt;
            &lt;name&gt;cassandra&lt;/name&gt;
            &lt;connection&gt;
                &lt;servers&gt;
                    &lt;server&gt;
                        &lt;host&gt;cassandra1&lt;/host&gt;
                        &lt;port&gt;9160&lt;/port&gt;
                        &lt;properties&gt;
                            &lt;property name=&quot;testonborrow&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonconnect&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonreturn&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testwhileidle&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;socket.timeout&quot; value=&quot;5000&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;failover.policy&quot; value=&quot;on.fail.try.one.next.available&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;retry&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                        &lt;/properties&gt;
                    &lt;/server&gt;
                    &lt;server&gt;
                        &lt;host&gt;cassandra2&lt;/host&gt;
                        &lt;port&gt;9160&lt;/port&gt;
                        &lt;properties&gt;
                            &lt;property name=&quot;testonborrow&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonconnect&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonreturn&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testwhileidle&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;socket.timeout&quot; value=&quot;5000&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;failover.policy&quot; value=&quot;on.fail.try.one.next.available&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;retry&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                        &lt;/properties&gt;
                    &lt;/server&gt;
                    &lt;server&gt;
                        &lt;host&gt;cassandra3&lt;/host&gt;
                        &lt;port&gt;9160&lt;/port&gt;
                        &lt;properties&gt;
                            &lt;property name=&quot;testonborrow&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonconnect&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonreturn&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testwhileidle&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;socket.timeout&quot; value=&quot;5000&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;failover.policy&quot; value=&quot;on.fail.try.one.next.available&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;retry&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                        &lt;/properties&gt;
                    &lt;/server&gt;
                    &lt;server&gt;
                        &lt;host&gt;cassandra4&lt;/host&gt;
                        &lt;port&gt;9160&lt;/port&gt;
                        &lt;properties&gt;
                            &lt;property name=&quot;testonborrow&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonconnect&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonreturn&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testwhileidle&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;socket.timeout&quot; value=&quot;5000&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;failover.policy&quot; value=&quot;on.fail.try.one.next.available&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;retry&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                        &lt;/properties&gt;
                    &lt;/server&gt;
                    &lt;server&gt;
                        &lt;host&gt;cassandra5&lt;/host&gt;
                        &lt;port&gt;9160&lt;/port&gt;
                        &lt;properties&gt;
                            &lt;property name=&quot;testonborrow&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonconnect&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;testonreturn&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;socket.timeout&quot; value=&quot;5000&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;failover.policy&quot; value=&quot;on.fail.try.one.next.available&quot;&gt;&lt;/property&gt;
                            &lt;property name=&quot;retry&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                        &lt;/properties&gt;
                    &lt;/server&gt;
                &lt;/servers&gt;
                &lt;properties&gt;
                    &lt;property name=&quot;loadbalancing.policy&quot; value=&quot;roundrobin&quot;&gt;&lt;/property&gt;
                    &lt;property name=&quot;retry&quot; value=&quot;true&quot;&gt;&lt;/property&gt;
                    &lt;property name=&quot;retry.delay&quot; value=&quot;1&quot;&gt;&lt;/property&gt;
                    &lt;property name=&quot;max.wait&quot; value=&quot;3000&quot;&gt;&lt;/property&gt;
                &lt;/properties&gt;
            &lt;/connection&gt;
        &lt;/dataStore&gt;
    &lt;/datastores&gt;
&lt;/clientProperties&gt;

---

Stack trace:

Caused by: com.impetus.kundera.KunderaException: All hosts are down. please check servers manully.
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.getPoolUsingPolicy(ThriftClientFactory.java:195)
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.instantiateClient(ThriftClientFactory.java:181)
    at com.impetus.kundera.loader.GenericClientFactory.getClientInstance(GenericClientFactory.java:245)
    at com.impetus.kundera.persistence.EntityManagerImpl.discoverClient(EntityManagerImpl.java:985)
    at com.impetus.kundera.persistence.EntityManagerImpl.<init>(EntityManagerImpl.java:137)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:246)
    at ...

**Comment by mevivs** [comment]
A fix has been added for the same in current trunk.

**Comment by vanessaschissato** [comment]
When is supposed to be launched the next release with this feature?

**Comment by mevivs** [comment]
A patch release is planned along with Cassandra 2.x upgrade probably in next 3 weeks

-Vivek

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1
