### ISSUE TITLE
Can't write to MariaDB unless autocommit mode is set to true

### ISSUE THREAD

**Issue by makearl** [Impetus/kundera#558]
Hi,

I'm seeing a problem where Kundera can't write to MariaDB unless autocommit mode is set to true in the persistence.xml.

According to MariaDB's documentation, it should be a drop-in replacement for MySQL in hibernate: https://mariadb.com/kb/en/hibernate-mariadb/ 

When I use the same configuration with MySQL instead, I can commit.

Here's what the persistence looks like for MySQL

``` xml
<persistence-unit name="maria_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>environment.model.DeviceString</class>
    <class>environment.model.EnvironmentFactRecord2</class>-->
    <properties>
        <property name="kundera.client.lookup.class" value="com.impetus.client.rdbms.RDBMSClientFactory" />
        <property name="hibernate.show_sql" value="true" />
        <property name="hibernate.format_sql" value="true" />
        <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLInnoDBDialect"/>
        <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
        <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3999/test" />
        <property name="hibernate.connection.username" value="root" />
        <property name="hibernate.current_session_context_class" value="org.hibernate.context.internal.ThreadLocalSessionContext" />
    </properties>
</persistence-unit>
```

Here's what the persistence.xml looks like for MariaDB:

``` xml
<persistence-unit name="maria_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>environment.model.DeviceString</class>
    <class>environment.model.EnvironmentFactRecord2</class>-->
    <properties>
        <property name="kundera.client.lookup.class" value="com.impetus.client.rdbms.RDBMSClientFactory" />
        <property name="hibernate.show_sql" value="true" />
        <property name="hibernate.format_sql" value="true" />
        <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLInnoDBDialect"/>
        <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
        <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/test" />
        <property name="hibernate.connection.username" value="root" />
        <property name="hibernate.current_session_context_class" value="org.hibernate.context.internal.ThreadLocalSessionContext" />
    </properties>
</persistence-unit>
```

I've also tried using the org.mariadb.jdbc.Driver instead of the MySQL driver but had the same issue.

I turned on query logging for both MySQL and MariaDB to compare the results when using the MySQL driver.

Here's the MySQL query log:
140401  8:36:29      13 Connect     root@localhost on test
    13 Query       set autocommit=1
    13 Query       USE test
    13 Query       select @@sql_mode
    13 Query       set autocommit=0
    13 Query       select database()
    13 Query       select devicestri0_.device_id as device1_1_, devicestri0_.device_name as device2_1_ from test.test_device_string devicestri0_
    13 Query       insert into test.test_device_string (device_name, device_id) values ('KunderaDevice', '8')
    13 Query       select devicestri0_.device_id as device1_1_, devicestri0_.device_name as device2_1_ from test.test_device_string devicestri0_

Here's the MariaDB query log:
140401  8:44:48     7 Connect   root@localhost as anonymous on test
    7 Query set autocommit=1
    7 Query USE test
    7 Query select @@sql_mode
    7 Query set autocommit=0
    7 Query select database()
    7 Query select devicestri0_.device_id as device1_1_, devicestri0_.device_name as device2_1_ from test.test_device_string devicestri0_
    7 Query insert into test.test_device_string (device_name, device_id) values ('KunderaDevice', '8')
    7 Query select devicestri0_.device_id as device1_1_, devicestri0_.device_name as device2_1_ from test.test_device_string devicestri0_

The only difference between the two is that root@localhost is connected 'as anonymous' for MariaDB.

No error is thrown by Kundera when this issue occurs. When I look at the console for the results, it looks as though the row was successfully written even when it was not (I do a select all on the table, try to write the row, then do another select all to verify the result):
Hibernate: 
    select
        devicestri0_.device_id as device1_1_,
        devicestri0_.device_name as device2_1_ 
    from
        test.test_device_string devicestri0_
Printing all devices
Device { id = 1, name = DummyDevice}

Hibernate: 
    insert 
    into
        test.test_device_string
        (device_name, device_id) 
    values
        (?, ?)
Persisting: Device { id = 8, name = KunderaDevice}
Hibernate: 
    select
        devicestri0_.device_id as device1_1_,
        devicestri0_.device_name as device2_1_ 
    from
        test.test_device_string devicestri0_
Printing all devices
Device { id = 1, name = DummyDevice}
Device { id = 8, name = KunderaDevice}

Process finished with exit code 0

**Comment by mevivs** [comment]
Version of mysql is > 5.5 ? AFAIK MariaDB built on top of MYSQL 5.5

Kundera relies on Hibernate for RDBMS related persistence, so ideally behavior should be consistent.

-Vivek

**Comment by makearl** [comment]
Sorry, that was a relic from trying all variations of the MySQL dialects.

I've opened a pull request for this issue: https://github.com/impetus-opensource/Kundera/pull/560

The logic for onBegin in HibernateClient.java was inverted, which caused MariaDB to not commit properly.
