### ISSUE TITLE
Please add support for JPA @MappedSuperclass

### ISSUE THREAD

**Issue by dansomething** [Impetus/kundera#56]
We would like to be able to apply mapping information to entities that inherit from a superclass with out having to use entity @Inheritance.  In other words, the superclass doesn't have a corresponding "table."   Please see the javax API: http://docs.oracle.com/javaee/6/api/javax/persistence/MappedSuperclass.html

Thanks,

Dan

**Comment by smecsia** [comment]
+1 for this issue. We have a lot of common logic for the entities. For example, it's very tediously to copy @Id field into each entity class directly.

**Comment by mevivs** [comment]
Partial work done. task listed for 2.4 release.

**Comment by mevivs** [comment]
Support enabled and releasing with 2.8
