### ISSUE TITLE
Auto ID generation in Kundera - hbase

### ISSUE THREAD

**Issue by jeevitesh** [Impetus/kundera#563]
Hi,

found a issue in auto id generation in kundera for hbase.

if I use below code id get generated at interval of 50(i guess is default) like 1, 50, 100 etc 
 @Id
 @GeneratedValue(strategy = GenerationType.TABLE)

It was bit confusing because I have multiple entity and H-rider was not showing in right order.  so wanted to generate in sequence(like 1,2,3,4.. for given entity)
So started with below code

@TableGenerator(name = "id_gen", allocationSize = 1, initialValue = 1)
@GeneratedValue(generator = "id_gen", strategy = GenerationType.TABLE)

It works fine but it has a issue first time it generate id say 1, second time it again generate same id 1 instead it should be 2(I guess it is because allocation size is 1) 
but from third time onwards it is generating properly.

**Comment by kkmishra** [comment]
Fixed in current trunk, Please verify.

Thanks
Kuldeep

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1
