### ISSUE TITLE
Insert with timestamp on Cassandra with Kundera 2.11

### ISSUE THREAD

**Issue by msfbrasil** [Impetus/kundera#575]
Hello there!

First of all, this is most a question than an issue report.

I've tried to use TIMESTAMP insert option of Cassandra using Kundera 2.11 without success, and I would like to know if is there any chance I'm doing it wrong or is, in fact, a known limitation of this version.

First try, I've used "createQuery", but when I've got the first exceptions, during some research, I've found some reports about JPA not supporting INSERT statement and that this kind of operation could be done using native queries.

So, I've changed to "createNativeQuery" like the code below:

this.entityManagerProvider.get().createNativeQuery("INSERT INTO \"newestmetric\" (\"id\", \"value\") VALUES (:id, :value) USING TIMESTAMP :timestamp").setParameter("id", newestMetric.getId()).setParameter("value", newestMetric.getValue()).setParameter("timestamp", timestampInMilliSecs).executeUpdate();

But I'm still getting exceptions.
Digging into Kundera's code, it seems that it doesn't support INSERT statements at all, including with native queries.

Could you guys, please, tell me if this could be done?

Thanks and best regards,
Mauro.

**Comment by mevivs** [comment]
setParameter() will not work over native CQL3 queries. it is only applicable for JPQLs

-Vivek

**Comment by msfbrasil** [comment]
Thanks a lot Vivek.

I'm not familiar with such usage of JPA and JPQL.
I've constructed the insert string with parameters and It worked pretty fine.

Thanks again and best regards,
Mauro.
