### ISSUE TITLE
Index Annotation 

### ISSUE THREAD

**Issue by jossef** [Impetus/kundera#576]
I followed the documentation and applied the Index annotation.
Then i found out that it's deprecated

![image](https://cloud.githubusercontent.com/assets/1287098/2709894/2aa13f9e-c4bb-11e3-83e4-1586e3f21135.png)

What should i do?

**Comment by mevivs** [comment]
Please use 
https://github.com/impetus-opensource/Kundera/blob/trunk/src/jpa-engine/core/src/main/java/com/impetus/kundera/index/Index.java
https://github.com/impetus-opensource/Kundera/blob/trunk/src/jpa-engine/core/src/main/java/com/impetus/kundera/index/IndexCollection.java

## Sample entity

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/PersonCassandra.java

**Comment by jossef** [comment]
Thanks :)
please update https://github.com/impetus-opensource/Kundera/wiki/Schema-Generation
