### ISSUE TITLE
problem sql in .jar

### ISSUE THREAD

**Issue by crcube** [Impetus/kundera#58]
HI, i have a select in kundera, i have two projects in eclipse, one with all the interfaces and objects, and the other is the interface that use the other project, when i run the sql in eclipse it works but when i export the two project to a .jar file i run the jar file i have the next exception 
java.lang.NullPointerException
        at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEvent
Listeners(EntityEventDispatcher.java:54)
        at com.impetus.kundera.persistence.PersistenceDelegator.persist(Persiste
nceDelegator.java:587)
        at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManag
erImpl.java:152)
Any clue?
thanks

**Comment by mevivs** [comment]
Could you please mention version number? using 2.0.5 or 2.0.6-snapshot?

By looking into this error, it looks like your jar does not contain persistence.xml under META-INF folder and that's why entity is not loaded.

Please provide more details, share logs, entity definition etc etc

**Comment by crcube** [comment]
HI, i am ussing kundera-cassandra-2.0.5-jar-with-dependencies
i have in my meta-inf folder two files persistence_2_0.xsd i didn´t made any change in this file and also i have persistence.xml here i have the definicion of the conexion and the class where i have the nosql entity

<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd" version="2.0">
    
    <persistence-unit name="cubenube">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>interfaceLibray.src.beans.nosql.tutorialNOSQL</class>  
        <properties>  
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="test"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>  
            <property name="server.config" value="C:\Program Files (x86)/apache-cassandra/conf/cassandra.yaml"/>  
        </properties>  
    </persistence-unit>
</persistence>

**Comment by mevivs** [comment]
Please share your server log.
