### ISSUE TITLE
Order by doesn't work.

### ISSUE THREAD

**Issue by zeremit** [Impetus/kundera#582]
I wrote a simple project https://github.com/zeremit/kundera-example
I used mongodb.
And try to use order by.
        CriteriaBuilder criteriaBuilder = em.getCriteriaBuilder();
        CriteriaQuery<User> query = criteriaBuilder.createQuery(User.class);
        Root<User> from = query.from(User.class);
        query.select(from.alias("p"));
        query.orderBy(criteriaBuilder.desc(from.get("name")));
        TypedQuery<User> q = em.createQuery(query);
        for(User u: q.getResultList()){
            System.out.println(u);
        }
        System.out.println();
        String jpql = "Select u from User u order by p.name DESC ";
        q = em.createQuery(jpql,User.class);
        for(User u: q.getResultList()){
            System.out.println(u);
        }
        System.out.println();
        jpql = "Select u from User u order by NAME DESC ";
        q = em.createQuery(jpql,User.class);
        for(User u: q.getResultList()){
            System.out.println(u);
        }
The result is:
User{userId='5359773544ae212642e39e7f', name='John', surname='Smith'}
User{userId='5359773544ae212642e39e80', name='Alex', surname='Smith'}
User{userId='5359773544ae212642e39e81', name='Dane', surname='Smith'}

User{userId='5359773544ae212642e39e7f', name='John', surname='Smith'}
User{userId='5359773544ae212642e39e80', name='Alex', surname='Smith'}
User{userId='5359773544ae212642e39e81', name='Dane', surname='Smith'}

User{userId='5359773544ae212642e39e7f', name='John', surname='Smith'}
User{userId='5359773544ae212642e39e81', name='Dane', surname='Smith'}
User{userId='5359773544ae212642e39e80', name='Alex', surname='Smith'}

The correct result is the last three row.

**Comment by chhavigangwal** [comment]
Looking into the issue. Will soon update.

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1
