### ISSUE TITLE
DSClientFactory and Session

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#583]
Right now the Session are created and closed on every operations in DSClientFactory  which isn't optimal based on the API.

http://www.datastax.com/drivers/java/2.0/com/datastax/driver/core/Session.html

“ … A session holds connections to a Cassandra cluster, allowing it to be queried. Each session maintains multiple connections to the cluster nodes, provides policies to choose which node to use for each query (round-robin on all nodes of the cluster by default), and handles retries for failed query (when it makes sense), etc...
Session instances are thread-safe and usually a single instance is enough per application. However, a given session can only be set to one keyspace at a time, so one instance per keyspace is necessary. “

**Comment by mevivs** [comment]
Make sense. Will make this change.

-Vivek

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1
