### ISSUE TITLE
a function which gets rowid as soon as I set the value

### ISSUE THREAD

**Issue by jeevitesh** [Impetus/kundera#584]
Need to find a function or feature where in I can know rowid as soon as I set the value and use persists. The workaround which I can think of is using select. Any other features...
thanks in advance

**Comment by kkmishra** [comment]
Hi,

Are you using auto generation for id and for which database?

Id field of persisting object get updated after persist, so you can get Id from that object as well.

-Kuldeep

**Comment by jeevitesh** [comment]
Yes I'm using autogeneration for Hbase.
Thanks it works
