### ISSUE TITLE
v2.11 - cassandra - InvalidRequestException(why:Unknown identifier key)

### ISSUE THREAD

**Issue by Rastusik** [Impetus/kundera#585]
When trying to persist an entity to cassandra, Kundera assumes, that the entity identifier's column name is "key".

Example - I have an entity like this:

```
@Entity
@Table(name="test", schema="test@cassandra_pu")
public class TestEntity
{
    @Id
    protected Integer id;

    @Column
    protected String title;
...
}
```

when I try to call 

```
entityManager.persist(testEntityInstance);
```

I'm getting this error:

Error during executing query BEGIN BATCH   INSERT INTO "test"("title","key") VALUES('titleTest',1)  APPLY BATCH, Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:Unknown identifier key)

Kundera somehow assumes, that the id property from the entity should be assigned to a column in cassandra namespace with the name 'key'.

btw. I have donloaded Kundera from the maven repository. The version 2.9.1 didn't have this problem.

**Comment by Rastusik** [comment]
I have just downloaded the 2.11.1 version (released just a couple of hours ago) and it seems like this issue is fixed already.

**Comment by Rastusik** [comment]
So, today I found the cause of the problem - it's the CassandraUtilities class, getIdColumnName() method.

Since the CassandraConstants.CQL_VERSION key is missing in the externalProperties HashMap, this method tries to find out, whether the entity class uses some of the CQL3 types in it's columns. My example entitie's columns use only basic types, so this code:

..
return isCql3Enabled || containsBasicCollectionField ? ((AbstractAttribute) m.getIdAttribute())
                .getJPAColumnName() : CassandraConstants.CQL_KEY;
..

returns 'key' instead of the real column name.

The fast fix would be to create an unused set or list or map column, but could somebody fix this issue properly, please? 

Thank you!

**Comment by chhavigangwal** [comment]
Looking into the issue will get this fixed.

**Comment by kkmishra** [comment]
I think it is a case of cql and thrift interoperability, that is you have created column families using cqlsh, and using kundera-cassandra in thrift way.

If you are creating column families using cqlsh then it is recommended to use kundera-cassandra in cql3 way.
To use kundera-cassandra in cql3 way just do the following while creating EntityManagerFactory.

```
 Map<String, String> propertyMap = new HashMap<String, String>();
 propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);

 EntityManagerFactory emf = Persistence.createEntityManagerFactory("pu-name", propertyMap);
```

Hope it will work for you.

Thanks 
Kuldeep

**Comment by Rastusik** [comment]
Thanks, I will try it as soon as possible, but I am leaving for a week now.

**Comment by Rastusik** [comment]
it seems that the code snipplet from @kkmishra worked for me, the issue with CQL3 detection hasn't occured anymore.. shall I close the issue?

thank you very much for your help!

**Comment by chhavigangwal** [comment]
+1 
Please close the issue.

Chhavi
