### ISSUE TITLE
cassandra - high concurrency read-write app problems

### ISSUE THREAD

**Issue by Rastusik** [Impetus/kundera#587]
I'm implementing an app, which is generating hundreds of thousands rows in 4 threads. Each thread opens a separate connection to cassandra.

Every item of the table has a unique hash identifier (String), but the primary key is an uuid.

The process of the item persisting is the following:

1) The item is created and its hash is computed. 
2) Then a lookup for the hash is being executed in a second table, which pairs hashes accordingly to the item's uuids.
3) If a hash - uuid pair is found, a lookup for the items uuid is being executed (1st table again) and since the item has to exist (because an hash - uuid pair was found), the item is loaded from cassandra to JPA and it's updated afterwards. When no hash - uuid pair is found, a new item is created in the corresponding table and a new "hash - uuid" pair is saved as well.

The data generation has two steps. The first step is running with empty tables and generates the first datasets. No errors happen there, because in the step nr. 3, a "hash - uuid" pair is never found, so no updates occur.

In the second step, the whole algorithm runs again, but already on populated data tables. In this step, random errors occur while reading the data items byt their correspnding uuids (primary keys) - sometimes the server doesn't retun complete text data (proper JSON strings are stored in the table, but incomplete JSON strings are retrieved into the application).

I'm completely sure, that my algorithm is correct, because the same algorithem worked with hibernate and mysql, even with postgresql (but since I need faster writes, I'm playing around with cassandra).

Has anybody an idea, how this behaviour could occur? Is there a bug in the datastax cassandra driver or in Kundera? Or am I using cassandra wrong and the database shouldn't be used this way?

**Comment by chhavigangwal** [comment]
Can you please share sample entities and emf operation code snippet ?

**Comment by Rastusik** [comment]
I am using following entities:

```
@Entity
@Table(name="test", schema="test@cassandra_pu")
public class Test
{

    @Id
    @Column(name = "id")
    protected UUID id;

    @Column(name = "test_id1")
    protected Integer testId1;

    @Column(name = "test_id2")
    protected Integer testId2;

    @Column
    protected Integer degree = 0;

    @Column
    protected String type;

    @Column(name = "test_set")
    @ElementCollection
    protected Set<Integer> testSet;

    @Column
    protected String points;

    @Column(name="test_lists")
    protected String testLists;

    @Column(name="other_lists")
    protected String otherLists;

    @Column(name="hash")
    protected String hash;

// getters and setters
}

@Entity
@Table(name="test_hash_ids", schema="test@cassandra_pu")
public class TestHashIds
{

    @Id
    @Column(name = "hash")
    protected String hash;

    @Column(name = "test_id")
    protected UUID testId;

    @Column
    protected Set<Integer> foo; // because of the bug #585 
// getters and setters
}
```

The basic process is like this:

```
        Test test = new Test();
// setting data to test ...
        String precomputedHash = test.getHash();

        TestHashIds oldTestHashId = testHashIdsRepository.find(precomputedHash);

        if (oldTestHashId == null) {
            test.setId(UUID.randomUUID());
        } else {
            Test oldTest = testRepository.find(oldTestHashId.getTestId());
            test = oldTest;
        }

        ttfE.getTestSet().add(someInteger);
```

after I collect at least 100 entities, I run this:

```
            for (Test test : newTestList) {
                testRepo.persist(test);
            }

            for (Test test : newTtfList) {
                TestHashIds hashId = new TestHashIds(test.getHash(), test.getId());
                testHashRepo.persist(hashId);
            }

            cassaRepository.flush();
            cassaRepository.clear();
```

The process runs in 2 steps, all the above code runs for the first time on with an empty database, after that it runs with the generated data from the first step. 

When running in 2 separate threads, no errors or exception occur, but when running in more threads (each thread has a separate connection to cassandra), wrong data is delivered to the JPA layer (to the entities). Also, the rrors occur only in the second step (when running on previously generated dataset).

I create separate connections like this: 

```
em = entityManagerFactory.createEntityManager();
em.setProperty(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
em.setFlushMode(FlushModeType.COMMIT);
```

entity manager factory is initialised this way:

```
LocalContainerEntityManagerFactoryBean emf = new LocalContainerEntityManagerFactoryBean();
        emf.setPersistenceProviderClass(KunderaPersistence.class);
        emf.setPersistenceUnitName("cassandra_pu");
```

I am using Kundera with Spring 4.0 with AnnotationConfigApplicationContext, the persistence.xml file is in the correct place.

My Json encoding function becomes this string as input:

```
[[80,20,0,0,0],[98,20,0,1,0],[158,20,0,2,0],[218,20,0,3,0],[278,20,0,4,0]]

                                                                          test_lists
                                                                                     L[[[15,3,85208]],[[15,3,85175]],[[15,3,85176]],[[15,3,85177]],[[15,3,85178]]]
                                                                                                                                                                  test_id1

other_lists
            [[15,3]]
test_id2
```

another example:

```
[[465,47,0,0,0]]

                test_lists
                           [[[3196,3195,104985]]]
                                                 test_id1

                                                                |
other_lists
[[3196,3195]]
```

sometimes the JSON string gets truncated, e.g. this:

```
[[465,4
```

All this only happens when there are more then 2 concurrent threads.

Am I creating the separate connections in a wrong way, or is there a bug somewhere? Any other ideas?

**Comment by Rastusik** [comment]
when I was using hibernate for data persisting, the code worked correctly

**Comment by kkmishra** [comment]
Please provide the code which is working fine with mysql, because that would help to dig out the problem easily.

Thanks 
Kuldeep

**Comment by Rastusik** [comment]
the code which is working with mysql is the same, it just works with hibernate entities and hibernate repositories, no difference there, even with 6-8 parallel worker  threads I get no errors (I haven't tried more, because there's no need to do that).

the main problem is, that Kundera Entities become wrong data from JPA. In the 1st data example above, the Json string I'm storing in Cassandra is 

```
[[80,20,0,0,0],[98,20,0,1,0],[158,20,0,2,0],[218,20,0,3,0],[278,20,0,4,0]]
```

but the entity becomes also the data from other cassandra columns in the string, which is supposed to be only the json string for the column called 'test_set' - when you look at the first data example again, there is also the following data in the string:

```
test_lists
                                                                                     L[[[15,3,85208]],[[15,3,85175]],[[15,3,85176]],[[15,3,85177]],[[15,3,85178]]]
                                                                                                                                                                  test_id1

other_lists
            [[15,3]]
test_id2
```

which is wrong. There is also some data from other columns. Maybe there is an error in the parsing process? Either in Kundera or in the Cassandra driver.

**Comment by kkmishra** [comment]
Hi,

Could you please share your working project?
That would help us to find out the problems.

On Wed, May 7, 2014 at 7:55 PM, Rasta notifications@github.com wrote:

> the code which is working with mysql is the same, it just works with
> hibernate entities and hibernate repositories, no difference there, even
> with 6-8 parallel worker threads I get no errors (I haven't tried more,
> because there's no need to do that).
> 
> the main problem is, that Kundera Entities become wrong data from JPA. In
> the 1st data example abov, the Json string I'm storing in Cassandra is
> 
> [[80,20,0,0,0],[98,20,0,1,0],[158,20,0,2,0],[218,20,0,3,0],[278,20,0,4,0]]
> 
> but the entity becomes also the data from other cassandra columns in the
> string, which is supposed to be only the json string for the column called
> 'other_lists' - when you look at the first data example again, there is
> also the following data in the string:
> 
> test_lists
>                                                                                      L[[[15,3,85208]],[[15,3,85175]],[[15,3,85176]],[[15,3,85177]],[[15,3,85178]]]
>                                                                                                                                                                   test_id1
> 
> other_lists
>             [[15,3]]
> test_id2
> 
> which is wrong. Maybe there is an error in the parsing process?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/587#issuecomment-42433232
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by Rastusik** [comment]
Hi, I would prefer not to publish my project. I will try to create my entity manager factory as told in #585 and see, if the problem still occurs. Anyway, I'm going away for a week, so I'll provide the feedback later. Thanks for help.

**Comment by Rastusik** [comment]
So now I'm creating the entity manager factory as suggested in #585, but nothing happens, same errors occur. I checked the number of active connections to cassandra and I got 20 of them, so the connections are opened as expected (every thread opens a new connection in a fixed thread pool, but only 4 of them are active, e.g. are writing and reading data). Could it be that there is a piece of unsynchronized code in Kundera which creates the conflicts? 

Did anybody try to do a similar job/workload with cassandra and kundera?

**Comment by mevivs** [comment]
Just to summarize, basically it is happening in case of : 
1. Data with same hash - uuid is present, means in case of update
2. Working fine with 2 concurrent threads but creating issue with more than > 2, please confirm.
3.  I can see UUID is generated via random function, what about the hash function?

Finally, about JSON string, can you please provide more detail how actually it is getting mapped with Cassandra and entity field which represents for this JSON string? Also, how this string is getting populated.

@kkmishra 
I second that, a sample project to replicate issue at our end can be a great input to quickly resolve it!

Thanks,
-Vivek

**Comment by Rastusik** [comment]
1) correct
2) correct (but I cannot confirm that on other computers it would work in the same way, it's just an inaccurate observation on my setup)
3) the hash function is a md5 checksum generated from the data of the data structure, but there is no problem with my app algorithm or checksum generation, I designed the algorithm to work with no conflicts at all, I'm 100% sure that there are no hash collisions, because when I switch to mysql or postgres, there are no errors.

I suspect that there might be 3 causes of the problem:
1) I am not initialising Kundera correctly (but I'm doing that as suggested in #585 )
2) non thread safe parsing problem in the Cassandra driver (not very likely)
3) non thread safe parsing problem in JPA/Kundera while setting entity data after read operations from cassandra

Yeah, well, or I did something stupid, that's a possibility too :)

I would prefer not to publish my app. The other thing is, that tha app is working with a 16 GB dataset, so it might be quite complicated get everything online...

About the JSON string mapping:

it is mapped as a String:

```
@Column(name="test_lists")
protected String testLists;
```

So I'm working with a string here. I have a decorator class, which encapsulates the entity and overrides its getters and setters like this:

```

    /**
     *
     * @return
     */
    @Override
    public IntArray2D getTestLists()
    {
        if (testLists == null) {
            try {
                testLists = IntArray2D.fromJson(getDecoratedEntity().getTestLists());
            } catch (Exception e) {
                System.out.println("JSON ERROR:");
                System.out.println(getId());
                System.out.println(getDecoratedEntity().getTestLists());
            }
        }
        return testLists;
    }

    /**
     *
     * @param points
     * @return
     */
    @Override
    public final DecoratedEntity setTestLists(IntArray2D testLists)
    {
        this.testLists = testLists;
    }

```

JSON data encoding occurs elsewhere, before the data is flushed to the database.

The output of the exception handler when an arror occurs is the following (I don't include the json decoding method, because the problem is the wrong input):

```
JSON ERROR:
f516d3f5-1939-4209-ad89-85c5644685ab
[[12,3,0,0,0],[
```

sometimes the input data is the following (the box is scrollable horizontally):

```
JSON ERROR:
c0be8f01-0e4d-4884-b61f-5cd348df84f9
(org.apache.cassandra.db.marshal.UTF8Typeid(org.apache.cassandra.db.marshal.UUIDType
                                                                                       UTF8Type
                                                                                              UTF8Type32,9,0,9,0],[438,9,0,10,0],[444,8,0,11,0],[456,9,0,12,0],[466,9,0,13,0],[473,9,0,14,0],[492,9,0,15,0],[498,9,0,16,0],[504,8,0,17,0],[526,9,0,18,0],[533,9,0,19,0],[546,9,0,20,0],[552,9,0,21,0],[564,8,0,22,0],[576,9,0,23,0],[586,9,0,24,0],[593,9,0,25,0],[612,9,0,26,0],[618,9,0,27,0],[624,8,0,28,0],[646,9,0,29,0],[653,9,0,30,0],[672,9,0,31,0],[678,9,0,32,0],[684,8,0,33,0],[706,9,0,34,0],[713,9,0,35,0],[732,9,0,36,0],[744,8,0,37,0],[766,9,0,38,0],[773,9,0,39,0],[780,9,0,40,0],[792,9,0,41,0],[804,8,0,42,0],[826,9,0,43,0],[833,9,0,44,0],[846,9,0,45,0],[852,9,0,46,0],[858,9,0,47,0],[864,8,0,48,0],[876,9,0,49,0],[886,9,0,50,0],[893,9,0,51,0],[912,9,0,52,0],[918,9,0,53,0],[924,8,0,54,0],[936,9,0,55,0],[947,9,0,56,0],[953,9,0,57,0],[972,9,0,58,0],[978,9,0,59,0],[985,9,0,60,0],[991,9,0,61,0],[996,9,0,62,0],[1006,9,0,63,0],[1013,9,0,64,0],[1032,9,0,65,0],[1038,9,0,66,0],[1044,8,0,67,0],[1049,10,0,68,0],[1056,9,0,69,0],[1066,9,0,70,0],[1073,9,0,71,0],[1086,9,0,72,0],[1092,9,0,73,0],[1098,9,0,74,0],[1104,8,0,75,0],[1116,9,0,76,0],[1126,9,0,77,0],[1133,9,0,78,0],[1140,41,0,79,0],[1152,9,0,80,0],[1158,9,0,81,0],[1164,8,0,82,0],[1186,9,0,83,0],[1193,9,0,84,0],[1212,9,0,85,0],[1218,9,0,86,0],[1224,8,0,87,0],[1246,9,0,88,0],[1253,9,0,89,0],[1266,9,0,90,0],[1284,8,0,91,0],[1306,9,0,92,0],[1313,9,0,93,0],[1320,41,0,94,0],[1344,8,0,95,0],[1366,9,0,96,0],[1373,9,0,97,0],[1392,9,0,98,0],[1404,8,0,99,0]]
```

the IntArray2D is a custom type, basically an encapsulated ArrayList<ArrayList<Integer>>, which has a toJson() method:

```
    /**
     *
     * @return
     */
    public String toJson()
    {
        Gson gson = new Gson();
        return gson.toJson(((IntArray2D) this).toArrayList());
    }
```

I don't suspect any trouble here cause it works with sql databases...

**Comment by Rastusik** [comment]
I created a sample app which reproduces the problem (as @kkmishra and @mevivs requested). You can download the sources from this link:
https://www.dropbox.com/s/1lhlf462yj2abvu/KunderaThreadTest.zip

Inside the zip archive, there is a maven project with a simpler demonstration of my problem (the problem still occures in the simpler version).

To run it correctly, you have to update the persistence.xml file for the correct setup for the cassandra connection. The sample data is provided in the init_data.cql file.

I hope that this helps to solve the problem. Thanks very much for your help!

**Comment by Rastusik** [comment]
has anybody tested the included app?

**Comment by chhavigangwal** [comment]
Hi,

The team was busy with 2.12 release and hence did not get a chance to test the project.
Will now test the shared project and share the findings.

Chhavi

**Comment by kkmishra** [comment]
Hi @Rastusik 

There is nothing in application.properties.
Is there any property which should be in application.properties?

Thanks
Kuldeep

**Comment by Rastusik** [comment]
Hi @kkmishra 
No, there should be nothing inside the application properties, I just let it there empty. You must understand, that the sample project is extracted from my working project, just for the demonstration purposes. In the working project, there is hibernate configuration inside, maybe also something else, but nothing is necessary to demonstrate the problem in the sample app.

Why are you asking? Is there any other issue while running the app?

**Comment by kkmishra** [comment]
Hi @Rastusik 
Actually It was referred in one class and so wanted to check why is it empty?

Also, in order to better analyze and resolve the issue it will good to connect once, can you please share your gmail id or any other messenger id for further discussion? Or you can also connect me at kuld.cs.mishra@gmail.com.

Thanks
Kuldeep

**Comment by Rastusik** [comment]
Yeah, it's just because I have made a copy of my real project and emptied the file, because there was nothing important for the sample project ... The file has really no importance in the sample project, I just stripped my project off from all irrelevant things, some empty config files or simple classes may have stayed in there.

I have sent you my contact info to your gmail address, feel free to contact me any time.

Thanks for your help.

**Comment by Rastusik** [comment]
I suspect a problem in the thrift client factory somewhere in the connection pooler maybe, but that's just a guess after I have walked through the code ...

**Comment by Rastusik** [comment]
@kkmishra is anybody working on this issue right now? I'm just asking about the status. Thanks.

**Comment by kkmishra** [comment]
Yes, we are working on it. Planning to release with 2.13.

Thanks
Kuldeep

**Comment by tsbatista** [comment]
+1 I've been seeing a lot of null values read from cassandra when I'm sure the entries contain valid data. I was using 2.9. I have just updated to 2.12, and will retest under load soon.

Is there anything I can do to help resolve this?

**Comment by kkmishra** [comment]
Hi,

Kundera implementation for EntityManager is non thread-safe . So please try and use one EntityManager per thread so that each thread can run independently without affecting the other.

Hope that Helps!
Kuldeep

**Comment by mevivs** [comment]
@kkmishra  

Non thread safe em means, thinking entityManager as a session and multiple threads within same session can't  be spooned!

-Vivek

**Comment by Rastusik** [comment]
@kkmishra @mevivs as far as I know I'm using a separate session for each thread. in my example application. feel free to prove me wrong :) 

but nevermind, I found a simpler library which works under my workload.

**Comment by Rastusik** [comment]
I have run my test app with Kundera 2.13 and it seems to work.

Should I close this issue?

**Comment by kkmishra** [comment]
Cool.. go head and close the issue!

On Tue, Jul 8, 2014 at 2:48 AM, Rasta notifications@github.com wrote:

> I have run my test app with Kundera 2.13 and it seems to work.
> 
> Should I close this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/impetus-opensource/Kundera/issues/587#issuecomment-48242513
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by Rastusik** [comment]
thanks for the fix ;)
