### ISSUE TITLE
Association state lost after persistence

### ISSUE THREAD

**Issue by dansomething** [Impetus/kundera#59]
We are experiencing the loss of state after persistence in case of association handling.  The association fields are being set to null.  However, the persist and find method works correctly.  Currently we are working around this issue by re-retrieving the associations after persisting the parent object.   Please see the group discussion for more info.

https://groups.google.com/forum/?fromgroups#!topic/kundera-discuss/jzvFrtBDk9o

**Comment by mevivs** [comment]
Should be working fine with 2.0.6 now with latest persistence context related changes.

-Vivek

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/issues/33, duplicate?

**Comment by dansomething** [comment]
Ok, thanks.  We'll upgrade to 2.0.6 and verify as soon as we can.

**Comment by mevivs** [comment]
Great!

**Comment by dansomething** [comment]
We verified that this is fixed in 2.0.6.  Thanks for the fix!
