### ISSUE TITLE
Problem in Cassandra pagination over composite keys

### ISSUE THREAD

**Issue by vanessaschissato** [Impetus/kundera#593]
I'm trying to make a pagination in Cassandra using composite keys.
CQL 3 (cassandra >= 2.0.6) allow this: https://issues.apache.org/jira/browse/CASSANDRA-4851

Entity 'Tag':

@Entity
@Table(name = "tags", schema = "a")
public class Tag {

@EmbeddedId
private TagId id;

// setters e getters
}

Entity 'TagId':

@Embeddable
public class TagId
{
@Column(name = "keya") // <----------- PARTITION KEY
private String keya;

@Column(name = "keyb")
private String keyb;

@Column(name = "keyc")
private String keyc;

```
// setters e getters
```

}

My query:

em..createNativeQuery("SELECT \* FROM tags"
                    + " WHERE keya = '" + tag.getKeya() + "'"
                    + " AND (host, metric) >= ('" + tag.getKeyb() + "', '" + tag.getKeyc() + "')"
                    + " LIMIT " + limit + " ALLOW FILTERING",
                    Tag.class);

My Stack Trace:

12 May 2014 13:59:17.934 [pool-3-thread-7] ERROR com.impetus.client.cassandra.CassandraClientBase - Error during executing query SELECT \* FROM tags WHERE keya = 'test' AND (host, metric) >= ('', '') LIMIT 51 ALLOW FILTERING, Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:line 1:63 missing EOF at '>=') .
12 May 2014 13:59:17.936 [pool-3-thread-7] ERROR com.impetus.client.cassandra.CassandraClientBase - Error while executing native CQL query Caused by {}.
javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: InvalidRequestException(why:line 1:63 missing EOF at '>=')
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1887)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2040)
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:854)
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:906)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:143)
    at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:937)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:161)
    at (...)

**Comment by chhavigangwal** [comment]
Trying on which version of Kundera ?

**Comment by vanessaschissato** [comment]
2.11.1

**Comment by chhavigangwal** [comment]
Few things :
1) Kundera-2.11.1 is currently stable to be used with Cassandra 2.0.4 
2) However , I tried running the following query with Cassandra 2.0.7 running as a standalone server :  
 Query q = em.createNativeQuery("SELECT \* FROM \"CompositeUser\""
                + " WHERE \"userId\" = '" + key.getUserId() + "'"
                + " AND (\"tweetId\", \"timeLineId\") >= (" + key.getTweetId() + ", " + key.getTimeLineId() + ")" + " LIMIT 51 ALLOW FILTERING",
                CassandraPrimeUser.class);

and this seems to be running fine.
3)  host, metric fields map to which field in your schema?

Chhavi

**Comment by vanessaschissato** [comment]
My real schema is below (i simplified this in the example above, but forgot to change in the logs):

CREATE TABLE tags (
    customer text,
    host text,
    metric text,
    PRIMARY KEY (customer, host, metric)
);

em.createNativeQuery(
                                                        "SELECT \* FROM \"tags\""
                                                       + " WHERE \"customer\" = '" + tag.getCustomer() + "'"
                                                       + " AND (\"host\", \"metric\") >= ('" + host + "', '" + metric + "')"
                                                        + " LIMIT " + limit,
                                                        Tag.class)

**Comment by chhavigangwal** [comment]
Tried running the same query along with the defined schema on Cassandra 2.0.6 and 2.0.7  both and it works fine . Which version of Cassandra are you using?

Can you share some more details of your app?

Chhavi
