### ISSUE TITLE
External Properties Not Honored For Neo4J

### ISSUE THREAD

**Issue by ghost** [Impetus/kundera#594]
Looks like the neo4j client factory never looks at external properties when instantiating GraphDatabaseService,  it only looks at what's in the puMetadata.  

```
        Properties props = puMetadata.getProperties();
        String datastoreFilePath = (String) props.get(PersistenceProperties.KUNDERA_DATASTORE_FILE_PATH);
        if (StringUtils.isEmpty(datastoreFilePath))
        {
            throw new PersistenceUnitConfigurationException(
                    "For Neo4J, it's mandatory to specify kundera.datastore.file.path property in persistence.xml");
        }

```

Looks like a bug to me.

**Comment by chhavigangwal** [comment]
Its an issue and needs to be fixed . Will discuss with the team if we can provide a fix for the same in 2.12 release. 
However , as the fix is not major and if its too critical and impacting your current work would you like to contribute a pull request for same?

Chhavi

**Comment by ghost** [comment]
Yes, i will go ahead and submit a pull request soon. 

Thanks
Manish

**Comment by ghost** [comment]
Looks like this is already fixed in trunk.

**Comment by chhavigangwal** [comment]
Got it fixed. Thanks.
Are we good to close on this issue ?

Chhavi
