### ISSUE TITLE
isTokenAware configuration property does not work

### ISSUE THREAD

**Issue by ngrigoriev** [Impetus/kundera#598]
I have not tested it but I have spotted a problem in the code while looking for the policy logic (DSClientFactory class):

```
    if (loadBalancingPolicy != null && StringUtils.isBlank(isTokenAware) && Boolean.valueOf(isTokenAware))
    {
        loadBalancingPolicy = new TokenAwarePolicy(loadBalancingPolicy);
    }
```

Most likely it is meant to be !isBlank(). Which is, in fact, not needed - using Boolean.valueOf() would be enough.

**Comment by mevivs** [comment]
Valid point. Would you like to contribute? Not sure but may need to handle Npe a well
+1 for change

-vivek

**Comment by ngrigoriev** [comment]
Sure, will be my pleasure. No, Boolean.valueOf() handles nulls. However, I think a unit test would be probably needed...I did not check if there was a test for handling of this property or not.

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/cassandra-ds-driver/src/test/java/com/impetus/kundera/client/cassandra/dsdriver/DSClientExternalPropertyTest.java

it is there.but looks like doesn't handle this scenario.

Thanks again,
-Vivek

**Comment by ngrigoriev** [comment]
Looks like there is another place in the same file:

```
String isTokenAware = (String) props.get("isLoggingRetry");

 if (retryPolicy != null && StringUtils.isBlank(isTokenAware) && Boolean.valueOf(isTokenAware))
    {
        retryPolicy = new LoggingRetryPolicy(retryPolicy);
    }
```

Will take care of that one too.

**Comment by mevivs** [comment]
My bad. Definitely I missed things. Copy paste effect. Thanks for fixing it

Cheers,
-Vivek

**Comment by ngrigoriev** [comment]
Vivek,

Do I need anything special in the environment to run your unit tests? Specifically, I am trying to run DSClientExternalPropertyTest. No luck on my Mac, runs out file descriptors when opening the sockets. I have tried to raise the limits until I killed my system ;) Trying now on a Linux box, not any better:

Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 48.171 sec <<< FAILURE!
missingPropertyTest2(com.impetus.kundera.client.cassandra.dsdriver.DSClientExternalPropertyTest)  Time elapsed: 5.178 sec  <<< ERROR!
com.impetus.kundera.configure.schema.SchemaGenerationException: org.apache.thrift.transport.TTransportException
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.create(CassandraSchemaManager.java:232)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:256)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:112)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:146)
....
Caused by: org.apache.thrift.transport.TTransportException
    at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
    at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
Results :

Tests in error:
  missingPropertyTest2(com.impetus.kundera.client.cassandra.dsdriver.DSClientExternalPropertyTest): org.apache.thrift.transport.TTransportException

I want to be able to run the tests before committing the change because I have a feeling that the tests will need to be adjusted. The effective policy will change after the fix and I see the tests are verifying the class name of the configured policy.

**Comment by mevivs** [comment]
Can you share your patch. let me take care of this test case. What's the thrift rpc_port setting? 9160 or different?

Cheers,
-Vivek

**Comment by ngrigoriev** [comment]
https://gist.github.com/ngrigoriev/a359d19c9c35c490b0dc

**Comment by ngrigoriev** [comment]
Also I did not configure anything for the tests - I was assuming it would use the default settings since the test starts embedded Cassandra, creates keyspace etc.

**Comment by mevivs** [comment]
@ngrigoriev 
Thanks. i will get this merged. Although a pull request could have been better.

-Vivek

**Comment by ngrigoriev** [comment]
@mevivs 

I can do a pull request, just was not comfortable about submitting something that may break the test(s) and not being able to try the tests

**Comment by chhavigangwal** [comment]
Merged the changes.
Thanks for contributing. 

Chhavi

**Comment by chhavigangwal** [comment]
Are we good to close on this ?

Chhavi

**Comment by ngrigoriev** [comment]
yes, thanks!
