### ISSUE TITLE
support for LatencyAwarePolicy

### ISSUE THREAD

**Issue by ngrigoriev** [Impetus/kundera#599]
It would be nice to support LatencyAwarePolicy in addition to DCAwareRoundRobinPolicy and RoundRobinPolicy.

**Comment by chhavigangwal** [comment]
+1
Would you like to share a pull request for same ?

Chhavi

**Comment by ngrigoriev** [comment]
will do - please assign to me

**Comment by chhavigangwal** [comment]
You can go ahead and submit a pull request even if the issue not being assigned to you :)
Please share the same.

Chhavi

**Comment by chhavigangwal** [comment]
Fixed releasing with 2.13
