### ISSUE TITLE
Kundera Datastax Distributed Persistence

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#600]
I am in trouble while persisting data in Cassandra using Kundera-Datastax, The control never comes back after em.persist(object) method is called. There is no exception on either client or the server side. However, the code works fine on a single node. I am using Kundera-Cassandra 2.11.1. I have a 3 node cluster with replication factor =2 and consistency level=1. I have specified all three nodes in server-connection-config.xml file. In my case I have only one seed node which I have specified on all nodes in Cassandra.yaml configuration file.

**Comment by chhavigangwal** [comment]
Any updates ? Is the issue resolved ?

Chhavi

**Comment by ansarrafique** [comment]
The issue was not resolved.
