### ISSUE TITLE
Where can i found the releases changelog?

### ISSUE THREAD

**Issue by vanessaschissato** [Impetus/kundera#608]
Anyone can tell me where can i found the Kundera releases changelog?

Thanks.

**Comment by mevivs** [comment]
I guess https://github.com/impetus-opensource/Kundera/tree/trunk/src#recent-releases should help you out.

-Vivek

**Comment by chhavigangwal** [comment]
Thanks Vivek for pointing out to the right link !

@nessauepa  are we good to close on this ?

Chhavi
