### ISSUE TITLE
int data type not working with mongodb on windows 7 box.

### ISSUE THREAD

**Issue by Abhijith-Nagaraja** [Impetus/kundera#617]
The detailed explanation can be found at
http://stackoverflow.com/questions/24411456/persistence-unit-for-class-issue

**Comment by chhavigangwal** [comment]
Can you try removing 

```
<property name="" value="datastore_mongo.jar"/>
```

 and share test.jar entities code ? 

Which version of Kundera are you using ?

Chhavi

**Comment by Abhijith-Nagaraja** [comment]
I removed the above mentioned property but no avail. It loaded in the classpath. This problem occurs only when I introduce the int data type. Otherwise it works just fine

The code is here:
https://github.com/Abhijith-Nagaraja/kundera-issue

Kundera : 2.11
MongoDb : mongodb-win32-i386-2.6.3

**Comment by mevivs** [comment]
@Abhijith-Nagaraja 
as per SO trace, it is some message entity, but code link which you have shared doesn't have any message entity. 

Am i missing anything?

-Vivek

**Comment by Abhijith-Nagaraja** [comment]
@mevivs 
As per SO trace, the error is "Persistence unit for class : int is not loaded". 
From where are you inferring it is message entity?. I have only those 4 files.
I am wondering whether it is a windows machine issue or not. I haven't tested it on a linux box yet

NOTE: This happens only when I introduce "int" data type. It does not matter whether it is a basic type or Object type. I haven't tested for other number types

**Comment by mevivs** [comment]
@Abhijith-Nagaraja 

```
NOTE: This happens only when I introduce "int" data type. It does not matter whether it is a basic type or Object type. I haven't tested for other number types
```

I understand that.

```
@Id
@Column(name="MESSAGE_ID")
private String messageId;

@Column(name = "SUBJECT")
private String subject;

@Column(name = "BODY")
private String body;

@Column(name = "zipcode")
private int zipcode;

@Embedded
private Contact from;
```

Can't figure out this entity over

```
https://github.com/Abhijith-Nagaraja/kundera-issue
```

As per error, it looks like some relational entity is defined with type of int. Project which you have share doesn't have it.

AFAIK, Java over windows box and linux should not make any difference.

-Vivek

**Comment by Abhijith-Nagaraja** [comment]
@mevivs 
There is no relational entity that is defined with type of int. I have only those 4 files. This is reproducible in my other project as well.

**Comment by mevivs** [comment]
@Abhijith-Nagaraja 
Could you please create a sample project to reproduce at our end? Only entity definition will not be of much help

-Vivek

**Comment by mevivs** [comment]
@Abhijith-Nagaraja 
I can see there is App.java. How are you testing it? Is it a maven based project or running with standalone jar?

-Vivek

**Comment by Abhijith-Nagaraja** [comment]
@mevivs 
This is a maven based project. But I am running App.java to populate the mongodb. 
I will upload the sample project as you requested around 8pm IST

**Comment by chhavigangwal** [comment]
@Abhijith-Nagaraja 

I tested the entities along with operation using the files you shared on Linux box and it seems to working smoothly. Will check the the same with project on Windows once you share it.

Chhavi

**Comment by chhavigangwal** [comment]
I tried the persisting the data using the classes you shared on Windows 7 box with MongoDB 2.6.3 and this code works for me.

Here's how my persistent unit looks like and entity classes and operation is as shared by you : 

```
<persistence-unit name="twingo">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.example.Attachment</class>
        <class>com.example.Email</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="localhost" />
            <property name="kundera.port" value="27017" />
            <property name="kundera.keyspace" value="test" />
            <property name="kundera.dialect" value="mongodb" />
            <property name="kundera.client.lookup.class"
                value="com.impetus.client.mongodb.MongoDBClientFactory" />
            <property name="kundera.ddl.auto.prepare" value="create" />
        </properties>
    </persistence-unit>
```

Can you try to add jar classes before properties tag  and after provider tag in your persistence unit?

Share a sample project to look into the issue further.

**Comment by Abhijith-Nagaraja** [comment]
@chhavigangwal 
I tried it, but no avail.

Here is the project setup
https://www.dropbox.com/s/g2fq9tlfovqey0a/kunderaissue.zip

**Comment by chhavigangwal** [comment]
I tried running the project setup you shared on Windows 7 box with mongodb-win32-i386-2.6.3 and it ran successfully without giving any exception. If possible share some of you messenger id so that we can connect and help you debug/resolve the issue.

P.S. : The only change I made was in keyspace name of persistence unit you shared which was  mistakenly written as "ac" instead of "test"

Chhavi

**Comment by Abhijith-Nagaraja** [comment]
We finally found out the issue. 

I had one entity class which I haven't used in the main program had the following declaration

```
@OneToOne(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
@JoinColumn(name = "intId")
private int pincode;
```

When you are preparing metadata, you are parsing all the entity class via reflection and populating the metadata instead which are all required.

I am closing this issue, but I have to say above is also an issue but you can debate it as designed.

**Comment by chhavigangwal** [comment]
@Abhijith-Nagaraja 

In order to prevent parsing of all classes you can explicitly include the classes you need by adding them in class tag and exclude the ones that you do not want by setting (as in sample pu shared above)

```
<exclude-unlisted-classes>true</exclude-unlisted-classes>
```

Glad your issue got resolved !

Chhavi
