### ISSUE TITLE
Data not inserted in child table which have Many to many relation ship in mongoDB 

### ISSUE THREAD

**Issue by sbheda** [Impetus/kundera#622]
Hi ,
I have two table like employee and project. Both have many to many relationship. Tables create properly but when i insert data ,data inserted in Employee table not in project table. Following are snap shot :
(1) Employee
@Entity
public class Employee {
     @Id
      @Column(name="ID")
      private long id;

```
 @Column(name="FIRST_NAME")
  private String firstName;
 @Column(name="LAST_NAME")
  private String lastName;

  @ManyToMany
  @JoinTable(
      name="EMP_PROJ",
      joinColumns={@JoinColumn(name="EMP_ID" ,referencedColumnName="ID")},
      inverseJoinColumns={@JoinColumn(name="PROJ_ID",                                           referencedColumnName="ID")})
  private List<Project> projects;
     //getter setter
```

}

(2)Project

@Entity
public class Project {
     @Id
      @Column(name="ID")
      private Integer id;

```
  @Column(name="PROJECT_NAME")
  private String  prijectName;

 @ManyToMany(mappedBy="projects")
  private List<Employee> employees;
```

//getter setter

}

(3) Main
public class Main{
public static void main(String[] args) {
EntityManagerFactory emf = Persistence.createEntityManagerFactory("mongounit");
        EntityManager em = emf.createEntityManager();

```
    Employee employee = new Employee(1, "ABC", "A");
    Employee employee2 = new Employee(2, "XYZ", "X");
    Employee employee3 = new Employee(3, "MNO", "M");

    Project project = new Project(1, "AAA");
    Project project2 = new Project(2, "BBB");
    Project project3 = new Project(3, "CCC");

     employee.getProjects().add(project);

    employee2.getProjects().add(project);
    employee2.getProjects().add(project3);

    employee3.getProjects().add(project);
    employee3.getProjects().add(project2);

    em.persist(employee);
    em.persist(employee2);
    em.persist(employee3);
```

}

}

**Comment by mevivs** [comment]
Try with cascading. Make sure if not opted for kundera to manage your schema,then those tables should be in place.

**Comment by sbheda** [comment]
Thank you very much for replay.
This issue has been solved by using cascading.
