### ISSUE TITLE
Cassandra configure multiple persistence.xml files in ear application

### ISSUE THREAD

**Issue by sunrain99** [Impetus/kundera#640]
Can anyone help Kundera cassandra configuration for multiple persistence units in multiple persistence files? I always get error messages:
com.impetus.kundera.configure.PersistenceUnitConfiguration] unconfigured persistence unit: cassandra-pu please validate with persistence.xml
[com.impetus.kundera.KunderaPersistence](default task-5) EntityManagerFactory not created, returning null.

Many thanks!

**Comment by chhavigangwal** [comment]
The same thing works with wildfly 8.1. Closing this one as the same will be resolved with  #534 .

Chhavi
