### ISSUE TITLE
@MappedSuperclass when child class doesn't add any columns

### ISSUE THREAD

**Issue by craigpnnl** [Impetus/kundera#642]
Hello,

I have a class structure where a child class doesn't add any addition attributes (columns) to the parent class.  Is it possible to use Kundera in this case?  I end up with a NullPointerException because the "type" is null on the line (SchemaConfiguration, ~133) as the following:

TableInfo tableInfo = new TableInfo(entityMetadata.getTableName(), type.name(), idClassName, idName); 

@MappedSuperclass
public class IdentifiedObject {

```
@Id
protected String mrid;

@Column
protected String dataType;

@Column
protected String name;
```

....

@Entity
public class Person extends IdentifiedObject {

}

When I change the Person class as follows type becomes COLUMN_FAMILY

@Entity
public class Person extends IdentifiedObject {
        @Column
    String otherData;

```
public String getOtherData() {
    return otherData;
}

public void setOtherData(String otherData) {
    this.otherData = otherData;
}
```

}

**Comment by chhavigangwal** [comment]
Fixed. Released with Kundera-2.15.

Chhavi
