### ISSUE TITLE
A blog column in the name of _ebean_intercept automatically inserted.

### ISSUE THREAD

**Issue by karthik1516** [Impetus/kundera#647]
I am using Kundera with play framework. I have the create option (<property name="kundera.ddl.auto.prepare" value="create" />)  in the persistence.xml. It inserts new row without any error. But, If I do a describe on the table, it is automatically adding a column  _ebean_intercept of type blob. If  I do a select on the table, I see a huge blob chunk along with my data. Can you please suggest what is wrong here?

CREATE TABLE car (
  key text,
  "_ebean_intercept" blob,
  color text,
  make text,
  model text,
  vin text,
  year text,
  PRIMARY KEY ((key))
) WITH COMPACT STORAGE AND

**Comment by chhavigangwal** [comment]
Can you share you entity definition and check whether it has a byte[] type column /attribute defined ?

Chhavi

**Comment by karthik1516** [comment]
Thanks! Following is the entity that I used. Please let me know, if you see something wrong here.

package models;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "car", schema = "fdl@fdlPu")
public class Car {
    @Id
    @Column(name="id")
    public String id; //Auto generated id
    @Column(name="make")
    public String make;
    @Column(name="model")
    public String model;
    @Column(name="year")
    public String year;
    @Column(name="vin")
    public String vin;
    @Column(name="color")
    public String color;
}

**Comment by chhavigangwal** [comment]
@karthik1516 

Try disabling ebean enhancer in your project , by setting ebeanEnabled := false in build.scala and the do a clean compile and try persisting the data again.

Chhavi

**Comment by karthik1516** [comment]
thanks!
