### ISSUE TITLE
Issue in Cassandre query table with subclass data.

### ISSUE THREAD

**Issue by kannuriajay** [Impetus/kundera#652]
Hi,

An  Material.class has--------------------------------
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
 @DiscriminatorColumn(name = "matl_cat_discr", discriminatorType = DiscriminatorType.STRING)
has coloms example..
@EmbeddedId
    private MaterialPK materialPK;

```
@Column(name = "matl_name")
private String matlName;

@Column(name = "matl_type")
private MaterialType materialType;
```

and another Class with

VendorMaterial extends Material------------------------------------
@DiscriminatorValue("Vendor")
@Column(name = "v_id")
    private UUID vendorId;

```
@Column(name = "p_id")
private UUID pid;
```

and another Class with 
HomeGrownMaterial extends Material--------------------------------
@DiscriminatorValue("HomeGrown")
@Column(name = "disposed_by")
    private String disposedBy;

I wrote a query for fetching pid from subclass.

String queryStr = "select labid  from material_by_lab where labid="+labId + " and p_id = "+pid ;

```
        return entityManager
        .createNativeQuery(queryStr , Material.class)
        .getResultList();
```

With the above query it is executing the query for twice every time.? 
log.info("materials is null == ");
shows double count 'I think it creating instance for both VandorMaterial and HomegrownMaterial,

When I use Cassandra CQL Shell and execute query same query shows single row but in Executing in application it returns two rows.
help is appreciated.

**Comment by chhavigangwal** [comment]
@kannuriajay 

If your Material.class is a MappedSuperClass then while executing the query you need to query it with subclass , e.g.

```
return entityManager
        .createNativeQuery(queryStr , VendorMaterial.class)
        .getResultList();
```

Also, can you please share further details of your sub classes ?

Chhavi

**Comment by kannuriajay** [comment]
Yes that Correct .. problom resolved.
Thank you.
