### ISSUE TITLE
Add ability to specify --authenticationDatabase for MongoDB

### ISSUE THREAD

**Issue by karavayeu** [Impetus/kundera#653]
Suppose there is one mongodb user that is added to "admin" database and has access to multiple client databases. With current driver (version 2.9.1) I have to create the same user in each database. The latest MongoDB Java driver uses MongoCredentials that takes database where the user is defined parameter.

**Comment by chhavigangwal** [comment]
@karavayeu   +1 for suggestion.

This will involve the upgrade of version supported of MongoDB by Kundera. We shall plan the same soon !

Chhavi

**Comment by mevivs** [comment]
Isn't it already supported or am i missing something?

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/resources/META-INF/persistence.xml#L36

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-mongo/src/test/resources/META-INF/persistence.xml#L37

https://github.com/impetus-opensource/Kundera/blob/273c13342ddd1aceed0cd23504649926ce8fdb84/src/kundera-mongo/src/test/java/com/impetus/client/crud/MongoAuthenticationTest.java

-Vivek

**Comment by karavayeu** [comment]
The authentication itself is supported, but the user must be in the same database. If the user is placed in a separate database the authentication will fail.

**Comment by chhavigangwal** [comment]
Fixed. Released with Kundera-2.15.

Chhavi
