### ISSUE TITLE
ClassCastException in QueryImpl.setRelationEntities

### ISSUE THREAD

**Issue by winston8** [Impetus/kundera#66]
Hi,

I have two entities, first of them has OneToMany relation to second. Persisting of the entities works fine, but when I try to get it by simple query (select p from FirstEntity p), kundera throw the ClassCastExcetion. You can see stack trace below:

java.lang.ClassCastException: com.test.kundera.FirstEntity cannot be cast to com.impetus.kundera.client.EnhanceEntity
    at com.impetus.kundera.query.QueryImpl.setRelationEntities(QueryImpl.java:191)
    at com.impetus.client.cassandra.query.CassQuery.recursivelyPopulateEntities(CassQuery.java:233)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:149)

I use kundera 2.0.6 and cassandra 1.1.0.  
Entity code:
@Entity
@Table(name="FirstEntity", schema="testkeyspace@cassandra_pu")
@Index(index = true, columns = { "pa_id", "field1", "field2", "currentTimestamp"})
public class FirstEntity extends BaseCassandraEntity{

```
@Id
@Column(name="pa_id")
private String id;

@Column(name="field1")
private String field1;

@Column(name="field2")
private String field2;

@Column(name="currentTimestamp") 
private Long currentTimestamp;

@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
@JoinColumn(name="pa_id")
private List<SecondEntity> entities;    

// getters and setters... 
```

}

@Entity
@Table(name="SecondEntity", schema="testkeyspace@cassandra_pu")
@Index(index = true, columns = { "id", "name", "value", "type"})
public class SecondEntity {    

```
@Id
@Column(name="id")
private String id;

@Column(name="name")
private String name;

@Column(name="value")
private String value;

@Column(name="type")
private String type;

@ManyToOne
@JoinColumn(name = "paf_id", nullable = true, referencedColumnName = "paf_id")    
private FirstEntity activity;

// getters and setters... 
```

}

**Comment by mevivs** [comment]
Hi,
This issue has been fixed into latest trunk branch. Could you please try on "trunk" branch. You need to download and build it manually.

-Vivek

**Comment by mevivs** [comment]
One more thing. Could you please share your persistence.xml changes?

**Comment by winston8** [comment]
Thank you. I will try the trunk version. You can see my persistence.xml below:

<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>  
        <class>com.test.kundera.FirstEntity</class>  
        <class>com.test.kundera.SecondEntity</class>  
        <properties>  
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="testkeyspace"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>  
            <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>  
        </properties>
       </persistence-unit>
</persistence>

**Comment by winston8** [comment]
thank you, it's help ))
