### ISSUE TITLE
Updating byte [] data (Blob) failure 

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#660]
If I update data that already exist in Cassandra/MongoDB using Kundera works as long as it is not byte [] data. I never get response back when I update byte [] data. It takes ages.

**Comment by chhavigangwal** [comment]
@ansarrafique 

As communicated the issue is not with updating byte[] but with EntityManager object's cache getting full. So by clearing the cache periodically there should not be any problem with byte[] data.

Chhavi

**Comment by ansarrafique** [comment]
Fixed
