### ISSUE TITLE
How to write java code to get Map field in cassandra 2.1.1

### ISSUE THREAD

**Issue by kannuriajay** [Impetus/kundera#662]
CREATE TABLE map_example (
  id text,
  m map<timeuuid, text>,
  PRIMARY KEY ((id))
)

I have a field that is a m map<timeuuid, text>, which I am trying to write method to get Key from Map in a Java

AjayKumar.

**Comment by chhavigangwal** [comment]
@kannuriajay 

Can you please elaborate further on what are you trying to achieve by giving example

Chhavi

**Comment by chhavigangwal** [comment]
@kannuriajay 

Any updates ?

Chhavi

**Comment by chhavigangwal** [comment]
Closing with Kundera-2.15.

Chhavi
