### ISSUE TITLE
Get scalar values for native query over Cassandra

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#663]
Right now, Kundera doesnt allow running such native queries 

select keyspace_name,columnfamily_name,column_name,type,validator from system.schema_columns 

unless we define a dummy entity. With Dummy entity, it is returning incorrect results with data wrapped around dummy entity. With native query support i should be allowed to fetch scalar values as an array.

-Vivek

**Comment by chhavigangwal** [comment]
Fixed with Kundera -2.17.
