### ISSUE TITLE
Many-To-One InvalidRequestException(why:Unknown identifier category_id)

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#666]
i am trying to map the one-to-many operation but its showing the error as below.
Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:Unknown identifier category_id)
    at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2328)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.persist(CassandraClientBase.java:2026)
    at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:156)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:105)
    at com.impetus.client.cassandra.thrift.ThriftClient.persist(ThriftClient.java:139)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:191)
    at com.impetus.kundera.graph.Node.flush(Node.java:531)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:403)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:145)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)

Entities
ProductCategory.java

@Entity
@Table(name = "product_category", schema = "xxx@cassandra")
public class ProductCategory {
    @Id
    @Column(name = "category_id")
    private String category_id;

```
@Column(name = "category_name")
private String category_name;

   @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
   @JoinColumn(name = "category_id")
private List<Product> products;
//Setter and getters
```

}

Product.java

@Entity
@Table(name = "product", schema = "xxx@cassandra")
public class Product implements Serializable {

```
@Id
@Column(name = "product_id")
private String product_id;

@Column(name = "product_name")
private String product_name;

@Column(name = "category_id")
private String category_id;

@Column(name = "product_brand")
private String product_brand;

@Column(name = "product_category")
private String product_category;

@Column(name = "product_price")
private String product_price;

@Column(name = "features")
private Map<String, String> features;

  //setter and getters
```

}

persistence.xml

<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
    version="2.0">

```
<persistence-unit name="cassandra">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.xrg.common.persistence.entity.Product</class>
    <class>com.xrg.common.persistence.entity.ProductCategory</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="9160" />
        <property name="kundera.keyspace" value="xxx" />
        <property name="kundera.dialect" value="cassandra" />

        <property name="kundera.client" value="thrift" />
        <property name="kundera.client.lookup.class"
            value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />

        <property name="kundera.client.property" value="kundera-cassandra.properties" />
        <property name="kundera.client.property" value="kunderaCounter.xml" />
        <property name="jboss.as.jpa.managed" value="false" />
    </properties>
</persistence-unit>
```

</persistence>

 Main.java
ProductCategory category = new ProductCategory();
        category.setCategory_id(CassandraUtil.getUniqueId());
        category.setCategory_name("Electronics");

```
    List<Product> list = new ArrayList<Product>();
    Product product = new Product();
    product.setProduct_name("Spice Android One Dream");
    product.setProduct_id(CassandraUtil.getUniqueId());
    product.setProduct_brand("Spice");
    product.setProduct_category("Mobiles");
    product.setProduct_price("13000");
    Map<String, String> map = new HashMap<String, String>();
    map.put("Color", "Black");
    map.put("OS", "Android");
    map.put("RAM", "1GB");
    map.put("Processor", "Dual core");
    product.setFeatures(map);

    Product product1 = new Product();
    product1.setProduct_name("Spice Android One Dream");
    product1.setProduct_id(CassandraUtil.getUniqueId());
    product1.setProduct_brand("Spice");
    product1.setProduct_category("Mobiles");
    product1.setProduct_price("13000");
    Map<String, String> map1 = new HashMap<String, String>();
    map1.put("Color", "Black");
    map1.put("OS", "Android");
    map1.put("RAM", "1GB");
    map1.put("Processor", "Dual core");
    product1.setFeatures(map1);
    list.add(product);
    list.add(product1);
    category.setProducts(list);

    EntityManagerFactory emf = Persistence
            .createEntityManagerFactory("cassandra");
    EntityManager em = emf.createEntityManager();

    em.persist(category);
    em.close();
    emf.close();
```

 maven dependency
    <dependency>
            <groupId>com.impetus.kundera.client</groupId>
            <artifactId>kundera-cassandra</artifactId>
            <version>2.13.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>3.1.2.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>3.1.2.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>3.1.2.RELEASE</version>
            <scope>provided</scope>
        </dependency>

Please help me

**Comment by chhavigangwal** [comment]
@sreekanth0041 

Please try setting cql version to 3 while creating EMF and try the same operation. You can set the cql version by : 

```
Map propertyMap = new HashMap();
 propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
 EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra", propertyMap);
EntityManager em = emf.createEntityManager();
```

Chhavi

**Comment by sreekanth0041** [comment]
Hi chhavigangwal,
Thank you for giving the replay.
I updated the code but still getting the same error.

**Comment by mevivs** [comment]
@sreekanth0041 
Can you please share output of given below command by running over cql shell:

```
describe table product_category;
```

-Vivek

**Comment by sreekanth0041** [comment]
Hi Vivek,
Output of the cammand:

CREATE TABLE xxx.product_category (
    key text PRIMARY KEY,
    category_name text
) WITH COMPACT STORAGE
    AND caching = '{"keys":"ALL", "rows
    AND comment = ''
    AND compaction = {'min_threshold':
mpaction.SizeTieredCompactionStrategy',
    AND compression = {'sstable_compres
LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = 'NONE';

**Comment by mevivs** [comment]
@sreekanth0041 
Check as per error, there is no field "category_id".Either change your entity as

```
@Id
@Column(name = "key")
private String category_id;
```

OR 

alter table xrg.product_category  to define Primary key column name as "category_id" instead of "key".

-Vivek

**Comment by sreekanth0041** [comment]
Thank you its working now

**Comment by mevivs** [comment]
@sreekanth0041  
I guess it can be labelled as "Not an Issue" and good to close?

-Vivek
