### ISSUE TITLE
Kundera ES: fetch specific fields from Elastic search

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#671]
Currently it is not supported to fetch specific fields from Elastic search. But Elastic search 1.4 api provides a way to fetch specific fields only!
That would enable support for given below query:

```
Select p.age from Perosn p
```

Transport client apis prepareGet and preapreSearch provides methods such "addField" or "setFields" to support this.

-Vivek

**Comment by chhavigangwal** [comment]
Fixed. Released with Kundera-2.15.

Chhavi
