### ISSUE TITLE
Like operation in kundera cassandra

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#676]
Hi,
Can you please tell me how to use the 'like' query operations in cassandra.

**Comment by chhavigangwal** [comment]
@sreekanth0041 

Like operation is not directly supported in Cassandra. You can however achieve the same by creating indexes over Lucene or Elastic search and then querying the data.

Chhavi

**Comment by chhavigangwal** [comment]
Fixed. Support enabled with Lucene and elastic search indexes as native Cassandra does not support 'like' query itself. Released with Kundera-2.15.

Chhavi
