### ISSUE TITLE
Working on collections MongoDB

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#682]
My entity class is below

```
@Entity
@Table(name = "resturant", schema = "mango@laalsa")
public class Restaurant {
    @Id
    @Column(name = "restaurant_id")
    private UUID restaurant_id;

    @Column(name = "restaurant_name")
    private String restaurant_name;

    @Column(name = "contact_person")
    private String contact_person;

    @Column(name = "contact")
    private Map<String,String> contactNumbers;

    @Column(name = "latitude")
    private String latitude;

    @Column(name = "longitude")
    private String longitude;

    @Column(name = "country")
    private String country;

    @Column(name = "state")
    private String state;

    @Column(name = "city")
    private String city;

    @Column(name = "addressLines")
    private Map<String,String> addressLines;

    @Column(name = "createdDate")
    private Timestamp createdDate;

    @Column(name = "createdBy")
    private UUID createdBy;

    @Column(name = "modifyDate")
    private Timestamp modifyDate;

    @Column(name = "modifyBy")
    private UUID modifyBy;

    @Column(name = "isActive")
    private boolean isActive;
//Setter and getters
}
```

Now i want to get the data with where clause of contactNumbers contains key.(Ex contactNumbers CONTAINS 'addressline1')

Any one can help me please

**Comment by mevivs** [comment]
I guess it is only possible via regex pattern matching. I think Kundera doesn't support it yet but possible?
http://howtodoinjava.com/2014/05/29/mongodb-selectqueryfind-documents-examples/  

Point 9.

-Vivek

**Comment by devender-yadav** [comment]
Kundera currently does not support searching on a map object directly. However you can achieve this  using  mongoDB's Native Script in the following manner : 

Suppose your Map<String,String> contactNumbers has an entry <”reception” , “9999”>
 and you want to query on the basis of KEY of this Map.
You can achieve this by writing a Script like this:

```
db.resturant.find({'contact.reception ':'9999'}).toArray()
```

Code :

```
String testScript = "db.resturant.find({'contact.reception ':'9999'}).toArray()";

Object result = (client).executeScript(testScript);
```

You will get BasicDBList of matching documents.

--Devender

**Comment by chhavigangwal** [comment]
Closing with Kundera-2.15 release.

Chhavi
