### ISSUE TITLE
Minor typo in the wiki

### ISSUE THREAD

**Issue by jisaacstone** [Impetus/kundera#688]
on [this page](https://github.com/impetus-opensource/Kundera/wiki/Datastax-java-driver-support-for-Cassandra-using-Kundera) under the **Maven dependency** header the example xml has a closing tag of `</dependancy>`. should be `</dependency>`

Don't seem to be able to do pull requests for a wiki so I am notifying you guys here.

Thanks. You guys are super awesome and the wiki is very helpful :+1:

**Comment by chhavigangwal** [comment]
Fixed. Released with Kundera-2.15.

Chhavi
