### ISSUE TITLE
support protected default constructor

### ISSUE THREAD

**Issue by boferri** [Impetus/kundera#693]
Currently only public default constructors are supported by Kundera. However, the JPA spec says: "Either public or protected no-arg constructor must exist. Additional constructors are fine". So it be cool, if you also can support this, because one do not always want to provide public default constructors ;)

**Comment by chhavigangwal** [comment]
@zazi 

Enabling the support for protected default constructor is targeted for an upcoming patch release in February and will be added in trunk soon.

Chhavi

**Comment by chhavigangwal** [comment]
Fixed with Kundera-2.15.1.
