### ISSUE TITLE
IN query not working?

### ISSUE THREAD

**Issue by georgkoester** [Impetus/kundera#70]
Hi there,

I found that 

select u from User u where u.id in :ids

isn't working - KunderaQuery doesn't know IN as an operator, is that right? Or am I missing something? I want to save server roundtrips.

Cheers,
Georg

**Comment by mevivs** [comment]
support for IN clause is not in place, but you can use BETWEEN clause for the same.

-Vivek

**Comment by georgkoester** [comment]
I ended up using the native query facility with cassandra CQL like:

SELECT Name, Occupation FROM People WHERE key IN (199, 200, 207);

Thanks!

**Comment by mevivs** [comment]
Great. I have written a blog post to demonstrate such scenarios:

http://mevivs.wordpress.com/2012/02/13/how-to-crud-and-jpa-association-handling-using-kundera/

findByRange() method is range scan over the key.

-Vivek
