### ISSUE TITLE
How to query Collection type column in MongoDb

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#713]
I have the Entity class below,I want to write query on values(i.e Map)

```
@Entity
@Table(name = "plan_usage", schema = "xxx@xxx")
public class PlanUsage implements Serializable{
    @Id
    @Column(name = "usage_id")
    private UUID usage_id;

    @Column(name = "restaurant_plan_id")
    private UUID restaurant_plan_id;

    @Column(name = "restaurant_name")
    private String restaurant_name;

@Column(name = "params")
    private Map<String,String> values;
}
```

**Comment by devender-yadav** [comment]
@sreekanth0041 
Please check similar issue related to query on map  #682

and check this test case for more details
https://github.com/impetus-opensource/Kundera/blob/c6101f21cd8f079fb4cc44e85de49261bf5fef7e/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java#L371

Also, we have enabled support for some native queries in Kundera-MongoDB in 2.15 Release.
check this test case for further exploration: https://github.com/impetus-opensource/Kundera/blob/c6101f21cd8f079fb4cc44e85de49261bf5fef7e/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java#L387

HTH,
Devender

**Comment by chhavigangwal** [comment]
@sreekanth0041 

Does the above suggestion works for you?

Chhavi

**Comment by sreekanth0041** [comment]
Yes thank you for your help.
