### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by admackin** [Impetus/kundera#714]
I can't find any mention of your project licensing on Github. Where I work, this is a big concern. The simplest solution would be to follow the defacto standard and insert the license text in a file 'LICENSE.txt' in the project root. (Sorry if it's to be found somewhere else, but even if it is, it could definitely be more obvious)

**Comment by chhavigangwal** [comment]
@admackin 

Kundera keeps its licensing information as per the specification of http://www.apache.org/licenses/LICENSE-2.0 and is incorporated as a part of its source code.

Chhavi

**Comment by admackin** [comment]
Great to know that it's Apache-licensed! I still think you should advertise this more prominently, so people don't need to drill down through the source tree to look at the header of a file - browsing to https://github.com/impetus-opensource/Kundera/blob/trunk/src/jpa-engine/core/src/main/java/com/impetus/kundera/Constants.java is a lot harder than looking at a hypothetical file in the standard location at https://github.com/impetus-opensource/Kundera/tree/trunk/src/LICENSE.txt (or a single line saying 'Apache License' at the bottom of your README.md). 

You could make the open-source world that much easier to navigate for those of us who work at places where we have to avoid certain open source licenses or projects where the license is ambiguous. 
(At my work, we routinely need to have lawyers review the licenses, and I don't think I can imagine them browsing through to a .java file 10 folders deep into the source tree to work out the project licence)

**Comment by chhavigangwal** [comment]
Fixed with Kundera -2.16 release.
