### ISSUE TITLE
HBase remodeling and version upgrade.

### ISSUE THREAD

**Issue by pragalbhgarg** [Impetus/kundera#716]
kundera-hbase is now upgraded to be compatible with HBase version 1.0.0 along with some restructuring.
In the new model
- A keyspace will be mapped to an HBase namespace (keyspace => namespace)
- An entity will be mapped to an HTable (entity => HTable)

It also has 
- Improved query support
- Support for nested embeddables

**Comment by chhavigangwal** [comment]
Fixed with Kundera -2.16 release.
