### ISSUE TITLE
Do I need to use Transactions, if I don't require them?

### ISSUE THREAD

**Issue by pluttrell** [Impetus/kundera#722]
I'm trying to deploy on Wildfly 8.2 and see in [https://github.com/impetus-opensource/Kundera/wiki/Using-Kundera-with-Jboss](https://github.com/impetus-opensource/Kundera/wiki/Using-Kundera-with-Jboss):

```
Application-managed entity managers don’t automatically propagate the JTA transaction context. Such applications need to manually gain access to the JTA transaction manager and add transaction demarcation information when performing entity operations. The javax.transaction.UserTransaction interface defines methods to begin, commit, and roll back transactions. Inject an instance of UserTransaction by creating an instance variable annotated with @Resource
```

If I don't require transactions for a particular persistence operation, do I still need to do this?

**Comment by karthikprasad13** [comment]
@pluttrell 

Yes, you need to perform every persistence operation within JTA transactions once you specify the type of transaction to JTA or having container managed transactions. 

If you dont require transactions for a particular persistence operation, you may create separate EntityManagerFactory without specifying the transaction type. You dont need to inject instance of UserTransaction in this case.

HTH
Karthik.
