### ISSUE TITLE
Update Kundera's compiler level to 1.7

### ISSUE THREAD

**Issue by karthikprasad13** [Impetus/kundera#730]
Some parts of Kundera are still using compiler 1.6, they must be updated to 1.7.

**Comment by mevivs** [comment]
I suggest, please take a look at classes in kundera-core where we have played around set and list for generic parameters type. This implementation differs from jdk 6 to jdk 7. Also, wonder how would you handle application using Kundera in production(with jdk6) to migrate on this new version?

-Vivek
