### ISSUE TITLE
Limit query kundera mongoDb

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#731]
I am using kundera mongoDb,I want to fetch the limited records i.e First time I want to get the 10 records next time i want to get the next 10 records.
Help me please.

**Comment by devender-yadav** [comment]
@sreekanth0041 

You can achieve it simply in JPA way as shown below :

```
    Query query = em.createQuery("Select p from PersonMongo p");
    query.setFirstResult(0);
    query.setMaxResults(10);
    List<PersonMongo> results = query.getResultList();
```

Nexy time when you want to get next 10 records, simply change 
        `query.setFirstResult(10);`

For more details find test case :-
https://github.com/impetus-opensource/Kundera/blob/c6101f21cd8f079fb4cc44e85de49261bf5fef7e/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java#L765

HTH,
Devender

**Comment by devender-yadav** [comment]
@sreekanth0041 
Did above solution work for you?

Devender

**Comment by sreekanth0041** [comment]
Yes devender thank you for your help...
