### ISSUE TITLE
Support timeUUId columns and auto-generation of timeUUID column values in Kundera.

### ISSUE THREAD

**Issue by TarlochanKalsi** [Impetus/kundera#732]
As per google group discussion -
https://groups.google.com/forum/#!topic/kundera-discuss/4puVy_NLhnc 
opening issue for the same.

Kundera does not support timeUUID(Type 1) column creation in the table and  does not support auto-generation of timeUUID(Type 1) column values.

Please add the same. 

Tarlochan K

**Comment by chhavigangwal** [comment]
Fixed with Kundera -2.17 release.

**Comment by brunocrt** [comment]
Cassandra 2.2.7
kundera-cassandra 3.4 
CQL 3.0.0 driver (ThriftClientFactory)

It doesn't seem to work with compound keys for clustering columns! I'm using @EmbeddedId annotation to a PartitionKey class that has inside 3 attributes and the last of them is an UUID id column with @GeneratedValue.  Kundera doesn't generate the value and doesn't create it as timeuuid type as desired. In fact it seems that there is no way to explicity say that your UUID column should be a timeuuid or not.

Follow my piece of code:
`@Entity
@Table(name="my_table")
public class MyTable {
    @EmbeddedId
    private MyCompKey key;
   ...
}

@Embeddable
public class MyCompKey implements Serializable {
     private String trade_date;
     private String ticker;
     @GeneratedValue
     private UUID id;
     ...
}
`
In my case I have a event based column family that data should by grouped by trade date and ticker name but we want to generate a surrogate key to make it unique, as we can have several events from same ticker in a day, and still write the events by the time sequence they occurred.

**Comment by karthikprasad13** [comment]
@brunocrt 

There is no way to map timeuuid and uuid differently with Java type, making it a limitation for Kundera. Also, auto generation inside embeddable object is not yet supported by Kundera.

-Karthik

**Comment by brunocrt** [comment]
Thank you very much @karthikprasad13 for you reply! You saved me time trying to do this!
