### ISSUE TITLE
Support schema auto-generation for Composite partition keys

### ISSUE THREAD

**Issue by karthikprasad13** [Impetus/kundera#734]
Referring the issue on kundera-discuss : https://groups.google.com/forum/#!topic/kundera-discuss/8aKaMX9G4gc 

Add the support to auto-generate schema for composite partition keys.

**Comment by mevivs** [comment]
Alternatively, he should be able to fire native CQL3 ddl command(via Kundera) for such schema related changes.

-Vivek

**Comment by chhavigangwal** [comment]
Fixed with Kundera 3.0 release.
