### ISSUE TITLE
Creating columnFamily dynamically

### ISSUE THREAD

**Issue by cherry316** [Impetus/kundera#736]
Is it possible to create a columnFamily through codes without adding this columnFamily in CQLSH? 
For instance, I created an entity/table named **UserProfile** then if I start the system, this table entity will be automatically generated in a Cassandra keyspace.

**Comment by karthikprasad13** [comment]
@cherry316 

You can add the following property in your `persistence.xml` file for generating columnFamilies automatically:

```
 <property name="kundera.ddl.auto.prepare" value="create" />
```

Please refer [this](https://github.com/impetus-opensource/Kundera/wiki/Schema-Generation) for more information about Schema Generation.

Karthik

**Comment by cherry316** [comment]
Thanks @karthikprasad13 , It's fine now.
:)
