### ISSUE TITLE
How transaction and rollback works in kundera with cassandra

### ISSUE THREAD

**Issue by almightypradeep** [Impetus/kundera#742]
Hi Cassandra expert

We have chosen kundera as client to access cassandra.

I have a usecase to ensure transactionality in cassandra and also understand how cassandra deletes an inserted record.
We want to understand a bit more on how kundera implements rollback. 

Can you please explain.

Thanks
Prad

**Comment by karthikprasad13** [comment]
@almightypradeep 

Kundera follows JPA specifications for implementing rollback (transactions). Please refer this [wiki page](https://github.com/impetus-opensource/Kundera/wiki/Transaction-Management).

Please refer [this](http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_about_transactions_c.html)  link to find out more about transactions at Cassandra level.

If you face any issue while implementing transactions in your use case you can get back to us.

-Karthik

**Comment by almightypradeep** [comment]
Thanks Karthik.

I want to understand how rollback is implemented using kundera, is it at the client side or at the cassandra. 
A bit more on how records are inserted and deleted due to transaction breaks.

Thanks for yr reply

**Comment by mevivs** [comment]
@almightypradeep 
Rollback and commit handled at Kundera API level as per JTA specification(if running with CMP ). AFAIK Cassandra supports lightweight transaction (CAS)  only, not sure still experimental or production ready now. You should be able allowed to access CAS support via Kundera's native CQL3 support.

```
A bit more on how records are inserted and deleted due to transaction breaks.
```

Kundera maintains event queue to handle rollback in sequence and deletes are physical deletes. So for very short time frame inserted records might be accessible with other connections(assuming not running a long transaction).  Ideally rollback in case of failure are unlikely considering Cassandra's high availability and distributed databases like feature set, but in case of network failure, timeout etc it might happen.

HTH,
-Vivek

**Comment by almightypradeep** [comment]
Thanks Vivek. This helps my question.
