### ISSUE TITLE
How do I create entityManager ?

### ISSUE THREAD

**Issue by kunderauser1234** [Impetus/kundera#743]
Hi,
I am using tomcat + kundera  + spring. I wanted to know the recommended way to persist objects. What is the difference between doing:

@PersistenceContext(unitName = "cassandra_persistent_unit", type = PersistenceContextType.EXTENDED, properties = { @PersistenceProperty(name = "consistency.level", value = "QUORUM") })
    private EntityManager entityManager;
...
 public void persist() {
    entityManager.persist(myobject);
}

and doing :

  @Autowired
  EntityManagerFactory entityManagerFactory

 public void persist() {
    EntityManager entityManager = entityManagerFactory.createEntityManager()
    entityManager.persist(myobject);
    entityManager.close();
}

Thanks!

**Comment by devender-yadav** [comment]
On using,  `@PersistenceContext`, you will get  _**container managed**_  `entityManager` instance (container manages things for you). Also, you have the  liberty to define `PersistenceContextType`, persistence `unitName` and  `properties` for the container or persistence provider at `entityManager` level.

Using  `@autowire entityManagerFactory` is similar to `@PersistenceUnit` annotation (it is just a matter of replacing the annotations) you will get instance of `entityManagerFactory` and then you are creating `entityManager` which is _**application managed**_ .

 It's better to use container-managed entity manager unless your application really need to manage the EntityManager lifecycle manually.

**Comment by chhavigangwal** [comment]
Closing with Kundera 3.1 release
