### ISSUE TITLE
Add support for @AttributeOverrides

### ISSUE THREAD

**Issue by zenzei** [Impetus/kundera#747]
Is there any plan to include @AttributeOverrides JPA annotation to Kundera? At least I'm trying the 2.17 version with Hbase and it doesn't seems to work.

In my use case I have an entity an @Embeddable entity that need to be embedded twice in a second entity.

``` java
@Entity
public class Customer {
    @Id
    private int id;
    @Embedded
    private Address home;
    @Embedded
    private Address work;
        ...
}

@Embeddable
public class Address {
    @Id
    private int id;
    private String street;
    ...
}
```

As @Embedded make the object "plain" in each row, if I don't use the @AttributeOverrides for one of the Address fields, the streets aren't save twice, but get overwritten (same column name for the same row). In fact the id field of the customer and steets are also overwritten.

In case AttributeOverride is not going to be supported, is there any recommended way to do this?

PS: By the way, Kundera is great!

**Comment by pragalbhgarg** [comment]
Hi @zenzei 

Thanks for letting us know this issue, we'll fix it very soon. As of now, there are 2 workarounds to your problem-
1. use `List<Address>` 
2. use `@SecondaryTable` annotation
You can find the test cases in the following links-

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/hbase/crud/embedded/EmbeddablesCrudTest.java

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/hbase/secondarytable/HbaseSecondaryTableTest.java

Please let us know which implementation of kundera-hbase you are using. Is it either `kundera-hbase` or `kundera-hbase-v2` ? We recommend you to use `kundera-hbase-v2`, it has a more features, better querying support and different data model design. Please refer the wiki here-
https://github.com/impetus-opensource/Kundera/wiki/Kundera-with-HBase#kundera-hbase-v2
Also, we can get into a live discussion using the given URL (just enter a nickname and captcha)-
http://webchat.freenode.net/?channels=Kundera#
Team is active and will fix your issue soon !

-PG

**Comment by zenzei** [comment]
Hi @pragalbhgarg for your kindly and quick response! 
I can confirm I'm using v2 version (kundera-hbase-v2). While you look at the issue I'll try your workarounds and let you know in the discussion group!

**Comment by pragalbhgarg** [comment]
@zenzei 

Hi, we have added a fix for this issue. You can either build Kundera from trunk to use the feature right away or you can wait for the next version of Kundera to release.

-PG

**Comment by zenzei** [comment]
It's working great, thanks for the quick fix!
