### ISSUE TITLE
i18n problem: String.getBytes used and generally assuming bytes are UTF-8

### ISSUE THREAD

**Issue by georgkoester** [Impetus/kundera#75]
Hi there,

looking at the codebase I saw stuff like this:
mutator.writeColumns(metadata.getTableName(), new Bytes(tf.getId().getBytes()),
                    Arrays.asList(tf.getColumns().toArray(new Column[0])));
    Source: PelopsClient line 695.

IMHO, getBytes uses the default enconding of the platform, which might not be UTF-8 but cp1252 on windows for example, so maybe better to use Bytes.fromUTF8 for example - or am I missing something?

I need my db to be i18n ready, so I need to keep this issue logged. These bugs can be real suckers.

Best,
Georg

**Comment by mevivs** [comment]
Change commited.

**Comment by mevivs** [comment]
Closing as lot of refactoring done around this and working fine.
