### ISSUE TITLE
Support for aggregations in CouchDB natively must be enabled.

### ISSUE THREAD

**Issue by pragalbhgarg** [Impetus/kundera#750]
Currently aggregations in CouchDB are supported by using ElasticSearch as indexing store. Support for such queries (count, min, max etc) must also be provided using CouchDB solely.

**Comment by pragalbhgarg** [comment]
The support has been added for the following aggregation queries without WHERE clause-
COUNT, MIN, MAX, SUM, AVG.

**Comment by chhavigangwal** [comment]
Fixed with Kundera 3.0 release.
