### ISSUE TITLE
Strategy for tests

### ISSUE THREAD

**Issue by gbrancovici-sam** [Impetus/kundera#754]
Hi,

I've been using Kundera for a while and I'm impressed with its power and simplicity of use. Great work! 

However, I've noticed that Kundera won't currently (2.17) pass its own tests when built from the source (hence the suggestion to use -DskipTests to avoid having tests run - or am I missing something?).

Given that this situation might make some decision makers nervous, I would be very interested to know if there are any plans to address the tests issues. Since the next major release (3.0 vs. 2.x) is coming soon, is this topic going to be addressed there?

Thanks.

**Comment by pragalbhgarg** [comment]
Are you building Kundera from current (`3.0-SNAPSHOT`) trunk or `2.17` source ? Since `3.0-SNAPSHOT` is under development there are some known build issues with it. And it is highly unlikely that `2.17` has build issues as we have released it on maven. We will take this issue on high priority and get back to you soon,

Regards,
-PG

**Comment by karthikprasad13** [comment]
Hi @haidukus 

There was one test case in the current trunk that was failing and we have fixed it now and build looks clean. You can confirm it at your end.

-Karthik

**Comment by gbrancovici-sam** [comment]
Hi,
I'm working with 2.17 right now.

Running:
mvn clean install -Pcassandra
ends with the failures below (I have an Cassandra instance running so I'm not skipping the tests in the command line).

Also, I would assume that any tests related to BIGINTs would fail, since they were only fixed recently in the trunk, right? I'm not sure whether other tests are failing or not, as some are skipped right now.

Thanks.

---

##  T E S T S

Running com.impetus.kundera.index.IndexManagerTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.596 sec
Running com.impetus.kundera.index.LuceneIndexerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.578 sec
Running com.impetus.kundera.persistence.EntityManagerSessionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.143 sec
Running com.impetus.kundera.persistence.EntityReaderTest
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.077 sec <<< FAILURE!
Running com.impetus.kundera.metadata.model.EntityMetadataTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.731 sec
Running com.impetus.kundera.cache.ehcache.EhCacheProviderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running com.impetus.kundera.cache.ehcache.EhcacheTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec
Running com.impetus.kundera.polyglot.tests.OOUPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.352 sec
Running com.impetus.kundera.polyglot.tests.MMBPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.557 sec
Running com.impetus.kundera.polyglot.tests.OMBPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.773 sec
Running com.impetus.kundera.polyglot.tests.MOBPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.5 sec
Running com.impetus.kundera.polyglot.tests.MOUPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.705 sec
Running com.impetus.kundera.polyglot.tests.MMUPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.986 sec
Running com.impetus.kundera.polyglot.tests.OMUPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.607 sec
Running com.impetus.kundera.polyglot.tests.OOBPolyglotTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.775 sec
Running com.impetus.kundera.query.PersonTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.557 sec
Running com.impetus.kundera.query.LuceneQueryTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.126 sec
Running com.impetus.kundera.query.QueryImplTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.207 sec
Running com.impetus.kundera.query.PersonEntityNameTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.601 sec

Results :

Failed tests:   testOneToMany(com.impetus.kundera.persistence.EntityReaderTest)

Tests run: 46, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] kundera ........................................... SUCCESS [0.563s]
[INFO] kundera-trunk ..................................... SUCCESS [1.029s]
[INFO] kundera-core-parent ............................... SUCCESS [0.020s]
[INFO] kundera-core ...................................... SUCCESS [37.230s]
[INFO] kundera-fallback-impl ............................. FAILURE [18.346s]
[INFO] kundera-elastic-search ............................ SKIPPED
[INFO] kundera-cassandra-parent .......................... SKIPPED
[INFO] kundera-cassandra ................................. SKIPPED
[INFO] kundera-cassandra-pelops .......................... SKIPPED
[INFO] kundera-cassandra-ds-driver ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.606s
[INFO] Finished at: Wed Jun 17 10:41:57 CDT 2015
[INFO] Final Memory: 50M/649M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project fallback-impl: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/xxx/Kundera/src/jpa-engine/fallback-impl/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]

**Comment by chhavigangwal** [comment]
Not reproducible
