### ISSUE TITLE
Custom id generator kundera for cassandra

### ISSUE THREAD

**Issue by JoshiManjila** [Impetus/kundera#756]
Dear sir,

We are testing Kundera for using for a project. But we have a requirement  to set custom made id for each row of column family. As far as we know, in Kundera  Cassandra  only possible way is to set generator strategy to table. Is there any way to add our on generator.

Any help and guidance will be greatly be appropriated. 

Joshi

**Comment by chhavigangwal** [comment]
@JoshiManjila 

You cannot achieve the same using Kundera's current code. However , we will add its support soon and update you . If it is high priority then let us know !

Chhavi

**Comment by JoshiManjila** [comment]
Thank you sir, We are looking forward to find it soon. Really we are planning to decorate the existing generated id by adding some string so that that Id will be unique across our system spanning more than one db. Hope your new fix will make it possible.

Joshi

**Comment by JoshiManjila** [comment]
Dear chhavigangwal,

How can test the fix you have committed. What would be the procedure to get this fix for me? Please help me, I am new to this forum.

Thanking you

Joshi

**Comment by karthikprasad13** [comment]
Hi @JoshiManjila 

This issue is not yet `Fixed` and the label `Fix` implies `To Fix`. We will update you once we are done with the fix.

-Karthik.

**Comment by chhavigangwal** [comment]
Fixed with Kundera 3.0 release.

**Comment by chhavigangwal** [comment]
@JoshiManjila 

Please find a sample at : 
https://github.com/impetus-opensource/Kundera/blob/adac3e59e7b2148bbdbcc0681a6c47e42bd2aaa2/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/generatedId/CustomGeneratedIdTest.java

https://github.com/impetus-opensource/Kundera/blob/adac3e59e7b2148bbdbcc0681a6c47e42bd2aaa2/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/generatedId/CustomIdGenerator.java

Hope that helps 
Chhavi
