### ISSUE TITLE
Cassandra auto generation using now () -- Efficiency.

### ISSUE THREAD

**Issue by bgawne** [Impetus/kundera#758]
Hi, 

I was reviewing the code for auto timeUUID generation and its structured as follows : 

final String generatedId = "Select now() from system.schema_columns";
## This will pull hundreds of rows, when you only need 1 row.

You should amend the query as follows : 

Select now() from system.schema_columns LIMIT 1

**Comment by karthikprasad13** [comment]
Hi @bgawne 

Thank you very much for pointing this out. We have updated the code and added the fix in trunk.

-Karthik

**Comment by chhavigangwal** [comment]
Fixed with Kundera 3.0 release.

**Comment by chhavigangwal** [comment]
Fixed with Kundera 3.0 release.
