### ISSUE TITLE
No Entity metadata found for the class class User. Returning null value.

### ISSUE THREAD

**Issue by superstarz** [Impetus/kundera#76]
Hi ! 
I'm trying to start an java project using Kundera ORM. 
I follow step from this page to start and see how an project run : https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes

So, when i run my project, i get this warning : 
[WARN ] [main] com.impetus.kundera.metadata.KunderaMetadataManager  - No Entity metadata found for the class class User. Any CRUD operation on this entity will fail.If your entity is for RDBMS, make sure you put fully qualified entity class name under <class></class> tag in persistence.xml for RDBMS persistence unit. Returning null value.

And more, i get this error (probably from the lastest warning ? ) : 

Exception in thread "main" java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:53)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:132)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:191)
    at KunderaExample.main(KunderaExample.java:22)

My project is structured like this in eclipse : 
/src/kunderaExample.java
/src/ User.java (Default package)
ressources/META-INF/persistence.xml (in path).

i get too this libraries :  kundera-cassandre2.0.6, libthrift05, log4j 1.2.14,  slf4j 1.6.1.

And my persistence.xml is : 
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>  
        <class>User</class>
        <class>KunderaExample</class>
        <properties>  
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="KunderaExamples"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>  
        </properties>  
    </persistence-unit>
</persistence>

Any ideas ? 

Sorry for my english ...

**Comment by mevivs** [comment]
Considering your entity is annotated with keyspace@puName for nosql DB, please make sure if you hold persistence.xml under /src/main/resources/META-INF folder(in case it is a maven based project). If you are using it with kjar-with-dependency, make sure  persistence.xml should be in your classpath!

**Comment by superstarz** [comment]
Thanks for your reply, 

I didnt use the maven repo, i just get the jar and all dependency for Kundera. 
Previously, i had the problem about the classpath, the persistence.xml could not be found, to resolve it, i put persistence.xml in an folder in src. And build this folder in my classpath. 

When I show the ToString of all my objects, i get this : 
com.impetus.kundera.persistence.EntityManagerImpl@bb94d9
com.impetus.kundera.persistence.EntityManagerFactoryImpl@129642c
User@6fa30c

So my objects are not null right ? 
In this case, how i get an nullpointerException ?

**Comment by mevivs** [comment]
Could you please try mapping your entity within '<class>' tag in your persistence.xml?

**Comment by mevivs** [comment]
Have a look at :
https://github.com/downloads/impetus-opensource/Kundera/project.zip

This is a sample project developed using jar-with-dependency option. It should help you out to figure out the issue

-Vivek

**Comment by superstarz** [comment]
My persistence.xml get this lines : 
<class User </class 

This line must define my Entity class right ?

**Comment by mevivs** [comment]
Yes. This must be with package name(if any).

**Comment by superstarz** [comment]
its in default package so it's just User (class name). I see in your project there aren't <class in pertinence.xml, why ?

**Comment by mevivs** [comment]
It is not required if classes are readily available for class loading(means in classpath). '<class>' is to map it explicitly. Sample project is added for reference, So if you map accordingly, you don't need to

**Comment by superstarz** [comment]
I tried to put my files in an different package. User in entity, KunduraExample in main, and i specified it in persistence.xml. 
=> Same result.

My error is from this line : "em.persist(user);", when I remove that, i get no one error.

**Comment by mevivs** [comment]
Are you running within eclipse or any other IDE or creating runnable jar?

In case you are creating runnable jar. Validate your jar structure for META-INF should be on root folder.

**Comment by mevivs** [comment]
Just now uploaded a png file to validate your jar structure.
Have a look: 

https://github.com/downloads/impetus-opensource/Kundera/jarstructure.png

**Comment by superstarz** [comment]
My jar is very close to your, you just have pc1 and pack folder. 
My project is running from eclipse. i'll upload an screenshot.

**Comment by superstarz** [comment]
http://image.noelshack.com/fichiers/2012/22/1338297784-untitled.jpg
this is my project.

**Comment by mevivs** [comment]
Please mail me your code base at vivek.mishra@yahoo.com

**Comment by superstarz** [comment]
done, thank you vivek !

**Comment by superstarz** [comment]
Resolved, i had eclipse and my workspace in C:\document and settings\me\
when i put all in C:\, eclipse has found my ententy class. 
Subject close

**Comment by mevivs** [comment]
Great!
