### ISSUE TITLE
List/nested embeddables bug?

### ISSUE THREAD

**Issue by zenzei** [Impetus/kundera#760]
I'm using kundera 3.0 snapshot from repository (cause i need the #747 fix), and I notice some kind of issue with lists/nested embeddables.

Currently I have something like this.

``` java
@Entity
public class Customer {
    @Id
    private int id;
    private String name;
    @ElementCollection
    private List<Address> addresses;
        ...
}

@Embeddable
public class Address {
   @Embeddable
    private City city;
    private String street;
    ...
}

@Embeddable
public class City {
    private String name;
    ...
}
```

What I see is that after saving a customer with two addresses, I have both street address, but only ony city. This are the columns in Hbase after running.
- name
- addresses#street#0
- addresses#street#1
- addresses#city#name
- addresses#size
  As you can see there are two streets (0 and 1), but only one city.

Maybe I'm mapping the entities in a wrong way?

**Comment by pragalbhgarg** [comment]
Hi @zenzei 

Thanks for raising the issue. Fix has been added in the trunk. Please build it and let us know.

-PG

**Comment by zenzei** [comment]
It works well, thanks for fixing it so quickly! 
You are great guys.
