### ISSUE TITLE
Does Kundera Entity support Tuple type mapping

### ISSUE THREAD

**Issue by rinascere** [Impetus/kundera#763]
Hi,
I'm using kundera in my cassandra project. but I don't see any documents about the Tuple Type mapping in entity, I tried com.datastax.driver.core.TupleType, and get null value in the tuple field.
Does Kundera support Tuple Type?
Thanks!

**Comment by karthikprasad13** [comment]
Hi @rinascere 

Kundera does not support `TupleType` fields as of now. There is a support for [`User-Defined Types`](https://github.com/impetus-opensource/Kundera/wiki/Support-for-User-Defined-Types-and-Indexes-on-Collections) (labeled version of TupleType) only.

-Karthik

**Comment by rinascere** [comment]
@karthikprasad13 
Thanks for your help.
