### ISSUE TITLE
when jql ends with ';' like "Select u from CassandraPrimeUser u where u.key.userId = :userId;", throw cannot find named parameter exception

### ISSUE THREAD

**Issue by patrickseptem** [Impetus/kundera#765]
when jql ends with ';' like "Select u from CassandraPrimeUser u where u.key.userId = :userId;", throw cannot find named paramter exception when query.setParameter("userId","name").

Should fix this or improve the error msg.

**Comment by patrickseptem** [comment]
the issue happens in latest 2.17 cassandra-core

**Comment by mevivs** [comment]
@patrickseptem 
Could you please share some more details around it? A test code snippet would really help.

tx,
-Vivek

**Comment by patrickseptem** [comment]
Hi Vivek,

You can use the test case onQuery of "./src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/compositeType/CassandraCompositeTypeTest.java" to check, just add append a character ";" in "Select u from CassandraPrimeUser u where u.key.userId = :userId".

**Comment by chhavigangwal** [comment]
Fixed with Kundera 3.1 release
