### ISSUE TITLE
IN clauses with cassandra

### ISSUE THREAD

**Issue by eugene-sotirescu** [Impetus/kundera#768]
what am i doing wrong?

using: CQL_VERSION, CassandraConstants.CQL_VERSION_3_0

@NamedQuery(
name="Persons.getPersons",
query="SELECT \* FROM persons p WHERE p.id IN :idList"
)
//id is a String in the cassandra cf persons

```
    EntityManager em = getEntityManagerFactory().createEntityManager();
    Query q = em.createNamedQuery("Persons.getPersons");
    List<String> ids = new ArrayList<String>();
    ids.add("1");
    ids.add("2");
    q.setParameter("idList", ids);
```

ERROR: "Bad query format FROM clause is mandatory for SELECT queries."

**Comment by karthikprasad13** [comment]
> what am i doing wrong?

Please use the following:

```
query="SELECT p FROM persons p WHERE p.id IN :idList"
              ^ 
   (valid JPA query format)
```

-Karthik

**Comment by eugene-sotirescu** [comment]
ah, yes, thank you.
