### ISSUE TITLE
findAll Bug

### ISSUE THREAD

**Issue by oswaldl** [Impetus/kundera#771]
i am using kundera **hbase** jpa client, and i have a class define like this:

```
@Entity 
@Table(name = "Oswaldl")
public class Oswaldl {

    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    private String id; 

    @Column(name="name")
    private String name; 

    @ElementCollection
    @Column(name="friends")
    private List<String> friends=new ArrayList<String>();

}
```

and i found array property **'friends'** is always empty when i use findAll method below:

this.entityManager.createQuery(String.format("select mb from %s mb", "Oswaldl")).setMaxResults(Integer.MAX_VALUE).getResultList();

Strange that when i use findById, it works!

this.entityManager.find(Oswaldl.class, "a id");

**Comment by devender-yadav** [comment]
@oswaldl 

kundera-hbase supports list of embeddable entities (e.g.`List<Embeddable Entity>`) and not native `List<String>`. So, as a work around you can create an embedded entity for `friends` with attribute `friend_name`, etc and use `List<friends>` instead of  `List<String>`.

It works in case of  `findById`(_as you mentioned_) because you are not clearing the persistence context before find. So, data is taken from persistence context cache rather than database. You can clear your persistence context  using `em.clear()`.

You can refer [this](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-hbase/kundera-hbase/src/test/java/com/impetus/client/twitter/TwitterTestBaseHbase.java) testcase where [TweetHbase](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-hbase/kundera-hbase/src/test/java/com/impetus/client/twitter/entities/TweetHbase.java) is embedded entity in [UserHBase](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-hbase/kundera-hbase/src/test/java/com/impetus/client/twitter/entities/UserHBase.java#L56).

**Comment by oswaldl** [comment]
so this is not a bug and won't be fixed?

**Comment by devender-yadav** [comment]
It's not a bug. As native HBase does not support collection, so managing those collections at Kundera  might create performance overhead. Hence kundera-hbase does not support it currently.

**Comment by oswaldl** [comment]
well, as you mention performance.

Will it be a performance problem if i don't use 'Embeddable' entity (e.g.List<Friend>friends) ?  

I've noticed that there will be a foreign key(e.g fk_oswaldl) created in 'Friend' entity pointing to parent entity 's rowkey. 

I doubt it is slow to gather friends across 'Friend' entity using a none rowkey property(fk_oswaldl)!

**Comment by devender-yadav** [comment]
In kundera-hbase list of embeddables is stored in the same column family. So, overhead is not much there.

**Comment by oswaldl** [comment]
so you mean the none-embed OneToMany usage which use a column family as a foreign key will be a problem if the many ones is huge?

**Comment by oswaldl** [comment]
Is it possible to query a property of type List here? e.g: select f from Family f WHERE :element in elements(f.elements)

**Comment by oswaldl** [comment]
how can i use pagination if i can't use the following querying for total count?
select count(*) from Family
causing:
com.impetus.kundera.KunderaException: Aggregations are not supported in this database. Please use Lucene or ES to create indexes if you want to do it

**Comment by devender-yadav** [comment]
In case of non-embedded one to many, children are stored in different HTable and having primary key of the parent. It will add an overhead as data is coming from two different HTable.  By the way, most of the NoSQL datastores are not meant for relationships, joins. So achieving this will obviously add a little bit of overhead.

**Comment by devender-yadav** [comment]
Regarding _Is it possible to query a property of type List here?_

Are you talking about IN query? eg: 

```
    List<Integer> list1 = new ArrayList<Integer>();
    list1.add(3);
    list1.add(4);
    list1.add(5);
    list1.add(6);
    Query query  = em.createQuery("select b from Book b where b.bookId in :list");
    query.setParameter("list", list1);
    results = query.getResultList();
```

This is supported. Find [this](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/query/HBaseQueryBaseTest.java#L169) testcase for more details.

**Comment by devender-yadav** [comment]
Regarding _Count Query_

Hbase does not support aggregations natively. You can use ElasticSearch to create indexes to perform aggregations over data.

Firstly, you need to add dependency for `kundera-elastic-search` in your `pom.xml`:

```
<dependency>
     <groupId>com.impetus.kundera.client</groupId>
     <artifactId>kundera-elastic-search</artifactId>
     <version>${kundera.version}</version>
</dependency> 
```

Then specify the indexer in the persistence unit and specify the fields in @IndexCollection on which aggregation need to be performed. Read [wiki](https://github.com/impetus-opensource/Kundera/wiki/How-to-perform-aggregation-over-data-stored-in-NoSQL%3F) for details.

Find testcase [here](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/query/HBaseESQueryTest.java).

**Comment by devender-yadav** [comment]
For _pagination_

As far as pagination is concerned, Hbase does not support it natively. But Kundera lets you set upper limit for the number of records that need to be fetched . It can be done using `setMaxResults` property.You need to manage the records that you want to fetch via your code. You can do that by  greater than query  based on row key id.

For example you have want to fetch only 3 books (max) having id > 3, you can do it as follows:

```
    String q = "Select b from Book b where b.id  > 3";
    Query query = em.createQuery(q);
    query.setMaxResults(3);     
    List<Book> resultList = query.getResultList();
```

**Comment by oswaldl** [comment]
For pagination

if i have total 5 records,

```
 String q = "Select b from Book b";
    Query query = em.createQuery(q);
    query.setFirstResult(3); 
    query.setMaxResults(3);     
    List<Book> resultList = query.getResultList();
```

resultList still return 3 records.

**Comment by devender-yadav** [comment]
`query.setFirstResult()` is not supported by `kundera-hbase`. Although you can limit no of records `query.setMaxResults()`. In your case, its showing top 3 records.

**Comment by oswaldl** [comment]
ok， many thanks!
