### ISSUE TITLE
extra data found in  OneToMany collection

### ISSUE THREAD

**Issue by oswaldl** [Impetus/kundera#772]
still using hbase jpa client, this is my entity definition:

```
@Entity
@Table(name="Oswaldl")
public class Man {
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    private String id;

    @Column(name = "name")
    private String name;

    @OneToMany(cascade=CascadeType.REMOVE)
    @OrderBy("id ASC")
    private Set<Man> boys = new HashSet<Man>();  
}
```

test code:

```
        Man m1 = new Man();
        m1.setId("id1");
        m1.setName("attr1");

        // add one boy here
        Man subm2 = new Man();
        subm2.setId("id2");
        subm2.setName("attr2");
        subm2.getBoys().add(subm2);
```

after save 'm1'  and refetch it, i got two boys in m1 instead of one(the extra one is m1 itself)!

**Comment by devender-yadav** [comment]
Are you using `kundera-hbase` or `kundera-hbase-v2` ?

**Comment by oswaldl** [comment]
com.impetus.kundera.client:kundera-hbase-v2:2.17

**Comment by devender-yadav** [comment]
We are marking it as a bug. We will add a fix soon.

**Comment by devender-yadav** [comment]
Thanks for raising the issue. Fix has been added in the trunk. Please build it and let us know.

**Comment by devender-yadav** [comment]
Find [this](https://github.com/impetus-opensource/Kundera/blob/854df7fceb51d44cdd0dd88256fddec919fc9125/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/hbase/crud/association/SelfReferentialUserOTMTest.java) testcase for more details.

**Comment by oswaldl** [comment]
ok, thanks

**Comment by oswaldl** [comment]
closed
