### ISSUE TITLE
null value can not be updated into hbase

### ISSUE THREAD

**Issue by oswaldl** [Impetus/kundera#775]
suppose i have a saved ObjectA and it have a name property values 'oswaldl',
then i set this name property to null and save ObjectA, 
fetch ObjectA again from Hbase, then you will find out that name property still values 'oswaldl'!
I manage to reset name property by setting it to '' now by the way~

**Comment by chhavigangwal** [comment]
@oswaldl 

Null values are not supported by HBase natively hence Kundera also ignores any null updates to an object. 

Chhavi
