### ISSUE TITLE
Does kundera-hbase support transation?

### ISSUE THREAD

**Issue by oswaldl** [Impetus/kundera#776]
Does following code works in kundera-hbase?

```
try{
entityManager.getTransaction().begin();
-----------some entities persist-----------------
this.entityManager.getTransaction().commit();
}catch(Exception e){
this.entityManager.getTransaction().rollback();
}
```

**Comment by devender-yadav** [comment]
Yes, transactions are supported in kundera-hbase. Refer [testcase](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/hbase/transaction/HBaseTransactionTest.java) for details.

**Comment by oswaldl** [comment]
i try to run a performance test

```
public SimpleTestOnPerform{
    private EntityManagerFactory entityMangerFactory = null;
    private EntityManager entityManager = null;
    static public SimpleTestOnPerform getInstance() {...}
    public boolean performAdd(ObjectA objectA) throws Exception{
        try {
            this.entityManager.getTransaction().begin();
            this.persist(objectA);
            this.entityManager.getTransaction().commit();
            return true;
        }catch (Exception e){
            e.printStackTrace();
            this.entityManager.getTransaction().rollback();
            return false;
        }
    }
}

```

number of threads: 100
code executed: SimpleTestOnPerform.getInstance().performAdd(objectA);
result: some errors(1%) occurs while runing the test, the error msg is:

```
java.lang.IllegalStateException: Transaction is already active
    at com.impetus.kundera.persistence.KunderaEntityTransaction.begin(KunderaEntityTransaction.java:57)
```

i wonder if it is the best practice to use entityManager as singlton pattern.

**Comment by oswaldl** [comment]
anyone tell me why?

**Comment by chhavigangwal** [comment]
@oswaldl 

An entity manager is not supposed to be thread-safe, so you shouldn't share it via a Singleton. Kundera does not create thread safe instance of entityManager itself.

Chhavi

**Comment by oswaldl** [comment]
Okay
