### ISSUE TITLE
HBase Cloudera Version - Kundera

### ISSUE THREAD

**Issue by karthicbalaji** [Impetus/kundera#778]
Dear Team,

Firstly thanks a lot for your dynamic approach to fit Kundera with multiple No-SQL DB.

I am new to this Kundera ORM library and I am trying to use HBase - Kundera with Cloudera distribution 5.4.

I request you to please guide me for using the same.

Also request you how to find the Kundera version equivalent for HBase support either Apache or Cloudera. I could not find this information in GitHub document and request to please specify the same.

Regards,
R.G. Karthic Balaji

**Comment by chhavigangwal** [comment]
@karthicbalaji 

As Cloudera distribution 5.4 uses HBase 1.0 , you can start using kundera-hbase-v2 's latest version 3.0 to start using HBase in your application. You can find further details at :

https://github.com/impetus-opensource/Kundera/wiki/Kundera-with-HBase

Hope that helps,
Chhavi

**Comment by karthicbalaji** [comment]
Dear Chhavi,

I will make use of Kundera-Hbase-v2 and will definitely post you...

Thanks for your timely comments...

Regards, 
R.G. Karthic Balaji

**Comment by oswaldl** [comment]
by the way, what is the difference bewteen 'Kundera-Hbase' and 'Kundera-Hbase-v2'?

**Comment by oswaldl** [comment]
can you give one maven-repo url works for 'com.impetus.kundera.client:kundera-hbase-v2:3.0'

**Comment by devender-yadav** [comment]
Find [wiki](https://github.com/impetus-opensource/Kundera/wiki/Kundera-with-HBase) for difference between the two.

**Comment by chhavigangwal** [comment]
Closing with Kundera 3.1 release
