### ISSUE TITLE
Read/write consistency configuration in using Kundera-Cassandra

### ISSUE THREAD

**Issue by FreeWhere** [Impetus/kundera#78]
I want to set the read/write consistency in Kundera client, but I can't where I can do it.

**Comment by mevivs** [comment]
Hi,
Please have a look at:
https://github.com/impetus-opensource/Kundera/issues/57

This will be delievered in 2.0.7 alongwith other features.

-Vivek

**Comment by FreeWhere** [comment]
Thanks.
