### ISSUE TITLE
Hbase find All Bug

### ISSUE THREAD

**Issue by oswaldl** [Impetus/kundera#780]
i am using kundera **hbase** jpa client, and i have a class define like this:

```
@Entity 
@Table(name = "Oswaldl")
public class Oswaldl {

    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    private String id; 

    @Column(name="name")
    private String name; 

}
```

test code:

```
        Oswaldl oswaldl1 = new Oswaldl();
        oswaldl1.setName("test1");

        this.persist(oswaldl1);
        List<Oswaldl> oswaldls1 = this.findAll(Oswaldl.class);
        System.out.println(oswaldls1.get(0).getName());

        oswaldl1.setName("test2");
        this.persist(oswaldl1);
        List<Oswaldl> oswaldls2 = this.findAll(Oswaldl.class);
        System.out.println(oswaldls2.get(0).getName());

        oswaldl1.setName("test3");
        this.persist(oswaldl1);
        List<Oswaldl> oswaldls3 = this.findAll(Oswaldl.class);
        System.out.println(oswaldls3.get(0).getName());
```

expected result:
test1
test2
test3

actual result:
test1
test2
test2

i think it's a bug of cache, because if i add 'this.getEntityManger().clear();', the result is right!

**Comment by pragalbhgarg** [comment]
This might not be a bug at all. I guess you are expecting wrong result since order of retrieval cannot be guaranteed to be same as order of insertion by Kundera. Hence, first result in the List `oswalds3` might not be the object with name field value as `test3`. You must check for all the objects in the list, if it does not contain all the objects, then this must be a bug.

-PG

**Comment by oswaldl** [comment]
only one object save here:
oswaldls1.size()==1;
oswaldls1.size()==oswaldls2.size();
oswaldls3.size()==oswaldls2.size();

**Comment by oswaldl** [comment]
i think this is a very terrible bug, many data inconsistent appears because of it. Is there a way to turn off the cache module for temporary solution ?

**Comment by chhavigangwal** [comment]
@oswaldl 

This is not a bug and you can simple handle this by adding this.getEntityManger().clear(); before every fetch operation.

Hope this helps !
Chhavi

**Comment by oswaldl** [comment]
i'v solved the problem finally by disable/drop table

**Comment by chhavigangwal** [comment]
@oswaldl 

Are we good to close on this?

Chhavi
