### ISSUE TITLE
support for UDTs in collections

### ISSUE THREAD

**Issue by eugene-sotirescu** [Impetus/kundera#788]
does kundera support something like this?

```
CREATE TYPE ip(
  ips set<text>
);
CREATE TABLE info(
network map<text, frozen<ip>>
);

@Embeddable
public class Ip{
    @Column
    private Set<String> ips;

    public Set<String> getIps() {
        return ips;
    }
    public void setIps(Set<String> ips) {
        this.ips= ips;
    }
```

and if it does support it, how do I code it in the Info entity class? how do I annotate the Ip class as Embedded? this doesn't work:

```
    private Map<String, Ip> network;

    public Map<String, Ip> getNetwork() {
        return network;
    }

    public void setNetwork(Map<String, Ip> network) {
        this.network= network;
    }
```

thanks.

**Comment by eugene-sotirescu** [comment]
correction:
CREATE TABLE info(
network map<text, frozen<ip>>,

);

**Comment by karthikprasad13** [comment]
@eugene-sotirescu 

Yes, Kundera supports UDTs in collections and it is facilitated by JPA equivalent of `@ElementCollection`. You just need to annotate the field as follows:

```
 @ElementCollection
 private Map<String, Ip> network;
```

You can refer this [`wiki`](https://github.com/impetus-opensource/Kundera/wiki/Support-for-User-Defined-Types-and-Indexes-on-Collections) for more info and this [`package`](https://github.com/impetus-opensource/Kundera/tree/trunk/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/cassandra/udt) which has entities with complex relations and testcases.

-Karthik

**Comment by eugene-sotirescu** [comment]
Thank you sir, this works!
Would you happen to know how I can refer to this type by a different name?
Say the UDT name is ip_numbers but I want to call my class Ip.
@Embeddable(name="ip_numbers")
class Ip...
doesn't work.

**Comment by karthikprasad13** [comment]
@eugene-sotirescu 

You are welcome, sir.
I am afraid this feature is not currently supported by Kundera. We have it in our road map and will try to add it soon.

-Karthik.

**Comment by chhavigangwal** [comment]
Emebddable does not have name property supported in JPA-2.1
