### ISSUE TITLE
TypedQuery#setFirstResult(int) isn't supported in HBase

### ISSUE THREAD

**Issue by mhorejsi** [Impetus/kundera#798]
When I create a TypedQuery

```
TypedQuery<...> query = ...
```

and call:

```
query.setFirstResult(4);
```

it doesn't have any effect. 

Looking into the sources, it's clear that this method isn't taken into account.
#384 claims that pagination is currently supported for HBase. What does it mean? Is there any other way to do pagination?

Do you plan to support Query#setFirstResult method? (Is it even possible?)

**Comment by devender-yadav** [comment]
@mhorejsi 

`query.setFirstResult()` is not supported by **kundera-hbase**. Although you can limit number of records using `query.setMaxResults()` as it is supported.

-Devender

**Comment by mhorejsi** [comment]
Do you plan to support it in the future? Is it even possible to implement it? I'm interested in `query.setFirstResult()` for kundera-hbase and kundera-oracle-nosql.

**Comment by chhavigangwal** [comment]
@mhorejsi 

Hbase internally does not support setting initial page limit and hence is not supported by Kundera as well.

Chhavi

**Comment by chhavigangwal** [comment]
Closing with Kundera-3.2
