### ISSUE TITLE
Provide support for Cross-store persistence in Kundera

### ISSUE THREAD

**Issue by xamry** [Impetus/kundera#8]
This is a feature that is much awaited and long overdue. 
It should enable user to store related entities in different databases. 

Eg. If User entity has Preference entity defined as relationship, and we specify that Preference entity to be persisted in "twibase" rather than "twissandra", Kundera should be able to persist User in cassandra and Preference in HBase.

@Table(name = "users", schema = "KunderaExamples")
public class User 
{
@OneToOne(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
      private Preference preference;

}
@Table(name = "preference", schema = "KunderaExamples@twibase")
public class Preference
{

}

**Comment by mevivs** [comment]
delivered in 2.0.4

**Comment by xamry** [comment]
implemented in version 2.0.4, closing
