### ISSUE TITLE
How can I execute batch insert?

### ISSUE THREAD

**Issue by FreeWhere** [Impetus/kundera#80]
How can I execute batch insert?

**Comment by mevivs** [comment]
Could you please explain it a bit?

**Comment by FreeWhere** [comment]
I want to execute batch insert using Kundera Cassandra, like batch_mutate in Thrift API. How can I do it?

**Comment by mevivs** [comment]
Currently not supported, 2.0.7 release will try to cover it up.

**Comment by FreeWhere** [comment]
What time will 2.0.7 release?

**Comment by mevivs** [comment]
i will post an update.. But most probably early week next month. I will try to post an update as soon as this feature becomes available in latest "trunk".

**Comment by FreeWhere** [comment]
Thanks, I will pull from "trunk".

**Comment by mevivs** [comment]
Reopening, as this is a release candidate for 2.0.8 now.

**Comment by mevivs** [comment]
Support added. Please refer :
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/CassandraBatchProcessorTest.java

for test case and how to use it.

**Comment by mevivs** [comment]
Closing it as batch process support is in.
