### ISSUE TITLE
Are scalar queries supported over DataStax Cassandra driver?

### ISSUE THREAD

**Issue by xshaka** [Impetus/kundera#802]
Hi, I'm a getting a really weird error when performing a scalar native query with Kundera over Datastax driver. When debugging, I set that when no class is set during native query creation, Kundera randomly chooses the EntityMetadata to use, and thus fails when trying to assign my String results to some Entity. My question then is, can I perform scalar queries over such driver? If so, how to do it??

**Comment by karthikprasad13** [comment]
@xshaka 

Yes, it is possible to perform scalar queries on Cassandra through Datastax driver. Please add the following line in your persistence unit if not already added.

```
<exclude-unlisted-classes>true</exclude-unlisted-classes>
```

Also, refer this [`testcase`](https://github.com/impetus-opensource/Kundera/blob/4bc732ebeea971d0449e4bf67a70023e83a72a8b/src/kundera-cassandra/cassandra-ds-driver/src/test/java/com/impetus/client/crud/CassandraScalarQueriesTest.java) for more info.

-Karthik

**Comment by xshaka** [comment]
Well, apparently, Kundera takes the scalar queries way only when no Entity class is supplied. Please confirm this is intended to work this way and we are done here. I will use a secondary persistence unit just to perform scalar queries.

**Comment by karthikprasad13** [comment]
@xshaka 

Scalar queries are an interface to write any native query (select, create, update, metadata queries, etc) and get the results in raw format (not wrapped in entities). Hence, they are not expected to be used with entities.

-Karthik

**Comment by karthikprasad13** [comment]
@xshaka 

Any updates? Are we good to close this issue?

-Karthik
