### ISSUE TITLE
RethinkDB support

### ISSUE THREAD

**Issue by anand-singh** [Impetus/kundera#805]
The open-source database for the realtime web. http://rethinkdb.com

**Comment by anand-singh** [comment]
no driver available and building some interesting work ..would like to use in prod

**Comment by anand-singh** [comment]
@mevivs : could you please look into this

Thanks,
Anand

**Comment by devender-yadav** [comment]
@anand-singh 

Thank you for suggestion. I see there is no Java api for rethinkDB as of now. Are you guys working on it? 

-Dev

**Comment by anand-singh** [comment]
Hi @devender-yadav,

Thanks for the interest, Actually we are building a project using RethinkDB as a Database.

So that looking for RethinkDB driver in Java or Scala.

Thanks,
Anand

**Comment by debop** [comment]
Now support Java  [Rethink-Java](https://rethinkdb.com/docs/install-drivers/java/) 
Check out java driver please.

**Comment by devender-yadav** [comment]
Hi @debop,

Thank you for the reply. We will add support for RethinkDB using Kundera in the very next release.

-Dev
