### ISSUE TITLE
Purging database on init, and IDs returning incorrectly

### ISSUE THREAD

**Issue by ghost** [Impetus/kundera#807]
I have a couple of issues, one of which was easy enough to solve and the other is ongoing.

First, when Kundera starts, it is currently purging the database of all rows. Initially I thought this would be it creating the schema, but it is already set to 'create' rather than 'create_delete', and neither 'update' or removing the line entirely was any help.

```
        <property name="kundera.nodes" value="localhost"/>
        <property name="kundera.port" value="9160"/>
        <property name="kundera.keyspace" value="mimdata"/>
        <property name="kundera.dialect" value="cassandra"/>
        <property name="kundera.ddl.auto.prepare" value="create" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
```

The second issue, which I have somewhat solved (although in a less than optimal way), is that when performing a query such as:

Select p from UserDetails p where p.email = 'someemail'

the result has a mangled id (p.id). Rather than maintaining the value it was set, it gets returned as -2147418110

Obviously when I go back to persist it, this creates an error. So to fix it I had to create a second column which duplicates this id, which does get returned correctly. 

Any clue how I can fix these two errors?

**Comment by devender-yadav** [comment]
Hi,

I suggest you to use `ThriftClient` instead of `PelopsClient`. You can do this by changing `kundera.client.lookup.class` property to the following:

```
<property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />         
```

Also, please share your `UserDetails` entity definition.

PS: Make sure you are using [latest version of Kundera](http://mvnrepository.com/artifact/com.impetus.kundera.client/kundera-cassandra)

-Dev

**Comment by ghost** [comment]
Yeah that worked
