### ISSUE TITLE
Kundera ClassCastException with MongoDB

### ISSUE THREAD

**Issue by oscarduque018** [Impetus/kundera#808]
I'm using Kundera to do the persistence in MongoDB. I can persist some documents in my collection, but everytime that I try to find a specific document by id, I get this error

java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb.BasicDBList com.impetus.kundera.persistence.AbstractEntityReader.findById(AbstractEntityReader.java:95) com.impetus.client.mongodb.MongoEntityReader.findById(MongoEntityReader.java:72) com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:com.impetus.kundera.graph.Node.find(Node.java:500) com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:225) com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:174) com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:263)

**Comment by devender-yadav** [comment]
@cosmicgarden 

Can you please share your Entity Class & query used to find the document by id ?

-Dev

**Comment by devender-yadav** [comment]
@cosmicgarden 

I answered your question at : http://stackoverflow.com/questions/33879771/kundera-classcastexception-with-mongodb

**Comment by devender-yadav** [comment]
@cosmicgarden 
Are we good to close this?

**Comment by chhavigangwal** [comment]
Closing it with Kundera-3.3
