### ISSUE TITLE
OracleNOSQL Enterprise : How do I authenticate ORACLENOSQL through SSL and Wallet? 

### ISSUE THREAD

**Issue by nikitaGoyal2** [Impetus/kundera#810]
I am looking for property name to provide authentication file.

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

We haven't added support for security in current release of oracle-kv client . We will add this soon in our trunk and release it as apart of 3.3 release

Chhavi

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

You can enable security related configurations by adding them as externalProperties map while creating EntityManagerFactory or specify them in an external configuration file and add it as a kundera.client.property file in persistence.xml

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-oracle-nosql/src/test/resources/kvstoreSecurityConfig.xml

Let me know in case you face any issue 

Chhavi
