### ISSUE TITLE
com.impetus.kundera.query.QueryHandlerException : No entity found by the name: Employee

### ISSUE THREAD

**Issue by vinitsharma87** [Impetus/kundera#819]
I am having Cassandra 2.2.4, Kundera 3.2 and Play! framework 2.4.6 versions respectively. I am trying to create a CRUD example using Cassandra db and Kundera 3.2. But its not getting connected. The error it shows during any database operation is
com.impetus.kundera.query.QueryHandlerException : No entity found by the name: Employee

The persistence.xml file contents are as under:
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra_employees">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>models.domains.Employee</class>
        <properties>
            <property name="kundera.nodes" value="localhost" />
            <property name="kundera.port" value="9160" />
            <property name="kundera.keyspace" value="employeeexample" />
            <property name="kundera.dialect" value="cassandra" />
            <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
            <property name="kundera.pool.size.max.active" value="50" />
            <property name="kundera.pool.size.max.total" value="50" />
        </properties>
    </persistence-unit>
</persistence>

Also my entity file is as under:

package models.domains

import java.util.Date
import javax.persistence._
import java.util.UUID

@Entity
@Table(name = "employees", schema = "employeeexample@cassandra_employees")
class Employee {

  @Id
  var id: String = UUID.randomUUID.toString()

  @Column(name = "name")
  var name: String = "Employee"

  @Column(name = "address")
  var address: String = "Address"

  @Column(name = "dob")
  var dob: String = (new Date).toLocaleString()

  @Column(name = "joiningDate")
  var joiningDate: String = (new Date).toLocaleString()

  @Column(name = "designation")
  var designation: String = "Test"

}

case class EmployeeForm(id: String, name: String, address: String, dob: Date, joiningDate: Date, designation: String)

**Comment by devender-yadav** [comment]
@vinitsharma87 

I checked the same project you mentioned over StackOverflow. We are looking into the issue & will update you soon.

-Dev

**Comment by devender-yadav** [comment]
Try to start your application by `activator run` command.

Also, add the below-mentioned property to create schema automatically.

```
  <property name="kundera.ddl.auto.prepare" value="create" />
```

Read more about [schema generation](https://github.com/impetus-opensource/Kundera/wiki/Schema-Generation) in Kundera.

-Dev

**Comment by vinitsharma87** [comment]
@devender-yadav : My entity file is as under:

package models.domains

import java.util.Date
import javax.persistence._
import java.util.UUID

@Entity
@Table(name = "employee", schema = "employeeexample@cassandra_employees")
class Employee {

  @Id
  var id: String = UUID.randomUUID.toString()

  @Column(name = "name")
  var name: String = "Employee"

  @Column(name = "address")
  var address: String = "Address"

  @Column(name = "dob")
  var dob: String = (new Date).toLocaleString()

  @Column(name = "joiningDate")
  var joiningDate: String = (new Date).toLocaleString()

  @Column(name = "designation")
  var designation: String = "Test"

}

case class EmployeeForm(id: String, name: String, address: String, dob: Date, joiningDate: Date, designation: String)

Please tell me what could be wrong with this ? Also one more thing, I created one simple java file inside which I was creating a KEYSPACE in cassandra. I was able to create keyspace from my java code, provided that I was using datastax driver. I wonder whats the requirement of datastax driver ? If I am  using Kundera, do I need a driver like this so as to get connected with the database ? Can I have a chat with you if you could spare some time ?

**Comment by devender-yadav** [comment]
@vinitsharma87  

Did the above solution work for you?

-Dev

**Comment by vinitsharma87** [comment]
@devender-yadav  No my problem is still unsolved. Can you avail me your yahoo or some other id where we can chat ? If thats fine with you ?

**Comment by devender-yadav** [comment]
@vinitsharma87 

Let's discuss here:  http://webchat.freenode.net/?channels=Kundera#

-Dev

**Comment by vinitsharma87** [comment]
I have joined that chat. Can't find you there.?

**Comment by karthikprasad13** [comment]
As discussed, problem was with the configuration. Closing as not an issue.
