### ISSUE TITLE
JPQL: "OR" operator not working for MongoDB

### ISSUE THREAD

**Issue by vreniers** [Impetus/kundera#823]
Hi, 

I'm having an issue with  the JPQL OR operator in MongoDB. Apparently this is not supported.
Even though it is stated as supported in the [documentation](https://github.com/impetus-opensource/Kundera/wiki/JPQL).

The following is an excerpt of my code:

``` java
String queryStr = "Select p from Person p WHERE p.firstName = :fstname OR p.lastName = :lstname";

Query query = em.createQuery(queryStr);

query.setParameter("fstname", person.getFirstName());
query.setParameter("lstname", person.getLastName());

List<Person> people = query.getResultList();
System.out.println(people.size());

```

This code seems to return way too little results, 1 or 2 instead of 300+ which the MongoDB find operator shows. I don't think there's anything wrong with the code, as I use the exact same code for another JPA implementation and it works fine there. Instead I think Kundera considers this OR as an AND.

**Comment by devender-yadav** [comment]
@vreniers 

For `OR` queries in Kundera-MongoDB, you need to put conditions in  _parenthesis_. Modify your query like this:

```
 "Select p from Person p WHERE (p.firstName = :fstname) OR (p.lastName = :lstname)"
```

-Dev

**Comment by vreniers** [comment]
This solved it. Thanks!
