### ISSUE TITLE
Kundera L1 Cache

### ISSUE THREAD

**Issue by vreniers** [Impetus/kundera#826]
Hi,

I was wondering if Kundera makes use of the L1 cache.
Other JPA-implementations often make use of the L1 cache to store objects while they
participate in transactions. The L1 Cache serves as a persistence context cache / transactional cache.

Is this the same for Kundera and is there a way to manage this cache?

**Comment by devender-yadav** [comment]
@vreniers 

Yes, Kundera makes use of the L1 cache. L1 cache is bound to entity manager/session as per JPA.
Kundera, being a JPA provider supports Transaction Management.
 Check out [documentation](https://github.com/impetus-opensource/Kundera/wiki/Transaction-Management) for more details.

-Dev
