### ISSUE TITLE
NoSQL : Multiple Nodes support not working

### ISSUE THREAD

**Issue by nikitaGoyal2** [Impetus/kundera#827]
I was trying to configure nosql cluster nodes in persistence.xml , 
     <property name="kundera.nodes" value="NIKIGOYA-IN, HIST2" />

but it is throwing oracle.kv.KVStoreException: Could not contact any RepNode at: [NIKIGOYA-IN, HIST2:5000] 

Please suggest.

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

Marking it as bug ,no you currently cannot use multiple nodes with Kundera-oraclenosql.
This fix will be available with 3.3 release.

Chhavi

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

This issue has been fixed and released with Kundera-3.3 , you can now use multiple nodes with kundera-oracle-noql by specifying in comma separated list in persistence.xml or an external xml file by adding it in kundera.client.property file property : https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-oracle-nosql/src/test/resources/kvstoreSecurityConfig.xml

Please let us know in case you face any issue

Chhavi

**Comment by nikitaGoyal2** [comment]
Hi chhavi,

But this version is not yet updated in
http://mvnrepository.com/artifact/com.impetus.kundera.client/kundera-oracle-nosql.
From where do I get jars?

Regards,
Nikita

On Sat, Jan 16, 2016 at 9:24 AM, chhavigangwal notifications@github.com
wrote:

> @nikitaGoyal2 https://github.com/nikitaGoyal2
> 
> This issue has been fixed and released with Kundera-3.3 , you can now use
> multiple nodes with kundera-oracle-noql by specifying in comma separated
> list in persistence.xml or an external xml file by adding it in
> kundera.client.property file property :
> https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-oracle-nosql/src/test/resources/kvstoreSecurityConfig.xml
> 
> Please let us know in case you face any issue
> 
> Chhavi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/impetus-opensource/Kundera/issues/827#issuecomment-172153658
> .

## 

_Regards ,_

Nikita Goyal
goyalnikita277@gmail.com

Mob-\* 91-9650630692*

**Comment by nikitaGoyal2** [comment]
Hi Chhavi,

Kindly update the jars on open artifactory.

Regards,
Nikita

On Sat, Jan 16, 2016 at 11:03 AM, Nikita Goyal goyalnikita277@gmail.com
wrote:

> Hi chhavi,
> 
> But this version is not yet updated in
> http://mvnrepository.com/artifact/com.impetus.kundera.client/kundera-oracle-nosql.
> From where do I get jars?
> 
> Regards,
> Nikita
> 
> On Sat, Jan 16, 2016 at 9:24 AM, chhavigangwal notifications@github.com
> wrote:
> 
> > @nikitaGoyal2 https://github.com/nikitaGoyal2
> > 
> > This issue has been fixed and released with Kundera-3.3 , you can now use
> > multiple nodes with kundera-oracle-noql by specifying in comma separated
> > list in persistence.xml or an external xml file by adding it in
> > kundera.client.property file property :
> > https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-oracle-nosql/src/test/resources/kvstoreSecurityConfig.xml
> > 
> > Please let us know in case you face any issue
> > 
> > Chhavi
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/impetus-opensource/Kundera/issues/827#issuecomment-172153658
> > .
> 
> ## 
> 
> _Regards ,_
> 
> Nikita Goyal
> goyalnikita277@gmail.com
> 
> Mob-\* 91-9650630692*

## 

_Regards ,_

Nikita Goyal
goyalnikita277@gmail.com

Mob-\* 91-9650630692*

**Comment by devender-yadav** [comment]
@nikitaGoyal2 

You can directly add this dependency to your project:

```
<dependency>
    <groupId>com.impetus.client</groupId>
    <artifactId>kundera-oracle-nosql</artifactId>
    <version>3.3</version>
</dependency>
```

**Comment by nikitaGoyal2** [comment]
I have configured multiple nodes in persistence.xml and
pointed kundera core and nosql to same version 3.3. But things stopped
working.

Please help here.

Getting below error:

Caused by: java.lang.IllegalArgumentException: helperHostPort is null

at oracle.kv.KVStoreConfig.setHelperHostsVoid(KVStoreConfig.java:331)

at oracle.kv.KVStoreConfig.setHelperHosts(KVStoreConfig.java:315)

at oracle.kv.KVStoreConfig.<init>(KVStoreConfig.java:220)

at
com.impetus.client.oraclenosql.OracleNoSQLClientFactory.getConnection(OracleNoSQLClientFactory.java:217)

at
com.impetus.client.oraclenosql.OracleNoSQLClientFactory.createPoolOrConnection(OracleNoSQLClientFactory.java:132)

at
com.impetus.kundera.loader.GenericClientFactory.load(GenericClientFactory.java:119)

at
com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:55)

at
com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)

at
com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)

at
com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)

at
com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)

at
javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)

at
javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)

... 49 more

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

Please share your persistence.xml

Chhavi

**Comment by nikitaGoyal2** [comment]
Please check.

<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://java.sun.com/xml/ns/persistence" version="2.0">
     <persistence-unit name="bacs-1-NOSQLTEST125_draft_events-write_">
            <provider>com.impetus.kundera.KunderaPersistence</provider>

<class>com.oracle.bacs.demo.speedcamera.avro.generated.CameraEvent_0_measurementsSql</class>
            <properties>
                <property name="kundera.nodes" value="NIKIGOYA-IN,
snikq.us.idm.com" />
                <property name="kundera.port" value="5000" />
                <property name="kundera.client.lookup.class"

value="com.impetus.client.oraclenosql.OracleNoSQLClientFactory" />
                <property name="kundera.keyspace" value="kvstore" />
                <property name="kundera.dialect" value="kvstore" />
                <property name="kundera.client" value="kvstore" />
                
                <property name="kundera.indexer.class"

value="com.impetus.client.oraclenosql.index.OracleNoSQLInvertedIndexer" />
            </properties>
        </persistence-unit>
</persistence>

On Sat, Jan 16, 2016 at 7:18 PM, chhavigangwal notifications@github.com
wrote:

> @nikitaGoyal2 https://github.com/nikitaGoyal2
> 
> Please share your persistence.xml
> 
> Chhavi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/impetus-opensource/Kundera/issues/827#issuecomment-172208187
> .

## 

_Regards ,_

Nikita Goyal
goyalnikita277@gmail.com

Mob-\* 91-9650630692*

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

I apologize for this miss and we will plan for a patch release pretty soon which will cover this fix. Meanwhile , can you follow these steps to build code once at your end  and check again for both security settings as well multiple nodes working in your code.

git clone https://github.com/impetus-opensource/Kundera/
cd Kundera
mvn clean install -DskipTests -Poracle-nosql 

Once you follow the above steps, please add dependency in your project as follows :

```
<dependency>
    <groupId>com.impetus.client</groupId>
    <artifactId>kundera-oracle-nosql</artifactId>
    <version>3.4-SNAPSHOT</version>
</dependency>
```

Please let us know in case you face any issue.

Chhavi
