### ISSUE TITLE
Kundera - Cassandra Transaction Rollback

### ISSUE THREAD

**Issue by KlemensEngel** [Impetus/kundera#829]
In kundera-cassandra 3.2 the transaction management is not working. When using the `EntityManager.merge(Entity)` method kundera creates an INSERT statement instead of an UPDATE statement. If the transaction fails and I call the rollback method then kundera deletes the entity from the cassandra database instead of rollback the update. 

Kundera-cassandra 3.2 
Cassandra 2.2.4

Link to a more detail information: http://stackoverflow.com/questions/35013300/kundera-cassandra-transaction-rollback-and-entity-update

**Comment by KlemensEngel** [comment]
It was a mistake from me: I fetched the entity with another instance of EntityManager class and also in another transaction, therefore Kundera was not able to correctly rollback the transaction. Take a look at http://stackoverflow.com/questions/35013300/kundera-cassandra-transaction-rollback-and-entity-update

In my opinion this issue can be closed.

**Comment by chhavigangwal** [comment]
Closing the issue :)
