### ISSUE TITLE
Slow performance - Kundera / Spring

### ISSUE THREAD

**Issue by jainman** [Impetus/kundera#83]
I am trying to build an application using Kundera ORM  communicating with  HBASE/ HDFS Standalone pseudo distributed standalone deployment.

I wrote a simple spring  application with Kundera ORM persistence APIs with  one Entity /  and DAO.

Now I am inserting around 2000 records.

The performance is very very slow- each record is taking around 30 seconds. 

Same application when work with MySQL inserts 2000 records in just < 2 mins.

Please suggest if I am missing something.

Sample code is https://github.com/impetus-opensource/Kundera-Examples/wiki/Using-Kundera-with-Spring

**Comment by mevivs** [comment]
Could you please share your your sample code?

**Comment by mevivs** [comment]
Wondering if mysql and HBase both are on local machine or remote machine?

We did notice some performance issues in HBase but not like 30seconds per record and we are working on it for next immediate release.

**Comment by mevivs** [comment]
Are you creating new EM or EMF on each record persistence?

Or simply calling em.persist() in a loop?

-Vivek

**Comment by jainman** [comment]
I am still facing this issue. Performance is very slow.  So better I share the code. [ I don't know How can upload  code here. So  send directly to ur mail.
I get one unique problem - For one of my entity Column family is not getting created.  See below.
But all other entities are having correct column family
LOGRECORD   {NAME => 'LOGRECORD', FAMILIES => []}

**Comment by mevivs** [comment]
Fixed and phased  out lucene for most of part.
