### ISSUE TITLE
maven-checkstyle-plugin dependency not resolvable

### ISSUE THREAD

**Issue by syr** [Impetus/kundera#831]
some dependencies are not resolvable.
maven-checkstyle-plugin version 2.3.2 -> Changed that to 2.15 to fix that.

further unresolvable deps:
org.safehaus.jug:jug-asl:jar:2.0.0 -> thus, module kundera-tests fails to build

**Comment by chhavigangwal** [comment]
This jar was uploaded in Kundera's missing dependencies repo location but seems to be missing from there now. We'll fix this and update you on same.

Chhavi

**Comment by karthikprasad13** [comment]
@syr 

`org.safehaus.jug:jug-asl:jar:2.0.0` is removed from kundera-tests module and `maven-checkstyle-plugin version 2.3.2` is now resolvable. We will upgrade it in future releases.

-Karthik
