### ISSUE TITLE
Add support for Couchbase

### ISSUE THREAD

**Issue by arun-gupta** [Impetus/kundera#833]
Please add support for Couchbase to Kundera.

**Comment by chhavigangwal** [comment]
@arun-gupta 

We have this in our road-map already but we would like to better understand the specific use case for this integration which will help us prioritize it. Please let me know a good time to connect at https://gitter.im/impetus-opensource/Kundera 

Chhavi

**Comment by arun-gupta** [comment]
Posted a message

**Comment by chhavigangwal** [comment]
@arun-gupta 

Kundera team will enable the support for Couchbase in parts in its next two releases.

Chhavi

**Comment by arun-gupta** [comment]
@chhavigangwal sounds good, let me when it is released.

**Comment by pedrofpvieira** [comment]
Any new milestone regarding this? would be great to see couchbase support

**Comment by devender-yadav** [comment]
Hi @arun-gupta @pedrofpvieira,

We started working on this and trying to cover basic features in the upcoming release.

-Dev

**Comment by devender-yadav** [comment]
Wiki - https://github.com/impetus-opensource/Kundera/wiki/Kundera-with-Couchbase
