### ISSUE TITLE
add support for datastax driver 3.0

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#835]
Hi,

In my project we use datastax ddc 3.2.1 which requires datastax driver 3.0. As of now, kundera uses datastax driver 2.1.3 which is not compatible with datastax ddc 3.2.1.

Do you have plan to upgrade datastax driver in kundra?

Thank you!

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
@mqian 

Hey,

We do have plans for upgrading datastax driver, most possibly with the next release.

-Karthik

**Comment by canopenerda** [comment]
@karthikprasad13 

Thanks Karthik for the quick response. As of now, I hardwired in the higher version, which is working fine with kundera, except for date types which can't be selected from the data store, since the interfaces in the ds driver changes. So I had to store date type in long type as a workaround.

Thanks & Regards,
Malcolm

**Comment by devender-yadav** [comment]
@mqian 

It is fixed in Kundera 3.5. Please verify.

-Dev
