### ISSUE TITLE
OracleNoSql Authentication

### ISSUE THREAD

**Issue by nikitaGoyal2** [Impetus/kundera#836]
As kundera doesnot support authentication for OracleNoSQL, how do we handle it in our project? We have username and password but how do we use in kundera.

**Comment by nikitaGoyal2** [comment]
Can you please update it on urgent basis?

**Comment by chhavigangwal** [comment]
@nikitaGoyal2 

You can simply configure username/password via adding these fields in persistence.xml 

```
<property name="kundera.username" value="kunderauser" />
<property name="kundera.password" value="kunderapassword" />
```

Please verify this at you end 

Chhavi
