### ISSUE TITLE
Setting different consistency level for write and read

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#837]
Hi,

I know how to set consistency level on entity manager through persistence context, but I'm wondering how I can set different consistency levels for read and write operations. In my project, we need to set ALL for write and ONE for read.

Thank you!

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
@mqian 

You can also set it directly at `EntityManager` level as follows:

```
em.setProperty("consistency.level", ConsistencyLevel.ALL);
```

-Karthik

**Comment by canopenerda** [comment]
@karthikprasad13 
The problem with setting it directly at EntityManager is that I need to set it back to the original value. Is there any better solution, e.g. through annotation on method?

Thank you!

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
@mqian 

There are 3 ways to set the `ConsistencyLevel`.. through external property file, through `EntityManagerFactory` and through `EntityManager`. So, setting it directly at `EntityManager` is the best solution as of now. Also, there are no annotations defined explicitly for this.

-Karthik

**Comment by canopenerda** [comment]
@karthikprasad13 
I tested with PersistenceContextType.EXTENDED, and directly set consistency level at EntityManager. Not all data are persisted. But if I wired in two entity managers each with different consistency level, and it had no issues.

Thank you!

Regards,
Malcolm
