### ISSUE TITLE
@ElementCollection for Map in Hbase

### ISSUE THREAD

**Issue by zenzei** [Impetus/kundera#842]
Does ElementCollection for a map work with Hbase? 

As I was having the issue explain in #838, I decide to use some kind of map for the attributes i need to store (instead of inheritance and discriminator column/value). Basically i update my code to this

``` java
@Entity
public class Table {
    @Id
    private String id;
    private String name ; 
    @ElementCollection
    private List<Field> columns ;
    ...
}

@Embeddable
public class Field {
    private String name ; 

    @ElementCollection
    private Map<String, Object> fieldTypeAttributes;
    ...
}
```

The map has the attribute name as the map key and the attribute value (objects that are basic types) as the map values But it seems that the Map annoted with ElementCollection is not being saved.

Can anyone confirm if doesn't work or I'm missing something? I'm using kundera-hbase-v2 (version 3.3).

Thanks!

**Comment by karthikprasad13** [comment]
@zenzei 

You don't need to annotate simple Map (Map that does not have an Embeddable as a Key or Value) with `@ElementCollection`. Hbase does not support `Map` inside `ElementCollection` as of now.

-Karthik

**Comment by zenzei** [comment]
Sorry, reading your answer I don't understand if my use case should work of not (having a Map without Embeddables). Cause I tried removing the @ElementCollection, and is not being save either.

**Comment by karthikprasad13** [comment]
@zenzei 

`private List<Field> columns` is an `ElementCollection` and having a `Map` inside `Field` is not yet supported in Hbase i.e. persisting list of maps is not possible.

-Karthik
