### ISSUE TITLE
rdbms pagination support

### ISSUE THREAD

**Issue by dreamingo88** [Impetus/kundera#844]
i create a demo with kundera 3.3 (rdbms) today (use mysql 5.6 to persist my data).
but rdbms doesn'e support pagination. 

demo code:
I create 50 rows of data, and then:
`Query q = em.createQuery("select ctg from Category ctg where ctg.code = 'abc'", Category.class); int startPos = page * 10; q.setFirstResult(startPos); q.setMaxResults(10); List<Category> ctg = q.getResultList();`

it always returns the same list with 50 rows.
please implement it, it's very important. thanks.

**Comment by karthikprasad13** [comment]
@dreamingo88 

Support has been added and will be available in next release. If it is very important, you can build the code from trunk use it.

-Karthik

**Comment by dreamingo88** [comment]
@karthikprasad13 
Thanks very much!
I will try this weekend.

**Comment by dreamingo88** [comment]
I have comfirmed just now. 
It works for me.
Thanks!

**Comment by karthikprasad13** [comment]
@dreamingo88 

Are we good to close? 

-Karthik

**Comment by dreamingo88** [comment]
@karthikprasad13 
Yes, Please close.
