### ISSUE TITLE
update cassandra to support 3.x release

### ISSUE THREAD

**Issue by dreamingo88** [Impetus/kundera#846]
Currently Kundera supports cassandra version 2.2.
Need to upgrade it to the latest version of cassandra (3.3).

**Comment by devender-yadav** [comment]
Hi @dreamingo88 

Code has been added to the trunk and it will be available from next release i.e. 3.5 (_expected to be released in this month_)

-Dev

**Comment by dreamingo88** [comment]
@devender-yadav 
Thanks for your hard work.
