### ISSUE TITLE
Aggregate doesn't work for Cassandra

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#848]
Hi

I have a table mapped to class Entity with time-based UUID, I would like to get the largest ID with max(id) but it returns a list of Entity instead of a scalar value.
`em.create("select max(e.id) from Entity e")`

Thank you!

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
@mqian 

Hi Malcolm,

Currently, aggregations in Cassandra can be invoked only with Native Queries. Please refer this [testcase](https://github.com/impetus-opensource/Kundera/blob/6c7eba2377505237666f3d60da1138c4b06d40db/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/CassandraNativeFunctionsTest.java#L91) for more details.

-Karthik

**Comment by canopenerda** [comment]
@karthikprasad13 

Thanks for the hint. But it seems parameterized named native query is not well supported because of setParameter.

Thank you!

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
Native queries cannot be parameterized in Kundera-Cassandra 3.3.
