### ISSUE TITLE
 {kundera-discuss} Re: 2 EntityClass in the same PersistenceUnit : find method put null value in my Entity

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#85]
---

From: kundera-discuss@googlegroups.com [kundera-discuss@googlegroups.com] on behalf of superstarz [ice.gamerz@gmail.com]
Sent: 12 July 2012 15:29
To: kundera-discuss@googlegroups.com
Subject: {kundera-discuss} Re: 2 EntityClass in the same PersistenceUnit : find method put null value in my Entity

I put logger in all the part of my project.
Values are correctely put when I upload files, and the byte[] can be seen in cassandra client.
The problem is the object which be returned by find method, when I try with an bad id, my program stop, and I get an error, so my row is correctly found in my DB.
The object returned have a goob values String id and String taille are good. But just the byte[] are received null.

The stacktrace appear to the line when I want to use my byte[], and the java null pointer is a result to a execution on null values.

Le mercredi 11 juillet 2012 17:49:15 UTC+2, superstarz a écrit :
Hello !

I work on a software for store files in Cassandra DB.
I had 1 EntityClass by Files with this var : fileName, size ... and File1 byte[] for store my file in Binary.
For increase the performance of my project, I decide to split my File in 2 Entity, 1 with all external value like fileName, author etc .. and an other Entity with just the Byte table.
In this case, when I want information about my File, I dont need to load the all my Byte[].

But now, when i try to find my entity for make the download  ( p = em.find(FileCassandraData.class, id); ) I get an JavaNullPointerException.

this is the toString of my p object :  [SQLloggerGED](DocumentQueries.java:337) - p=FileCassandradata [Id: 8; tab1: null; tab2: null; tab3: null; tab4: null; taille: 381]

We can see that, the method find works fine, but dont put all the value in the object. When I check in cassandra client, there are values in File column ...

I guess that find contruct the object by using setters right ?
My entity Class has this value ;
@Column(name = "FILE1")
private byte[] tab1;

public void setTab1(byte[] tab1) {
this.tab1 = tab1;
}

Any ideas ?

**Comment by superstarz** [comment]
Hello xamry,

If you need more information about this problem you can ask question here, or talk to me on yahoo msgr (icezzz@rocketmail.com). 
Good luck

**Comment by xamry** [comment]
I am in the process of testing your scenario and will get back to you as soon as I can

Regards,
Xamry

**Comment by superstarz** [comment]
Hello xamry, 

So, I wanted some news about this issues, did you identified the problem ? Is it in the way to resolve ?
Thanks sir !

**Comment by xamry** [comment]
Hi,

There was a bug in com.impetus.kundera.property.accessor.ObjectAccessor class related to byte[] filds reading. I have fixed this and is available in latest trunk branch.

In order to get your code working, replace this class file in your Jar with the the file that I sent you through email.

A similar test case for file reading/ writing is available here:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-tests/src/test/java/com/impetus/kundera/tests/file/dao/ProfilePictureDaoTest.java

Please let me know if you face any issue.

Regards,
Amresh

**Comment by superstarz** [comment]
GREAT JOB XAMRY THATS WORKS !!! 

Thanks a lot !!! :D

**Comment by mevivs** [comment]
Great. Marking it as close.

-Vivek
