### ISSUE TITLE
Cassandra 3.4 Listening_address issue

### ISSUE THREAD

**Issue by siten0308** [Impetus/kundera#852]
Hello,

I am trying to get Apache Cassandra 3.4 up and running, I have 2 nodes, 1 is 10.8.118.43 and the other is 44. 

I did install OPs Center on .43 machine as well, however trying to get up cassandra but is giving me this error message:

10.8.118.43:7000 is in use by another process. Chagne listen_address:storage_port in cassandra.yaml to values that do not conflict with other services.

I tried to change storage port to 7005, however that didnt work... any other ideas?
Would Ops Center being using the same ports?

**Comment by karthikprasad13** [comment]
@siten0308 

Is the issue resolved? Are you facing this issue while using Cassandra with Kundera (3.3)?

-Karthik
