### ISSUE TITLE
schema generation with clustering order by

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#855]
How can I annotate an entity so that the schema generated includes a 'with clustering order by' clause?

An example would be greatly appreciated.

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
You can use `OrderBy` annotation as follows:

```
@EmbeddedId
@OrderBy("key.tweetId ASC, key.timeLineId DESC")
private UserTimeLine key;
```

[Here](https://github.com/impetus-opensource/Kundera/blob/6ee77aa5ee891be90d181ec41c52c1af8cacdb5f/src/kundera-cassandra/cassandra-ds-driver/src/test/java/com/impetus/kundera/client/cassandra/composite/PrimeUser.java) is the sample entity for reference.

Presuming you already added `kundera.ddl.auto.prepare` property in your `persistence.xml`.

-Karthik

**Comment by devender-yadav** [comment]
@mqian 

Did the above solution work for you?

-Dev
