### ISSUE TITLE
Kundera generated CQLs are not leveraging key/row cache

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#856]
CQLs generated from Kundera use token function which doesn't leverage key/row cache.
I have a named query which simply queries by primary key, and I have key and row cache enabled. But the generated query uses token function and results in 0 cache hit.

Thank you!
Regards,
Malcolm Qian

**Comment by karthikprasad13** [comment]
@mqian 

Which query are you using? and what is the generated query?

-Karthik

**Comment by canopenerda** [comment]
@karthikprasad13 

I have an entity and I'm querying it by id in a named query. I have kundera.show.sql set to true. I expected the generated query to be select \* from entity where id = ?, but the actually query is select \* from entity where token(id) = token(?).

In schema, I have row cache and key cache enabled for the column family. Querying with id in cqlsh hits cache while querying with token function doesn't.

Thank you!

Regards,
Malcolm Qian

**Comment by karthikprasad13** [comment]
@mqian 

Sorry for late response. The current scenario, with key/row cache is yet to be handled. We will fix this soon and will be available in next release.

-Karthik

**Comment by devender-yadav** [comment]
Hi @mqian, 

Fixed in Kundera 3.5

-Dev
