### ISSUE TITLE
bug: JPA query fails with "Arithmetic expression is not supported currently"

### ISSUE THREAD

**Issue by achaiah** [Impetus/kundera#857]
I'm using Kundera 3.4 (with mongodb). This issue seems to be very similar to [issue 751](https://github.com/impetus-opensource/Kundera/issues/751). 

I have a very simple statement:

> String qstr = "select u from User u where u.email = " + email + " and u.active = " + active;
> q = em.createQuery(qstr);

and I get this error: 

> com.impetus.kundera.KunderaException: Arithmetic expression is not supported currently

The error seems to be very similar to what's been reported before: a dot (.) in the email address is being misinterpreted as an arithmetic operation, for some reason....

**Comment by devender-yadav** [comment]
@achaiah 

`email` field is String. So you need to wrap it in single quotes.

Modify your query :

```
String qstr = "select u from User u where u.email =  '" + email + "' and u.active = " + active;
q = em.createQuery(qstr);
```

-Dev

**Comment by achaiah** [comment]
Ah, thanks for the insight. Maybe the error can be changed to give more of a hint of what's going on? It is very confusing as it doesn't even say which "arithmetic operation" is not supported.  Also, I assumed that since it is known that the email is a string I wouldn't have to escape it myself.
