### ISSUE TITLE
Failure to persist uni-directional OneToMany relationship

### ISSUE THREAD

**Issue by achaiah** [Impetus/kundera#858]
I'm using kundera-mongo and seem to be running into a problem with maintaining relationships.  I am using this guide as a template: https://github.com/impetus-opensource/Kundera/wiki/Polyglot-Persistence for a uni-directional OneToMany relationship.

I have a `User` class that's annotated like so:

```
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
@JoinColumn(name="security_roles")
public List<SecurityRole> roles;
```

And a `SecurityRole`class that doesn't have a reciprocal annotation (just like it is shown in the link). It is very simple...

```
@Entity
public class SecurityRole {

    @Id
    public String roleName;
}
```

First I noticed that no "security_roles" entry is present in the User object when it is stored in mongo. Also...

I have  `<property name="kundera.show.query" value="true" />` set so that I can see what queries are being issued.  The relevant generated query seems to be:

`Find by relation:{ "security_roles" : "5719386fb64a516e7c7f0493"}`

The ID here is the **User object's ID** and **not** the SecureRole object's ID!  So seems like there are two issues:

1) proper entry is not generated in the User object
2) the ID points back to the User object and not to a SecurityRole object

**Comment by devender-yadav** [comment]
@achaiah 

First of all, polyglot persistence means cross-datastore persistence. This should be used when your objects are distributed across multiple databases. 

So in your example, where do you want to store `User` and `SecurityRole`?

**Comment by achaiah** [comment]
I'm not necessarily using multiple databases, just using the page as an example of how to correctly "wire-up" relationships via JPA + Kundera.

**Comment by devender-yadav** [comment]
@achaiah 

No need to go via polyglot persistence way. Just do it in the same way as you do in case of normal entity(_with relationships, inheritance, etc_)

Refer [test case](https://github.com/impetus-opensource/Kundera/blob/6ee77aa5ee891be90d181ec41c52c1af8cacdb5f/src/kundera-mongo/src/test/java/com/impetus/client/crud/MongoMTOTest.java)  for more details. 

Let me know if you face any issue with that.

-Dev

**Comment by achaiah** [comment]
I was only using the polyglot page as a reference because it seems to be the most comprehensive set of examples of how JPA is supported by Kundera.  Thanks for linking me the mongo example. When I was looking through it I thought I saw what I was searching for but then the annotations confused me.

Please take a look at the [PersonMongoMTO](https://github.com/impetus-opensource/Kundera/blob/6ee77aa5ee891be90d181ec41c52c1af8cacdb5f/src/kundera-mongo/src/test/java/com/impetus/client/crud/entities/PersonMongoMTO.java) class. I saw this annotation:

```
@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(nullable = false)
private AddressMongoMTO address;
```

Why is this a ManyToOne? Isn't there supposed to be one person for many addresses or am I thinking about the annotation wrong? I was expecting a OneToMany (which is what I am trying to do as well, with my class).

At any rate, all I am trying to do is save the information about the relationship between two entities in the "parent" entity... so, for example, if there is a relationship that indicates: "Person has many addresses" then I would like to save the Ids of Addresses inside the Person object.  Does that make sense? Is it possible with Kundera's support for JPA?

Thanks.

**Comment by devender-yadav** [comment]
@achaiah 

Your scenario is valid. Yes, OneToMany association is possible using Kundera.

I was giving you an example for running entity association case. Above example is for ManyToOne. I would have mentioned it in above comment. You can try OneToMany in a similar way using @OneToMany annotation (_unidirectional or bidirectional whichever you want_)

-Dev

**Comment by achaiah** [comment]
Ok thanks, so then what is wrong with the annotations that I used in the original post?  I would expect them to work but they do not.

**Comment by devender-yadav** [comment]
@achaiah 

Please share your entities, persistence unit and test case you tried to insert data  or query over data.

-Dev

**Comment by devender-yadav** [comment]
@achaiah 

Any update on this? 

-Dev
