### ISSUE TITLE
After row deletion by other process, deleted key not persit in database when reused.

### ISSUE THREAD

**Issue by ghost** [Impetus/kundera#865]
1.   Persist an object X (id = 1) using kundera.
   Check with RazorSQL, entry in DB.  [OK]
   Check with Kundera,  entry in DB.  [OK]
2.  Delete X with Kundera
   Check with RazorSQL, entry not in  DB.  [OK]
   Check with Kundera, entry not in  DB.  [OK]
3. Persist new object X (id = 1) using kundera.
   Check with RazorSQL, entry in DB.  [OK]
   Check with Kundera,  entry in DB.  [OK]
4. Delete X from RazorSQL.
   Check with RazorSQL, entry not in  DB.  [OK]
   Check with Kundera, entry not in  DB.  [OK]
5. Persist new object X (id = 1) using kundera.
   Check with RazorSQL, entry in DB.  [NOK]
   Check with Kundera,  entry in DB.  [NOK]

ID can not be used anymore, there is no error at creation.
 .
I use  both javax.persistence.EntityManager and  javax.persistence.EntityManagerFactory 
entitymanager is open and closed for each transaction.

**Comment by devender-yadav** [comment]
@hToulan 

Can you please share complete error trace. Also, share Kundera version, Cassandra version, `persistence.xml` file and entity.

-Dev

**Comment by ghost** [comment]
Hi,
Thanks you for your reply.
There is no error trace. 
Error occurs with both Cassandra 3.4, and 2.1 
Kundera version is 3.4

 We solved the issue by specifying the CQL version in the persistence.xml.  “cql.version=3.0.0”
Do you have an explanation ?

**Comment by ghost** [comment]
Hi,
Thanks you for your reply.
There is no error trace.
Error occurs with both Cassandra 3.4, 2.1
Kundera version is 3.4

ð  We solved the issue by specifying the CQL version in the persistence.xml.  “cql.version=3.0.0”
Do you have an explanation ?

De : Devender Yadav [mailto:notifications@github.com]
Envoyé : vendredi 3 juin 2016 09:48
À : impetus-opensource/Kundera
Cc : Toulan Herve; Mention
Objet : Re: [impetus-opensource/Kundera] After row deletion by other process, deleted key not persit in database when reused. (#865)

@hToulanhttps://github.com/hToulan

Can you please share complete error trace. Also, share Kundera version, Cassandra version, persistance.xml file and entity.

-Dev
