### ISSUE TITLE
Disable Logging in Kundera for Cassandra

### ISSUE THREAD

**Issue by ZakariaHili** [Impetus/kundera#869]
hi,
All CRUD operations being logged in our application logs by Kundera, which make my stream processing application very slow (I have to process more than 50000 data per second). Is there a way to turn it off ?

**Comment by devender-yadav** [comment]
HI @ZakariaHili 

You can control log level via `logback.xml` .

Set `<root level="ERROR">` to minimize logs (_error only_).

-Dev

**Comment by ZakariaHili** [comment]
Hi,
I tried this, but I still receive info logs.

**Comment by devender-yadav** [comment]
@ZakariaHili 

Please share your `logback.xml`.

-Dev

**Comment by ZakariaHili** [comment]
Hi,

this is my logback.xml file

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${user.home}/kundera.log</file>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <Pattern>%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</Pattern>
        </encoder>

        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <FileNamePattern>${user.home}/kundera.%i.log.zip</FileNamePattern>
            <MinIndex>1</MinIndex>
            <MaxIndex>10</MaxIndex>
        </rollingPolicy>

        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <MaxFileSize>2MB</MaxFileSize>
        </triggeringPolicy>
    </appender>

    <logger name="log4j.logger.com.impetus" level="ERROR" additivity="false">
            <appender-ref ref="STDOUT" />
            <appender-ref ref="FILE" />
    </logger>

    <root level="ERROR">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

zakaria

**Comment by devender-yadav** [comment]
Hi,

This `logback.xml` file is working fine at my end. Have you added this to the classpath?

-Dev

**Comment by ZakariaHili** [comment]
Hi,
Yes, but I m using storm as my framework.
-Zakaria

**Comment by brunocrt** [comment]
Hi,
I'm also facing the same problem and tried the same approach as @ZakariaHili 
Any thoughts on how to avoid that log?

**Comment by devender-yadav** [comment]
@brunocrt 

I already mentioned a way:

Set `<root level="ERROR">`

Did not it work for you?

-Dev

**Comment by brunocrt** [comment]
Hi Dev, thanks for your support! It is working now! there was a typo on logger name that was stopping the package classes to log information properly.

**Comment by devender-yadav** [comment]
@brunocrt 

Happy to help.

-Dev

**Comment by brunocrt** [comment]
Yes I did change it but I believe that in order to improve the driver it must set the logging level properly for CRUD operations. I mean that should be DEBUG not INFO, why should that too much verbose by default? Nobody wants such behavior on production so for that reason it is better than let just low level messages to INFO and other detailed and frequent messages to DEBUG or WARN level.
