### ISSUE TITLE
After remove, query list return null values 

### ISSUE THREAD

**Issue by superstarz** [Impetus/kundera#87]
Hello ! 

I discovered an another "bug" in kundera, when I delete an row of my DB as that : 

p = em.find(FileCassandra.class , id);
em.remove(p);

Thats work, with Cassandra-cli I see the row is deleted.
But, I have an global return list, which return all the row of my DB : 

```
    String query = "Select p From FileCassandra p ";
    // // List all result
    Query q = em.createQuery(query);
    List<FileCassandra> list = q.getResultList();
```

After delete, this method return a list where the row I deleted appear to "null". 
I already resolved it by use an iterator and remove all null values but resolve this can be nice for the next release of kundera :).

Thanks again for the job of the developper team !

**Comment by mevivs** [comment]
This is because after deleting a record from cassandra, it does not delete that row key from cassandra server to avoid reuse of row key and other reasons. Hence we limited kundera to return null record for such scenarios. However i will get this done to avoid null record to be added in a list!

-Vivek

**Comment by superstarz** [comment]
Oh ok that was intentionaly ... Sorry i believe discover an bug. 
An iterator is the simplest way to resolve it 3 lines ;)

**Comment by mevivs** [comment]
Hi Fabiens,
It was actually a Bug. I have fixed this and checked-in for not to add null records in a list of returning entities.

That explanation is just to discuss the reason behind it :)

Thanks,
Vivek

**Comment by superstarz** [comment]
Again a great job Vivek,  so I close this issue :)
