### ISSUE TITLE
@ElementCollection does not work for collection of @Embeddable types

### ISSUE THREAD

**Issue by nitin02** [Impetus/kundera#873]
I am trying to include a Element Collection to my Entity which has other columns of basic type too such as,

```
@ElementCollection
private List<Statement> statements;
```

Statement is Embeddable, so ideally, equivalent type in cassandra should be,

`statements List<frozen<Statement>>`

However, it changes my entire Entity structure to below,

```
key text,
column1 text,
 "" map<text, blob>,
PRIMARY KEY (key, column1)
```

Note that embedding just the Statement object is proper, 

```
@Embedded
private Statement statement;
```

is created as,

`statement frozen<Statement>`

I'm using Kundera 3.5 and the latest version of Kundera-Cassandra driver. 
Thank you for your help.

**Comment by karthikprasad13** [comment]
@nitin02 

Please make sure you are using with CQL3 enabled and also the annotation `@Embeddable` in `Statement` class.

Also, share your entities and `persistence.xml` if the above doesn't work.

-Karthik

**Comment by nitin02** [comment]
CQL3 is set. So is `@Embeddable` in `Statement`.

Here is the entire set of details a little bit **simplified** for **convenience**,

```
@Entity
@Table(name = "stream", schema = "xstream@cassandra_pu")
public class Stream {

    @Id
    private String id;

    @Column(name = "version")
    private String version;

    @ElementCollection
    private List<Statement> statements;

        //getters and setters omitted
}
```

```
@Embeddable
public class Statement {

    @Column(name = "id")
    private String id;

    @Column(name = "version")
    private String version;

        //getters and setters omitted
}
```

```
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>     
        <properties>            
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9042"/>
            <property name="kundera.keyspace" value="xstream"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.ddl.auto.prepare" value="create" />
            <property name="kundera.client.lookup.class" value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />         
        </properties>       
    </persistence-unit>
</persistence>
```

CQL is set as shown [here ](https://github.com/impetus-opensource/Kundera/wiki/Cassandra-Specific-Features),

```
Map propertyMap = new HashMap();
propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
EntityManagerFactoryImpl emf = Persistence.createEntityManagerFactory("cassandra_pu",propertyMap);
```

**Comment by karthikprasad13** [comment]
@nitin02 

I debugged the code and found that there is a bug in `CassandraSchemaGeneration` class in `isCql3Enabled()` method. We will add the fix soon.

As a workaround, you can create table manually and proceed for now.

-Karthik

**Comment by nitin02** [comment]
Do you think downgrading kundera version could solve the issue temporarily?

**Comment by karthikprasad13** [comment]
@nitin02 

No, this issue needs a fix.

-Karthik

**Comment by zak-hassan** [comment]
@karthikprasad13  Downgrade to which version? I ran into the same issue as well.

**Comment by nitin02** [comment]
@zmhassan  Version downgrade does not solve the issue. I guess, one'd have to wait for the next release for a proper fix. Until then, @karthikprasad13 suggests to manually create the tables and proceed.
