### ISSUE TITLE
How to configure Kundera for multi-dc cassandra deployment?

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#875]
Hi folks,

I'm wondering how I can set different replica factors for each dc in multi-dc deployment.
For example, I have 2 DC, DC A and DC B, and I would like to set replica factor to 3 and 1 for DC A and DC B respectively.
How can I do this in Kundera? Any advice would be highly appreciated!

P.S. For kundera.client.lookup.class, I'm using com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
@mqian 

Sorry for late response.
As of now, we cannot do this through Kundera.

-Karthik

**Comment by karthikprasad13** [comment]
@mqian 

Is there a reason for not using CQL to update the replication factor? Why do you want to do it through Kundera?

If you just want to update you can use `entityManager.nativeQuery` with the following query

```
ALTER KEYSPACE <keyspace_name> WITH REPLICATION =
       {'class' : 'NetworkTopologyStrategy', 'DC A' : 3, 'DC B' : 1}
```

-Karthik

**Comment by canopenerda** [comment]
@karthikprasad13 

I would like to have schema generated by Kundera. So I'm wondering if it is possible to do multi-dc replication factor by Kundera.

Malcolm

**Comment by karthikprasad13** [comment]
@mqian 

The code will be available from the next release or you can build it from trunk.

Follow the below steps to achieve the same:
- Create an xml file (say `cassprops.xml`) with the following

```
<?xml version="1.0" encoding="UTF-8"?>
    <clientProperties>
    <datastores>
        <dataStore>
            <name>cassandra</name>
            <schemas>
                <schema>
                    <name>keyspace_name</name>
                    <properties>
                    <property name="strategy.class" value="NetworkTopologyStrategy"></property>
                    </properties>
                    <dataCenters>
                        <dataCenter>
                            <name>DC A</name>
                            <value>3</value>
                        </dataCenter>
                        <dataCenter>
                            <name>DC B</name>
                            <value>1</value>
                        </dataCenter>
                    </dataCenters>
                </schema>
            </schemas>
        </dataStore>
    </datastores>
</clientProperties>
```
- Add the following property in `persistence.xml` to load the properties file

```
<property name="kundera.client.property" value="cassprops.xml" />
```

Please feel free to ask if there is any confusion.
-Karthik
