### ISSUE TITLE
add support for more policies from ds drivers

### ISSUE THREAD

**Issue by canopenerda** [Impetus/kundera#876]
Hi folks,

Do you have plan to support more policies from ds drivers, e.g. load balancing (LatencyAwarePolicy, HostFilterPolicy, etc), retry (IdempotenceAwareRetryPolicy)?

Thank you!

Regards,
Malcolm

**Comment by karthikprasad13** [comment]
Hi Malcolm,

We have it in our roadmap but it is not yet picked. 

Currently supported:

> **Load Balancing Policies**: LatencyAwarePolicy, TokenAwarePolicy, RoundRobinPolicy, DCAwareRoundRobinPolicy
> **Retry Policies**: DowngradingConsistencyRetryPolicy, FallthroughRetryPolicy, LoggingRetryPolicy and Custom Policy

To be supported:

> **Load Balancing Policies**: HostFilterPolicy, WhiteListPolicy
> **Retry Policy**:  IdempotenceAwareRetryPolicy

If you are interested in contributing, let us know.

-Karthik
