### ISSUE TITLE
Kundera does not connect to all nodes on Cassandra cluster

### ISSUE THREAD

**Issue by mmajcenic** [Impetus/kundera#877]
Greetings,

I am trying to setup a simple client, based on  [Getting Started in 5 minutes](https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes), to connect to multi-node Cassandra Cluster.
I am using Cassandra 3.7 and Kundera 3.5.
I've got two Cassandra instances, and I can connect to each of them individually and work with them as intended.

My `persistence.xml` file:

```
 <persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
         version="2.0">
<persistence-unit name="cassandra_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>main.User</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="kundera.client.property" value="META-INF/loadBalancing.xml" />
        <property name="kundera.nodes" value="127.0.0.1,192.168.50.4" />
        <property name="kundera.port" value="9042" />
        <property name="kundera.keyspace" value="KunderaExamples"/>
        <property name="kundera.dialect" value="cassandra"/>
        <property name="kundera.ddl.auto.prepare" value="create" />
        <property name="kundera.client.lookup.class"
                  value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />
    </properties>
</persistence-unit>
</persistence>
```

And `loadBalancing.xml` file, referenced above, is:

```
<?xml version="1.0" encoding="UTF-8"?>
 <clientProperties>
<datastores>
    <dataStore>
        <name>cassandra</name>
        <connection>
            <servers>
            </servers>

            <properties>
                <property name="loadbalancing.policy" value="RoundRobinPolicy"></property>
                <property name="retry" value="true"></property>
                <property name="retry.delay" value="1"></property>
                <property name="max.wait" value="3000"></property>
            </properties>
        </connection>
    </dataStore>
</datastores>
</clientProperties>
```

For the purpose of replication, main method is simple:

```
public static void main(String[] args) {

    Map<String, String> propertyMap = new HashMap<>();
    propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu", propertyMap);
    EntityManager em = emf.createEntityManager();

    em.close();
    emf.close();

}
```

The problem I am facing is that Kundera only connects to one node.

I suspect, but can't know for sure, that the issue is related to following line printed in console:

> WARN  com.datastax.driver.core.Cluster - You listed /192.168.50.4:9042 in your contact points, but it wasn't found in the control host's system.peers at startup

As for Cassandra hosts, I did not change cassandra.yaml, or configured Cassandra in any other way. I simply started server and used enablethrift with nodetool.

What am I missing?

Full console stack trace, if it could help:

<pre><code>14:49:06.633 [main] INFO  c.i.k.p.EntityManagerFactoryImpl - Loading Core
14:49:06.639 [main] INFO  c.impetus.kundera.loader.CoreLoader - Loading Kundera Core Metdata ... 
14:49:06.640 [main] INFO  c.i.k.p.EntityManagerFactoryImpl - Loading Persistence Unit MetaData For Persistence Unit(s) cassandra_pu.
14:49:06.644 [main] INFO  c.i.k.c.PersistenceUnitConfiguration - Loading Metadata from persistence.xml ...
14:49:06.732 [main] INFO  c.i.k.c.PersistenceUnitConfiguration - Finishing persistence unit metadata configuration ...
14:49:06.739 [main] DEBUG c.i.k.c.MetamodelConfiguration - Loading Entity Metadata...
14:49:06.788 [main] DEBUG c.i.k.v.rules.EntityAnnotationRule - Validating main.User
14:49:06.813 [main] DEBUG c.i.k.c.MetamodelConfiguration - Metadata not found in cache for main.User
14:49:06.825 [main] DEBUG c.i.kundera.metadata.MetadataBuilder - Processing @Entity >> class main.User
14:49:06.825 [main] DEBUG c.i.k.m.processor.TableProcessor - Processing @Entity(main.User) for Persistence Object.
14:49:06.876 [main] DEBUG c.i.k.m.processor.IndexProcessor - Processing @Entity main.User for Indexes.
14:49:06.881 [main] INFO  c.i.k.c.ClientMetadataBuilder - Loading client factory for persistence unit cassandra_pu
14:49:06.882 [main] INFO  c.i.kundera.client.ClientResolver - Initializing client factory for: cassandra_pu
14:49:06.896 [main] INFO  c.i.kundera.client.ClientResolver - Finishing factory initialization
14:49:06.897 [main] INFO  c.i.k.configure.SchemaConfiguration - Configuring schema export for : cassandra_pu
14:49:07.161 [main] INFO  c.i.c.c.c.CassandraPropertyReader - Returning placement strategy value org.apache.cassandra.locator.SimpleStrategy
14:49:09.875 [main] INFO  c.i.k.loader.GenericClientFactory - Loading client metadata for persistence unit : cassandra_pu
14:49:09.875 [main] INFO  c.i.k.loader.GenericClientFactory - Initializing client for persistence unit : cassandra_pu
14:49:09.884 [main] INFO  c.i.k.loader.GenericClientFactory - Constructing pool for persistence unit : cassandra_pu
14:49:09.884 [main] DEBUG c.i.k.c.c.dsdriver.DSClientFactory - Intiatilzing connection
14:49:09.978 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
14:49:09.978 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
14:49:09.980 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
14:49:10.103 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [/127.0.0.1:9042, /192.168.50.4:9042]
14:49:10.125 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
14:49:10.141 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
14:49:10.142 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
14:49:10.142 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
14:49:10.143 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
14:49:10.144 [main] DEBUG i.n.util.internal.PlatformDependent - Platform: Windows
14:49:10.144 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
14:49:10.144 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
14:49:10.144 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
14:49:10.145 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
14:49:10.209 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: available
14:49:10.210 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\marko\AppData\Local\Temp (java.io.tmpdir)
14:49:10.210 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
14:49:10.210 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
14:49:10.219 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
14:49:10.222 [main] WARN  com.datastax.driver.core.NettyUtil - Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
14:49:10.225 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
14:49:10.232 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
14:49:10.232 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
14:49:10.259 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
14:49:10.265 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
14:49:10.387 [main] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] preparing to open 1 new connections, total = 1
14:49:10.394 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
14:49:10.404 [main] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.**matchers**.com.datastax.driver.core.Message$ResponseMatcher
14:49:10.421 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
14:49:10.421 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 4
14:49:10.421 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
14:49:10.421 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
14:49:10.422 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
14:49:10.422 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
14:49:10.422 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
14:49:10.422 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
14:49:10.422 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
14:49:10.422 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
14:49:10.437 [main] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.**matchers**.com.datastax.driver.core.FrameMatcher
14:49:10.442 [main] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.**matchers**.com.datastax.driver.core.Message$RequestMatcher
14:49:10.465 [main] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xde81bd81c0d2fa3f (took 9 ms)
14:49:10.485 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
14:49:10.485 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
14:49:10.521 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] Connection established, initializing transport
14:49:10.540 [cluster1-nio-worker-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
14:49:10.577 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] Connection[/127.0.0.1:9042-1, inFlight=0, closed=false] Transport initialized, connection ready
14:49:10.579 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] Refreshing node list and token map
14:49:10.644 [main] WARN  com.datastax.driver.core.Cluster - You listed /192.168.50.4:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
14:49:10.652 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] Refreshing schema
14:49:10.935 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] Refreshing node list and token map
14:49:11.003 [main] DEBUG com.datastax.driver.core.Host.STATES - [Control connection] established to /127.0.0.1:9042
14:49:11.005 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
14:49:11.013 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.CHECK_IO_DEADLOCKS is undefined, using default value true
14:49:11.019 [main] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] preparing to open 1 new connections, total = 2
14:49:11.022 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-2, inFlight=0, closed=false] Connection established, initializing transport
14:49:11.061 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] Connection[/127.0.0.1:9042-2, inFlight=0, closed=false] Transport initialized, connection ready
14:49:11.064 [cluster1-nio-worker-1] DEBUG c.d.driver.core.HostConnectionPool - Created connection pool to host /127.0.0.1:9042 (1 connections needed, 1 successfully opened)
14:49:11.064 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Session - Added connection pool for /127.0.0.1:9042
14:49:11.071 [cluster1-nio-worker-1] WARN  c.d.d.core.policies.RoundRobinPolicy - Detected request at Consistency Level null but the non-DC aware RoundRobinPolicy is in use. It is strongly advised to use DCAwareRoundRobinPolicy if you have multiple DCs/use DC-aware consistency levels (note: this message will only be logged once)
14:49:11.087 [main] INFO  c.i.k.p.EntityManagerFactoryImpl - EntityManagerFactory created for persistence unit : cassandra_pu
14:49:11.094 [main] DEBUG c.i.k.persistence.EntityManagerImpl - Creating EntityManager for persistence unit : cassandra_pu
14:49:11.104 [main] INFO  c.i.k.persistence.EntityManagerImpl - Returning client instance for persistence unit cassandra_pu.
14:49:11.104 [main] DEBUG c.i.k.loader.GenericClientFactory - Returning fresh client instance for persistence unit : cassandra_pu
14:49:11.119 [main] DEBUG c.i.k.persistence.EntityManagerImpl - Created EntityManager for persistence unit : cassandra_pu
14:49:11.119 [main] DEBUG c.i.k.p.PersistenceDelegator - Flushing following flush stack to database(s) (showing stack objects from top to bottom):
[]
14:49:11.120 [main] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-2, inFlight=0, closed=true] closing connection
14:49:11.121 [main] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] Connection[/127.0.0.1:9042-2, inFlight=0, closed=true] closed, remaining = 1
14:49:11.126 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
14:49:11.128 [main] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9042-1, inFlight=0, closed=true] closing connection
14:49:11.129 [main] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9042] Connection[/127.0.0.1:9042-1, inFlight=0, closed=true] closed, remaining = 0
14:49:13.554 [threadDeathWatcher-2-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 34 thread-local buffer(s) from thread: cluster1-nio-worker-0
14:49:13.554 [threadDeathWatcher-2-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 7 thread-local buffer(s) from thread: cluster1-nio-worker-1 </pre></code>

**Comment by karthikprasad13** [comment]
Hi @Sarpedion 

I am not sure if this is an issue with Kundera, I tried to replicate the issue, using a 3 node cluster to connect and it was working fine. 

-Karthik
