### ISSUE TITLE
Select * from table not working with Cassandra

### ISSUE THREAD

**Issue by zak-hassan** [Impetus/kundera#878]
Hi, I tried the following

``` java
    Query query = em.createQuery("SELECT * FROM Schema");
    List resultList = query.getResultList();
    for (Schema schema2 : resultList) {
          System.out.println(schema2.getDoc());
     }

```

This doesn't seem to work. Could you advise how one would perform a query using either createNativeQuery or createQuery ?

**Comment by karthikprasad13** [comment]
@zmhassan 

You need to use JPA query format with `createQuery`:

```
Query query = em.createQuery("SELECT s FROM Schema s");
```

Or directly use the native query with `createNativeQuery`:

```
Query query = em.createNativeQuery("SELECT * FROM Schema");
```

You can explore more with these [testcases](https://github.com/impetus-opensource/Kundera/blob/6ee77aa5ee891be90d181ec41c52c1af8cacdb5f/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/PersonCassandraTest.java)

-Karthik

**Comment by zmhassan** [comment]
I've opted to use hibernate-ogm instead as  it provides this
