### ISSUE TITLE
Pagination using Datastax java driver support for Cassandra using Kundera

### ISSUE THREAD

**Issue by brunocrt** [Impetus/kundera#887]
I'm testing the pagination feature on a table with composite partition key and I'm getting just one row (1) as result set. I'm setting the fetch size for 500 but the iterator just return 1 item. 

There is no exception/error on logs! There are more than 10 thousands events registered on this table.

`String queryString= "SELECT e FROM OrderEvent e WHERE e.primaryKey.partitionKey.location='US' AND e.primaryKey.partitionKey.year=2015";

 com.impetus.kundera.query.Query query = (com.impetus.kundera.query.Query) em.createQuery(queryString,
 entityClass);

 query.setFetchSize(500);

 Iterator<OrderEvent> rows = query.iterate();
 while(rows.hasNext()) {
 resultList.add( rows.next() );
 }
 `

I'm using kundera-cassandra-ds-driver version 3.4 with cassandra-driver-core (com.datastax.casssandra) version 2.1.10.3

In my driver configuration I'm using the DSClientFactory and CQL version 3.0.0

It seems that the issue is related to the composite partition key, because I tried a similar query with other table without composite partition key and it returned all the rows as expected.

**Comment by karthikprasad13** [comment]
@brunocrt 

I have debugged the code and this needs a fix. I will fix this asap and push it to the trunk.

-Karthik

**Comment by brunocrt** [comment]
I'm happy you guys are delivering this fix! hoping the next release! thanks

**Comment by devender-yadav** [comment]
@brunocrt 

Fixed in Kundera 3.7.

-Dev
