### ISSUE TITLE
Kundera features wish list

### ISSUE THREAD

**Issue by mevivs** [Impetus/kundera#89]
Format should in line with:

DB Name: Cassandra, HBase,Mongo etc.
DB Version:  
Feature Description: 

Thanks,
Vivek

**Comment by mevivs** [comment]
module : kundera-core
Issue: https://github.com/impetus-opensource/Kundera/issues/95
Feature descriptin: Added cache support.

-Vivek

**Comment by juneng603** [comment]
DB Name : HBase
DB Version : 0.92.1

Feature : 
need an annotation to indicate a column-family to store model data itself in an entity-level

for example, 

``` java
public class Sample {
  @Id 
  private int id;

  @ColumnFamily(name="CF1")
  @Column(name="C1")
   private String firstName;

  @ColumnFamily(name="CF1")
  @Column(name="C2")
   private String middleName;

  @ColumnFamily(name="CF1")
  @Column(name="C3")
   private String lastName;

  @ColumnFamily(name="CF2")
  @Column(name="C1")
   private String address;
}
```

thanks for your supports.

-- Henry

**Comment by OleksandrSemenov** [comment]
DB Name: Cassandra
DB Version: 1.1

It will be good if issues listed below will be implemented
1) Composite Key stroring and selecting. It can dramatically simplify indexing and get rid of additional column families for it
2) Add ability to select several rows by set of keys. For example:
    a)Add IN clause support for JPQL. 
    b)Or implement Criteria Query API
Unfortunately existing workarounds can do it only via CQL native query, so selects for multiple keys will not be applicable to super column families

**Comment by mevivs** [comment]
Composite Key stroring and selecting. It can dramatically simplify indexing and get rid of additional column families for it (Supported with 2.2 release)

**Comment by mevivs** [comment]
update for 2.4 now
