### ISSUE TITLE
Dependency Javax.persistence#persistence-api;2.0 could be resolved

### ISSUE THREAD

**Issue by songlin** [Impetus/kundera#890]
When trying to import kundera to my Play!2.5 project, sbt cannot resolve javax.persistence dependency, actually i've searched a lot of existing maven repository, none of them have this dependency. the closest Jar i've got is https://mvnrepository.com/artifact/javax.persistence/persistence-api/1.0

Error:Error while importing SBT project:<br/>...<br/><pre>[warn]    ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: javax.persistence#persistence-api;2.0: not found
[warn]  :: org.xerial#snappy;1.0.1-rc4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      javax.persistence:persistence-api:2.0
[warn]        +- com.impetus.core:kundera-core:2.5
[warn]        +- com.impetus.client:kundera-cassandra:2.5 (/Users/songlinwei/Projects/play/test-play-java/build.sbt#L9-18)
[warn]        +- test-play-java:test-play-java_2.11:1.0-SNAPSHOT
[warn]      org.xerial:snappy:1.0.1-rc4
[warn]        +- com.impetus.client:kundera-cassandra:2.5 (/Users/songlinwei/Projects/play/test-play-java/build.sbt#L9-18)
[warn]        +- test-play-java:test-play-java_2.11:1.0-SNAPSHOT
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error](*:update) sbt.ResolveException: unresolved dependency: javax.persistence#persistence-api;2.0: not found
[error] unresolved dependency: org.xerial#snappy;1.0.1-rc4: not found
[error](*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: javax.persistence#persistence-api;2.0: not found
[error] unresolved dependency: org.xerial#snappy;1.0.1-rc4: not found
[error] Total time: 31 s, completed Oct 17, 2016 11:55:50 AM</pre><br/>See complete log in <a href="/Users/songlinwei/Library/Logs/IdeaIC2016.1/sbt.last.log">/Users/songlinwei/Library/Logs/IdeaIC2016.1/sbt.last.log</a>

**Comment by devender-yadav** [comment]
@songlin 

Please you latest version of Kundera i.e. 3.6

For example, for Cassandra use:

```
com.impetus.kundera.client:kundera-cassandra:3.6
```

-Dev

**Comment by songlin** [comment]
@devender-yadav Thank You！ Problem solved after do what as you told. Some suggestion here: you guys could have the "Using-Kundera-with-Play!-Framework" guide changed too.

**Comment by devender-yadav** [comment]
@songlin 

Thank you for the suggestion. We will upgrade the document. 

-Dev
