### ISSUE TITLE
Change logging level from INFO to DEBUG on Cassandra client queries

### ISSUE THREAD

**Issue by brunocrt** [Impetus/kundera#892]
Some **classes from Cassandra client** are generating too many logs on my application due its **INFO level configured by default** on logback. Could it be possible **to change it to default to DEBUG level** instead of INFO for CQL queries?
I think this change is reasonable as queries are frequently executed during application runtime and as developers we wish do not pollute the application log with this kind of information during production runtime.

Sample log from my application
Oct 28, 2016 13:50:50.546 {Thread-28} **INFO**  com.impetus.client.cassandra.**CassandraClientBase.executeSelectQuery** : Executing cql query SELECT \* FROM "trade_event" WHERE "eventid" = 100956017 LIMIT 10000  ALLOW FILTERING.

Oct 28, 2016 13:50:50.547 {Thread-28} **INFO**  com.impetus.client.cassandra.CassandraClientBase$**CQLClient.executeQuery** : Executing query SELECT \* FROM "trade_event" WHERE "eventid" = 100956017 LIMIT 10000  ALLOW FILTERING.
O`

**Comment by devender-yadav** [comment]
Refer this: https://github.com/impetus-opensource/Kundera/issues/869

**Comment by karthikprasad13** [comment]
@brunocrt 

Your point is absolutely valid; we will review and update accordingly.

-Karthik

**Comment by brunocrt** [comment]
@karthikprasad13  thanks! this change will be useful!
