### ISSUE TITLE
Kundera-rdbms uses old version of Hibernate Core

### ISSUE THREAD

**Issue by jswordfish** [Impetus/kundera#894]
There is use of deprecated import
import org.hibernate.service.ServiceRegistryBuilder;

which is not present in current hibernate-core version. This causes clashes in libraries & entity manger bean is not getting created due to missing class. Due to spring latest ORM i cannot downgrade Hibernate version.

How to solve this issue

**Comment by devender-yadav** [comment]
Hi @jswordfish,

We will update hibernate dependencies in the upcoming release.

Thanks for your input.

-Dev
