### ISSUE TITLE
@EntityListeners not working on @MappedSuperclass

### ISSUE THREAD

**Issue by michael-rhoese** [Impetus/kundera#898]
Hallo, I'm using Kundera 3.7 with Cassandra. Everting works fine but now I have to add a entity listener to do magic on 'prePersist'. The listener is located on an abstract class annotated with @MappedSuperclass and the listener should run on all entity classes extended by the abstract class. But Kundera runs only entity listener on classes annoted with @Entity. Is this the actual behaviour or a bug?

Thx and greez, Micha

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,


Have you seen https://github.com/impetus-opensource/Kundera/issues/492?


-Dev

**Comment by michael-rhoese** [comment]
Hi Dev,
Yes, but it isn't working. I using a breakpoint to see whats happend and @EntityListener does not working on @MappedSupperclass.

    @MappedSuperclass
    @EntityListeners(ExportableListener.class)
    public abstract class AbstractExportableEntity<ID extends Serializable, EXTERN_ID extends Serializable> extends AbstractEntity<ID> implements ExportableEntity<ID, EXTERN_ID> {

        private EXTERN_ID externId;

        public AbstractExportableEntity() {
        }

        public AbstractExportableEntity(EXTERN_ID externId, ID id) {
            super(id);
            this.externId = externId;
        }

        @Override
        public EXTERN_ID getExternId() {
            return this.externId;
        }

        @Override
        public void setExternId(EXTERN_ID externId) {
            this.externId = externId;
        }
    }

    @Entity
    @XmlRootElement
    public class Person extends AbstractExportableEntity<String, String> implements Comparable<Person> {
    }

    public class ExportableListener {

        @PrePersist
        void onPrePersist(final Object entity) {

            String uuid = UUID.randomUUID().toString();

            ((ExportableEntity) entity).setExternId(uuid);
        }
    }

**Comment by karthikprasad13** [comment]
@michael-rhoese 

We are looking into the issue and will update soon.

-Karthik

**Comment by karthikprasad13** [comment]
@michael-rhoese 

We added fix for this issue. You can use this fix from trunk for now.
This fix will be available in Kundera-3.8 release _(expected in mid of Feb 2017)_

-Karthik
