### ISSUE TITLE
Incorrect Limit clause

### ISSUE THREAD

**Issue by fredlumm** [Impetus/kundera#902]
Hi,

I've come across a problem that kundera adds limit clause to the cql while using JPA model. I just want to select all the entities, but it add "limit 0", which causes the problem.

Can you please give some suggestion to solve this problem.

**Comment by devender-yadav** [comment]
Hi @fredlumm, 

Please share Kundera version, Cassandra version and `persistence.xml`.

-Dev

**Comment by devender-yadav** [comment]
Hi @fredlumm,

Is it adding "limit 0" or "limit 100" ?

-Dev

**Comment by fredlumm** [comment]
Thanks for replying, and it adds limit 0, 
Here are the information you are asking:
1. Kundera Version: 3.7
2. Cassandra Version: 3.9
3. persistence.xml:
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
	https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
	version="2.0">

        <persistence-unit name="cassandra_pu">
		<provider>com.impetus.kundera.KunderaPersistence</provider>
		<properties>
			<property name="kundera.nodes" value="localhost" />
			<property name="kundera.port" value="9160" />
			
			<property name="kundera.keyspace" value="test" /> 
			<property name="kundera.dialect" value="cassandra" />

			<property name="kundera.client.lookup.class"
				value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
		</properties>
	</persistence-unit>

</persistence>

**Comment by devender-yadav** [comment]
Hi @fredlumm,

Can you please share JPA query you tried?

-Dev

**Comment by devender-yadav** [comment]
Hi @fredlumm,

I tried to replicate your issue with Cassandra version 3.9 but test cases are working at my end. Please share your entity, JPA query and sample test case. 

-Dev
