### ISSUE TITLE
Reference A's foreign compound key when B's key is also compound

### ISSUE THREAD

**Issue by si24803** [Impetus/kundera#921]
Hi,

The MapsId annotation works when an EmbeddedId references a simple key. My scenario is a bit more farfetched. I want a field in entity A's compound key to reference a field in entity B's compound key. I'm not getting there and have tried a lot of things (from JoinColumn to MapsId and dot notation fields.
What I'm trying to do is:
A.ID.fieldKey1OfB *----1 B.ID.fieldKey1OfB
Kundera creates all the columns of B's key as A's columns :(.

Am I overthinking this, or is there a way?

Thank you. 
[KunderaIssue.zip](https://github.com/impetus-opensource/Kundera/files/840398/KunderaIssue.zip)
Regards

**Comment by devender-yadav** [comment]
Hi @si24803,

Which module are you using - `kundera-cassandra` or something else? Also share Kundera version. 

-Dev

**Comment by si24803** [comment]
Hi Dev,

Sorry for that. I'm using kundera-cassandra 3.8.

Thank you

A ter, 14/03/2017, 08:48, Devender Yadav <notifications@github.com>
escreveu:

**Comment by karthikprasad13** [comment]
Hi @si24803 

This is not a valid usecase. Since `ClassB` is uniquely identified by the combination of **all** columns in EmbeddedID, the reference columns cannot be less than the number of columns that are uniquely identifying the Parent class.

-Karthik

**Comment by si24803** [comment]
Hi Karthik,

That makes perfect sense. That's the point that I was missing. I'm using compound keys to be able to define cluster order by clauses. What I'll do is create a compound key that consists of a compound primary key and the clustering keys. I believe this will work. I'll check back when I have results.
Thank you very much.

Regards
Antonio Pedro Santos
