### ISSUE TITLE
Cannot fetch entitiy with embedded key as inner class

### ISSUE THREAD

**Issue by romikk** [Impetus/kundera#925]
Consider this entity class:
```
@Entity
public class MyEntity implements Serializable {
    @EmbeddedId
    private Key key;
    @Column
    private String someStuff;
    @Column
    private double weight;

    @Embeddable
    public static class Key implements Serializable {
        @Column
        private int id;
        @Column
        private int version;

        /** Do not use. */
        @Deprecated
        public Key() {}

        public Key(final int id, final int version) {
            this.id= id;
            this.version = version;
        }
    }
}
```
When fetching its instance from EntityManager, it will return null with this warning:
11:17:19.689 [main] WARN  c.impetus.kundera.utils.ObjectUtils - Returning null as error during clone, Caused by:MyEntity$Key cannot be cast to java.lang.Enum

Reason is because this method:
com.impetus.kundera.property.PropertyAccessorFactory#getPropertyAccessor(java.lang.Class<?>)
```
            if (clazz.getName().indexOf("$") > 0)
            {
                accessor = map.get(Enum.class);
            }
            else
            {
                accessor = map.get(Object.class);
            }
```
Will return incorrect accessor, since key class name is "MyEntity$Key"
I think this should be replaced with `Enum.class.isAssignableFrom(clazz)`

**Comment by romikk** [comment]
Why is this closed? any comments?

**Comment by devender-yadav** [comment]
Hi @romikk,

Is it working after your change? I already merged your PR.

-Dev
