### ISSUE TITLE
Nested/Composite key in MongoDB

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#928]
The nested/composite key (cf. example below) is working with Cassandra, but not for MongoDB

@Entity
public class Data{

	@EmbeddedId
	private Key key;

	@Column
	private byte[] value;

	public Data(){}

	public Key getKey() {
		return key;
	}

	public void setKey(Key key) {
		this.key = key;
	}

	public byte[] getValue() {
		return value;
	}

	public void setValue(byte[] value) {
		this.value = value;
	}
}

@Embeddable
public class Key implements java.io.Serializable{
	
	@Embedded
	private PartitionKey partitionKey;
	
	@Column
	private String columname;
	
	
	public Key(){
	}

	public String getColumname() {
		return columname;
	}

	public void setColumname(String columname) {
		this.columname = columname;
	}

	public PartitionKey getPartitionKey() {
		return partitionKey;
	}

	public void setPartitionKey(PartitionKey partitionKey) {
		this.partitionKey = partitionKey;
	}
}

@Embeddable
public class PartitionKey{

	@Column
	private String classname;
	
	@Column
	private String id;

	public String getClassname() {
		return classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
}

**Comment by devender-yadav** [comment]
Hi @ansarrafique,

This issue is fixed in Kundera 3.9.

-Dev

**Comment by ansarrafique** [comment]
This works only for the insert operation. The entity, which contains composite key can be inserted. However, it doesn't work when you read/update/delete an entity.

This is how my entity looks like

@Embeddable
public class Key implements java.io.Serializable{
	@Embedded
	private CompositeKey compositekey ;
	@Column
	private String columname;
}
@Embeddable
public class CompositeKey{
	@Column
	private String classname;
	@Column
	private String id;
}

Now, when I execute the query (SELECT d FROM Data d WHERE e.key.compositekey .classname = '"+entity.getClass().getSimpleName()+"' AND d.key.compositekey.id = '"+primaryKey.toString()+"')

I am getting this exception

java.lang.IllegalArgumentException: attribute of the given name and type is not present in the managed type, for name:compositekey.classname

**Comment by ansarrafique** [comment]
BTW, I am using Kundera 3.10.
