### ISSUE TITLE
Enum mapping exception

### ISSUE THREAD

**Issue by michael-rhoese** [Impetus/kundera#943]
Hi Kundera Team,
I use Kundera Mongo version 3.8 and want to query a list of entities which contains an embedded type with an enum (which is located in an other package).
The enum field is annotated with `@Enumerated(EnumType.STRING)`. Storing works as expected...
```
String query = String.format(
    "SELECT e FROM Event e WHERE e.metadata.site = %s AND e.metadata.rssFeedId = %d",
    this.getCurrentSite().name(),
    rssFeedId );

List<Event> res = this.getEntityManager().createQuery( query ).getResultList();
```
 ... but if i query for some entries the following exception is thrown:

    java.lang.IllegalArgumentException: java.lang.Class is not an enum type
	at java.lang.Class.enumConstantDirectory(Class.java:3344) ~[na:1.8.0_112]
	at java.lang.Enum.valueOf(Enum.java:232) ~[na:1.8.0_112]
	at com.impetus.kundera.property.accessor.EnumAccessor.fromString(EnumAccessor.java:94) [kundera-core-3.8.jar:na]
	at com.impetus.kundera.property.accessor.EnumAccessor.fromString(EnumAccessor.java:31) [kundera-core-3.8.jar:na]
	at com.impetus.client.mongodb.query.MongoDBQuery.createSubMongoQuery(MongoDBQuery.java:456) [kundera-mongo-3.8.jar:na]
	at com.impetus.client.mongodb.query.MongoDBQuery.populateQueryComponents(MongoDBQuery.java:273) [kundera-mongo-3.8.jar:na]
	at com.impetus.client.mongodb.query.MongoDBQuery.createMongoQuery(MongoDBQuery.java:340) [kundera-mongo-3.8.jar:na]
	at com.impetus.client.mongodb.query.MongoDBQuery.recursivelyPopulateEntities(MongoDBQuery.java:216) [kundera-mongo-3.8.jar:na]
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377) [kundera-core-3.8.jar:na]
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200) [kundera-core-3.8.jar:na]
	...

I debugged into it and find out that in class `MongoDBQuery` on line 452 the following code works wrong:
```
if (value.getClass().isAssignableFrom(String.class) && f != null && !f.getType().equals(value.getClass())) {
    value = PropertyAccessorFactory.getPropertyAccessor(f).fromString(f.getType().getClass(),
    value.toString());
}
```
The call of `.getType().getClass()` is useless because `getType()` already returns the enum type itself.
```
if(f != null) {
    if(value.getClass().isAssignableFrom( String.class ) && !f.getType().equals( value.getClass() )) {
        value = PropertyAccessorFactory.getPropertyAccessor( f ).fromString( f.getType(), value.toString() );
    }
}
```

**Comment by michael-rhoese** [comment]
Is this project alive? Could anyone release the fix of this bug?

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,

Kundera is alive.

I will check your issue and get back to you soon. Also, you can make a pull request, if you fixed it. 

-Dev

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,

Please share your entity class.

-Dev

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,

Thank you for pointing out the issue!

I am able to replicate it. Fix is added in the trunk and it will be available from the next release _(Kundera 4.0)_. If you need this fix early, you can build the code from trunk.


-Dev

**Comment by michael-rhoese** [comment]
@devender-yadav thx for your answer. The project I working on only accept stable releases of dependencies. So I have to wait for your release.

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,

If this fix is critical to you, I can provide a minor release with this fix in next 2-3 days. There are no changes in Kundera-MongoDB module after last (3.9) release. So, Kundera-MongoDB module is stable. 

-Dev

**Comment by michael-rhoese** [comment]
It is a critical issue for our project. It would be great if a minor release is possible. I can wait 3 days you need to release it. Many thanks for your reply!

**Comment by devender-yadav** [comment]
@michael-rhoese,
 
You're welcome. We will provide a minor release within 3 days. 

-Dev

**Comment by karthikprasad13** [comment]
Hi @michael-rhoese 

We released a minor version with this fix. You can use `3.9.1` version of Kundera to get this fix.

-Karthik

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,

Try this latest release _(3.9.1)_.  Let us know if you face any other issue.

-Dev
