### ISSUE TITLE
Pagination feature for Cassandra doesn't work

### ISSUE THREAD

**Issue by RobertMlo** [Impetus/kundera#954]
Hi,

I've an `Api` table included 130 records. I'm trying to display all of them using a pagination feature (Query is from `com.impetus.kundera.query` package):

    public List<Api> getApis() {
        Query query = (Query) entityManager.createQuery("SELECT a FROM Api a", Api.class);
        query.setFetchSize(50);
        Iterator<Api> apis = query.iterate();
        List<Api> resultApis = new ArrayList<>();
        while(apis.hasNext()) {
            resultApis.add(apis.next());
        }
        return resultApis;
    }

I receive only 100 records instead of 130. Is there a bug or is it expected result?

I use a Cassandra 3.10. My `build.gradle` included the following dependencies:

    compile('com.impetus.kundera.client:kundera-cassandra-ds-driver:3.8')
    compile('com.impetus.kundera.client:kundera-cassandra:3.8')
    compile('com.datastax.cassandra:cassandra-driver-core:3.3.0')

My `persistence.xml` file:

	<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
		http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
		version="2.0">
		<persistence-unit name="cassandra_pu">
			<provider>com.impetus.kundera.KunderaPersistence</provider>
			<class>com.test.data.model.User</class>
			<class>com.test.data.model.Api</class>
			<class>com.test.data.model.Subscription</class>
			<exclude-unlisted-classes>true</exclude-unlisted-classes>
			<properties>
				<property name="cql.version" value="3.0.0" />
				<property name="kundera.port" value="9042"/>
				<property name="kundera.dialect" value="cassandra"/>
				<property name="kundera.nodes" value="localhost"/>
				<property name="kundera.keyspace" value="test"/>
				<property name="kundera.ddl.auto.prepare" value="update" />
				<property name="kundera.client.lookup.class" value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />
				<property name="kundera.client.property" value="kundera-cassandra.xml" />
				<property name="jboss.as.jpa.managed" value="false" />
			</properties>
		</persistence-unit>
	</persistence>

My `Api` class:

	@Entity
	@Table(name = "api")
	@IndexCollection(columns = {@Index(name = "name"), @Index(name = "owner")})
	public class Api {
		@Id
		@Column(name = "api_id")
		private UUID id;
		@Column(name = "name")
		private String name;
		@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
		@JoinColumn(name = "api_id")
		private Set<Subscription> subscriptions;
		@Column(name = "owner")
		private String owner;

		//getters && setters
	}

I know that Kundera has a limit by default as well as Cassandra for select operation. Kundera's default is 100 and Cassandra's default is 10000, but I thought I can work around this limit by means of pagination. If it isn't a bug, the only way to receive all of Api's records is to implement own pagination feature which based on `setFirstResult()` and `setMaxResult()`, right?

**Comment by karthikprasad13** [comment]
@RobertMlo 

Kundera adds a default limit of 100 on records and this behavior is expected. You have to add `setMaxResult()` in query for fetching more than 100 records.

In your case just add `query.setMaxResult(130)` or `query.setMaxResult(<large value>)`.

-Karthik

**Comment by RobertMlo** [comment]
@karthikprasad13 

Thanks for feedback. 

The `java.persistance.Query#setMaxResult(...)` method (as the `com.impetus.kundera.query.Query` class doesn't have `setMaxResult()`) works, but is there any different way to receive all of records without knowledge about the size of table?

I'm trying to implement my own pagination feature using `java.persistence.Query#setFirstResult()` and `java.persistence.Query#setMaxResult()` to achieve that, but when I send the following request, I expect to receive records from 100 to 130, but I always receive the records from 0 to 100 instead. Does the `java.persistence.Query#setFirstResult()` method work with Kundera? If not, is there any way to indicate a starting row?

        //...
        javax.persistence.Query query = entityManager.createQuery("SELECT a FROM Api a", Api.class);
        query.setFirstResult(100);
        query.setMaxResults(100);
        List<Api> apis = query.getResultList(); //expected: from 100 to 130; actual: from 0 to 100
        //...

**Comment by karthikprasad13** [comment]
@RobertMlo 

Without knowledge about the size of table, you can do something like `setMaxResults(Integer.MAX_VALUE)`.

Yes, `setFirstResult()` method works with Kundera but it doesn't work with Cassandra module. There is no way in cassandra to provide firstresult in fetch command.

You can check [DSResultIterator.java](https://github.com/impetus-opensource/Kundera/blob/84fc212fe8ffde95d6e33d254a98fdd3e20005df/src/kundera-cassandra/cassandra-ds-driver/src/main/java/com/impetus/kundera/client/cassandra/dsdriver/DSResultIterator.java) class for reference about how we achieved pagination. In thrift client we use `token` function to achieve pagination.

-Karthik

**Comment by RobertMlo** [comment]
@karthikprasad13 

Thanks for your help and advices!

I've the last question, I'm wondering what is the reason to set a default limit of 100 on records? It's quite small.

**Comment by karthikprasad13** [comment]
@RobertMlo 

You are welcome.

There is no strong reason for keeping the default as 100. Usually default for retrieval is kept small unless explicitly specified else it would blowup things.

-Karthik

**Comment by RobertMlo** [comment]
@karthikprasad13 

BTW: Is there any way to set the max result option along with the fetch size option? I don't see `setMaxResult()` in `com.impetus.kundera.query.Query` interface. Have you cosidered to add this feature?

**Comment by karthikprasad13** [comment]
@RobertMlo 

You can use `javax.persistence.Query` to set max results before casting it to `com.impetus.kundera.query.Query`.

Example:

    Query query = (Query) entityManager.createQuery("SELECT a FROM Api a", Api.class).setMaxResults(500);

-Karthik

**Comment by RobertMlo** [comment]
@karthikprasad13 

Thanks again.
