### ISSUE TITLE
OrphanRemoval option

### ISSUE THREAD

**Issue by RobertMlo** [Impetus/kundera#955]
Hi,

I'd like to use an `orphanRemoval` option to delete associations but it isn't work along with a `FetchType.LAZY` option.

There are my classes:

	@Entity
	@Table(name = "api")
	@IndexCollection(columns = {@Index(name = "name"), @Index(name = "owner")})
	public class Api {
		@Id
		@Column(name = "api_id")
		private UUID id;
		@Column(name = "name")
		private String name;
		@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
		@JoinColumn(name = "api_id")
		private Set<Subscription> subscriptions;
		@Column(name = "owner")
		private String owner;

		//getters && setters
	}

	@Entity
	@Table(name = "subscription")
	public class Subscription {
		@Id
		@Column(name = "subscription_id")
		private UUID id;
		@Column(name = "user")
		private String user;
		@Column(name = "api")
		private String api;

		//getters and setters
	}

How you see there is the unidirectional @OneToMany association between `Api` and `Subscription`. I set `orphanRemoval = true` to delete all `Subscription` entities when the `Api` object is deleted. When the `FetchType.EAGER` option is set - it works, but when the `FetchType.LAZY` option is set - it doesn't work. Does the `orphanRemoval` option work in Kundera? The code which executes deleting looks like the following: 

	Api api = entityManager.find(Api.class, apiID);
	entityManager.remove(api);

I was trying to use `JOIN FETCH` as well, but the following code throws the exception due to `Identification variable is mandatory in FROM clause for SELECT queries`.

        TypedQuery<Api> query = entityManager
            .createQuery("SELECT a FROM Api a JOIN FETCH a.subscriptions WHERE a.id = :id", Api.class);
        query.setParameter("id", apiID);
        try {
            Api api = query.getSingleResult();
            entityManager.remove(api);
        } catch (NoResultException e) {
		//...
        }

**Comment by devender-yadav** [comment]
Hi @RobertMlo,

Please share Kundera version and database _along with version_. 

-Dev

**Comment by RobertMlo** [comment]
Hi @devender-yadav,

Sure, I forgot about that. I use a Kundera 3.8 and a Cassandra 3.10. 

My `build.gradle` included the following dependencies:

    compile('com.impetus.kundera.client:kundera-cassandra-ds-driver:3.8')
    compile('com.impetus.kundera.client:kundera-cassandra:3.8')
    compile('com.datastax.cassandra:cassandra-driver-core:3.3.0')

My `persistence.xml` file:

	<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
		http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
		version="2.0">
		<persistence-unit name="cassandra_pu">
			<provider>com.impetus.kundera.KunderaPersistence</provider>
			<class>com.test.data.model.User</class>
			<class>com.test.data.model.Api</class>
			<class>com.test.data.model.Subscription</class>
			<exclude-unlisted-classes>true</exclude-unlisted-classes>
			<properties>
				<property name="cql.version" value="3.0.0" />
				<property name="kundera.port" value="9042"/>
				<property name="kundera.dialect" value="cassandra"/>
				<property name="kundera.nodes" value="localhost"/>
				<property name="kundera.keyspace" value="test"/>
				<property name="kundera.ddl.auto.prepare" value="update" />
				<property name="kundera.client.lookup.class" value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />
				<property name="kundera.client.property" value="kundera-cassandra.xml" />
				<property name="jboss.as.jpa.managed" value="false" />
			</properties>
		</persistence-unit>
	</persistence>

**Comment by devender-yadav** [comment]
Hi @RobertMlo,

Join queries and `orphanRemoval` are not supported in Kundera. 

You can delete associated objects using `CascadeType.DELETE`. While using `FetchType.LAZY`, you need to **`get`** associated objects for deleting them as well.

-Dev

**Comment by RobertMlo** [comment]
Hi @devender-yadav,

I see, thanks for feedback.
