### ISSUE TITLE
Near Queries not working

### ISSUE THREAD

**Issue by sreekanth9985** [Impetus/kundera#956]
I am trying to get nearest location data but not working.My code is below
``
@Entity
@Table(name = "Restaurants")
public class Restaurant implements Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "name")
	private String name = "";
	@Embedded
	@CollectionTable(name = "location")
	private Point location;
//getter and setters
}

@Embeddable
public class Point implements Serializable {	
	@Column(name = "latitude")
	private double latitude;
	@Column(name = "longitude")
	private double longitude;
//getter and setters
}
``

//getting the data using below code
`
Query q = entityManager.createQuery("Select r from Restaurant r where r.location > :point AND r.location < :maxDistance",Restaurant.class);
			q.setParameter("point", point);
			q.setParameter("maxDistance", distance);
			List<Restaurant> persons = q.getResultList();
`
below is persistence.xml file

`
<persistence-unit name="XXX">
	<provider>com.impetus.kundera.KunderaPersistence</provider>
		<class>com.XXX.entity.Rule</class>
		<class>com.XXX.entity.Order</class>
		<class>com.XXX.entity.Restaurant</class>
		<class>com.XXX.entity.Point</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes>
		<properties>
			<property name="kundera.nodes" value="localhost" />
			<property name="kundera.port" value="27017" />
			<property name="kundera.keyspace" value="localdb" />
			<property name="kundera.dialect" value="mongodb" />
			<property name="kundera.client.lookup.class"
				value="com.impetus.client.mongodb.MongoDBClientFactory" />
			<property name="kundera.username" value="CCCC" />
			<property name="kundera.password" value="XXXX" />
		 	<property name="kundera.pool.size.min.idle" value="1" />
			<property name="kundera.pool.size.max.active" value="10" />
			<property name="kundera.pool.size.max.total" value="50" /> 
		</properties>
	</persistence-unit>
`

But i am getting below error
`
com.impetus.kundera.query.QueryHandlerException: java.lang.RuntimeException: json can't serialize type : class com.XXX.entity.Point
	at com.impetus.client.mongodb.query.MongoDBQuery.populateEntities(MongoDBQuery.java:172)
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
	at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250)
	at com.XXX.repository.impl.FoodRepositoryImpl.findRestaurantByLocation(FoodRepositoryImpl.java:40)
	at com.XXX.util.Test2.main(Test2.java:208)

`
Can you please help me

**Comment by devender-yadav** [comment]
Hi @sreekanth9985,

Geo spatial queries are executed in a different manner. 
Check documentation - https://github.com/impetus-opensource/Kundera/wiki/Geospatial-Persistence-and-Queries 

-Dev

**Comment by sreekanth9985** [comment]
Instead of com.impetus.kundera.gis.geometry.Point; i am using my own Point embedded object.
 if am using com.impetus.kundera.gis.geometry.Point also i am getting below error
com.impetus.kundera.query.QueryHandlerException: java.lang.RuntimeException: json can't serialize type : class com.impetus.kundera.gis.geometry.Point

**Comment by devender-yadav** [comment]
Hi @sreekanth9985,

You need to create index on `Point` object.

    @IndexCollection(columns = { @Index(name = "location", type = "GEO2D") })

For using near query, you need to use Kundera's `Point` class. 

If you still face any issue, please share updated test case with us.

-Dev

**Comment by devender-yadav** [comment]
Hi @sreekanth9985,

It's working at my end using `com.impetus.kundera.gis.geometry.Point`. Please share sample project so that I can replicate this issue _(use `com.impetus.kundera.gis.geometry.Point` in your entity)_.

-Dev
