### ISSUE TITLE
JPQL Count not working for Cassandra

### ISSUE THREAD

**Issue by crashedserver** [Impetus/kundera#957]
Trying to test pagination with Kundera Cassandra which in turn uses JPQL count query.

I am getting the following exception.

Here is the code and the exception...

     public List<Student> getPagedStudentData(int pageNumber)
    {
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        EntityTransaction et = entityManager.getTransaction();
        et.begin();
        int pageSize = 10;
        CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

        CriteriaBuilder qb = entityManager.getCriteriaBuilder();
        CriteriaQuery<Long> cq = qb.createQuery(Long.class);
        cq.select(qb.count(cq.from(Student.class)));
        Long count = entityManager.createQuery(cq).getSingleResult();

        CriteriaQuery<Student> criteriaQuery = criteriaBuilder
                .createQuery(Student.class);
        Root<Student> from = criteriaQuery.from(Student.class);
        CriteriaQuery<Student> select = criteriaQuery.select(from);
        List<Student> studentsPage=null;
        TypedQuery<Student> typedQuery = entityManager.createQuery(select);
        while (pageNumber < count.intValue()) {
            typedQuery.setFirstResult(pageNumber - 1);
            typedQuery.setMaxResults(pageSize);
            studentsPage=typedQuery.getResultList();
            System.out.println("Current page: " + typedQuery.getResultList());
            pageNumber += pageSize;
        }
        et.commit();
        entityManager.close();
        return studentsPage;
    }

    java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at example.MyStudentApp.main(MyStudentApp.java:27) [classes/:na]
    Caused by: java.lang.IllegalArgumentException: Mismatch in expected return type. Expected:class java.lang.Long But actual class is:class example.entity.Student
	at com.impetus.kundera.persistence.EntityManagerImpl.onTypedQuery(EntityManagerImpl.java:969) ~[kundera-core-3.10.jar:na]
	at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:723) ~[kundera-core-3.10.jar:na]
	at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:709) ~[kundera-core-3.10.jar:na]
	at example.repository.service.StudentDao.getPagedStudentData(StudentDao.java:95) ~[classes/:na]
	at example.MyStudentApp.run(MyStudentApp.java:110) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	... 6 common frames omitted

Sample Code: https://stackoverflow.com/questions/2883887/in-jpa-2-using-a-criteriaquery-how-to-count-results

**Comment by devender-yadav** [comment]
Hi @crashedserver,

Please check https://github.com/impetus-opensource/Kundera/issues/735#issuecomment-109997018.

-Dev

**Comment by crashedserver** [comment]
@devender-yadav  Does not work. Same exception.

**Comment by karthikprasad13** [comment]
@crashedserver 

It should work.. please update with your latest code and also check this [test case](https://github.com/impetus-opensource/Kundera/blob/c645d7f7e949a0e9f9b06b010e527725a4b0a3d2/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/PersonCassandraTest.java#L435)

-Karthik

**Comment by crashedserver** [comment]
@karthikprasad13  @devender-yadav 

Here is my method...
    
    public List<Student> getPagedStudentData(int pageNumber)
    {
        Map propertyMap = new HashMap();
        EntityManager entityManager = entityManagerFactory.createEntityManager(propertyMap);
        EntityTransaction et = entityManager.getTransaction();
        et.begin();
       // int pageSize = 10;

        CriteriaBuilder qb = entityManager.getCriteriaBuilder();
        CriteriaQuery<Object> cq = qb.createQuery(Object.class);
        Root<Student> from = cq.from(Student.class);
        cq.select(qb.count((Expression<?>) from.alias("s")));
        Object result = entityManager.createQuery(cq).getSingleResult();

        Query q = entityManager.createQuery(cq);
        List noOfRows = q.getResultList();
        Object o=(noOfRows.get(0));
        if(o instanceof Student)
        {
            System.out.println("Student toString====>"+((Student)o).toString());
        }
        et.commit();
        entityManager.close();
        return null;
    }

It returns a Student object and here is the sysout.

    Student toString====>{"primaryKey":{}}

My Student class is  having a composite partition key and primary key. Here is the Student Class.

    import org.json.JSONObject;
    import javax.persistence.*;
    import java.util.List;

    @Entity
    @Table(name = "STUDENT5", schema = "test@cassandra_pu")
    public class Student
    {
        @Column(name = "NAME")
        private String name;

        @EmbeddedId
        private StudentKey primaryKey;

        @ElementCollection(targetClass = Address.class)
        @Column(name = "ADDRESSES")
        private List<Address> addresses;

        public Student()
        {

        }

        public Student(StudentKey studentKey, String name, List<Address> addresses)
        {
            this.primaryKey = studentKey;
            this.name=name;
            this.addresses=addresses;
        }

        public String toString()
        {
            return (new JSONObject(this)).toString();
        }

        public StudentKey getPrimaryKey()
        {
            return primaryKey;
        }

        public void setPrimaryKey(StudentKey primaryKey)
        {
            this.primaryKey = primaryKey;
        }

        public String getName()
        {
            return name;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        public List<Address> getAddresses()
        {
            return addresses;
        }

        public void setAddresses(List<Address> addresses)
        {
            this.addresses = addresses;
        }
    }

**Comment by crashedserver** [comment]
@karthikprasad13 Any updates?

**Comment by karthikprasad13** [comment]
@crashedserver 

In your code, `noOfRows` should be an instance of `ArrayList` with one `HashMap` element. This map should have key as `count` and value an integer (count of Students). This is because `q` is defined as

    Query q = entityManager.createQuery(cq);

and `cq` is selected as 

    cq.select(qb.count((Expression<?>) from.alias("s")));

-Karthik

**Comment by crashedserver** [comment]
@karthikprasad13  Please refer below...

    Query q = entityManager.createQuery(cq);
        List noOfRows = q.getResultList();
        Object o=((Map)noOfRows.get(0)).get("count");

Here is the exception. 
>> Caused by: java.lang.ClassCastException: example.entity.Student cannot be cast to java.util.Map

Here is the JPA Query that gets generated.

    Select Count(s) from Student s

Clearly it is returning the instance of Student Entity. <b>Would like to reiterate that the Student Object is having a composite partition and clustering key.</b>

 Can you please point me to a simple working COUNT example with composite partition and clustering key?

UPDATE: The same code works fine for Simple Entities WITHOUT composite partition key and clustering columns.

**Comment by karthikprasad13** [comment]
@crashedserver 

This is a bug and we have fixed it. You can build Kundera code from trunk and use it for now. We will try to provide a minor release with this fix if it is critical for you. Also, can you tell us more about your use case?

-Karthik

**Comment by crashedserver** [comment]
@karthikprasad13  Many Thanks. Yes, it is critical for us. Would be great if you can provide a minor release.

**Comment by karthikprasad13** [comment]
@crashedserver 

We released `kundera-3.10.1`. You can use this version in your project for this update.

-Karthik

**Comment by crashedserver** [comment]
@karthikprasad13 @devender-yadav  Many Thanks for the fix. It works. Can the team consider adding Unit test cases(if already not done) for composite partition key and multiple clustering columns? This will help people who model their entities that way.

**Comment by devender-yadav** [comment]
Hi @crashedserver,

Good point! 
Since Kundera is a community driven project, you can also add a test case for it. Check [contribution guideline](https://github.com/impetus-opensource/Kundera/wiki/How-to-Contribute#contribution-guidelines) for details.


-Dev
