### ISSUE TITLE
Cassandra: Unable to Unnest composite @Id including embedded composite partition key and cluster columns

### ISSUE THREAD

**Issue by crashedserver** [Impetus/kundera#958]
JPQL :

     Query queryForIds = entityManager.createQuery(
                "Select s.primaryKey from Student s");

Generated CQL Query:

    SELECT "**partitionKey**","STUDENT_ID","STUDENT_SSN" FROM "STUDENT5" LIMIT 12;

Exception:

    com.impetus.kundera.KunderaException: InvalidRequestException(why:Undefined column name "partitionKey")

Student Entity is mentioned [here](https://github.com/impetus-opensource/Kundera/issues/957)

**Comment by karthikprasad13** [comment]
@crashedserver 

This is a bug and we have fixed it. You can build the code from trunk for this fix.

-Karthik

**Comment by crashedserver** [comment]
Many Thanks. Is it possible to get a minor release.

**Comment by karthikprasad13** [comment]
@crashedserver 

You can build the code from trunk and use it for now and proceed with your use case. If there are any more bugs/issues we will fix them and release it at once after your use case is stable.

-Karthik
