### ISSUE TITLE
question about lucene index

### ISSUE THREAD

**Issue by publicocean0** [Impetus/kundera#962]
I m searching a way for building automatically lucene index in cassadra writed as annotation in entities
how can i add a annotation  feature in entity?
i want add Annotation LuceneIndex in Cassandra entity 
for building automatically lucene indexes. 

I might retrieve the registered entitties .I use spring.

**Comment by karthikprasad13** [comment]
Answered in  https://github.com/impetus-opensource/Kundera/issues/961#issuecomment-328024146
