### ISSUE TITLE
Running a query directly on Cassandra when using Elasticsearch -question

### ISSUE THREAD

**Issue by urielcalvi** [Impetus/kundera#963]
Hi!
I use Cassandra NoSQL database with Elasticsearch as a index store.
According to the documents, in this use case, my JPA query is passed to Kundera Core Engine, to the Index Store, and then to Client Delegator.
This works well for powerfull querys that needs Elasticsearch. But, if I need to run a simple query, like a search directly in Row Key, run Index Store step is unnecessary and expensive. Has a way to run simple querys that no pass in Index Store?

Thanks!

**Comment by karthikprasad13** [comment]
@urielcaire 

As of now, there is no way to bypass index store for simple queries.

As a workaround, you can create a `persistence unit` just for Cassandra and another for Cassandra + Elasticsearch. Then create two `EntityManagerFactory`s and `EntityManager`s for each persistence unit. Now use one `EntityManager` for Cassandra specific queries and other for Cassandra + Elasticsearch queries.

-Karthik

**Comment by urielcalvi** [comment]
@karthikprasad13 

It helps!
Thanks for your reply.
