### ISSUE TITLE
Exception in thread "main" java.lang.AbstractMethodError: org.apache.xerces.dom.DeferredDocumentImpl.getXmlVersion()Ljava/lang/String;

### ISSUE THREAD

**Issue by gsndr** [Impetus/kundera#971]
Hi,
I have got this exception (when I run `emf = Persistence.createEntityManagerFactory(_PU)`)
Exception in thread "main" java.lang.AbstractMethodError: org.apache.xerces.dom.DeferredDocumentImpl.getXmlVersion()Ljava/lang/String;
	at com.impetus.kundera.loader.PersistenceXMLLoader.findPersistenceUnits(PersistenceXMLLoader.java:276)
	at com.impetus.kundera.configure.PersistenceUnitConfiguration.findPersistenceMetadatas(PersistenceUnitConfiguration.java:155)
	at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:83)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configurePersistenceUnit(EntityManagerFactoryImpl.java:659)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:133)
	at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)

I don't understand what's the problem

**Comment by devender-yadav** [comment]
Hi @giusy123,

Provide information of Kundera version, database used (with version) and sample test case.


-Dev

**Comment by gsndr** [comment]
Hi,
my Kundera version is 3.10.1 and database is hbase ( I use maven with kundera-hbase-v2 artifact).
I use dom4j library in my code, it's possibile there's a conflict? 

My persistence file is
`<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
	https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd" version="2.0">
  <persistence-unit name="rhumes">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <properties>
      <property name="kundera.dialect" value="hbase"/>
      <property name="kundera.nodes" value="localhost"/>
      <property name="kundera.port" value="60000"/>
      <property name="kundera.keyspace" value="rhumes"/>
      <property name="kundera.ddl.auto.prepare" value="validate"/>
      <property name="kundera.client.lookup.class" value="com.impetus.client.hbase.HBaseClientFactory"/>
    </properties>
  </persistence-unit>
</persistence>`

I wrote an entity class is:
`import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "edge")
public class Edge {
	
	@Id
	@Column(name = "row_key")
	private int id;
	
		@Column(name = "key_net")
	private int key_net;
	
	@Column(name = "net")
	private String net;
	@Column(name = "endNode")
	private String endNode;
	@Column(name = "startNode")
	private String startNode;
	@Column(name = "relationship")
	private String relationship;

	public Edge() {
	}

		
	/** The edge id. */
  
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id){
		this.id = id;
	}
	
	
	public int getNetID() {
		return this.key_net;
	}
	
	public void setNetID(int key_net){
		this.key_net = key_net;
	}

	public String getNet() {
		return this.net;
	}
	
	public void setNet(String net){
		this.net = net;
	}

	public String getEndNode() {
		return this.endNode;
	}
	
	public void setEndNode(String node){
		this.endNode = node;
	}
	
	public String getStartNode() {
		return this.startNode;
	}
	
	public void setStartNode(String node){
		this.startNode = node;
	}

	public String getRelationship() {
		return this.relationship;
	}
	
	public void setRelationship(String type){
		this.relationship = type;
	}`

Thank you

**Comment by devender-yadav** [comment]
Hi @giusy123,

Check for `Xerces` lib. There might be multiple libs in the classpath. 

-Dev

**Comment by gsndr** [comment]
Hi,
I solved. Conflict is between Kundera and Apache ddl utils library.

**Comment by devender-yadav** [comment]
Nice. Are we good to close it?

**Comment by gsndr** [comment]
Yes, thanks
