### ISSUE TITLE
Persistence.xml path

### ISSUE THREAD

**Issue by gsndr** [Impetus/kundera#973]
My project create persistence.xml at runtime. It's possible configure external persistence.xml path (not in META-INF path) for  my Kundera project?
Thanks

**Comment by devender-yadav** [comment]
Hi @giusy123,

As per JPA, `persistence.xml` has to be under META-INF folder. So, you cant configure that outside META-INF.
 

-Dev

**Comment by gsndr** [comment]
Ok thank you
