### ISSUE TITLE
Remove limits to Hbase and Cassandra

### ISSUE THREAD

**Issue by gsndr** [Impetus/kundera#978]
Hi,
I notice I've got limit for Hbase and Cassandra query (limit it's 100 row).
It's possibile to scan all row into a table?
I've read about setMaxResults(integer); method but my question is:
If I don't know exactaly max number of row in a table and if I work with big table it's possible to scan all row in a table?
And what's best way to do?
Thanks

**Comment by devender-yadav** [comment]
Hi @giusy123,

Set `Integer.MAX_VALUE` in `setMaxResults()`

-Dev
