### ISSUE TITLE
Cannot query by java.util.Date field

### ISSUE THREAD

**Issue by dstrawson** [Impetus/kundera#98]
I have an entity with a field that's a Date, there's a secondary index on it as well, when I query it I get the following exception:

com.impetus.kundera.query.QueryHandlerException: unsupported data type:class java.util.Date

Would it be possible to add support?

**Comment by mevivs** [comment]
I will have a look.

**Comment by mevivs** [comment]
Fixed in trunk. Please verify.

-Vivek

**Comment by mevivs** [comment]
Test case added for all data types. 
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes

closing it.
