### ISSUE TITLE
multiple order by support

### ISSUE THREAD

**Issue by asafbennatan** [Impetus/kundera#987]
kundera with mongo fails when using multiple order by clause criteria api:

com.impetus.kundera.query.JPQLParseException: Invalid sort order provided:ASCp.endTime. For details, see: http://openjpa.apache.org/builds/1.0.4/apache-openjpa-1.0.4/docs/manual/jpa_langref.html#jpa_langref_bnf

**Comment by devender-yadav** [comment]
Hi @asafbennatan,

Please share the query that you are trying?

**Comment by devender-yadav** [comment]
Hi @asafbennatan,

    Select p from PersonMongo p order by p.personId ASC, p.personName DESC

is working fine at my end.

You missed _comma_ after first order by clause in your query.

**Comment by asafbennatan** [comment]
Hi @devender-yadav ,
i know there is a comma missing but this is what being generated by the criteria api , here is the code:


```
CriteriaBuilder cb=em.getCriteriaBuilder();
CriteriaQuery<TestNoSQl> q=cb.createQuery(TestNoSQl.class);
Root<TestNoSQl> r=q.from(TestNoSQl.class);
q.select(r.alias("p")).orderBy(cb.asc(r.get("testName")),cb.asc(r.get("creationDate")));
TypedQuery<TestNoSQl> query=em.createQuery(q);
if(pageSize >-1 && currentPage>-1){
           query.setFirstResult(pageSize*currentPage);
            query.setMaxResults(pageSize);
        }
return query.getResultList();
```

Thanks

**Comment by devender-yadav** [comment]
Hi @asafbennatan,

This is an issue with `CriteriaQueryTranslator`. We will fix it soon.

**Comment by asafbennatan** [comment]
Thanks!

2018-02-08 11:30 GMT+02:00 Devender Yadav <notifications@github.com>:

**Comment by devender-yadav** [comment]
Hi @asafbennatan,

Fix has been added to the trunk. You can build it or wait till we release Kundera 3.13

As a workaround, you can use JPA query.

Sample query:

    Select p from PersonMongo p order by p.personId ASC, p.personName DESC


-Dev

**Comment by asafbennatan** [comment]
Hi @devender-yadav 
Thanks for the quick fix,
another question , i have commented on a closed issue https://github.com/Impetus/Kundera/issues/180
should i open a new issue or you will see it as it is there ?
Thanks.

**Comment by devender-yadav** [comment]
Hi @asafbennatan,

I recommend raising a new issue with the same comment. You can add #180 as a reference.
