### ISSUE TITLE
MongoDB Only Support DataType String??

### ISSUE THREAD

**Issue by timlong** [Impetus/kundera#99]
HI,I am new to kundera and I like it very much .
 I used it in my project,bu I found that use kundera  mongodb client insert data only  support Data Type String .
eg.
        @Id
    @GeneratedValue
    @Column(name = "_id")
    private String id;

```
@Column(name = "app_id")
private int app_id;

@Column(name = "earn_type")
private int earn_type;

@Column(name = "pid")
private int pid;
```

After I  insert this object to MongoDB app_id/earn_type/pid will be String but not NumberInt as I expected

I debug the source file com.impetus.client.mongodb.MongoDBDataHandler 
com.impetus.client.mongodb.MongoDBDataHandler.extractEntityField(Object, DBObject, Column)
 else
        {
            // TODO : this should have been handled by DocumentObjectMapper.
            Object valObj = PropertyAccessorHelper.getObject(entity, column.getField());
            if (valObj != null)
            {
                dbObj.put(column.getName(), valObj instanceof Calendar ? ((Calendar) valObj).getTime().toString()
                        : valObj.toString())/*
                                             \* PropertyAccessorHelper.getObject(
                                             \* entity,
                                             \* column.getField()).toString())
                                             */;
            }
        }
this function make everything toString
Can Kundera MongoDB Client support  other data type??

**Comment by mevivs** [comment]
Hi,
It supports for other data type as well. Kundera internally handles conversion to different data type fields. AFAIK, mongo DB support BSON format of data, so eventually persisting everything into String after conversion. But yes, that conversion can be avoided. 

I am sharing one test case for reference to data type support, here it is:

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoTest.java

-Vivek

**Comment by mevivs** [comment]
KK, can you please look into this. I guess, we can avoid this string conversion.

**Comment by timlong** [comment]
Thanks for replay
But my problem is my job is to write data into MongDB, other will use pymongo read the  data, they can only handle data type like:

{
   "_id": ObjectId("501ccbe09f1f949da2145f50"),
   "app_id": NumberInt(204),
   "earn_type": NumberInt(2),
   "pid": NumberInt(27) 
}
But if  I use Kundera, it will be:
{
   "_id": ObjectId("501ccbe09f1f949da2145f50"),
   "app_id":"204",
   "earn_type": "2",
   "pid": "27" 
}
so here is the problem...

**Comment by mevivs** [comment]
Well. As a quick fix removing toString conversion can do the trick. But this will break for BigInteger, BigDecimal, and java.sql datatypes.(As Mongo is complaining about BigDecimal,BigInteger data types about serialization).

If it is on prioirty, i would request you to update source by removing "toString" for now. But i will update you soon with proper fix around this, as i am already looking into other issues around Data type conversion.

-Vivek

**Comment by timlong** [comment]
Thanks Very Much
I will remove toString for temporary fix

**Comment by mevivs** [comment]
This has been fixed in trunk now.

-Vivek

**Comment by mevivs** [comment]
Test cases added.

https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-mongo/src/test/java/com/impetus/client/crud/datatypes
