### ISSUE TITLE
Table is created in DB but i am getting this ____Exception in thread "main" java.lang.NoSuchMethodError: com.impetus.kundera.metadata.model.attributes.AbstractAttribute.getTableName()Ljava/lang/String;

### ISSUE THREAD

**Issue by mayankqait** [Impetus/kundera#990]
Exception in thread "main" java.lang.NoSuchMethodError: com.impetus.kundera.metadata.model.attributes.AbstractAttribute.getTableName()Ljava/lang/String;	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumnOrSuperColumnThriftRow(CassandraDataHandlerBase.java:1273)	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.toThriftRow(CassandraDataHandlerBase.java:367)	at com.impetus.client.cassandra.CassandraClientBase.prepareMutation(CassandraClientBase.java:1681)	at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:160)	at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:88)	at com.impetus.client.cassandra.thrift.ThriftClient.persist(ThriftClient.java:136)	at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)	at com.impetus.kundera.graph.Node.flush(Node.java:533)	at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:413)	at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:151)	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)	at com.example.demo.KunderaSpringSampleApplication.main(KunderaSpringSampleApplication.java:57)

**Comment by mayankqait** [comment]
webConfig.java


package com.infotech.config;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;
import org.springframework.data.cassandra.repository.config.EnableCassandraRepositories;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.orm.jpa.JpaVendorAdapter;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.servlet.config.annotation.DefaultServletHandlerConfigurer;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import com.impetus.kundera.persistence.AbstractEntityReader;
import com.impetus.kundera.persistence.EntityManagerFactoryImpl;

@Configuration
@EnableTransactionManagement
//@EnableJpaRepositories(basePackages="com.infotech.repository")
@EnableCassandraRepositories(basePackages="com.infotech.repository")
@ComponentScan(basePackages="com.infotech")
public class WebConfig extends WebMvcConfigurerAdapter{
	
	
	@Override 
	public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {  
		configurer.enable();   
		}
	
	@Autowired 
	private Environment env;
	
	@Bean 
	public DataSource dataSource() { 
		DriverManagerDataSource dataSource = new DriverManagerDataSource();
		/*dataSource.setDriverClassName(env.getProperty("spring.datasource.driverClassName"));
		dataSource.setUrl(env.getProperty("spring.datasource.url")); 
		dataSource.setUsername(env.getProperty("spring.datasource.username")); 
		dataSource.setPassword(env.getProperty("spring.datasource.password")); */
		
		//dataSource.setDriverClassName(env.getProperty("spring.data.cassandra.contact-points"));
		dataSource.setUrl(env.getProperty("spring.data.cassandra.contact-points")); 
		//dataSource.setUsername(env.getProperty("spring.data.cassandra.keyspace-name")); 
		
		//dataSource.setPassword(env.getProperty("spring.datasource.password")); 
		return dataSource;
		}
	
	  @Bean 
	  public LocalContainerEntityManagerFactoryBean entityManagerFactory() {     
		  LocalContainerEntityManagerFactoryBean em = new LocalContainerEntityManagerFactoryBean();
		  em.setPersistenceXmlLocation("resources/persistence.xml");
		 // em.setDataSource(dataSource());     
		  em.setPackagesToScan(new String[] { "com.infotech"});  
		  JpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
		  em.setJpaVendorAdapter(vendorAdapter);     
		  return em;  
		  }

}



**Main boot class** 

package com.example.demo;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.PersistenceUnit;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import com.impetus.client.cassandra.common.CassandraConstants;
import com.impetus.kundera.KunderaPersistence;
import com.impetus.kundera.persistence.EntityManagerFactoryImpl;
import com.infotech.model.User;
//@PersistenceUnit
@EntityScan("com.infotech.model")
@ComponentScan(basePackages="com.infotech")
//@EnableCassandraRepositories("com.infotech.cassRepo")
@EnableJpaRepositories("com.infotech.repository")
@Configuration
@EnableAutoConfiguration
@SpringBootApplication
public class KunderaSpringSampleApplication {
    
	//@PersistenceContext(unitName = "mysqlPU", type = PersistenceContextType.EXTENDED)
    //private static EntityManager emf;
	@Autowired
	static KunderaPersistence kp;
	
	public static void main(String[] args) {
		User u = new User();
        u.setUserId(1);
        u.setFirstName("ram");
        u.setLastName("gopal");
        u.setCity("Noida");
        
        
        //enable CQL3
       /*Map<String, String> props = new HashMap<>();
        props.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_2_0);*/
       //EntityManagerFactoryImpl emf = (EntityManagerFactoryImpl) kp.createEntityManagerFactory("mysqlPU", null);
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandrapu");
       EntityManager em = emf.createEntityManager();
        
        em.persist(u);
        em.close();    
        emf.close();
		SpringApplication.run(KunderaSpringSampleApplication.class, args);
								
	}
}

persistence.xml



<persistence xmlns="http://java.sun.com/xml/ns/persistence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
	https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
	version="2.0">
  

  <persistence-unit name="cassandrapu" transaction-type="RESOURCE_LOCAL">
		<provider>com.impetus.kundera.KunderaPersistence</provider>
    	
		<class>com.infotech.model.User</class>
		<class>com.impetus.kundera.datakeeper.entities.SubordinatesCounter</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes>
		<properties>
			<property name="kundera.nodes" value="localhost" />
			<property name="kundera.port" value="9160" />
			<property name="kundera.keyspace" value="employeecombo" />
			 <property name="kundera.ddl.auto.prepare" value="validate" />
			 <property name="kundera.dialect" value="cassandra"/>
			<property name="kundera.client" value="thrift" />
			<property name="kundera.client.lookup.class"
				value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
		</properties>
	</persistence-unit>  
	
	
</persistence> 

pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.infotech</groupId>
	<artifactId>KunderaSpringSample</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>KunderaSpringSample</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.9.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
         
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-cassandra</artifactId>      
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		 <dependency>
          <groupId>com.impetus.kundera.client</groupId>
          <artifactId>kundera-cassandra</artifactId>
          <version>2.9.1</version> 
       </dependency> 
       
       
       <dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>5.2.2.Final</version>
</dependency> 
       <dependency>
         <groupId>com.impetus.client</groupId>
          <artifactId>kundera-rdbms</artifactId>
          <version>2.8.1</version> 
      </dependency>  
      
         
      <dependency>
	    <groupId>com.impetus.kundera.core</groupId>
	    <artifactId>kundera-core</artifactId>
	    <version>2.9.1</version> 
     </dependency>
      
        <dependency>
          <groupId>com.impetus.kundera.client</groupId>
          <artifactId>data-as-object</artifactId>
          <version>3.12</version>
       </dependency> 
	</dependencies>
    
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>

**Comment by devender-yadav** [comment]
Hi @mayankqait,

Is #988 working for you now? Did you resolve dependency conflicts? 
@karthikprasad13 already [commented](https://github.com/Impetus/Kundera/issues/988#issuecomment-364114110) there.

**Comment by mayankqait** [comment]
Yes we can close this issue #988. 
Thank u
