### ISSUE TITLE
I have a query that Is it possible to persist same data in two different database simultaneously.

### ISSUE THREAD

**Issue by mayankqait** [Impetus/kundera#992]
When i am trying this Schema is generated for both the databases(mysql and cassandra) but data is only persisted into one database()mysql.
Is it possible to persist data in boththe databases.

[CassandraEmpTask.zip](https://github.com/Impetus/Kundera/files/1730550/CassandraEmpTask.zip)

**Comment by devender-yadav** [comment]
Hi @mayankqait,

Using Polyglot persistence you can persist parts of relational entities in different databases. For example, if you have `User` and `Address` entities having _one to many_ relationship. You want to save `User` in Cassandra and `Address` in Mysql; you can do it with polyglot persistence. 

Now for saving the same entity in both the databases, you need to create 2 persistence-unit in your `persistence.xml` and need to create two `EntityManagerFactory` instances using each persistence-unit.  Now create `entityManager` and save entity objects.

**Comment by mayankqait** [comment]
Thank you for updating on this.
