### ISSUE TITLE
Cassandra DS Driver: NoClassDefFoundError: io/netty/channel/group/ChannelMatchers of 

### ISSUE THREAD

**Issue by vinceynhz** [Impetus/kundera#993]
Hi!

I'm trying to use the Cassandra DS driver as described [here](https://github.com/Impetus/Kundera/wiki/Datastax-java-driver-support-for-Cassandra-using-Kundera) and everything goes fine until the shutdown process of the container (TomEE) that I get the following exception:

```
Exception in thread "Shutdown-checker" java.lang.NoClassDefFoundError: io/netty/channel/group/ChannelMatchers
	at io.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:208)
	at com.datastax.driver.core.Connection$Factory.shutdown(Connection.java:842)
	at com.datastax.driver.core.Cluster$Manager$ClusterCloseFuture$1.run(Cluster.java:2526)
Caused by: ...
```

Am I missing something? My pom.xml contains **only** the following dependency related to kundera:

```xml
<dependency>
    <groupId>com.impetus.kundera.client</groupId>
    <artifactId>kundera-cassandra-ds-driver</artifactId>
    <version>3.9</version>
</dependency>
```

Also set the persistence.xml as described in the link:

```xml
<persistence-unit name="cloud_cassandra_pu" transaction-type="RESOURCE_LOCAL">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <properties>
        <property name="kundera.nodes" value="localhost"/>
        <property name="kundera.port" value="9042"/>
        <property name="kundera.keyspace" value="resources"/>
        <property name="kundera.dialect" value="cassandra"/>
        <property name="kundera.client.lookup.class" value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory"/>
        <property name="kundera.client.property" value="loadBalancer.xml" />
        <property name="kundera.pool.size.max.active" value="5" />
        <property name="kundera.pool.size.max.idle" value="5" />
        <property name="kundera.pool.size.min.idle" value="2" />
        <property name="kundera.username" value="app"/>
        <property name="kundera.password" value="app"/>
    </properties>
</persistence-unit>
```

Thanks

**Comment by vinceynhz** [comment]
Nevermind, I think I found the reason and it has nothing to do with Kundera.

Apparently, the issue I'm seeing has to do with the interaction of netty threads spawned by the web application and the inability for them to shutdown before the web application gets removed by the container, thus making the netty classes unavailable for the threads.

See more here:
https://stackoverflow.com/questions/40930844/java-tomcat-underlying-netty-threads-not-stopped/40941642#40941642
https://github.com/graylog-labs/log4j2-gelf/issues/28

**Comment by devender-yadav** [comment]
@vinceynhz thanks for the update!
