### ISSUE TITLE
Regarding SSL support

### ISSUE THREAD

**Issue by mayankqait** [Impetus/kundera#994]
Hi team ,

Does Kundera support SSL for cassandra?

**Comment by devender-yadav** [comment]
Hi @mayankqait,

Currently _(version 3.12)_, Kundera does not support SSL for Cassandra. Can you tell us more about your use case?

**Comment by mayankqait** [comment]
Thanks for confirming. We are evaluating kundera and other JPA compliant datastores to be used in our application. Currently there is no use case for SSL but for a long term, we may need to support it.

**Comment by devender-yadav** [comment]
@mayankqait we are not planning to add SSL support in this release for Kundera-Cassandra. But we can add in upcoming releases. 
If any community member wants to add support for this feature, we are happy to help him/her.
