### ISSUE TITLE
Do kundera work with jpa repository as shown below

### ISSUE THREAD

**Issue by mayankqait** [Impetus/kundera#995]
hi team ,can i run query like this
@Repository
public interface EmpRepository  extends JpaRepository<Employee,Integer>{
     
	@Query(value="SELECT e FROM Employee e WHERE e.name = :name")
	public List<Employee> findByName(@Param("name") String name);
}

As i am getting this error :-1:  using postman

could not prepare statement; SQL [select employee0_.id as id1_0_, employee0_.dept as dept2_0_, employee0_.mobile as mobile3_0_, employee0_.name as name4_0_ from employeecombo@cassandra_pu.employee employee0_ where employee0_.name=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement

**Comment by devender-yadav** [comment]
Hi @mayankqait,

JpaRepository is a part of Spring Data JPA. It will not work with Kundera.

-Dev

**Comment by mayankqait** [comment]
Thank u
