### ISSUE TITLE
Save ordinal type of enum

### ISSUE THREAD

**Issue by tpor31** [Impetus/kundera#997]
Hi,

I use kundera-hbase-v2 version 3.6
Can I  save a field that is a ordinal enumerator? 

	@Enumerated(EnumType.ORDINAL)
	private Source source;

Thanks

**Comment by devender-yadav** [comment]
Hi @tpor31,

Yes, you can use it. 

-Dev

**Comment by tpor31** [comment]
Thanks devender-yadav
